### ISSUE TITLE
Sonarr loses track of special it queued

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1039]
Sonarr can parse `Sherlock.The Abominable Bride.720p HDTV x264-FoV` from the indexer, but it fails after its in the download queue (not shown and not imported).

**Comment by feld** [comment]
I hit the same problem. It did lose complete track of it, but I was able to rename the file to include s0e09 and do a manual import just fine.

**Comment by markus101** [comment]
Logs from the forums:

```
16-1-3 17:17:06.1|Error|DownloadMonitoringService|Couldn't process tracked download Sherlock.The.Abominable.Bride.2016.1080p.5.1Ch.Web-DL.ReEnc-DeeJayAhmed

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Download.CompletedDownloadService.Import(TrackedDownload trackedDownload) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 123
   at NzbDrone.Core.Download.CompletedDownloadService.Process(TrackedDownload trackedDownload, Boolean ignoreWarnings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 109
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientItems(IDownloadClient downloadClient, DownloadClientItem downloadItem) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 128
```

**Comment by slamanna212** [comment]
Same issue here! just noticed it today. I manaully searched for it, downloaded that exact release and got the same error

**Comment by markus101** [comment]
Fixed in develop.
