### ISSUE TITLE
Couldn't process tracked download. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by bobloadmire** [Sonarr/Sonarr#1042]
Just started happening. Hadn't logged into the server for weeks, pretty sure nothing changed.

Total records: 11,520
Details
Message

Couldn't process tracked download Sherlock.The.Abominable.Bride.2016.1080p.5.1Ch.Web-DL.ReEnc-DeeJayAhmed: Object reference not set to an instance of an object.

Exception

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Download.CompletedDownloadService.Import(TrackedDownload trackedDownload) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 123
   at NzbDrone.Core.Download.CompletedDownloadService.Process(TrackedDownload trackedDownload, Boolean ignoreWarnings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 109
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientItems(IDownloadClient downloadClient, DownloadClientItem downloadItem) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 128

Sonarr Ver. 2.0.0.3645, windows 8.

**Comment by markus101** [comment]
Please use the forums for support.

Additional logging information (debug) would be helpful.

**Comment by bobloadmire** [comment]
heres the log https://www.dropbox.com/s/zxkvd2a6xjjrp7p/nzbdrone.txt?dl=0

I made an account over at the forums, but i can't post for whatever reason. I can't even reply to the Mod IMs
