### ISSUE TITLE
Sonarr isn't moving downloads from qBittorrent when completed

### ISSUE THREAD

**Issue by Flippage** [Sonarr/Sonarr#1085]
When I download a torrent using Sonarr, it adds to qBittorrent with no troubles. It labels it with Sonarr-tv. Downloads it to my F:\Videos\Downloads\TV\ folder. And it shows the progress correctly in the Sonarr activity tab.

But when the download is finished, nothing happens. The download sits in qBittorrent, but Sonarr never  moves / copies / hardlinks the file to the series folder.

I've found I have to run a manual Drone Factory scan on the download folder, and then everything gets imported. But I want this to work automatically (as it's supposed to).

Should I not use the qBittorrent downloader, and go back to using Torrent Blackhole ? (Which worked perfectly)

I need some help here. I've messed with so many settings and nothing seems to work.

I run "Check for completed downloads" from the task menu, and nothing happens either. Activity shows "Grabbed and sent to download client" but nothing in there mentions trying to copy or move the file.

I can see this in the log file, but I don't understand what this means. qBittorrent used to work as well...

"16-1-21 17:28:03.9|Error|TaskExtensions|Task Error

System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8080
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Rest.RestSharpExtensions.ValidateResponse(IRestResponse response, IRestClient restClient) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Rest\RestSharpExtensions.cs:line 33
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.GetConfig(QBittorrentSettings settings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\qBittorrent\QBittorrentProxy.cs:line 60
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.GetStatus() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\qBittorrent\QBittorrent.cs:line 179
   at NzbDrone.Core.HealthCheck.Checks.ImportMechanismCheck.<Check>b__0(IDownloadClient v) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\HealthCheck\Checks\ImportMechanismCheck.cs:line 25
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.HealthCheck.Checks.ImportMechanismCheck.Check() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\HealthCheck\Checks\ImportMechanismCheck.cs:line 25
   at NzbDrone.Core.HealthCheck.HealthCheckService.<PerformHealthCheck>b__0(IProvideHealthCheck c) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 56
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.HealthCheck.HealthCheckService.PerformHealthCheck(Func`2 predicate) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 55
   at NzbDrone.Core.HealthCheck.HealthCheckService.HandleAsync(ApplicationStartedEvent message) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 92
   at NzbDrone.Core.Messaging.Events.EventAggregator.<>c__DisplayClass3`1.<PublishEvent>b__0() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 72
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()"

Please help me with this.

**Comment by markus101** [comment]
Please use the forums for support.

Sonarr is unable to connect to qBittorrent, check that you're using the correct port and that qBittorrent's Web UI/API is working (It should load in a browser).
