### ISSUE TITLE
Log a different error when config file is empty or contains only an invalid character

### ISSUE THREAD

**Issue by AveSharia** [Sonarr/Sonarr#1104]
I'm not sure how my config file got made blank, but after a Windows Update Sonarr was throwing an InvalidConfigFileException. The logs gave the stack trace but that just told me the error was thrown by the XML parser.

16-1-28 19:09:16.4|Fatal|WindowsApp|EPIC FAIL: C:\ProgramData\NzbDrone\config.xml is invalid, please see the http://wiki.sonarr.tv for steps to resolve this issue.

I looked at my config file and it was blank so I figured what the heck, I'll just delete it. Sonarr recreated and populated it properly, and the error went away. The problem can be reproduced by deleting the text from config.xml (again, not sure how this happened) and trying to run Sonarr.

Log attached anyway. Ctrl+F "EPIC FAIL" (you named it, not me!)
[nzbdrone.txt](https://github.com/Sonarr/Sonarr/files/109081/nzbdrone.txt)

**Comment by markus101** [comment]
I've seen it before when it wasn't blank but had an invisible character so the XML was unable to be parsed, which according the the error looks like what happened.

I think we could probably tell the user its blank instead of saying its invalid (check before parsing the XML), but I don't think automatically recreating it makes sense, since it could expose it to the outside world without security.

**Comment by markus101** [comment]
http://stackoverflow.com/questions/11036799/hexadecimal-value-0x00-is-a-invalid-character

Current exception log:

```
16-1-28 19:06:57.1|Fatal|WindowsApp|EPIC FAIL: C:\ProgramData\NzbDrone\config.xml is invalid, please see the http://wiki.sonarr.tv for steps to resolve this issue.

NzbDrone.Core.Configuration.InvalidConfigFileException: C:\ProgramData\NzbDrone\config.xml is invalid, please see the http://wiki.sonarr.tv for steps to resolve this issue. ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at NzbDrone.Core.Configuration.ConfigFileProvider.LoadConfigFile() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 351
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Configuration.ConfigFileProvider.LoadConfigFile() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 363
   at NzbDrone.Core.Configuration.ConfigFileProvider.<>c__DisplayClass1.<GetValue>b__0() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 261
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Cache\Cached.cs:line 87
   at NzbDrone.Core.Configuration.ConfigFileProvider.GetValue(String key, Object defaultValue, Boolean persist) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 259
   at NzbDrone.Core.Configuration.ConfigFileProvider.GetValueInt(String key, Int32 defaultValue) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 244
   at NzbDrone.Core.Configuration.ConfigFileProvider.get_Port() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Configuration\ConfigFileProvider.cs:line 139
   at NzbDrone.Host.AccessControl.UrlAclAdapter.ConfigureUrls() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Host\AccessControl\UrlAclAdapter.cs:line 55
   at NzbDrone.Host.Owin.OwinHostController.StartServer() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Host\Owin\OwinHostController.cs:line 48
   at NzbDrone.Host.NzbDroneServiceFactory.Start() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Host\ApplicationServer.cs:line 55
   at NzbDrone.Host.Router.Route(ApplicationModes applicationModes) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Host\Router.cs:line 38
   at NzbDrone.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Host\Bootstrap.cs:line 70
   at NzbDrone.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Host\Bootstrap.cs:line 38
   at NzbDrone.WindowsApp.Main(String[] args) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone\WindowsApp.cs:line 23
```
