### ISSUE TITLE
RSS Sync Fails if one feed fails

### ISSUE THREAD

**Issue by markus101** [Sonarr/Sonarr#1165]
A bad RSS feed caused the entire RSS Sync to fail. `FetchAndParseRssService` should probably have a try/catch.

```
16-3-2 17:52:42.4|Info|RssSyncService|Starting RSS Sync
16-3-2 17:52:42.9|Error|TaskExtensions|Task Error
 
NzbDrone.Core.Indexers.Exceptions.UnsupportedFeedException: Empty feed, cannot check if feed is parsable.
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.GetGenericTorrentRssParserSettings(IndexerResponse response, TorrentRssIndexerSettings indexerSettings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 120
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.GetParserSettings(IndexerResponse response, TorrentRssIndexerSettings indexerSettings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 69
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssSettingsDetector.Detect(TorrentRssIndexerSettings indexerSettings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssSettingsDetector.cs:line 57
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.DetectParserSettings(TorrentRssIndexerSettings indexerSettings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:line 55
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.<>c__DisplayClass2.<GetParser>b__1() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:line 32
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Cache\Cached.cs:line 87
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssParserFactory.GetParser(TorrentRssIndexerSettings indexerSettings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssParserFactory.cs:line 32
   at NzbDrone.Core.Indexers.TorrentRss.TorrentRssIndexer.GetParser() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\TorrentRss\TorrentRssIndexer.cs:line 38
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(IndexerPageableRequestChain pageableRequestChain, Boolean isRecent) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 119
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchRecent() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 51
   at NzbDrone.Core.Indexers.FetchAndParseRssService.<>c__DisplayClass5.<Fetch>b__2() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\FetchAndParseRssService.cs:line 50
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
 
16-3-2 17:52:44.2|Error|CommandExecutor|Error occurred while executing task RssSync
```

**Comment by markus101** [comment]
Fixed in https://github.com/Sonarr/Sonarr/commit/5a877cbd627a66fd0e046a49006275bc5de67350
