### ISSUE TITLE
rtorrent compatibility

### ISSUE THREAD

**Issue by d2dyno** [Sonarr/Sonarr#1199]
I started using a dedicated seedbox, and integrated it with Sonarr. When Sonarr tries to send a release to rtorrent, through rutorrent, the following error occurs:

[v2.0.0.3953] CookComputing.XmlRpc.XmlRpcFaultException: **Server returned a fault exception: [-506] Method 'system.method.set_key' not defined**
at CookComputing.XmlRpc.XmlRpcSerializer.DeserializeResponse(XmlDocument xdoc, Type returnType)
at CookComputing.XmlRpc.XmlRpcSerializer.DeserializeResponse(Stream stm, Type svcType)
at CookComputing.XmlRpc.XmlRpcClientProtocol.ReadResponse(XmlRpcRequest req, WebResponse webResp, Stream respStm, Type returnType)
at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(Object clientObj, MethodInfo mi, Object[] parameters)
at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(MethodInfo mi, Object[] Parameters)
at XmlRpcProxyfc166f13-322f-473c-ba6b-ff0e75ae9daa.SetKey(String key, String cmd_key, String value)
at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.SetDeferredMagnetProperties(String hash, String category, String directory, RTorrentPriority priority, RTorrentSettings settings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 244
at NzbDrone.Core.Download.Clients.RTorrent.RTorrent.AddFromMagnetLink(RemoteEpisode remoteEpisode, String hash, String magnetLink) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrent.cs:line 52
at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromMagnetUrl(RemoteEpisode remoteEpisode, String magnetUrl) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 176
at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteEpisode remoteEpisode) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 75
at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteEpisode remoteEpisode) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\DownloadService.cs:line 66
at NzbDrone.Api.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 67
at NzbDrone.Api.Indexers.ReleaseModule.<.ctor>b__0(Object x) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 46
at CallSite.Target(Closure , CallSite , Func`2 , Object )
at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

I sent a ticket to the host thinking it was an issue on their end, but they said "This program is using old rtorrent commands, "system.method.set_key" has not been used since rtorrent 0.9.3". Would it be possible to update this within Sonar?

**Comment by markus101** [comment]
Looks like its now `method.set_key`, but other parts of the command might have changed:

https://github.com/rakshasa/rtorrent/issues/242

**Comment by d2dyno** [comment]
@markus101 Ok, I had seen that issue on Github in my search for answers earlier. What do I need to change where (if possible, I'm on Windows), in order to patch this up?

**Comment by markus101** [comment]
That was mostly for future us as we look into solving it, I don't have a rtorrent setup at the moment, but wanted to make sure my brief research was useful.

Without fixing it and re-compiling Sonarr there isn't a way to patch it.

**Comment by markus101** [comment]
z

**Comment by d2dyno** [comment]
Ah ok. Sure thing. I'll patiently wait for a fix then :)
