### ISSUE TITLE
Cannot connect to Deluge Web service

### ISSUE THREAD

**Issue by martylavender** [Sonarr/Sonarr#1281]
Deluge service is running
WebUI is accessible

If the password is wrong I get an authentication error
If the password is correct the test fails and the following is logged by Sonarr:

```
[v2.0.0.3953] System.Net.WebException: The request was aborted: The operation has timed out.
   at NzbDrone.Core.Rest.RestSharpExtensions.ValidateResponse(IRestResponse response, IRestClient restClient) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Rest\RestSharpExtensions.cs:line 33
   at NzbDrone.Core.Rest.RestSharpExtensions.Read[T](IRestResponse restResponse, IRestClient restClient) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Rest\RestSharpExtensions.cs:line 60
   at NzbDrone.Core.Rest.RestSharpExtensions.ExecuteAndValidate[T](IRestClient client, IRestRequest request) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Rest\RestSharpExtensions.cs:line 72
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult](IRestClient client, String action, Object[] arguments) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 226
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ConnectDaemon(IRestClient restClient) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 296
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.AuthenticateClient(IRestClient restClient) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 275
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult](DelugeSettings settings, String action, Object[] arguments) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 189
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.GetVersion(DelugeSettings settings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 50
   at NzbDrone.Core.Download.Clients.Deluge.Deluge.TestConnection() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:line 203

16-5-5 20:23:04.2|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unknown exception: The request was aborted: The operation has timed out.
```

**Comment by markus101** [comment]
Please open a thread on the forums for support.

But deluge is failing to respond in a timely matter when Sonarr attempts to connect to the daemon through the web API.
