### ISSUE TITLE
handle responses more gracefully when sonarr is unable to reach the internet

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#1306]
recently i lost internet at my old house and saw sonarr flood my logs with things such as:

`Request Failed: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.`

```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Serializer\Json.cs:line 37
   at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\HttpResponse.cs:line 97
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\HttpClient.cs:line 199
   at NzbDrone.Core.Update.UpdatePackageProvider.GetRecentUpdates(String branch, Version currentVersion) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Update\UpdatePackageProvider.cs:line 51
   at NzbDrone.Core.Update.RecentUpdateProvider.GetRecentUpdatePackages() in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Update\RecentUpdateProvider.cs:line 27
   at NzbDrone.Api.Update.UpdateModule.GetRecentUpdates() in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\Update\UpdateModule.cs:line 21
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__32_0(Object options) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\REST\RestModule.cs:line 111
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

and also things like:

`Couldn't refresh info for [296654][Criminal Minds: Beyond Borders]: Unexpected character encountered while parsing value: ﻿. Path '', line 0, position 0.`

```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: ﻿. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Serializer\Json.cs:line 37
   at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\HttpResponse.cs:line 97
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\HttpClient.cs:line 199
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetSeriesInfo(Int32 tvdbSeriesId) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 40
   at NzbDrone.Core.Tv.RefreshSeriesService.RefreshSeriesInfo(Series series) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Tv\RefreshSeriesService.cs:line 57
   at NzbDrone.Core.Tv.RefreshSeriesService.Execute(RefreshSeriesCommand message) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Tv\RefreshSeriesService.cs:line 164
```

**Comment by markus101** [comment]
I did some looking and it looks like we'd only run into this if there was a response, but its not valid JSON, since we don't try to parse the JSON if there isn't a response at all. We could prevent it from blowing up as it is right now, but we'd still end up logging some error there, we'd have a shorter stack trace.

@kayone @Taloth what do you guys think about logging a better message there? Not sure if gives us much except for a smaller stack trace.

**Comment by kayone** [comment]
I think it might be nicer if we check the response content type and log that with status code if not `application/json` instead of blindly trying to deserialize it.

**Comment by Taloth** [comment]
For kat we check against text/html only and reject that. A little bit less strict than demanding application/json.

**Comment by markus101** [comment]
Covered by https://github.com/Sonarr/Sonarr/commit/ae6d920e2a049e6b4993dfec62e384809fe83b30
