### ISSUE TITLE
Hdbits indexer fails after api change

### ISSUE THREAD

**Issue by joggs** [Sonarr/Sonarr#1443]
The hdbits api has changed and the result is the the hdbits indexer is not working.

 i see in the log that sonarr tries to convert the id to an int64. The id is a hash now, right, which means that you will get a  conversion error:

Newtonsoft.Json.JsonSerializationException: Error converting value "2aa43e456d6c5ddb1ad03e7ac70a416ea4a2be84e478045ae390814327c5d2fee581ad21b8f056a49cfbd1fddd5bb8c6fb1353caaa17dd3666b55e1383c27fc5" to type 'System.Int64'. Path '[0].id'. ---> System.FormatException: Input string was not in a correct format. at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
at System.String.System.IConvertible.ToInt64(IFormatProvider provider)
at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
--- End of inner exception stack trace ---

 A solution could be to probably just remove the id from the request and set id to string in the response

**Comment by joggs** [comment]
Update 160830: I spoke with the hdbits developer and the change has been reverted, so it works for now.
To be ready, we should use a more generic solution that can handle hashes/letters as id, and not only numbers, eg remove the Int64 cast
