### ISSUE TITLE
deluge on seedbox stays connected for a few minutes at a time then disconnects. 

### ISSUE THREAD

**Issue by sch1308** [Sonarr/Sonarr#1447]
NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to Deluge, please check your settings ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 67
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\HttpClient.cs:line 65
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult](JsonRpcRequestBuilder requestBuilder, String method, Object[] arguments) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 209
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult](JsonRpcRequestBuilder requestBuilder, String method, Object[] arguments) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 235
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult](DelugeSettings settings, String method, Object[] arguments) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 181
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.GetTorrentsByLabel(String label, DelugeSettings settings) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 81
   at NzbDrone.Core.Download.Clients.Deluge.Deluge.GetItems() in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:line 94

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
Please open a thread on the forums with the requested information.
