### ISSUE TITLE
Sonarr 2.0.0.4323 and Sabnzbd 1.1.0 no longer able to connect

### ISSUE THREAD

**Issue by almapavi** [Sonarr/Sonarr#1456]
This issue has appeared with the version below. Was working before the update.

I have a backup so I will revert back but how do I prevent auto update?

Thanks.

**Sonarr version : 2.0.0.4323
SABNZBD : Version:	1.1.0 [8abcf08]
Windows
Sabnzbd	Unable to connect to SABnzbd, please check your settings: Unable to connect to SABnzbd, please check your settings

NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to SABnzbd, please check your settings ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
at System.Net.HttpWebRequest.GetResponse()
at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 67
at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\HttpClient.cs:line 65
at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 167
--- End of inner exception stack trace ---
at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 175
at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.GetHistory(Int32 start, Int32 limit, String category, SabnzbdSettings settings) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 109
at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.GetHistory() in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Sabnzbd\Sabnzbd.cs:line 115

Debug:
16-9-11 14:29:07.6|Debug|Api|[GET] /api/log/file: 200.OK (156 ms)
16-9-11 14:29:07.7|Debug|Api|[GET] /api/log/file: 200.OK (15 ms)
16-9-11 14:29:07.7|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (15 ms)
16-9-11 14:29:07.9|Debug|SabnzbdProxy|Url: https://X.Y.Z.30:9090/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
16-9-11 14:29:07.9|Warn|Sabnzbd|Couldn't get download queue. Unable to connect to SABnzbd, please check your settings
16-9-11 14:29:07.9|Debug|SabnzbdProxy|Url: https://X.Y.Z.30:9090/api?mode=history&start=0&limit=30&category=tv&apikey=(removed)&output=json
16-9-11 14:29:07.9|Error|Sabnzbd|Unable to connect to SABnzbd, please check your settings

**Comment by markus101** [comment]
Looks like this is caused by an old SSL cert, possibly an old signature type that is not supported with TLS 1.1 or 1.2.
