### ISSUE TITLE
Error: MetadataService failed while processing 

### ISSUE THREAD

**Issue by seanvree** [Sonarr/Sonarr#1457]
Running Sonarr Sonarr Ver. 2.0.0.4322 develop on Windows 10 Enterprise

I get this error about every 30 mintues in my logs:
Message:

MetadataService failed while processing [MediaCoversUpdatedEvent]: Object reference not set to an instance of an object

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Metadata.MetadataService.ProcessSeriesImages(IMetadata consumer, Series series, List`1 existingMetadataFiles) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Metadata\MetadataService.cs:line 265
   at NzbDrone.Core.Metadata.MetadataService.Handle(MediaCoversUpdatedEvent message) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Metadata\MetadataService.cs:line 64
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

**Comment by markus101** [comment]
Please open a thread on the forums with the information requested when opening the thread. We'll also need to know which Metadata consumers are enabled in Sonarr's settings.
