### ISSUE TITLE
SabNZBD Error that started recently for some reason - failing downloads

### ISSUE THREAD

**Issue by russdyer** [Sonarr/Sonarr#1479]
NzbDrone.Core.Download.Clients.DownloadClientException: Error response received from SABnzbd: 
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.CheckForError(HttpResponse response) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 208
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.ProcessRequest(HttpRequestBuilder requestBuilder, SabnzbdSettings settings) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 178
   at NzbDrone.Core.Download.Clients.Sabnzbd.SabnzbdProxy.DownloadNzb(Byte[] nzbData, String filename, String category, Int32 priority, SabnzbdSettings settings) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Sabnzbd\SabnzbdProxy.cs:line 45
   at NzbDrone.Core.Download.Clients.Sabnzbd.Sabnzbd.AddFromNzbFile(RemoteEpisode remoteEpisode, String filename, Byte[] fileContent) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Sabnzbd\Sabnzbd.cs:line 40
   at NzbDrone.Core.Download.UsenetClientBase`1.Download(RemoteEpisode remoteEpisode) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\UsenetClientBase.cs:line 75
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteEpisode remoteEpisode) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\DownloadService.cs:line 66
   at NzbDrone.Api.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 67
   at NzbDrone.Api.Indexers.ReleaseModule.<.ctor>b__7_0(Object x) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 46
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by markus101** [comment]
SAB returned an error response. Trace logs should show what the error was (for some reason that wasn't logged).

**Comment by russdyer** [comment]
SAB error is that the nzb file is empty. This happens on every download
that Sonarr sends.

**Comment by markus101** [comment]
Which indexer? Have you tried another? Empty NZB means Sonarr got an empty NZB from the indexer.

**Comment by russdyer** [comment]
Oznbz. Didn't think it was an indexer issue as it works fine in CouchPotato?

**Comment by markus101** [comment]
Check trace/debug logs for the URL Sonarr is using to get the NZB, downloading it in a browser should confirm. If not we need to see the full logs with the error, not a snippet.


P.S. Really this should have been filed on the support forums (where it asks you for the appropriate information up front).
