### ISSUE TITLE
Repeated Null Ref Exception from RSS parser in logs when 'bad' RSS feed encountered

### ISSUE THREAD

**Issue by itb2k13** [Sonarr/Sonarr#1563]
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Indexers.RssParser.GetDownloadUrl(XElement item) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\RssParser.cs:line 195
   at NzbDrone.Core.Indexers.RssParser.ProcessItem(XElement item, ReleaseInfo releaseInfo) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\RssParser.cs:line 150
   at NzbDrone.Core.Indexers.TorrentRssParser.ProcessItem(XElement item, ReleaseInfo releaseInfo) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\TorrentRssParser.cs:line 38
   at NzbDrone.Core.Indexers.RssParser.ProcessItem(XElement item) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\RssParser.cs:line 138
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Indexers\RssParser.cs:line 58

**Comment by itb2k13** [comment]
Generated by component 'EzrssTorrentRssParser'

**Comment by markus101** [comment]
What feed is Sonarr trying to parse?
Has this feed worked previously?

**Comment by markus101** [comment]
Not enough information, closing.
