### ISSUE TITLE
Unable to perform manual search

### ISSUE THREAD

**Issue by seanvree** [Sonarr/Sonarr#1755]
Windows 10E
Version 2.0.0.4651 (Develop)

Not sure when this started happening, but it works fine when it searches automatically. when I choose manual search, it just sists there and spins. I never get any results.  

Using both Jackett and NZBHydra.  I can test the indexers just fine. 

[v2.0.0.4651] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.UpgradeDiskSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\Specifications\UpgradeDiskSpecification.cs:line 25
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 135

17-3-11 19:52:36.0|Error|DownloadDecisionMaker|Couldn't evaluate decision on The.Venture.Bros.S01E02.Careers.in.Science.DVDRip.DD2.0.x264-Atomsk

[v2.0.0.4651] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.CutoffSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\Specifications\CutoffSpecification.cs:line 25
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 135

17-3-11 19:52:36.0|Error|DownloadDecisionMaker|Couldn't evaluate decision on The.Venture.Bros.S01E02.Careers.in.Science.DVDRip.DD2.0.x264-Atomsk

[v2.0.0.4651] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.UpgradeDiskSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\Specifications\UpgradeDiskSpecification.cs:line 25
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 135

17-3-11 19:52:36.0|Error|DownloadDecisionMaker|Couldn't evaluate decision on The.Venture.Bros.S01E02.INTERNAL.DVDRip.XviD-RiTALiX

[v2.0.0.4651] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.CutoffSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\Specifications\CutoffSpecification.cs:line 25
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 135

17-3-11 19:52:36.0|Error|DownloadDecisionMaker|Couldn't evaluate decision on The.Venture.Bros.S01E02.INTERNAL.DVDRip.XviD-RiTALiX

[v2.0.0.4651] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.UpgradeDiskSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\Specifications\UpgradeDiskSpecification.cs:line 25
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 135

17-3-11 19:52:36.0|Error|DownloadDecisionMaker|Couldn't evaluate decision on The.Venture.Bros.S01E02.iNTERNAL.DVDRip.XviD-RiTALiX

[v2.0.0.4651] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.CutoffSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\Specifications\CutoffSpecification.cs:line 25
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 135

17-3-11 19:52:36.0|Error|DownloadDecisionMaker|Couldn't evaluate decision on The.Venture.Bros.S01E02.iNTERNAL.DVDRip.XviD-RiTALiX

[v2.0.0.4651] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.UpgradeDiskSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\Specifications\UpgradeDiskSpecification.cs:line 25
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 135

17-3-11 19:52:36.1|Error|DownloadDecisionMaker|Couldn't evaluate decision on The.Venture.Bros.S01E02.720p.BluRay.x264-YELLOWBiR...

[v2.0.0.4651] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.CutoffSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\Specifications\CutoffSpecification.cs:line 25
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 135

17-3-11 19:52:36.1|Error|DownloadDecisionMaker|Couldn't evaluate decision on The.Venture.Bros.S01E02.720p.BluRay.x264-YELLOWBiR...

[v2.0.0.4651] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.UpgradeDiskSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\Specifications\UpgradeDiskSpecification.cs:line 25
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 135

17-3-11 19:52:36.1|Error|DownloadDecisionMaker|Couldn't evaluate decision on The.Venture.Bros.S01E02.BDRip.x264-PHASE

[v2.0.0.4651] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.CutoffSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\Specifications\CutoffSpecification.cs:line 25
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 135

17-3-11 19:52:36.1|Error|DownloadDecisionMaker|Couldn't evaluate decision on The.Venture.Bros.S01E02.BDRip.x264-PHASE

[v2.0.0.4651] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.DecisionEngine.Specifications.UpgradeDiskSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\Specifications\UpgradeDiskSpecification.cs:line 25
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:line 135

**Comment by markus101** [comment]
Based on the logs it looks like Sonarr thinks that episode has a file, but there isn't one in the database. If you refresh the series do you have the same issue?
Did you recently remove the episode file for that episode from disk?

**Comment by seanvree** [comment]
@markus101  - 

Nope this is a new episode.  never searched before.

**Comment by markus101** [comment]
Can you PM me a copy of nzbdrone.db on the forums, I want to confirm my suspicions as to why this is happening. I have the same username there.

**Comment by seanvree** [comment]
@markus101  Sent.

**Comment by seanvree** [comment]
@markus101 - any update on this?

**Comment by markus101** [comment]
I've taken a look at this a couple times and the error in the logs seems to be caused by a scenario where an episode file exists, but is deleted after the results are parsed, but are still processing, which isn't a very big window usually, but based on the number of indexers you have (!!!) processing the results could take a while. The error itself will lead to an error message being shown instead of the reason for a rejection in manual search and with that many indexers depending on the total number of results it could take a while to go through them all. 

I've pushed a fix to better handle with this scenario though.

**Comment by seanvree** [comment]
@markus101 - Yeah, this seemed to have worked! Thanks!
