### ISSUE TITLE
RefreshSeries: The underlying connection was closed: The connection was closed unexpectedly.

### ISSUE THREAD

**Issue by jdchandler** [Sonarr/Sonarr#1785]
Windows Server 2012 R2
Sonarr Version 2.0.0.4645

I am trying to refresh my series as I have added some episodes and wanted to update the series accordingly. However every time I refresh I get the follow series of errors:

> Failed to Update Scene Mappings.: The underlying connection was closed: The connection was closed unexpectedly.

```
System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 76
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 60
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 198
   at NzbDrone.Core.DataAugmentation.Xem.XemProxy.GetSceneTvdbNames() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Xem\XemProxy.cs:line 82
   at NzbDrone.Core.DataAugmentation.Xem.XemService.GetSceneMappings() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Xem\XemService.cs:line 197
   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingService.UpdateMappings() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Scene\SceneMappingService.cs:line 151
Close
```

> Failed to Update Scene Mappings.: The underlying connection was closed: The connection was closed unexpectedly.

```
System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 76
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 60
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 198
   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingProxy.Fetch() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Scene\SceneMappingProxy.cs:line 29
   at NzbDrone.Core.DataAugmentation.Scene.ServicesProvider.GetSceneMappings() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Scene\ServicesProvider.cs:line 16
   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingService.UpdateMappings() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Scene\SceneMappingService.cs:line 151
```

> Error occurred while executing task RefreshSeries: The underlying connection was closed: The connection was closed unexpectedly.

```
System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 76
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 60
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 198
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetSeriesInfo(Int32 tvdbSeriesId) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 40
   at NzbDrone.Core.Tv.RefreshSeriesService.RefreshSeriesInfo(Series series) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Tv\RefreshSeriesService.cs:line 57
   at NzbDrone.Core.Tv.RefreshSeriesService.Execute(RefreshSeriesCommand message) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Tv\RefreshSeriesService.cs:line 154
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41
Close

```
I have been running for like a year now and haven't ever had this issue.

I came across a forum thread with similar issues as I had for an earlier version and the fix was to run this command at the command prompt: netsh interface tcp set global ecncapability=disabled

This did not solve the issue. I have restarted Sonarr but not yet the server.

Any insight?

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by markus101** [comment]
Please use the forums for support.

It looks like CloudFlare closed the connection (if you're running over a VPN this can happen more often). You can try loading http://skyhook.sonarr.tv/v1/tvdb/shows/en/79488 in a browser to test.
