### ISSUE TITLE
Issue Adding New Series

### ISSUE THREAD

**Issue by Fiala06** [Sonarr/Sonarr#1840]
Trying to add: Pride and Prejudice (1995) and it doesn't go through. I checked the logs and is posted below. Not sure what it means. 

Running version: 2.0.0.4689

Message:
Request Failed. POST /api/series: Object reference not set to an instance of an object.

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Tv.SeriesTitleSlugValidator.<>c__DisplayClass2_0.<IsValid>b__0(Series s) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Tv\SeriesTitleSlugValidator.cs:line 22
   at System.Collections.Generic.List`1.FindIndex(Int32 startIndex, Int32 count, Predicate`1 match)
   at NzbDrone.Core.Tv.SeriesTitleSlugValidator.IsValid(PropertyValidatorContext context) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Tv\SeriesTitleSlugValidator.cs:line 22
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in C:\projects\FluentValidation\src\FluentValidation\Validators\PropertyValidator.cs:line 79
   at FluentValidation.Internal.PropertyRule.InvokePropertyValidator(ValidationContext context, IPropertyValidator validator, String propertyName) in C:\projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 368
   at FluentValidation.Internal.PropertyRule.<Validate>d__60.MoveNext() in C:\projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 242
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in C:\projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 114
   at FluentValidation.AbstractValidator`1.Validate(T instance) in C:\projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 95
   at NzbDrone.Core.Tv.AddSeriesService.AddSeries(Series newSeries) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Tv\AddSeriesService.cs:line 58
   at NzbDrone.Api.Series.SeriesModule.AddSeries(SeriesResource seriesResource) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\Series\SeriesModule.cs:line 119
   at NzbDrone.Api.REST.RestModule`1.<set_CreateResource>b__41_0(Object options) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\REST\RestModule.cs:line 155
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by Tophicles** [comment]
Was just about to post this very same issue. Occurred after upgrading to Version 2.0.0.4689.
Not complaining, merely observing and relating :)

**Comment by markus101** [comment]
Related forum post has more information on this issue: https://forums.sonarr.tv/t/problem-adding-series/14359/7
