### ISSUE TITLE
Usenet Crawler - parsing error

### ISSUE THREAD

**Issue by gregorij89** [Sonarr/Sonarr#1913]
Hi,

probably Usenet Crawler changed their XML schema, or anything else happened because my Sonarr deployment is unable to communicate with this indexer for almost a week. The relevant part of the log is:

17-5-9 22:31:27.8|Info|NzbSearchService|Searching 8 indexers for [Gotham : S01E20]
17-5-9 22:31:28.7|Error|Newznab|An error occurred while processing feed. https://www.usenet-crawler.com/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=274431&rid=38049&tvmazeid=11&season=1&ep=20

[v2.0.0.4689] System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NzbDrone.Core.Indexers.RssParser.LoadXmlDocument(IndexerResponse indexerResponse) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\RssParser.cs:line 96
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess(IndexerResponse indexerResponse) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\NewznabRssParser.cs:line 21
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\RssParser.cs:line 50
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 284
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(IndexerPageableRequestChain pageableRequestChain, Boolean isRecent) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 142

17-5-9 22:31:35.0|Info|DownloadDecisionMaker|Processing 46 releases
17-5-9 22:31:36.0|Info|EpisodeSearchService|Episode search completed. 0 reports downloaded.

Weird thing is that in Radarr, it is working without any issue.

Gregorij.

**Comment by markus101** [comment]
> probably Usenet Crawler changed their XML schema, or anything else happened because my Sonarr deployment is unable to communicate with this indexer for almost a week

If they changed the schema they'd no longer be following the Newznab spec and not be supported.

> System.Xml.XmlException: Root element is missing.

Sometimes, not every request they are returning a completely empty response from their API, other times it works properly.

> Weird thing is that in Radarr, it is working without any issue.

Perhaps only affecting TV searches or Radarr is getting lucky, since it fails in Chrome about 25% of the time or more for me. You'll need to contact the admins of usenet crawler for them to investigate.

> Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Next time please use the forum for support.
