### ISSUE TITLE
Cannot connect Deluge to Sonarr

### ISSUE THREAD

**Issue by Quiksmage** [Sonarr/Sonarr#1936]
Hi, 

I have filled in 
```
host: 192.168.1.74
port: 8112
Password: password I set 
```
into Sonarr, but when clicking test, it's throwing an error.

Here is a trace log of my test.

```
17-5-17 11:18:22.4|Trace|Http|Req: 2995 [POST] /api/downloadclient/test
17-5-17 11:18:22.4|Trace|HttpClient|Req: [POST] http://192.168.1.74:8112/json: daemon.info()
17-5-17 11:18:22.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-5-17 11:18:22.4|Trace|HttpClient|Res: [POST] http://192.168.1.74:8112/json: 200.OK (8 ms)
17-5-17 11:18:22.5|Trace|HttpClient|Response content (53 bytes): {"id": "86f8ba44", "result": "1.3.12", "error": null}
17-5-17 11:18:22.5|Trace|HttpClient|Req: [POST] http://192.168.1.74:8112/json: core.get_enabled_plugins()
17-5-17 11:18:22.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-5-17 11:18:22.5|Trace|HttpClient|Res: [POST] http://192.168.1.74:8112/json: 200.OK (5 ms)
17-5-17 11:18:22.5|Trace|HttpClient|Response content (157 bytes): {"id": "73522644", "result": ["TotalTraffic", "Stats", "AutoAdd", "Label", "Notifications", "WebUi", "SeedTime", "browsebutton", "MoveTools"], "error": null}
17-5-17 11:18:22.5|Trace|HttpClient|Req: [POST] http://192.168.1.74:8112/json: label.get_labels()
17-5-17 11:18:22.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-5-17 11:18:22.5|Trace|HttpClient|Res: [POST] http://192.168.1.74:8112/json: 200.OK (7 ms)
17-5-17 11:18:22.5|Trace|HttpClient|Response content (162 bytes): {"id": "d1311fd8", "result": ["ahd", "apollo", "btn", "iptorrents", "mtv", "pth", "ptp", "radarr", "sonarr", "sonarr-tv", "torrentday", "what.cd"], "error": null}
17-5-17 11:18:22.5|Trace|HttpClient|Req: [POST] http://192.168.1.74:8112/json: label.add("sonarr-TV")
17-5-17 11:18:22.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-5-17 11:18:37.5|Error|Deluge|Test aborted due to exception

[v2.0.0.4753] NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to Deluge, please check your settings ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 76
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 60
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 70
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult](JsonRpcRequestBuilder requestBuilder, String method, Object[] arguments) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 208
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult](JsonRpcRequestBuilder requestBuilder, String method, Object[] arguments) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 234
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult](DelugeSettings settings, String method, Object[] arguments) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 180
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.AddLabel(String label, DelugeSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 153
   at NzbDrone.Core.Download.Clients.Deluge.Deluge.TestCategory() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:line 251
   at NzbDrone.Core.Download.Clients.Deluge.Deluge.Test(List`1 failures) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:line 182
   at NzbDrone.Core.Download.DownloadClientBase`1.Test() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\DownloadClientBase.cs:line 116

17-5-17 11:18:37.5|Trace|NzbDroneErrorPipeline|Handling Exception
17-5-17 11:18:37.5|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Test was aborted due to an error: Unable to connect to Deluge, please check your settings
17-5-17 11:18:37.5|Trace|Http|Res: 2995 [POST] /api/downloadclient/test: 400.BadRequest (15091 ms)
17-5-17 11:18:37.5|Debug|Api|[POST] /api/downloadclient/test: 400.BadRequest (15091 ms)
17-5-17 11:18:40.8|Trace|Http|Req: 2996 [GET] /api/health
17-5-17 11:18:40.8|Trace|Http|Res: 2996 [GET] /api/health: 200.OK (0 ms)
17-5-17 11:18:40.8|Debug|Api|[GET] /api/health: 200.OK (0 ms)
17-5-17 11:18:40.8|Trace|Http|Req: 2997 [GET] /api/diskspace
17-5-17 11:18:40.8|Trace|Http|Req: 2998 [GET] /api/health
17-5-17 11:18:40.8|Trace|Http|Res: 2998 [GET] /api/health: 200.OK (15 ms)
17-5-17 11:18:40.8|Debug|Api|[GET] /api/health: 200.OK (15 ms)
17-5-17 11:18:41.8|Trace|Http|Req: 2999 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc
17-5-17 11:18:41.8|Trace|Http|Res: 2999 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (31 ms)
17-5-17 11:18:41.8|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (31 ms)
17-5-17 11:18:41.9|Trace|Http|Req: 3000 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc
17-5-17 11:18:41.9|Trace|Http|Res: 3000 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (31 ms)
17-5-17 11:18:41.9|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (31 ms)
17-5-17 11:18:42.5|Trace|Http|Req: 3001 [GET] /api/log/file
17-5-17 11:18:42.5|Trace|Http|Res: 3001 [GET] /api/log/file: 200.OK (15 ms)
17-5-17 11:18:42.5|Debug|Api|[GET] /api/log/file: 200.OK (15 ms)
17-5-17 11:18:42.6|Trace|Http|Req: 3002 [GET] /api/log/file/sonarr.trace.txt
```

Looking at the log, it looks like it's able to contact it as i see some information in there from the client. Do you know why it may be failing?

**Comment by markus101** [comment]
>Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

Please use the forums for support.

> Unable to connect to Deluge, please check your settings ---> System.Net.WebException: The operation has timed out

Deluge never responded to Sonarr's request, checking Deluge's WEB API logs (if there are any)
