### ISSUE TITLE
Not unblocking indexers after successful test 

### ISSUE THREAD

**Issue by Safihre** [Sonarr/Sonarr#1961]
I located this special episode via the Manual Search, but Sonarr wouldn't download it because it couldn't parse the titles (why not actually?), so I downloaded it manually from the indexer website using internet browser.

So that job has been in my SABnzbd history since then and it seems Sonarr has been trying to import it ever since. The file is not there anymore, I deleted it yesterday after watching.

Additionally, Sonarr has been showing "All indexers are unavailable due to failures" for the whole day now. I already did "Test" on all my indexers and it still shows this and doesn't want to download anything (in the log at `17-6-5 19:43:49.6`)
```
17-6-5 14:59:23.8|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 15:00:53.9|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 15:02:24.0|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 15:03:54.1|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 15:05:24.2|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 15:06:54.2|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 15:08:24.3|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 15:09:54.3|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
....
More of the same......
...
17-6-5 16:24:57.9|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 16:26:28.0|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 16:27:58.1|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 16:29:28.0|Info|RssSyncService|Starting RSS Sync
17-6-5 16:29:28.1|Warn|FetchAndParseRssService|No available indexers. check your configuration.
17-6-5 16:29:28.1|Info|DownloadDecisionMaker|No results found
17-6-5 16:29:28.1|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-6-5 16:29:28.1|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
....
More of the same......
...
17-6-5 16:53:29.0|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 16:54:59.0|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 16:56:29.1|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 16:57:59.1|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 16:59:29.2|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 17:00:59.3|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 17:02:29.3|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 17:03:59.4|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 17:05:29.4|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 17:06:59.4|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 17:08:29.5|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 19:43:49.6|Info|RssSyncService|Starting RSS Sync
17-6-5 19:43:49.6|Warn|FetchAndParseRssService|No available indexers. check your configuration.
17-6-5 19:43:49.6|Info|DownloadDecisionMaker|No results found
17-6-5 19:43:49.6|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-6-5 19:43:50.1|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 19:43:50.2|Info|SceneMappingService|Updating Scene mappings
....
More of the same......
...
17-6-5 20:24:20.8|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 20:25:50.9|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 20:27:20.9|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 20:28:51.0|Info|RssSyncService|Starting RSS Sync
17-6-5 20:28:51.0|Warn|FetchAndParseRssService|No available indexers. check your configuration.
17-6-5 20:28:51.0|Info|DownloadDecisionMaker|No results found
17-6-5 20:28:51.0|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-6-5 20:28:51.2|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
....
More of the same......
...
17-6-5 20:46:51.6|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 20:48:21.6|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 20:49:51.8|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 20:51:21.7|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
17-6-5 20:52:51.8|Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: C:\Users\USER\Videos\Complete\Catfish.The.TV.Show.S06E00.The.Untold.Stories.Part.9.1080p.WEB.x264-TBS
```

**Comment by Taloth** [comment]
Hey Safihre, that's why we always recommend ppl to have a separate category in sab for stuff that Sonarr should auto-import.
The only way to get rid of downloads with deleted files is to remove the item from sab history, or change the category.

Did those indexer tests return success? If so, what was the first indexer error logged afterwards?

**Comment by Safihre** [comment]
While I am looking at the log, this error appears every time before/after a shutdown/restart of Sonarr, always 3 times. And then it starts just fine.
```
17-6-5 10:23:57.8|Info|ConsoleApp|Exiting main.
17-6-5 10:23:58.0|Info|ServiceProvider|NzbDrone has stopped successfully.
17-6-5 10:23:57.5|Error|CommandExecutor|Unknown error in thread

[v2.0.0.4800] System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.<GetConsumingEnumerable>d__68.MoveNext()
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 37

17-6-5 10:23:57.5|Error|CommandExecutor|Unknown error in thread

[v2.0.0.4800] System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.<GetConsumingEnumerable>d__68.MoveNext()
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 37

17-6-5 10:23:57.5|Error|CommandExecutor|Unknown error in thread

[v2.0.0.4800] System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.<GetConsumingEnumerable>d__68.MoveNext()
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 37

17-6-5 10:25:40.1|Info|Bootstrap|Starting Sonarr - C:\ProgramData\NzbDrone\bin\NzbDrone.exe - Version 2.0.0.4800
17-6-5 10:25:40.7|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\NzbDrone\nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 10:25:40.9|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\NzbDrone\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 10:25:41.1|Info|Router|Application mode: Interactive
``

**Comment by Taloth** [comment]
Looks to me that that's just the shutdown terminating the 3 background threads that process commands in sonarr. I've never seen it log that error though. I'll look into that.

**Comment by Safihre** [comment]
Oke so I found the last time it reported an error for my indexers:
```
17-6-5 09:44:10.6|Error|Sabnzbd|Downloading nzb for episode 'Silicon.Valley.S04E07.720p.HDTV.x264-AVS' failed (http://api.nzbgeek.info/api?t=get&id=445b796ff56229515e34ed6f60ae8adf&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
```
After this I tested all of the 3 times. Around 11 this morning, 3 this afternoon, and now at 21:30.
But it doesn't seem to log tests.
I also restarted Sonarr and triggered a health check.

Maybe I'm not patient enough, but it's been stuck in this state since 9 this morning (12 hours ago).

**Comment by Taloth** [comment]
After a successful 'Test' like here:
![image](https://cloud.githubusercontent.com/assets/6383890/26799557/656238fa-4a36-11e7-8ca2-b567672a0841.png)
the indexer should automatically be used again in the next RSS Sync. But if the indexer fails again during that sync, or during nzb grab, then it will get hit with the automatic back-off again (which is cumulative from 5 min up to 24h iirc). It's kinda hard to explain, but if an indexer fails repeatedly even with intermittent successes, it gets disabled longer and longer, up to 24h.

> The remote name could not be resolved: 'api.nzbgeek.info'

Dns or connection issues?

**Comment by Safihre** [comment]
> but if an indexer fails repeatedly even with intermittent successes, it gets disabled longer and longer, up to 24h.

Yes, this is what happened!
I see in the log that this indexer was hit multiple times while my laptop was getting out of standby and connecting to the work network.
It seems to try every single release.
```
17-6-5 09:42:37.2|Error|Sabnzbd|Downloading nzb for episode 'Last.Week.Tonight.with.John.Oliver.S04E14.1080p.HBO.WEB-DL.AAC2.0.H.264-monkee-Obfuscated' failed (http://api.nzbgeek.info/api?t=get&id=0f6672473897dd1512e9dde586e5d04c&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
17-6-5 09:42:39.2|Error|Sabnzbd|Downloading nzb for episode 'Last.Week.Tonight.with.John.Oliver.S04E14.1080p.HBO.WEB-DL.AAC2.0.H.264-monkee' failed (http://api.nzbgeek.info/api?t=get&id=798f02658327c2ef52ae4fe2380e061f&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
17-6-5 09:42:41.2|Error|Sabnzbd|Downloading nzb for episode 'Last.Week.Tonight.With.John.Oliver.S04E14.1080p.WEB.h264-TBS-Obfuscated' failed (http://api.nzbgeek.info/api?t=get&id=ffff31b859b447d76e4207c734ce5699&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
17-6-5 09:42:43.2|Error|Sabnzbd|Downloading nzb for episode 'Last.Week.Tonight.With.John.Oliver.S04E14.1080p.WEB.h264-TBS' failed (http://api.nzbgeek.info/api?t=get&id=9aa449bd2162d29104f30df16e8dc24d&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
17-6-5 09:42:45.2|Error|Sabnzbd|Downloading nzb for episode 'Last.Week.Tonight.with.John.Oliver.S04E14.720p.WEBRip.AAC2.0.H.264-doosh-Obfuscated' failed (http://api.nzbgeek.info/api?t=get&id=7e3ddc412133ff3ebed7ecd8a6e13c1d&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
17-6-5 09:42:51.4|Error|Sabnzbd|Downloading nzb for episode 'Last.Week.Tonight.with.John.Oliver.S04E14.720p.WEB-DL.AAC2.0.H.264-doosh-Obfuscated' failed (http://api.nzbgeek.info/api?t=get&id=41a9aa399136ba8a31c031818997067b&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
17-6-5 09:42:53.4|Error|Sabnzbd|Downloading nzb for episode 'Last.Week.Tonight.with.John.Oliver.S04E14.720p.WEB-DL.AAC2.0.H.264-doosh' failed (http://api.nzbgeek.info/api?t=get&id=5428c03f4018cd119d9386c22df41985&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
17-6-5 09:42:55.4|Error|Sabnzbd|Downloading nzb for episode 'Last.Week.Tonight.with.John.Oliver.S04E14.720p.WEBRip.AAC2.0.H.264-doosh' failed (http://api.nzbgeek.info/api?t=get&id=e9dde6bb32370d83a82c4d7e8f0b3c09&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
17-6-5 09:42:57.7|Error|Sabnzbd|Downloading nzb for episode 'Last.Week.Tonight.With.John.Oliver.S04E14.720p.WEB.h264-TBS-Obfuscated' failed (http://api.nzbgeek.info/api?t=get&id=f86f5c6502050aa352a8d4c2dbfb4ab3&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
17-6-5 09:42:59.7|Error|Sabnzbd|Downloading nzb for episode 'Last.Week.Tonight.With.John.Oliver.S04E14.720p.WEB.h264-TBS' failed (http://api.nzbgeek.info/api?t=get&id=09d6fb36d4edfbad84123b95bb39ec3e&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
17-6-5 09:43:01.9|Error|Sabnzbd|Downloading nzb for episode 'Last.Week.Tonight.With.John.Oliver.S04E14.720p.HDTV.x264-BATV-Obfuscated' failed (http://api.nzbgeek.info/api?t=get&id=72689779af040de27ad51620de755894&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
17-6-5 09:43:03.9|Error|Sabnzbd|Downloading nzb for episode 'Last.Week.Tonight.With.John.Oliver.S04E14.720p.HDTV.x264-BATV' failed (http://api.nzbgeek.info/api?t=get&id=31b70b1287ce02f76ff9db60e10f950f&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
```
And then... It goes again for a different show! 

```
17-6-5 09:43:18.2|Error|Sabnzbd|Downloading nzb for episode 'Silicon.Valley.S04E07.The.Patent.Troll.1080p.HBO.WEB-DL.DD5.1.H.264-monkee-Scrambled' failed (http://api.nzbgeek.info/api?t=get&id=e4df01ba3467a846350cf42eb0c7552b&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'
17-6-5 09:43:20.2|Error|Sabnzbd|Downloading nzb for episode 'Silicon.Valley.S04E07.The.Patent.Troll.1080p.HBO.WEB-DL.DD5.1.H.264-monkee-Obfuscated' failed (http://api.nzbgeek.info/api?t=get&id=8eeba50be8fe50166f71d1d8c9e211f1&apikey=(removed) System.Net.WebException: The remote name could not be resolved: 'api.nzbgeek.info'

** And on and on and on!
```

**Comment by Safihre** [comment]
But the tests have succeeded every time after 9 this morning, showing the success popup every time.
In the log it shows that it did not try the sync again with that provider:
```
17-6-5 21:13:52.7|Warn|FetchAndParseRssService|No available indexers. check your configuration.
17-6-5 21:13:52.7|Info|DownloadDecisionMaker|No results found
```

**Comment by Taloth** [comment]
@markus101 You think we can detect the system coming out of standby? or detect a network change and give it a bit to stabilize?

Also, looks like Safihre is on the dev branch, could any of out latest changes have anything to do with it? Like store & forward?

What initially surprised me is that it manages to fetch the list of releases from the indexer, but can't fetch the nzb. As it's going through the options it fails to fetch the nzb. But that could just be the pending list.

@Safihre Do the releases show up in Activity->Queue as Pending or something?

**Comment by Safihre** [comment]
Yes indeed they did, they showed as Pending in the Queue.

Strange indeed that it found something. This is the first thing from the morning, where it cannot resolve anything via DNS but still finds 79 releases?
```
17-6-5 09:42:22.7|Info|RssSyncService|Starting RSS Sync
17-6-5 09:42:22.8|Warn|Newznab|PFmonkey https://www.pfmonkey.com/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100 The remote name could not be resolved: 'www.pfmonkey.com'
17-6-5 09:42:22.9|Warn|Newznab|AltHub https://api.althub.co.za/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100 The remote name could not be resolved: 'api.althub.co.za'
17-6-5 09:42:22.9|Warn|Newznab|6Box https://6box.me/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100 The remote name could not be resolved: '6box.me'
17-6-5 09:42:22.9|Warn|Newznab|NZBgeek https://api.nzbgeek.info/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100 The remote name could not be resolved: 'api.nzbgeek.info'
17-6-5 09:42:23.0|Info|DownloadDecisionMaker|Processing 79 releases
```

**Comment by Taloth** [comment]
It's a new feature on develop, if a download client is unavailable it can remember releases it saw. Next time the download client is available it will try the best release again until it can add it to the download client or 2weeks go by.
It's similar to the Delay Profile logic which put it in the 'pending' list too. Basically during Rss Sync, the results from the indexer + the pending list gets re-evaluated, re-sorted and then processed normally.

I guess we didn't account for this particular scenario, it doesn't actually 'hurt', it just spits out more errors and warnings than expected.

**Comment by markus101** [comment]
A bit broader than just after coming out of standby, but we've had this GHI open a for a while: https://github.com/Sonarr/Sonarr/issues/359

**Comment by Safihre** [comment]
It's now 24 hours later and it still is blocking all the indexers. I did Test's on all indexers again, all were successful, and another health check.
I think that's a bug?

**Comment by Safihre** [comment]
I would like it if Sonarr could maybe just want 2 minutes after coming out of hibernation/standy.
For example I switched my PC to standby in the evening, then it woke itself up at 2:00 to go into hibernation, but immediatly Sonarr starts running and failing because probably the wifi wasn't connected yet:
```
17-6-5 22:07:26.4|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
17-6-5 22:07:26.4|Info|ExistingExtraFileService|Found 0 extra files
17-6-6 02:08:15.3|Info|SceneMappingService|Updating Scene mappings
17-6-6 02:08:16.3|Info|RssSyncService|Starting RSS Sync
17-6-6 02:08:16.3|Warn|FetchAndParseRssService|No available indexers. check your configuration.
17-6-6 02:08:16.3|Info|DownloadDecisionMaker|No results found
17-6-6 02:08:16.3|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-6-6 02:08:15.4|Error|SceneMappingService|Failed to Update Scene Mappings.
[v2.0.0.4800] System.Net.WebException: The remote name could not be resolved: 'thexem.de'
17-6-6 02:08:16.4|Error|SceneMappingService|Failed to Update Scene Mappings.
[v2.0.0.4800] System.Net.WebException: The remote name could not be resolved: 'services.sonarr.tv'
17-6-6 08:59:52.5|Info|SceneMappingService|Updating Scene mappings
17-6-6 08:59:54.4|Info|RssSyncService|Starting RSS Sync
17-6-6 08:59:54.4|Warn|FetchAndParseRssService|No available indexers. check your configuration.
17-6-6 08:59:54.5|Info|DownloadDecisionMaker|No results found
17-6-6 08:59:54.5|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
```

**Comment by thezoggy** [comment]
i would say that you need to make that store n forward have a duration before the cache is dirty and cant be trusted.. 3 hours?

**Comment by Taloth** [comment]
Using the cache is fine, it just should be network connectivity aware. Or at least honor the indexer back-off once it becomes aware, so it doesn't log 10+ errors, but just 1.

**Comment by Taloth** [comment]
@markus101  I did a few fixes here.
First, there was a fault in my  refactoring of the ProviderStatus stuff, preventing Tests from reactivating indexers/download clients.
Second, I added a specification that keeps releases temporarily blocked if they came from an blocked indexer. That should prevent the flood of errors.

I dunno if that covers all the weird behavior seen in this issue, which is why I haven't closed it yet.

**Comment by Safihre** [comment]
@Taloth 👍 
I will watch my log the upcoming week, if nothing happens, we can close this.

**Comment by Taloth** [comment]
Tnx, the release isn't out yet, something weird happening with the build server, but I'm sure @markus101 will get it working later today.

**Comment by Safihre** [comment]
Con confirm that the fixes work.
Today again I was auto-connected to my work's public wifi which caused all indexers to fail, but clicking Test on them brought them back to life.
👍

**Comment by Safihre** [comment]
The restart-errors are still there though, but I guess they are non-trivial:
```
17-6-20 17:10:36.6|Error|CommandExecutor|Unknown error in thread

[v2.0.0.4831] System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.<GetConsumingEnumerable>d__68.MoveNext()
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 37

17-6-20 17:10:36.6|Error|CommandExecutor|Unknown error in thread

[v2.0.0.4831] System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.<GetConsumingEnumerable>d__68.MoveNext()
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 37

17-6-20 17:10:39.8|Info|Bootstrap|Starting Sonarr - C:\ProgramData\NzbDrone\bin\nzbdrone.console.exe - Version 2.0.0.4831
```

**Comment by Taloth** [comment]
Knew I forgot something... :)

**Comment by Safihre** [comment]
Totally unrelated side-question: a while ago I saw all that work on a new interface, is that still in the making? :)

**Comment by markus101** [comment]
Yup, still in the making. :)
