### ISSUE TITLE
Error when adding qBittorent as client (v. 2.0.0.4855 on Win 7)

### ISSUE THREAD

**Issue by jpfroud** [Sonarr/Sonarr#2032]
On Windows 7

Here are the settings on qBittorent:
http://i.imgur.com/zG0KY6K.png

No problem using browser:
http://i.imgur.com/3HSosVa.png

But on Sonarr:
http://i.imgur.com/o3R8q3z.png

Details
Message:
`Unable to test qBittorrent: Failed to connect to qBitTorrent, please check your settings.`

Exception
```
NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBitTorrent, please check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [401:Unauthorized] [POST] at [http://localhost:8083/login]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 106
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, QBittorrentSettings settings, Boolean reauthenticate) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 215
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, QBittorrentSettings settings, Boolean reauthenticate) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 225
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest[TResult](HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 156
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.GetVersion(QBittorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 45
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.TestConnection() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 191
```

**Comment by markus101** [comment]
Please use the forums for support. Make sure you are not using Qbit 3.3.13 as the API does not work (and has been covered here and the forums multiple times).

**Comment by jpfroud** [comment]
Sorry for duplicate, I did a search before though but couldn't find this info:
http://i.imgur.com/kdZ56ob.png
