### ISSUE TITLE
Errors without internet connection

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#2054]
noticed a few things today when I woke up to find that my internet is down.. posting errors w/exceptions

```
Failed to determine newznab api capabilities for https://althub.co.za, using the defaults instead till Sonarr restarts.: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.ParseCapabilities(HttpResponse response) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 86
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 67
```

```
Failed to Update Scene Mappings.: The remote name could not be resolved: 'services.sonarr.tv'
System.Net.WebException: The remote name could not be resolved: 'services.sonarr.tv'
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 76
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 60
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 198
   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingProxy.Fetch() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Scene\SceneMappingProxy.cs:line 29
   at NzbDrone.Core.DataAugmentation.Scene.ServicesProvider.GetSceneMappings() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Scene\ServicesProvider.cs:line 16
   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingService.UpdateMappings() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Scene\SceneMappingService.cs:line 152
```

```
Failed to Update Scene Mappings.: The remote name could not be resolved: 'thexem.de'
System.Net.WebException: The remote name could not be resolved: 'thexem.de'
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 76
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 60
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 198
   at NzbDrone.Core.DataAugmentation.Xem.XemProxy.GetSceneTvdbNames() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Xem\XemProxy.cs:line 82
   at NzbDrone.Core.DataAugmentation.Xem.XemService.GetSceneMappings() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Xem\XemService.cs:line 205
   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingService.UpdateMappings() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\DataAugmentation\Scene\SceneMappingService.cs:line 152
```

**Comment by markus101** [comment]
The first error looks like something we could clean up, but not sure if there is anything worthwhile for us to do for the other two errors, unless @Taloth thinks there is something worth doing.

**Comment by thezoggy** [comment]
The `.:` bugs me on the last two

**Comment by markus101** [comment]
> The `.:` bugs me on the last two

Got it, that's an easy fix.

Which version of Sonarr are you running? That first error seems a bit odd, unless Sonarr received a response somehow, but the line number doesn't correspond with where I think it would have failed.

**Comment by thezoggy** [comment]
Latest develop
