### ISSUE TITLE
Unable to connect to AltHub

### ISSUE THREAD

**Issue by nrlatsha** [Sonarr/Sonarr#2199]
Unable to add AltHub
17-9-30 16:50:05.7|Debug|NewznabCapabilitiesProvider|Failed to get newznab api capabilities from https://api.althub.co.za

[v2.0.0.4949] System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 82.118.236.91:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 95
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 53
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 55
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 220
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 57

17-9-30 16:50:05.8|Warn|Newznab|Unable to connect to indexer

[v2.0.0.4949] System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 82.118.236.91:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 95
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 53
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 55
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 220
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 62
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.<>c__DisplayClass4_0.<GetCapabilities>b__0() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 35
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Cache\Cached.cs:line 81
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities(NewznabSettings indexerSettings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 35
   at NzbDrone.Core.Indexers.Newznab.Newznab.get_PageSize() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\Newznab.cs:line 22
   at NzbDrone.Core.Indexers.Newznab.Newznab.GetRequestGenerator() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\Newznab\Newznab.cs:line 26
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 315

17-9-30 16:50:06.0|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
17-9-30 16:50:06.0|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (21297 ms)

**Comment by markus101** [comment]
Please use https://forums.sonarr.tv/ for support or other questions.
