### ISSUE TITLE
Dictionary key errors when executing post download script

### ISSUE THREAD

**Issue by awwwwwyup** [Sonarr/Sonarr#2274]
## Bug Report
Looking through my logs it seems to have started occurring after the Nov 5th update was downloaded and installed. A snippet of the latest entries detailing the exception are below.

### System Information/Logs
**Sonarr Version:** 2.0.0.5054
**Operating System:** Windows Server 2008 R2
**.net Framework:** .NET Framework 4.5.2

17-11-7 12:13:42.2|Error|ProcessProvider|Unable to set environment variable 'sonarr_eventtype'

[v2.0.0.5054] System.ArgumentException: Item has already been added. Key in dictionary: 'sonarr_eventtype'  Key being added: 'sonarr_eventtype'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Collections.Specialized.StringDictionaryWithComparer.Add(String key, String value)
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action1 onOutputDataReceived, Action1 onErrorDataReceived) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 136

17-11-7 12:13:44.4|Error|NotificationService|Unable to send OnGrab notification to AutoExtractor

[v2.0.0.5054] System.ArgumentException: Item has already been added. Key in dictionary: 'sonarr_eventtype'  Key being added: 'sonarr_eventtype'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Collections.Specialized.StringDictionaryWithComparer.Add(String key, String value)
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action1 onOutputDataReceived, Action1 onErrorDataReceived) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 150
   at NzbDrone.Common.Processes.ProcessProvider.StartAndCapture(String path, String args, StringDictionary environmentVariables) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 218
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.ExecuteScript(StringDictionary environmentVariables) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Notifications\CustomScript\CustomScript.cs:line 139
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.OnGrab(GrabMessage message) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Notifications\CustomScript\CustomScript.cs:line 60
   at NzbDrone.Core.Notifications.NotificationService.Handle(EpisodeGrabbedEvent message) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Notifications\NotificationService.cs:line 108

17-11-7 12:13:44.8|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 1
17-11-7 12:15:10.0|Error|ProcessProvider|Unable to set environment variable 'sonarr_download_id'

[v2.0.0.5054] System.ArgumentException: Item has already been added. Key in dictionary: 'sonarr_download_id'  Key being added: 'sonarr_download_id'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Collections.Specialized.StringDictionaryWithComparer.Add(String key, String value)
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action1 onOutputDataReceived, Action1 onErrorDataReceived) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 136

17-11-7 12:15:10.0|Warn|NotificationService|Unable to send OnDownload notification to: AutoExtractor

[v2.0.0.5054] System.ArgumentException: Item has already been added. Key in dictionary: 'sonarr_download_id'  Key being added: 'sonarr_download_id'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Collections.Specialized.StringDictionaryWithComparer.Add(String key, String value)
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action1 onOutputDataReceived, Action1 onErrorDataReceived) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 150
   at NzbDrone.Common.Processes.ProcessProvider.StartAndCapture(String path, String args, StringDictionary environmentVariables) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 218
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.ExecuteScript(StringDictionary environmentVariables) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Notifications\CustomScript\CustomScript.cs:line 139
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.OnDownload(DownloadMessage message) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Notifications\CustomScript\CustomScript.cs:line 103
   at NzbDrone.Core.Notifications.NotificationService.Handle(EpisodeImportedEvent message) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Notifications\NotificationService.cs:line 144

**Comment by markus101** [comment]
Please post a link to the debug logs as requested.

**Comment by awwwwwyup** [comment]
Apologies, debug log attached. Errors start around 17-11-8 10:36:50.  I can switch on trace level logs and collect more tomorrow if needed.

[sonarr.debug.1.txt](https://github.com/Sonarr/Sonarr/files/1453799/sonarr.debug.1.txt)

**Comment by markus101** [comment]
I haven't been able to reproduce this issue, if you're still seeing this issue, please enable trace logging and post the logs when it happens again (trace logs will log each environment variable being set).

**Comment by awwwwwyup** [comment]
Still seeing this issue unfortunately, also worth noting I tried restarting the computer and updating the .NET framework to no avail. Trace log attached; first exception occurs around line 1730 and continues as the download moves through its various phases.

[sonarr.trace.16.txt](https://github.com/Sonarr/Sonarr/files/1510031/sonarr.trace.16.txt)

**Comment by markus101** [comment]
The only way I've been able to reproduce this is by setting a User/System environment variable with the name `sonarr_eventtype` (in any casing). When Sonarr sets the environment variable, existing variables are pulled in from user/system and Sonarr appends to them for that process only.

You can check if the variable has already been set by running `echo %sonarr_eventtype% in cmd.

And to remove it (little dated UI wise, but the process is the same):
http://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-windows-gui/

**Comment by awwwwwyup** [comment]
That did it; good find! I did set some variables to test my script but thought they were local to the cmd window I had open at the time. Apologies for the run around.

**Comment by markus101** [comment]
Awesome, closing this out.
