### ISSUE TITLE
Bug Manual Import failure

### ISSUE THREAD

**Issue by maciver** [Sonarr/Sonarr#2384]
Typically if Sonarr fails to add a file I download I would hit manual import then manually add them, now it fails to even open the screen. I just get the dancing dots no adblocker on all addons off, still nothing. Below is the log information. I found it odd that it says file path too long when the path is e:\new media\
Any ideas? Pictures in links below.

https://ibb.co/iZygbw 

https://ibb.co/gEJ3pG 

Sonarr version 2.0.0.5129 - Jan 23 2018

NzbDroneErrorPipeline
Request Failed. GET /api/manualimport: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at System.IO.DirectoryInfo..ctor(String path)
   at NzbDrone.Common.Extensions.PathExtensions.IsParentPath(String parentPath, String childPath) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 93
   at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath(String parentPath, String childPath) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 60
   at NzbDrone.Core.MediaFiles.DiskScanService.<>c__DisplayClass16_0.<FilterFiles>b__0(String file) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 163
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.DiskScanService.FilterFiles(String basePath, IEnumerable`1 files) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 163
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.ProcessFolder(String folder, String downloadId) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\EpisodeImport\Manual\ManualImportService.cs:line 114
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.GetMediaFiles(String path, String downloadId) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MediaFiles\EpisodeImport\Manual\ManualImportService.cs:line 92
   at NzbDrone.Api.ManualImport.ManualImportModule.GetMediaFiles() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\ManualImport\ManualImportModule.cs:line 26
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__32_0(Object options) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\REST\RestModule.cs:line 111
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by markus101** [comment]
Please post the debug logs leading up to and including that error.

**Comment by maciver** [comment]
[sonarr.debug.txt](https://github.com/Sonarr/Sonarr/files/1669794/sonarr.debug.txt)

**Comment by markus101** [comment]
The issue appears to be related to a release with a ridiculously long file name. Long files name will be supported in v3, meanwhile I've updated Manual Import to show an error message when it fails to load items.
