### ISSUE TITLE
Can't start Sonarr with SSL enabled. Port is already in use. (It's not, I scanned with nmap)

### ISSUE THREAD

**Issue by BetaLeaf** [Sonarr/Sonarr#2385]
```
18-1-27 00:31:20.1|Info|Bootstrap|Starting Sonarr - C:\ProgramData\NzbDrone\bin\nzbdrone.console.exe - Version 2.0.0.5085
18-1-27 00:31:20.7|Info|Router|Application mode: Service
18-1-27 00:31:20.9|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\NzbDrone\nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-1-27 00:31:21.1|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\NzbDrone\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-1-27 00:31:21.6|Info|OwinHostController|Listening on the following URLs:
18-1-27 00:31:21.6|Info|OwinHostController|  http://*:5061/
18-1-27 00:31:21.6|Info|OwinHostController|  https://*:5051/
18-1-27 00:31:21.8|Info|NancyBootstrapper|Starting Web Server
18-1-27 00:32:34.9|Info|Bootstrap|Starting Sonarr - C:\ProgramData\NzbDrone\bin\NzbDrone.exe - Version 2.0.0.5085
18-1-27 00:32:36.5|Info|Router|Application mode: Interactive
18-1-27 00:32:37.2|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\NzbDrone\nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-1-27 00:32:37.7|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\NzbDrone\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
18-1-27 00:32:39.1|Info|OwinHostController|Listening on the following URLs:
18-1-27 00:32:39.1|Info|OwinHostController|  http://*:5061/
18-1-27 00:32:39.1|Info|OwinHostController|  https://*:5051/
18-1-27 00:32:39.7|Info|NancyBootstrapper|Starting Web Server
18-1-27 00:32:41.5|Fatal|WindowsApp|EPIC FAIL

[v2.0.0.5085] NzbDrone.Host.Owin.PortInUseException: Port 5061 is already in use, please ensure NzbDrone is not already running. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: Failed to listen on prefix 'https://*:5051/' because it conflicts with an existing registration on the machine.
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.StartServer(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at NzbDrone.Host.Owin.OwinAppFactory.CreateApp(List`1 urls) in M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Host\Owin\OwinServiceProvider.cs:line 52
   --- End of inner exception stack trace ---
   at NzbDrone.Host.Owin.OwinAppFactory.CreateApp(List`1 urls) in M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Host\Owin\OwinServiceProvider.cs:line 63
   at NzbDrone.Host.Owin.OwinHostController.StartServer() in M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Host\Owin\OwinHostController.cs:line 53
   at NzbDrone.Host.NzbDroneServiceFactory.Start() in M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Host\ApplicationServer.cs:line 61
   at NzbDrone.Host.Router.Route(ApplicationModes applicationModes) in M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Host\Router.cs:line 47
   at NzbDrone.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Host\Bootstrap.cs:line 78
   at NzbDrone.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in M:\BuildAgent\work\3a352f0853732683\src\NzbDrone.Host\Bootstrap.cs:line 41
   at NzbDrone.WindowsApp.Main(String[] args) in M:\BuildAgent\work\3a352f0853732683\src\NzbDrone\WindowsApp.cs:line 23
```

**Comment by BetaLeaf** [comment]
Radarr is also having the same problem. https://github.com/Radarr/Radarr/issues/2451

**Comment by markus101** [comment]
Please use the forums for support.

In this case the port isn't in use (though that's the most common reason for this error), it's `Failed to listen on prefix 'https://*:5051/' because it conflicts with an existing registration on the machine.`, you could remove the existing URL ACL or change the port.

**Comment by BetaLeaf** [comment]
Doesn't matter what port I set it to, it always fails.

**Comment by BetaLeaf** [comment]
I figured it out.
```
netsh http delete urlacl http://*:5051/
netsh http delete urlacl http://*:5061/
netsh http delete urlacl https://*:5051/
netsh http delete urlacl https://*:5061/
```
