### ISSUE TITLE
Sonarr 2.0.0.5153 can no longer remove downloads from qBittorrent

### ISSUE THREAD

**Issue by teejo75** [Sonarr/Sonarr#2438]
## Bug Report

Sonarr no longer removes downloads from qbittorrent. This was working fine prior to the current version.

### System Information/Logs

**Sonarr Version:** 2.0.0.5153

**Operating System:** Windows 2012 R2

**.net Framework (Windows) or mono (macOS/Linux) Version:** 

**Link to Log Files (debug or trace):** 
```
18-3-2 17:20:41.1|Error|DownloadEventHub|Couldn't remove item from client SomeFile.S1E1.720p.HDTV.x264

[v2.0.0.5153] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://192.168.1.54:8080/command/deletePerm]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 94
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 225
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 241
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.RemoveTorrent(String hash, Boolean removeData, QBittorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 118
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.RemoveItem(String hash, Boolean deleteData) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 167
   at NzbDrone.Core.Download.DownloadEventHub.RemoveFromDownloadClient(TrackedDownload trackedDownload) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\DownloadEventHub.cs:line 67

18-3-2 17:20:41.2|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.1.54:8080/command/deletePerm: 400.BadRequest
```

**Comment by teejo75** [comment]
At least one other person has the same issue.

https://forums.sonarr.tv/t/wont-delete-from-qbittorrent-since-v2-0-0-5153/17850

**Comment by teejo75** [comment]
https://github.com/Sonarr/Sonarr/blob/99ee59e9cc75ca79d5814578b2d529920f8116cc/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxy.cs#L115

This line is adding the form parameter 'category', and according to the API, only 'hashes' is required. This could be why the request is failing.

https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#delete-torrent

**Comment by olliebean** [comment]
This seems to be a side effect of the fix "Send category to qBittorrent when adding torrent/magnet."

**Comment by SkyAFS** [comment]
same problem here, my qbittorrent has more then 200 torrents now, i think i will do manually until this is fixed

**Comment by Gareth4321** [comment]
Same issue here. qBittorrent.

**Comment by teejo75** [comment]
Update your sonarr, this issue was fixed a while ago.

**Comment by Gareth4321** [comment]
@teejo75 Thanks! I have the latest versions of both. I reinstalled both and the issue is now resolved!
