### ISSUE TITLE
Unable to remove duplicated torrents from qBittorrent via Sonarr

### ISSUE THREAD

**Issue by tunes0710** [Sonarr/Sonarr#2454]
### System Information/Logs

**Sonarr Version:** 2.0.0.5153

**Operating System:** Windows 7

**.net Framework (Windows) or mono (macOS/Linux) Version:** 4.7.1

**Link to Log Files (debug or trace):**

**Browser (for UI bugs):** Chrome 65.0.3325.146

### Additional Information
If a duplicated episode has been downloaded via qBittorrent and it showing up in Sonarr as not an upgrade for existing episode. I am unable to delete it.

I get the following errors in the logs
HttpClient | HTTP Error - Res: [POST] http://localhost:22084/command/deletePerm: 400.BadRequest
NzbDroneErrorPipeline | Request Failed. DELETE /api/queue/97609950: Failed to connect to qBittorrent, check your settings.

NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://localhost:22084/command/deletePerm]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 94
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 225
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 241
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.RemoveTorrent(String hash, Boolean removeData, QBittorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 118
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.RemoveItem(String hash, Boolean deleteData) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 167
   at NzbDrone.Api.Queue.QueueActionModule.Remove(Int32 id) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\Queue\QueueActionModule.cs:line 70
   at NzbDrone.Api.Queue.QueueActionModule.<.ctor>b__7_0(Object x) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\Queue\QueueActionModule.cs:line 39
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

This is using qBt 4.0.4

-- | --

**Comment by Taloth** [comment]
Dupe https://github.com/Sonarr/Sonarr/issues/2449
Dupe https://github.com/Sonarr/Sonarr/issues/2445
Dupe https://github.com/Sonarr/Sonarr/issues/2438
