### ISSUE TITLE
Extra "category" parameter in POST body causing QBittorrent to return a 400 error when Sonarr attempts to remove a torrent from the client

### ISSUE THREAD

**Issue by burkasaurusrex** [Sonarr/Sonarr#2459]
### System Information/Logs

**Sonarr Version:** 2.0.0.5153

**Operating System:** Windows 10

**Link to Log Files (debug or trace):**

Error message: Couldn't remove item from client [Show]: Failed to connect to qBittorrent, check your settings.

`NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [POST] at [http://[PC]:8080/command/deletePerm]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 94
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 225
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 241
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.RemoveTorrent(String hash, Boolean removeData, QBittorrentSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 118
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.RemoveItem(String hash, Boolean deleteData) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 167
   at NzbDrone.Core.Download.DownloadEventHub.RemoveFromDownloadClient(TrackedDownload trackedDownload) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\DownloadEventHub.cs:line 67`

### Additional Information

I'm running QBittorrent v4.0.4, so this may have been introduced in the latest version. Every other command sent to QBittorrent works fine with my settings, except for the delete commands ('delete' and 'deletePerm').

After digging into the requests in Fiddler, it looks like the 'category' parameter is being POST'd when it shouldn't, causing an error. When I resend the same request without the 'category' parameter, it works just fine.

It seems like it should work fine if you could remove that parameter from the POST body for those commands. Let me know if you have any questions. Thanks!

**Comment by markus101** [comment]
Dupe https://github.com/Sonarr/Sonarr/issues/2449
Dupe https://github.com/Sonarr/Sonarr/issues/2445
Dupe https://github.com/Sonarr/Sonarr/issues/2438
Dupe https://github.com/Sonarr/Sonarr/issues/2454
