### ISSUE TITLE
Can restart but will crash shortly after

### ISSUE THREAD

**Issue by Codgedodger** [Sonarr/Sonarr#2498]
### System Information/Logs
Version - 2.0.0.5163
Mono Version -5.8.0.127

### Other Information

Shortly after restart, it will scan in shows then suddenly do a core crash. I've reinstalled mono-complete and nzbdrone with no avail. Google searching doesn't show much on the error. 

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
225     ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S: No such file or directory.
  Id   Target Id         Frame
* 1    Thread 0x7f3dd82e0740 (LWP 25643) "mono" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  2    Thread 0x7f3dd67ff700 (LWP 25646) "SGen worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7f3dd6eee700 (LWP 25648) "Finalizer" 0x00007f3dd77b6827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0xa1bfc0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  4    Thread 0x7f3dcf1ff700 (LWP 25658) "Timer-Scheduler" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  5    Thread 0x7f3dcd539700 (LWP 25802) "mono" 0x00007f3dd72c274d in poll () at ../sysdeps/unix/syscall-template.S:84
  6    Thread 0x7f3dcd338700 (LWP 25803) "mono" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  7    Thread 0x7f3dcd137700 (LWP 25804) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  8    Thread 0x7f3dccf36700 (LWP 25805) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  9    Thread 0x7f3dccd35700 (LWP 25828) "mono" 0x00007f3dce5161db in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
  10   Thread 0x7f3dccb34700 (LWP 25829) "mono" 0x00007f3dd77b7f7b in __waitpid (pid=27395, stat_loc=0x7f3dccb31a6c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  11   Thread 0x7f3dcc933700 (LWP 25830) "mono" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  12   Thread 0x7f3dcc4ff700 (LWP 25834) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  13   Thread 0x7f3dcc2fe700 (LWP 25835) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  14   Thread 0x7f3da7ba0700 (LWP 25850) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  15   Thread 0x7f3da5a7e700 (LWP 26247) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  16   Thread 0x7f3da587d700 (LWP 26248) "Threadpool work" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  17   Thread 0x7f3da567c700 (LWP 26249) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  18   Thread 0x7f3d7d7ff700 (LWP 26873) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  19   Thread 0x7f3d7d5fe700 (LWP 26874) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  20   Thread 0x7f3d7d083700 (LWP 26875) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  21   Thread 0x7f3d7ce82700 (LWP 26876) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  22   Thread 0x7f3d7cc81700 (LWP 26877) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  23   Thread 0x7f3d7ca80700 (LWP 26878) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  24   Thread 0x7f3d7c87f700 (LWP 26879) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  25   Thread 0x7f3d7c4ff700 (LWP 26880) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  26   Thread 0x7f3d479fe700 (LWP 26881) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
  27   Thread 0x7f3d477fd700 (LWP 26882) "Threadpool work" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225

Thread 27 (Thread 0x7f3d477fd700 (LWP 26882)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3d477fd700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 26 (Thread 0x7f3d479fe700 (LWP 26881)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3d479fe700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 25 (Thread 0x7f3d7c4ff700 (LWP 26880)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3d7c4ff700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 24 (Thread 0x7f3d7c87f700 (LWP 26879)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3d7c87f700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 23 (Thread 0x7f3d7ca80700 (LWP 26878)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3d7ca80700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 22 (Thread 0x7f3d7cc81700 (LWP 26877)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3d7cc81700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 21 (Thread 0x7f3d7ce82700 (LWP 26876)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3d7ce82700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 20 (Thread 0x7f3d7d083700 (LWP 26875)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3d7d083700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 19 (Thread 0x7f3d7d5fe700 (LWP 26874)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3d7d5fe700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 18 (Thread 0x7f3d7d7ff700 (LWP 26873)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3d7d7ff700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 17 (Thread 0x7f3da567c700 (LWP 26249)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3da567c700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 16 (Thread 0x7f3da587d700 (LWP 26248)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000692a75 in ?? ()
#2  0x000000000060a119 in ?? ()
#3  0x000000000060a5d5 in ?? ()
#4  0x0000000000633546 in ?? ()
#5  0x000000004125b1b7 in ?? ()
#6  0x00007f3da66f2bb0 in ?? ()
#7  0x00007f3dd8238810 in ?? ()
#8  0x0000000000000000 in ?? ()

Thread 15 (Thread 0x7f3da5a7e700 (LWP 26247)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3da5a7e700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 14 (Thread 0x7f3da7ba0700 (LWP 25850)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3da7ba0700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 13 (Thread 0x7f3dcc2fe700 (LWP 25835)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000692a75 in ?? ()
#2  0x000000000060a119 in ?? ()
#3  0x000000000060a5d5 in ?? ()
#4  0x0000000000633546 in ?? ()
#5  0x000000004125b1b7 in ?? ()
#6  0x00007f3dcc6c63e0 in ?? ()
#7  0x00007f3dd8238810 in ?? ()
#8  0x0000000000000000 in ?? ()

Thread 12 (Thread 0x7f3dcc4ff700 (LWP 25834)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3dcc4ff700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 11 (Thread 0x7f3dcc933700 (LWP 25830)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x000000000069c4ab in ?? ()
#3  0x00000000005ed2cf in ?? ()
#4  0x000000004126a62f in ?? ()
#5  0x0000000000000001 in ?? ()
#6  0x00007f3dd6891f60 in ?? ()
#7  0x00007f3dd6a281b8 in ?? ()
#8  0x00007f3dce1525b0 in ?? ()
#9  0x0000000000000447 in ?? ()
#10 0x00007f3da80021a0 in ?? ()
#11 0x00007f3dcc932480 in ?? ()
#12 0x00007f3dcc932480 in ?? ()
#13 0x00007f3dcc9321a0 in ?? ()
#14 0x00007f3dd4711687 in System_Threading_Thread_Sleep_int (millisecondsTimeout=1095) from /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
#15 0x00007f3dd47116fa in System_Threading_Thread_Sleep_System_TimeSpan (timeout=10953580) from /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
#16 0x00000000413ac533 in ?? ()
#17 0x00007f3dd6a2a840 in ?? ()
#18 0x00007f3da6af55c0 in ?? ()
#19 0x0000000000a7236c in ?? ()
#20 0x48d59db3ae42b048 in ?? ()
#21 0x48d59db3aee9d3b4 in ?? ()
#22 0x0000000001312d00 in ?? ()
#23 0x48d59db3b01b00b4 in ?? ()
#24 0x0000000000a7236c in ?? ()
#25 0x0000000001312d00 in ?? ()
#26 0x00007f3dd6a2ad60 in ?? ()
#27 0x00007f3dd6a2ad78 in ?? ()
#28 0x00007f3dcd9682f0 in ?? ()
#29 0x00007f3dd6a2ad60 in ?? ()
#30 0x00007f3dd6a2ad60 in ?? ()
#31 0x00007f3dd6a2ad60 in ?? ()
#32 0x00007f3dd6a2ad60 in ?? ()
#33 0x00007f3da46cb830 in ?? ()
#34 0x0000000041473a99 in ?? ()
#35 0x0000000000000000 in ?? ()

Thread 10 (Thread 0x7f3dccb34700 (LWP 25829)):
#0  0x00007f3dd77b7f7b in __waitpid (pid=27395, stat_loc=0x7f3dccb31a6c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00000000004b34d6 in ?? ()
#2  0x000000000051ea16 in ?? ()
#3  0x00007f3d83884091 in ?? () from /usr/lib/x86_64-linux-gnu/libmediainfo.so.0
#4  0x00007f3d83669489 in ?? () from /usr/lib/x86_64-linux-gnu/libmediainfo.so.0
#5  0x00007f3d8366a542 in ?? () from /usr/lib/x86_64-linux-gnu/libmediainfo.so.0
#6  0x00007f3d8366a6d0 in ?? () from /usr/lib/x86_64-linux-gnu/libmediainfo.so.0
#7  0x00007f3d8366b4a8 in ?? () from /usr/lib/x86_64-linux-gnu/libmediainfo.so.0
#8  0x00007f3d836b1dd6 in ?? () from /usr/lib/x86_64-linux-gnu/libmediainfo.so.0
#9  0x00007f3d8366a8f5 in ?? () from /usr/lib/x86_64-linux-gnu/libmediainfo.so.0
#10 0x00007f3d8366b4a8 in ?? () from /usr/lib/x86_64-linux-gnu/libmediainfo.so.0
#11 0x00007f3d836e8eca in ?? () from /usr/lib/x86_64-linux-gnu/libmediainfo.so.0
#12 0x00007f3d836b862c in MediaInfoLib::MediaInfo::Open_Buffer_Continue(unsigned char const*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libmediainfo.so.0
#13 0x00007f3d83a7f84d in MediaInfo_Open_Buffer_Continue () from /usr/lib/x86_64-linux-gnu/libmediainfo.so.0
#14 0x0000000041401210 in ?? ()
#15 0x0000000000000000 in ?? ()

Thread 9 (Thread 0x7f3dccd35700 (LWP 25828)):
#0  0x00007f3dce5161db in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#1  0x00007f3dce516d70 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#2  0x00007f3dce54b98d in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#3  0x00007f3dce54f201 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#4  0x00007f3dce56f129 in ?? () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#5  0x00007f3dce5781a7 in sqlite3_step () from /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
#6  0x00000000410d5d8d in ?? ()
#7  0x00007f3dd68ce2a8 in ?? ()
#8  0x0000000000007530 in ?? ()
#9  0x00007f3dd68ce648 in ?? ()
#10 0x00007f3dd68cccc8 in ?? ()
#11 0x00007f3dd68ce648 in ?? ()
#12 0x00007f3db00021a0 in ?? ()
#13 0x0000000000000000 in ?? ()

Thread 8 (Thread 0x7f3dccf36700 (LWP 25805)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3dccf36700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 7 (Thread 0x7f3dcd137700 (LWP 25804)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x00000000005f30b4 in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3dcd137700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7f3dcd338700 (LWP 25803)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x000000000069c4ab in ?? ()
#3  0x00000000005f3a53 in ?? ()
#4  0x00000000005ef0ec in ?? ()
#5  0x00007f3dd77ae6ba in start_thread (arg=0x7f3dcd338700) at pthread_create.c:333
#6  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7f3dcd539700 (LWP 25802)):
#0  0x00007f3dd72c274d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00000000005f5635 in ?? ()
#2  0x00000000005f661c in ?? ()
#3  0x00000000005ef0ec in ?? ()
#4  0x00007f3dd77ae6ba in start_thread (arg=0x7f3dcd539700) at pthread_create.c:333
#5  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7f3dcf1ff700 (LWP 25658)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x000000000060a119 in ?? ()
#3  0x000000000060a61e in ?? ()
#4  0x000000000060acb0 in ?? ()
#5  0x00000000005ed665 in ?? ()
#6  0x000000004101ca6f in ?? ()
#7  0x0000000000f706e0 in ?? ()
#8  0x00000000000001f3 in ?? ()
#9  0x00000000000001f3 in ?? ()
#10 0x00007f3dd69ddba8 in ?? ()
#11 0x0000000000000000 in ?? ()

Thread 3 (Thread 0x7f3dd6eee700 (LWP 25648)):
#0  0x00007f3dd77b6827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0xa1bfc0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0xa1bfc0, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f3dd77b68d4 in __new_sem_wait_slow (sem=0xa1bfc0, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007f3dd77b697a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x000000000062acf7 in ?? ()
#5  0x00000000005ef0ec in ?? ()
#6  0x00007f3dd77ae6ba in start_thread (arg=0x7f3dd6eee700) at pthread_create.c:333
#7  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f3dd67ff700 (LWP 25646)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000685f5f in ?? ()
#2  0x00007f3dd77ae6ba in start_thread (arg=0x7f3dd67ff700) at pthread_create.c:333
#3  0x00007f3dd72ce41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f3dd82e0740 (LWP 25643)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000000000692a1b in ?? ()
#2  0x000000000069c4ab in ?? ()
#3  0x00000000005ed2cf in ?? ()
#4  0x000000004126a62f in ?? ()
#5  0x0000000000000000 in ?? ()

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

Aborted (core dumped)
```

**Comment by markus101** [comment]
Please use the forums for support, also link to logs, don't paste them in the body of the issue.

You'll need to capture the standard output and error to a file, with trace logging enabled in Sonarr to see exactly what Sonarr was doing leading up to the crash, but given it's during a refresh, make sure the latest libmediainfo is installed (from their repo, not your OSes default repo, that'll be very out of date likely).

**Comment by Codgedodger** [comment]
Apologies mate. I've updated the log. 

Tried to do some googling on updating libmediainfo but wasn't able to find anything. Do you have any helpful links?

**Comment by markus101** [comment]
That's going to depend on your OS typically the mediainfo version in the OSes repo is very out of date, https://mediaarea.net/en/MediaInfo/Download may be of some use.

**Comment by Codgedodger** [comment]
I know this is isn't a support form but I want to thank you for your help!

Updating libmediainfo0 v18.03.1 and libzen0 v0.4.37 fixed it!
