### ISSUE TITLE
Error when adding Jersey Shore from BTN

### ISSUE THREAD

**Issue by joshkay** [Sonarr/Sonarr#2576]
**Describe the bug**
Adding Jersey Shore with BroadcastheNet as the indexer causes the indexer to fail and become unavailable.  Tested with another show (Halt and Catch Fire) with no issue.

**Logs**
An error occurred while processing feed. http://api.broadcasthe.net/: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.Dictionary`2[System.Int32,NzbDrone.Core.Indexers.BroadcastheNet.BroadcastheNetTorrent]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'result.torrents', line 1, position 39.

Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.Dictionary`2[System.Int32,NzbDrone.Core.Indexers.BroadcastheNet.BroadcastheNetTorrent]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'result.torrents', line 1, position 39.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Serializer\Json.cs:line 37
   at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpResponse.cs:line 95
   at NzbDrone.Core.Indexers.BroadcastheNet.BroadcastheNetParser.ParseResponse(IndexerResponse indexerResponse) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\BroadcastheNet\BroadcastheNetParser.cs:line 19
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 290
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 133

**UI Bugs:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 2.0.0.5163

**Comment by markus101** [comment]
Please post a link to the debug logs as requested...

**Comment by joshkay** [comment]
Sorry, new to sonarr.  I changed the log level to debug.

Here is the log after the failed attempt.

https://pastebin.com/dvGx7Tbv

**Comment by markus101** [comment]
@Taloth this is the JSON we're getting back:

`{"id":"d9fa8ff3","result":{"torrents":[],"results":0}}`

Not sure what BTN returned before for empty searches.

**Comment by Taloth** [comment]
Pretty sure they didn't return that, coz it triggers back-off. There's also a thread about it on the btn forums.

**Comment by onedr0p** [comment]
Yep, I am getting this error as well. My guess was backend changes to their API or something.

**Comment by markus101** [comment]
Yeah, looks like they return an empty array when there aren't any results otherwise it's an object:

```
{
  "id": "b6898236",
  "result": {
    "results": 4,
    "torrents": {
      "958242": {
        "Category": "Episode",
        "Codec": "H.264",
        "Container": "MP4",
        "DownloadURL": "actual download URL",
        "GroupID": "490062",
        "GroupName": "S01E08",
        "ImdbID": "7686456",
        "InfoHash": "6ECCE2C7ED54543C1E96AD9B9DBB59C8FC0D9879",
        "Leechers": "0",
        "Origin": "P2P",
        "ReleaseName": "Jersey.Shore.Family.Vacation.S01E08.The.Temptation.of.the.Keto.Guido.HDTV.x264-NY2",
        "Resolution": "SD",
        "Seeders": "55",
        "Series": "Jersey Shore Family Vacation",
        "SeriesBanner": "//cdn2.broadcasthe.net/tvdb/banners/graphical/338539-g.jpg",
        "SeriesID": "75887",
        "SeriesPoster": "//cdn2.broadcasthe.net/tvdb/banners/posters/338539-1.jpg",
        "Size": "391568418",
        "Snatched": "9",
        "Source": "HDTV",
        "Time": "1526707473",
        "TorrentID": "958242",
        "TvdbID": "338539",
        "TvrageID": "0",
        "YoutubeTrailer": "https://www.youtube.com/v/xNNxGzBfZ2k"
      }
    }
  }
}
```

**Comment by rjb8682** [comment]
Just wanted to chime in and say i'm also running into this issue on some shows. Testing the indexer works fine, but fails when searching for results

**Comment by Taloth** [comment]
@markus101 No. The first step is not a hack, let the btn techs fix the issue on their end. If they prove unwilling to do so then we can consider dealing with it on our end.

@ everyone else, please no 'me also' comments any further. It affects everyone.

**Comment by markus101** [comment]
I'm not advocating we do anything right now, just listing a possible course of action if it comes to it.

**Comment by predakanga** [comment]
This should now be fixed on BTN's end - it was due to a peculiarity of PHP using the same type for associative- and non-associative arrays.
