### ISSUE TITLE
Can't add some already downloaded series

### ISSUE THREAD

**Issue by lukecamilo** [Sonarr/Sonarr#2579]
**Describe the bug**
For some reason i stopped getting RSS syncs for Marvel's Agents of Shield, so i removed the show from my sonarr library and tried to re-add it, both from "search for series" and from disk. None of them worked. In the last case, i got some errors on the log, which i'm pasting down below.

**Screenshots**

**Logs**

```
System.Net.WebException: Failed to read complete http response ---> System.Net.WebException: The operation has timed out.
   at System.Net.GZipWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at NzbDrone.Common.Extensions.StreamExtensions.ToBytes(Stream input) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Extensions\StreamExtensions.cs:line 13
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 108
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 112
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 53
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 55
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 225
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetSeriesInfo(Int32 tvdbSeriesId) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 40
   at NzbDrone.Core.Tv.AddSeriesService.AddSkyhookData(Series newSeries) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Tv\AddSeriesService.cs:line 77
   at NzbDrone.Core.Tv.AddSeriesService.AddSeries(Series newSeries) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Tv\AddSeriesService.cs:line 46
   at NzbDrone.Api.Series.SeriesModule.AddSeries(SeriesResource seriesResource) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\Series\SeriesModule.cs:line 113
   at NzbDrone.Api.REST.RestModule`1.<set_CreateResource>b__41_0(Object options) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\REST\RestModule.cs:line 155
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, firefox]

**Additional context**

**Comment by markus101** [comment]
Looks like a connection problem between you and CloudFlare.

Please open a thread on the forums and we'll do what we can to help, but this isn't a bug in Sonarr. We'll need to see debug logs leading up to this error.
