### ISSUE TITLE
Errors on when checking for finished downloads with qbittorrent and version 2.0.0.5225

### ISSUE THREAD

**Issue by Spirevipp** [Sonarr/Sonarr#2634]
**Describe the bug**
Errors on when checking for finished downloads with qbittorrent 4.1.1 and version 2.0.0.5225

**Logs**
`Newtonsoft.Json.JsonReaderException: JSON integer 18446744073709535000 is too large or small for an Int64. Path '[0].eta', line 1, position 232.
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.GetTorrents(QBittorrentSettings settings) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 67
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.TestGetTorrents() in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 304`

**System Information**

 - Sonarr Version: 2.0.0.5225
 - Operating System: Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Comment by markus101** [comment]
Please post the [debug logs](https://github.com/Sonarr/Sonarr/wiki/Log-Files) as requested and provide the link to them here.

**Comment by Spirevipp** [comment]
I have enabled the debug logging now. My sonar.txt log file has only a couple of lines after restarting the server.
I have gotten this error each day since the update. After restarting qbittorrent re adding as downloadclient and restarting sonarr a couple of times it disappears.

[sonarr.txt](https://github.com/Sonarr/Sonarr/files/2129236/sonarr.txt)

**Comment by markus101** [comment]
The debug log file is a separate file and if that error is occurring it'll show up in the debug log.

**Comment by markus101** [comment]
This should be fixed in https://github.com/Sonarr/Sonarr/commit/03997e2a0d3c1418ed4723d839385e5a3fbf000f

We can re-open if the debug logs show something else, but closing this out.
