### ISSUE TITLE
Activity is stuck at 100% even though file is finished 

### ISSUE THREAD

**Issue by iCrypticS** [Sonarr/Sonarr#2635]
**Describe the bug**
When Sonarr grabs a torrent it sends it to qbittorrent (4.1.0) it finishes downloading but sonarr does not see it as finished. 

**Below is the only log that Sonarr produces about failing a torrent and I have 16 other ones sitting in activity at 100% downloaded that has no log to match.** 

**Screenshots**
https://imgur.com/a/GfFJN9S
https://imgur.com/a/VXrpKEx

**Logs**
`Couldn't add report to download queue. Boku no Hero Academia - 12 (2018) [HorribleSubs] [WEBRip] [HD 720p]: Download client failed to add torrent`

```
NzbDrone.Core.Download.Clients.DownloadClientException: Download client failed to add torrent
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.AddTorrentFromFile(String fileName, Byte[] fileContent, QBittorrentSettings settings) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 118
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromTorrentFile(RemoteEpisode remoteEpisode, String hash, String filename, Byte[] fileContent) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 58
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteEpisode remoteEpisode, String torrentUrl) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 189
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteEpisode remoteEpisode) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 117
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteEpisode remoteEpisode) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\DownloadService.cs:line 76
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 76
```

**System Information**

 - Sonarr Version: 2.0.0.5228
 - Operating System: Windows 10

**Additional context**
Troubleshooting I did:
Rebooting workstation, uninstalling and reinstalling sonarr from a backup, installed latest version (was happening on 2.0.0.5225), removing the torrent and adding it again (activity saw it as gone and removed it from the list until it was added again and then was stuck at 100% again) and enabled trace log, attempted different qbittorrent versions.

**Comment by markus101** [comment]
Please use the forums for support.

Hover over the icon on the left of Activity: Queue to see why Sonarr is not importing it. As well as looking at debug logs (the logs here don't have anything to do with the import).
