### ISSUE TITLE
System.InvalidProgramException: Common Language Runtime detected an invalid program.

### ISSUE THREAD

**Issue by mhouston100** [Sonarr/Sonarr#2647]
## Support / Questions

Please use https://forums.sonarr.tv/ for support. Support requests or questions will be redirected to the forums and the issue will be closed.

### System Information/Logs

**Sonarr Version:**
2.0.0.5228
**Operating System:**
Server 2016
**.net Framework (Windows) or mono (macOS/Linux) Version:**
.Net 4.7
**Link to Log Files (debug or trace):**

**Browser (for UI bugs):**

### Additional Information
Been running fine for months

### What problem are you looking to solve?

After the last update Sonarr refuses to start with the error:

18-6-24 01:14:56.1|Info|InstallUpdateService|Deleting old update files
18-6-24 01:14:56.9|Info|InstallUpdateService|Downloading update 2.0.0.5228
18-6-24 01:14:58.1|Info|InstallUpdateService|Verifying update package
18-6-24 01:14:58.6|Info|InstallUpdateService|Update package verified successfully
18-6-24 01:14:58.6|Info|InstallUpdateService|Extracting Update package
18-6-24 01:15:13.5|Info|InstallUpdateService|Update package extracted successfully
18-6-24 01:15:13.7|Info|BackupService|Starting Backup
18-6-24 01:15:23.2|Info|InstallUpdateService|Preparing client
18-6-24 01:15:23.4|Info|InstallUpdateService|Starting update client C:\Users\media\AppData\Local\Temp\nzbdrone_update\NzbDrone.Update.exe
18-6-24 01:15:23.4|Info|InstallUpdateService|Sonarr will restart shortly.
18-6-24 01:15:27.1|Info|NzbDroneServiceFactory|Attempting to stop application.
18-6-24 01:15:27.1|Info|OwinHostController|Attempting to stop OWIN host
18-6-24 01:15:27.6|Info|OwinHostController|Host has stopped
18-6-24 01:15:27.6|Info|NzbDroneServiceFactory|Application has finished stop routine.
18-6-24 01:15:27.7|Info|ConsoleApp|Exiting main.
18-6-24 01:15:48.5|Info|Bootstrap|Starting Sonarr - C:\ProgramData\NzbDrone\bin\NzbDrone.Console.exe - Version 2.0.0.5228
18-6-24 01:15:50.2|Fatal|ConsoleApp|EPIC FAIL!

[v2.0.0.5228] TinyIoC.TinyIoCResolutionException: Unable to resolve type: NzbDrone.Core.Instrumentation.ReconfigureLogging ---> TinyIoC.TinyIoCResolutionException: Unable to resolve type: NzbDrone.Core.Configuration.IConfigFileProvider ---> TinyIoC.TinyIoCResolutionException: Unable to resolve type: NzbDrone.Core.Configuration.ConfigFileProvider ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at NzbDrone.Core.Configuration.ConfigFileProvider..ctor(IAppFolderInfo appFolderInfo, ICacheManager cacheManager, IEventAggregator eventAggregator, IDiskProvider diskProvider)
   at lambda_method(Closure , Object[] )
   at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\TinyIoC.cs:line 3560
   --- End of inner exception stack trace ---
   at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\TinyIoC.cs:line 3568
   at TinyIoC.TinyIoCContainer.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\TinyIoC.cs:line 2738
   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\TinyIoC.cs:line 3232
   at TinyIoC.TinyIoCContainer.Resolve(Type resolveType, String name) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\TinyIoC.cs:line 1456
   at NzbDrone.Common.Composition.Container.<>c__DisplayClass12_0.<CreateSingletonImplementationFactory>b__0(TinyIoCContainer c, NamedParameterOverloads p) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Composition\Container.cs:line 81
   at TinyIoC.TinyIoCContainer.DelegateFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\TinyIoC.cs:line 2501
   --- End of inner exception stack trace ---
   at TinyIoC.TinyIoCContainer.DelegateFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\TinyIoC.cs:line 2505
   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\TinyIoC.cs:line 3232
   at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\TinyIoC.cs:line 3536
   --- End of inner exception stack trace ---
   at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\TinyIoC.cs:line 3549
   at TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\TinyIoC.cs:line 3324
   at TinyIoC.TinyIoCContainer.Resolve(Type resolveType) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\TinyIoC.cs:line 1429
   at TinyIoC.TinyIoCContainer.Resolve[ResolveType]() in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\TinyIoC.cs:line 1548
   at NzbDrone.Common.Composition.Container.Resolve[T]() in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Composition\Container.cs:line 34
   at NzbDrone.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Host\Bootstrap.cs:line 66
   at NzbDrone.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Host\Bootstrap.cs:line 41
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Console\ConsoleApp.cs:line 37

**Comment by mhouston100** [comment]
Reinstall from source and recreated the service resolved this.
