### ISSUE TITLE
Sonarr trying to rename file over 255 characters

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [Sonarr/Sonarr#2699]
**Describe the bug**
I have a file that encompasses multiple episodes of a show, specifically the Battlestar Galactica 2005 Razor miniseries. With the naming options I have set, Sonarr fails to rename the file as it tries to put all the episode titles in the file name.
This doesn't crash Sonarr, but there's no error in the UI when the rename fails so I had trouble figuring out why it wasn't moving/renaming the file.

**Screenshots**
![image](https://user-images.githubusercontent.com/1719461/43646030-b88ea22a-9701-11e8-9071-57d4f1a70b5e.png)

**Logs**
Important part
```
18-8-3 09:42:28.2|Info|RenameEpisodeFileService|Selected episode files renamed for Battlestar Galactica (2003)
18-8-3 09:42:31.7|Info|RenameEpisodeFileService|Renaming 1 files for Battlestar Galactica (2003)
18-8-3 09:42:31.7|Error|RenameEpisodeFileService|Failed to rename file /media/TV Shows/Battlestar Galactica Complete Bluray 1080p x265/tmp/Battlestar.Galactica.Razor.Flashbacks.Complete.v3.1080p.6ch.x265.HEVC.mkv

[v2.0.0.5228] System.IO.PathTooLongException: Path is too long. Path: 
  at System.IO.File.Move (System.String sourceFileName, System.String destFileName) [0x00116] in <c5bcd0ec45b240acb20cfcfa5eee2246>:0 
  at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal (System.String source, System.String destination) [0x00000] in <8faeb593f49341d6a7a6d2c3c281887c>:0 
  at NzbDrone.Mono.Disk.DiskProvider.MoveFileInternal (System.String source, System.String destination) [0x00076] in <cd50cb4f3a50490d80a10df172583553>:0 
  at NzbDrone.Common.Disk.DiskProviderBase.MoveFile (System.String source, System.String destination, System.Boolean overwrite) [0x000e3] in <8faeb593f49341d6a7a6d2c3c281887c>:0 
  at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileTransactional (System.String sourcePath, System.String targetPath, System.Int64 originalSize, NzbDrone.Common.Disk.DiskTransferVerificationMode verificationMode) [0x0008f] in <8faeb593f49341d6a7a6d2c3c281887c>:0 
  at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, NzbDrone.Common.Disk.TransferMode mode, System.Boolean overwrite, NzbDrone.Common.Disk.DiskTransferVerificationMode verificationMode) [0x003ce] in <8faeb593f49341d6a7a6d2c3c281887c>:0 
  at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, NzbDrone.Common.Disk.TransferMode mode, System.Boolean overwrite, System.Boolean verified) [0x0000e] in <8faeb593f49341d6a7a6d2c3c281887c>:0 
  at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile (NzbDrone.Core.MediaFiles.EpisodeFile episodeFile, NzbDrone.Core.Tv.Series series, System.Collections.Generic.List`1[T] episodes, System.String destinationFilePath, NzbDrone.Common.Disk.TransferMode mode) [0x0012c] in <f8c4a2c9e6194b509efc6018724d76df>:0 
  at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.MoveEpisodeFile (NzbDrone.Core.MediaFiles.EpisodeFile episodeFile, NzbDrone.Core.Tv.Series series) [0x0008b] in <f8c4a2c9e6194b509efc6018724d76df>:0 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.RenameFiles (System.Collections.Generic.List`1[T] episodeFiles, NzbDrone.Core.Tv.Series series) [0x0003d] in <f8c4a2c9e6194b509efc6018724d76df>:0 
```
**System Information**

 - Sonarr Version: 2.0.0.5228
 - Operating System: FreeBSD 11.1-STABLE (FreeNAS)
 - mono Version: 5.2.0

**Additional context**
I expected Sonarr to name the episode `S00E33-39 - Razor Minisode (1-7) [Bluray-1080p x265 AAC] |Sonarr|.mkv` or similar, but since each episode has a partially different name it's slapping them all together and making the name obscenely long.

Is there any way to have a fallback renaming sceme? Or maybe the ability to specify a custom name for the episode from within Sonarr?

**Comment by markus101** [comment]
v3 will have long path support to deal with this problem, no plans to work around it before then.

https://github.com/Sonarr/Sonarr/issues/815

**Comment by Adrian-at-CrimsonAuzre** [comment]
The ZFS **filename** limit is 255 characters, how is a new .net/mono version going to add support for longer filenames than the filesystem allows?

**Comment by markus101** [comment]
Ahh, overlooked that part of the issue.

Sonarr tried to shorten the episode title when it's a repeat with only a number at the end changing, but in this case they're too different for that to apply.

Removing the episode titles in this scenario is likely the solution we'd go for.

**Comment by Adrian-at-CrimsonAuzre** [comment]
Maybe strip everything after the (#) when dealing with a single file multipart episode? It can probably be assumed that, everything after that is the individual episode title.

**Comment by Buri** [comment]
Any progress on this? Still an error on v3 nightly

**Comment by warsix4** [comment]
The error now produced after updating to v3: 

```
19-8-4 00:47:05.9|Warn|ImportApprovedEpisodes|Couldn't import episode \\storage\Scratch\Completed\[HorribleSubs] Okaa-san Online - 04 [720p].mkv

[v3.0.2.560] System.IO.DirectoryNotFoundException: Could not find a part of the path.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal(String source, String destination) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 240
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 227
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 594
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 338
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 213
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile(EpisodeFile episodeFile, Series series, List`1 episodes, String destinationFilePath, TransferMode mode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 119
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.MoveEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 79
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 77
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 108

19-8-4 00:47:33.5|Error|DiskTransferService|Failed to properly rollback the file move [\\storage\Scratch\Completed\[HorribleSubs] Okaa-san Online - 04 [720p].mkv] to [\\storage\Alt Media\Subbed\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks\Season 1\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks! - S01E04 - Kids Are Kids and Parents Are Parents but Also Human Beings, and It Takes All Kinds, but They Get Through It Together, Right HDTV-720p.mkv], incomplete file may be left in target path.

[v3.0.2.560] System.IO.DirectoryNotFoundException: Could not find a part of the path '\\storage\Alt Media\Subbed\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks\Season 1\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks! - S01E04 - Kids Are Kids and Parents Are Parents but Also Human Beings, and It Takes All Kinds, but They Get Through It Together, Right HDTV-720p.mkv'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at NzbDrone.Common.Disk.DiskProviderBase.DeleteFile(String path) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 190
   at NzbDrone.Common.Disk.DiskTransferService.RollbackPartialMove(String sourcePath, String targetPath) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 376

19-8-4 00:47:33.5|Warn|ImportApprovedEpisodes|Couldn't import episode \\storage\Scratch\Completed\[HorribleSubs] Okaa-san Online - 04 [720p].mkv

[v3.0.2.560] System.IO.DirectoryNotFoundException: Could not find a part of the path.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal(String source, String destination) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 240
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 227
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 594
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 338
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 213
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile(EpisodeFile episodeFile, Series series, List`1 episodes, String destinationFilePath, TransferMode mode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 119
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.MoveEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 79
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 77
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 108
```

**Comment by markus101** [comment]
Which directory isn't there? None of those path sections exceed 255 characters so nothing is truncated.

Best to open a thread on the forums/subreddit for troubleshooting. WE'll need to see debug logs.

**Comment by warsix4** [comment]
I posted on reddit about this, and commente don two other threads with the same issue with the same show!

Here's the current log

```
19-8-5 16:08:06.3|Warn|ImportApprovedEpisodes|Couldn't import episode \\storage\Scratch\NZB\complete\[HorribleSubs] Okaa-san Online - 03 [720p]\[HorribleSubs] Okaa-san Online - 03 [720p].mkv

[v3.0.2.560] System.IO.DirectoryNotFoundException: Could not find a part of the path.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal(String source, String destination) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 240
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 227
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 594
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 338
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 213
   at NzbDrone.Core.MediaFiles.RecycleBinProvider.DeleteFile(String path, String subfolder) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RecycleBinProvider.cs:line 120
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 64
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 108

19-8-5 16:08:41.1|Error|DiskTransferService|Failed to properly rollback the file move [\\storage\Alt Media\Subbed\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks\Season 1\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks! - S01E03 - Underwear is Armor. Make Sure It’s High in Defense. Otherwise, My Son Might Die! HDTV-720p.mp4] to [\\storage\Scratch\Recycle Bin\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks\Season 1\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks! - S01E03 - Underwear is Armor. Make Sure It’s High in Defense. Otherwise, My Son Might Die! HDTV-720p.mp4], incomplete file may be left in target path.

[v3.0.2.560] System.IO.DirectoryNotFoundException: Could not find a part of the path '\\storage\Scratch\Recycle Bin\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks\Season 1\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks! - S01E03 - Underwear is Armor. Make Sure It’s High in Defense. Otherwise, My Son Might Die! HDTV-720p.mp4'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at NzbDrone.Common.Disk.DiskProviderBase.DeleteFile(String path) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 190
   at NzbDrone.Common.Disk.DiskTransferService.RollbackPartialMove(String sourcePath, String targetPath) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 376

19-8-5 16:08:41.1|Error|RecycleBinProvider|Unable to move '\\storage\Alt Media\Subbed\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks\Season 1\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks! - S01E03 - Underwear is Armor. Make Sure It’s High in Defense. Otherwise, My Son Might Die! HDTV-720p.mp4' to the recycling bin: '\\storage\Scratch\Recycle Bin\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks\Season 1\Do You Love Your Mom and Her Two-Hit Multi-Target Attacks! - S01E03 - Underwear is Armor. Make Sure It’s High in Defense. Otherwise, My Son Might Die! HDTV-720p.mp4'

[v3.0.2.560] System.IO.DirectoryNotFoundException: Could not find a part of the path.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal(String source, String destination) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 240
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 227
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 594
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 338
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 213
   at NzbDrone.Core.MediaFiles.RecycleBinProvider.DeleteFile(String path, String subfolder) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RecycleBinProvider.cs:line 115

19-8-5 16:08:41.1|Warn|ImportApprovedEpisodes|Couldn't import episode \\storage\Scratch\NZB\complete\[HorribleSubs] Okaa-san Online - 03 [720p]\[HorribleSubs] Okaa-san Online - 03 [720p].mkv

[v3.0.2.560] System.IO.DirectoryNotFoundException: Could not find a part of the path.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal(String source, String destination) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 240
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 227
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 594
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 338
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 213
   at NzbDrone.Core.MediaFiles.RecycleBinProvider.DeleteFile(String path, String subfolder) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RecycleBinProvider.cs:line 120
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 64
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 108

19-8-5 16:08:41.2|Warn|DownloadedEpisodesImportService|Non-sample file detected: [\\storage\Scratch\NZB\complete\[HorribleSubs] Okaa-san Online - 03 [720p]\[HorribleSubs] Okaa-san Online - 03 [720p].mkv]
```

This is what happens after updating v3 recently now instead of getting the filename length error. Did Sonarr make a folder it can't access for some reason?

**Comment by markus101** [comment]
Have you enabled long file support in Windows? https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/
Those aren't debug logs.

PS you got "shot down" because this is not the correct place to troubleshoot issues, we use our forums or the subreddit for that.

**Comment by warsix4** [comment]
I was implying I got shot down on Reddit!On Aug 5, 2019 5:56 PM, Mark McDowall <notifications@github.com> wrote:Have you enabled long file support in Windows? https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/
Those aren't debug logs.
PS you got "shot down" because this is not the correct place to troubleshoot issues, we use our forums or the subreddit for that.
