### ISSUE TITLE
Update does not work and Search for new series stopped working too

### ISSUE THREAD

**Issue by francesco2013** [Sonarr/Sonarr#2732]
Hi,

All of a sudden Sonarr's search functionality for adding new series stopped working and now Sonarr cant find anything. Anything I search is not to be found. I have tried adding a series I have already add too. No results. 

Version
2.0.0.5228
Mono Version
5.12.0.301

Update section loads for a long time and then:

[Debug] Api: [GET] /api/update: 500.InternalServerError (61082 ms)
[Fatal] NzbDroneErrorPipeline: Request Failed. GET /api/update

[v2.0.0.5228] System.Net.WebException: Failed to read complete http response ---> System.Net.WebException: Error getting response stream (ReadAsync): ReceiveFailure Value cannot be null.
Parameter name: src ---> System.ArgumentNullException: Value cannot be null.
Parameter name: src
  at System.Net.HttpWebRequest+<RunWithTimeoutWorker>d__244`1[T].MoveNext () [0x000ba] in <a360a10e096b4659a9142a244ddaea3e>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <b0e1ad7573a24fd5a9f2af9595e677e7>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <b0e1ad7573a24fd5a9f2af9595e677e7>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <b0e1ad7573a24fd5a9f2af9595e677e7>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <b0e1ad7573a24fd5a9f2af9595e677e7>:0
  at System.Net.WebResponseStream+<ReadAsync>d__48.MoveNext () [0x00253] in <a360a10e096b4659a9142a244ddaea3e>:0
   --- End of inner exception stack trace ---
  at System.Net.WebConnectionStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00077] in <a360a10e096b4659a9142a244ddaea3e>:0
  at NzbDrone.Common.Extensions.StreamExtensions.ToBytes (System.IO.Stream input) [0x0001c] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Extensions\StreamExtensions.cs:13
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x001dd] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:108
   --- End of inner exception stack trace ---
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x001e9] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:112
  at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000b5] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:53
  at NzbDrone.Common.Http.HttpClient.ExecuteRequest (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookieContainer) [0x0007e] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:121
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00008] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:57
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:264
  at NzbDrone.Common.Http.HttpClient.Get[T] (NzbDrone.Common.Http.HttpRequest request) [0x00000] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:269
  at NzbDrone.Core.Update.UpdatePackageProvider.GetRecentUpdates (System.String branch, System.Version currentVersion) [0x0006c] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Update\UpdatePackageProvider.cs:55
  at NzbDrone.Core.Update.RecentUpdateProvider.GetRecentUpdatePackages () [0x0000c] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Update\RecentUpdateProvider.cs:27
  at NzbDrone.Api.Update.UpdateModule.GetRecentUpdates () [0x00000] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Api\Update\UpdateModule.cs:20
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Api\REST\RestModule.cs:111
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0

[Debug] Api: [GET] /api/update: 500.InternalServerError (60042 ms)

What have you done ? It was all working perfectly and nothing was touched/changed on my side. 

Please look into it and help me fixing this big issues. 

Thanks.

Francesco Fazio

**Comment by Vehlin** [comment]
Same issue for me. Looks like an issue with the search API.

18-9-14 11:14:30.2|Trace|HttpClient|Res: [GET] http://skyhook.sonarr.tv/v1/tvdb/search/en/?term=star%20trek: 200.OK (30079 ms)
18-9-14 11:14:30.2|Trace|Http|Res: 387 [GET] /api/series/lookup?term=star+trek: 200.OK (30098 ms)
18-9-14 11:14:30.2|Debug|Api|[GET] /api/series/lookup?term=star+trek: 200.OK (30098 ms)
18-9-14 11:14:31.4|Trace|HttpClient|Res: [GET] http://services.sonarr.tv/v1/update/master?version=2.0.0.5228&os=windows&runtimeVer=4.6.2: 504.GatewayTimeout
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<meta http-equiv="refresh" content="0">
<title>services.sonarr.tv | 504: Gateway time-out</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>
</head>
<body>
<div id="cf-wrapper">
<div id="cf-error-details" class="cf-error-details-wrapper">
<div class="cf-wrapper cf-error-overview">
<h1>
<span class="cf-error-type">Error</span>
<span class="cf-error-code">504</span>
<small class="heading-ray-id">Ray ID: 45a214e234bfbc4a &bull; 2018-09-14 10:14:33 UTC</small>
</h1>
<h2 class="cf-subheadline">Gateway time-out</h2>
</div>
<div class="cf-section cf-highlight cf-status-display">
<div class="cf-wrapper">
<div class="cf-columns cols-3">
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-browser"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc">You</span>
<h3 class="cf-status-name">Browser</h3>
<span class="cf-status-label">Working</span>
</div>
<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-cloud"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc">London</span>
<h3 class="cf-status-name">Cloudflare</h3>
<span class="cf-status-label">Working</span>
</div>
<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-server"></i>
<i class="cf-icon-status cf-icon-error"></i>
</div>
<span class="cf-status-desc">services.sonarr.tv</span>
<h3 class="cf-status-name">Host</h3>
<span class="cf-status-label">Error</span>
</div>
</div>
</div>
</div>
<div class="cf-section cf-wrapper">
<div class="cf-columns two">
<div class="cf-column">
<h2>What happened?</h2>
<p>The web server reported a gateway time-out error.</p>
</div>
<div class="cf-column">
<h2>What can I do?</h2>
<p>Please try again in a few minutes.</p>
</div>
</div>
</div>
<div class="cf-error-footer cf-wrapper">
<p>
<span class="cf-footer-item">Cloudflare Ray ID: <strong>45a214e234bfbc4a</strong></span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span>Your IP</span>: 94.12.11.238</span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
</p>
</div>
</div>
</div>
</body>
</html>
 (60073 ms)
18-9-14 11:14:31.4|Warn|HttpClient|HTTP Error - Res: [GET] http://services.sonarr.tv/v1/update/master?version=2.0.0.5228&os=windows&runtimeVer=4.6.2: 504.GatewayTimeout
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<meta http-equiv="refresh" content="0">
<title>services.sonarr.tv | 504: Gateway time-out</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>
</head>
<body>
<div id="cf-wrapper">
<div id="cf-error-details" class="cf-error-details-wrapper">
<div class="cf-wrapper cf-error-overview">
<h1>
<span class="cf-error-type">Error</span>
<span class="cf-error-code">504</span>
<small class="heading-ray-id">Ray ID: 45a214e234bfbc4a &bull; 2018-09-14 10:14:33 UTC</small>
</h1>
<h2 class="cf-subheadline">Gateway time-out</h2>
</div>
<div class="cf-section cf-highlight cf-status-display">
<div class="cf-wrapper">
<div class="cf-columns cols-3">
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-browser"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc">You</span>
<h3 class="cf-status-name">Browser</h3>
<span class="cf-status-label">Working</span>
</div>
<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-cloud"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc">London</span>
<h3 class="cf-status-name">Cloudflare</h3>
<span class="cf-status-label">Working</span>
</div>
<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-server"></i>
<i class="cf-icon-status cf-icon-error"></i>
</div>
<span class="cf-status-desc">services.sonarr.tv</span>
<h3 class="cf-status-name">Host</h3>
<span class="cf-status-label">Error</span>
</div>
</div>
</div>
</div>
<div class="cf-section cf-wrapper">
<div class="cf-columns two">
<div class="cf-column">
<h2>What happened?</h2>
<p>The web server reported a gateway time-out error.</p>
</div>
<div class="cf-column">
<h2>What can I do?</h2>
<p>Please try again in a few minutes.</p>
</div>
</div>
</div>
<div class="cf-error-footer cf-wrapper">
<p>
<span class="cf-footer-item">Cloudflare Ray ID: <strong>45a214e234bfbc4a</strong></span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span>Your IP</span>: 94.12.11.238</span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
</p>
</div>
</div>
</div>
</body>
</html>

18-9-14 11:14:31.4|Error|TaskExtensions|Task Error

[v2.0.0.5228] NzbDrone.Common.Http.HttpException: HTTP request failed: [504:GatewayTimeout] [GET] at [http://services.sonarr.tv/v1/update/master?version=2.0.0.5228&os=windows&runtimeVer=4.6.2]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:line 96
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:line 269
   at NzbDrone.Core.Update.UpdatePackageProvider.GetLatestUpdate(String branch, Version currentVersion) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Update\UpdatePackageProvider.cs:line 38
   at NzbDrone.Core.Update.CheckUpdateService.AvailableUpdate() in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Update\UpdateCheckService.cs:line 26
   at NzbDrone.Core.HealthCheck.Checks.UpdateCheck.Check() in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\HealthCheck\Checks\UpdateCheck.cs:line 63
   at NzbDrone.Core.HealthCheck.HealthCheckService.<>c.<PerformHealthCheck>b__11_0(IProvideHealthCheck c) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 71
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.HealthCheck.HealthCheckService.PerformHealthCheck(IProvideHealthCheck[] healthChecks) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 71
   at NzbDrone.Core.HealthCheck.HealthCheckService.HandleAsync(IEvent message) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\HealthCheck\HealthCheckService.cs:line 123
   at NzbDrone.Core.Messaging.Events.EventAggregator.<>c__DisplayClass6_1`1.<PublishEvent>b__0() in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 111
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<meta http-equiv="refresh" content="0">
<title>services.sonarr.tv | 504: Gateway time-out</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>
</head>
<body>
<div id="cf-wrapper">
<div id="cf-error-details" class="cf-error-details-wrapper">
<div class="cf-wrapper cf-error-overview">
<h1>
<span class="cf-error-type">Error</span>
<span class="cf-error-code">504</span>
<small class="heading-ray-id">Ray ID: 45a214e234bfbc4a &bull; 2018-09-14 10:14:33 UTC</small>
</h1>
<h2 class="cf-subheadline">Gateway time-out</h2>
</div>
<div class="cf-section cf-highlight cf-status-display">
<div class="cf-wrapper">
<div class="cf-columns cols-3">
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-browser"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc">You</span>
<h3 class="cf-status-name">Browser</h3>
<span class="cf-status-label">Working</span>
</div>
<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-cloud"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc">London</span>
<h3 class="cf-status-name">Cloudflare</h3>
<span class="cf-status-label">Working</span>
</div>
<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-server"></i>
<i class="cf-icon-status cf-icon-error"></i>
</div>
<span class="cf-status-desc">services.sonarr.tv</span>
<h3 class="cf-status-name">Host</h3>
<span class="cf-status-label">Error</span>
</div>
</div>
</div>
</div>
<div class="cf-section cf-wrapper">
<div class="cf-columns two">
<div class="cf-column">
<h2>What happened?</h2>
<p>The web server reported a gateway time-out error.</p>
</div>
<div class="cf-column">
<h2>What can I do?</h2>
<p>Please try again in a few minutes.</p>
</div>
</div>
</div>
<div class="cf-error-footer cf-wrapper">
<p>
<span class="cf-footer-item">Cloudflare Ray ID: <strong>45a214e234bfbc4a</strong></span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span>Your IP</span>: 94.12.11.238</span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
</p>
</div>
</div>
</div>
</body>
</html>

**Comment by desy83** [comment]
Same issue here:
Sonarr Version
    2.0.0.5054
Mono Version
    5.8.0.108

**Comment by rpatel** [comment]
searches by tvdbID work

**Comment by Haydonn** [comment]
Same issue here:
Sonarr Version
2.0.0.5228
Mono Version
5.14.0.177

**Comment by Rikumo1978** [comment]
Confirmed not working here too. TVDB ID doesn't work for me either. Rebooted VM's and Software multiple times just in case it was out of RAM or something. Nothing works. I'm sure it will come back online today though. :-)

**Comment by Dnkhatri** [comment]
The backend skyhook system seems down

**Comment by yoyellow** [comment]
Same issue here, cant find series on name or tvdbID

**Comment by markus101** [comment]
Thanks for reaching out. A docker container that should have been disabled started up and chewed through the available diskspace rapidly through the night and took prevented the DB backing skyhook/services from functioning properly. I've taken care of the offending container and cleaned up the disk space.

Everything should be functional now.

**Comment by Rikumo1978** [comment]
Yep! All is well!

**Comment by francesco2013** [comment]
The update tab does not seem to load but the search works again. I can confirm it. 
@markus101 thank you for your help man !

**Comment by markus101** [comment]
Gave the services app an extra kick and updates are coming through again. Thanks for letting me know.
