### ISSUE TITLE
Unable to add new show to monitor list

### ISSUE THREAD

**Issue by gvtters** [Sonarr/Sonarr#2765]
## Message

`Request Failed. POST /api/v3/series: Error converting value "allEpisodes" to type 'NzbDrone.Core.Tv.MonitorTypes'. Path 'addOptions.monitor', line 1, position 1450.
`

## Exception
`Newtonsoft.Json.JsonSerializationException: Error converting value "allEpisodes" to type 'NzbDrone.Core.Tv.MonitorTypes'. Path 'addOptions.monitor', line 1, position 1450. ---> System.ArgumentException: Requested value 'allEpisodes' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Type t)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize(String json, Type type) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Serializer\Json.cs:line 55
   at Sonarr.Http.Extensions.ReqResExtensions.FromJson(Stream body, Type type) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Http\Extensions\ReqResExtensions.cs:line 31
   at Sonarr.Http.Extensions.ReqResExtensions.FromJson[T](Stream body, Type type) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Http\Extensions\ReqResExtensions.cs:line 24
   at Sonarr.Http.Extensions.ReqResExtensions.FromJson[T](Stream body) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Http\Extensions\ReqResExtensions.cs:line 19
   at Sonarr.Http.REST.RestModule`1.ReadResourceFromRequest(Boolean skipValidate) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Http\REST\RestModule.cs:line 198
   at Sonarr.Http.REST.RestModule`1.<set_CreateResource>b__42_0(Object options) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Http\REST\RestModule.cs:line 165
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)`

**Sonarr Version: 3.0.0.263**

**Operating System: Win 10 1803**

**.net Framework (Windows) or mono (macOS/Linux) Version:**

**Link to Log Files (debug or trace):**

**Browser (for UI bugs): Chrome**

**Comment by D3nn3** [comment]
Have the same problem. Workaround for now: Select in the Monitoring options something else than "All Episodes". Did the trick for me.
