### ISSUE TITLE
TVDB 503s on site and in Sonarr API requests, impossible to add new series

### ISSUE THREAD

**Issue by ericralph** [Sonarr/Sonarr#2815]
TVDB appears to have been down for at least a week, preventing me from adding new shows to Sonarr through the UI. When searching for anything at all, the search will error:

> There Was An Error Searching For 'Show'.
> If the series title contains non-alphanumeric characters try removing them, otherwise try your search again later.

TVDB's main page appears to be fine, but searching for anything results in a 503.

**Logs**

> 18-11-11 17:53:21.1|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (2 ms)
> 18-11-11 17:53:21.6|Warn|SkyHookProxy|The underlying connection was closed: The connection was closed unexpectedly.
> 
> [v2.0.0.5270] System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
>    at System.Net.HttpWebRequest.GetResponse()
>    at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 96
>    at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 53
>    at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:line 121
>    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:line 57
>    at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:line 269
>    at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewSeries(String title) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 92
> 
> 18-11-11 17:53:21.6|Debug|Api|[GET] /api/series/lookup?term=de: 503.ServiceUnavailable (2153 ms)
> 18-11-11 17:53:22.7|Warn|SkyHookProxy|The underlying connection was closed: The connection was closed unexpectedly.
> 
> [v2.0.0.5270] System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
>    at System.Net.HttpWebRequest.GetResponse()
>    at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 96
>    at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 53
>    at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:line 121
>    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:line 57
>    at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:line 269
>    at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewSeries(String title) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 92
> 
> 18-11-11 17:53:22.7|Debug|Api|[GET] /api/series/lookup?term=deadwind: 503.ServiceUnavailable (1015 ms)
> 18-11-11 17:53:25.3|Debug|Api|[GET] /api/health: 200.OK (0 ms)
> 18-11-11 17:53:25.4|Debug|Api|[GET] /api/health: 200.OK (0 ms)
> 18-11-11 17:53:25.4|Debug|Api|[GET] /api/diskspace: 200.OK (57 ms)
> 18-11-11 17:53:25.4|Debug|Api|[GET] /api/diskspace: 200.OK (50 ms)
> 18-11-11 17:53:27.3|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (16 ms)
> 18-11-11 17:53:27.3|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (6 ms)
> 18-11-11 17:54:32.5|Debug|Api|[GET] /api/log/file: 200.OK (5 ms)
> 18-11-11 17:54:32.5|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (1 ms)
> 18-11-11 17:54:38.8|Debug|Api|[GET] /api/log/file: 200.OK (4 ms)
> 18-11-11 17:54:38.8|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (0 ms)
> 18-11-11 17:54:42.6|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (2 ms)

**System Information**

 - Sonarr Version: 2.0.0.5270
 - Operating System: Windows 10
 - .net Framework: Windows 4.7.2

**Comment by ericralph** [comment]
psych. Found the problem. No clue why TVDB also 503'd for me outside of Sonarr, but my proxy client had changed the password on me without notifying. Updated the password and everything is back to normal.
