### ISSUE TITLE
Check Content Type before parsing when fetching data from skyhook/services

### ISSUE THREAD

**Issue by CollinChaffin** [Sonarr/Sonarr#2817]
Suddenly receiving this really cryptic error when refreshing a series.  Series added in Sonarr after it looked up successfully is the series named `24`.  All episodes shown, even downloaded one using Sonarr interface so was surprised when clicking refresh and getting this multiple times now:

Message:
````
Error occurred while executing task RefreshSeries: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. (Json snippet '<--error--><!DOCTYPE html PUBLI')
````

Exception:
````
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. (Json snippet '<--error--><!DOCTYPE html PUBLI') ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Serializer\Json.cs:line 40
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Serializer\Json.cs:line 44
   at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpResponse.cs:line 97
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Http\HttpClient.cs:line 269
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetSeriesInfo(Int32 tvdbSeriesId) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 40
   at NzbDrone.Core.Tv.RefreshSeriesService.RefreshSeriesInfo(Series series) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Tv\RefreshSeriesService.cs:line 57
   at NzbDrone.Core.Tv.RefreshSeriesService.Execute(RefreshSeriesCommand message) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Tv\RefreshSeriesService.cs:line 175
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 95
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41
````

**Comment by CollinChaffin** [comment]
I should add it has refreshed once and been sporadic so perhaps this is related to a skyhook lookup issue?  Also of note the episode successfully added with Sonarr only for this series for some reason also did not have it's file timestamp modified date reset to air date whereas another series/ep on same run just did so perhaps it's related to this series having a name that is merely a small integer?

**Comment by Taloth** [comment]
@markus101 At the least we should check the content type like we do with indexers so the error is less cryptic.

**Comment by CollinChaffin** [comment]
Looks good now as far as the refresh any idea why for s01e01 of 24 which aired 11/5/2001 that it is not refreshing what I assume is the original file (unpacked) date of 8/7/2017?  Not huge but want to verify since no log errors and this series is about the shortest (and only numeric) title there is and I know Sonarr has had some parsing issues in the past.

Thanks!

**Comment by markus101** [comment]
@Taloth Updated the title to reflect the action we need to take.

@CollinChaffin the series title wouldn't have change how it's parsed/how dates are updated, you'll need to check the debug logs for more information on that. Please open a thread on the forums if you have any questions after taking a look.
