### ISSUE TITLE
Sonarr is unable to connect to Download Station if 2-Factor Authentication is enabled on your DSM account

### ISSUE THREAD

**Issue by Smultie** [Sonarr/Sonarr#3121]
After today's DSM update, I get the following warning when going to the Download Client settings:
"Sonarr is unable to connect to Download Station if 2-Factor Authentication is enabled on your DSM account"

Pressing 'Test' gives 
Failed to get the list of torrents: Failed to get serial number. Reason: 119 - Unknown error
Unknown exception: Failed to get info of /autodownload/series. Reason: 119 - Unknown error

Log:
19-5-15 20:05:19.7|Error|FileStationProxy|Failed to get info of /autodownload/series. Reason: 119 - Unknown error
19-5-15 20:05:19.7|Error|TorrentDownloadStation|Error testing Torrent Download Station

[v2.0.0.5322] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to get info of /autodownload/series. Reason: 119 - Unknown error
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.DiskStationProxyBase.ProcessRequest[T](HttpRequestBuilder requestBuilder, String operation, DiskStationApi api, DownloadStationSettings settings) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\DiskStationProxyBase.cs:line 115
   at NzbDrone.Core.Download.Clients.DownloadStation.Proxies.FileStationProxy.GetInfoFileOrDirectory(String path, DownloadStationSettings settings) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\DownloadStation\Proxies\FileStationProxy.cs:line 41
   at NzbDrone.Core.Download.Clients.DownloadStation.TorrentDownloadStation.TestOutputPath() in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Download\Clients\DownloadStation\TorrentDownloadStation.cs:line 319

**Comment by markus101** [comment]
Please fill out all the requested information. Including the debug logs uploaded elsewhere and linked here.

The obvious question is do you have 2 factor authentication enabled?

**Comment by Smultie** [comment]
I do, I've always had, never was an issue.

**Comment by markus101** [comment]
https://github.com/Sonarr/Sonarr/issues/1912 has a number of possible causes/fixes, given you did an upgrade permissions seems possible. Having 2FA enabled is a known issue though, best to use another account.
