### ISSUE TITLE
Error during importing of downloaded file: ImportDecisionMaker and ImportApprovedEpisodes

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [Sonarr/Sonarr#3159]
**Describe the bug**
During importing of downloaded files from the download folder to the target folder, two errors occur.

**System Information**

 - Sonarr Version: 2.0.0.5322
 - Operating System: Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: None, is this required? It worked before without this as well.

**Logs**
[sonarr-logs.txt](https://github.com/Sonarr/Sonarr/files/3273694/sonarr-logs.txt)

```
19-6-10 22:31:04.8|Error|ImportDecisionMaker|Couldn't evaluate decision on G:\Downloads\completed\The.Handmaids.Tale.S02E01.June.1080p.HULU.WEBRip.AAC2.0.H264-NTb[rarbg]\The.Handmaid's.Tale.S02E01.June.1080p.HULU.WEB-DL.AAC2.0.H.264-NTb.mkv

[v2.0.0.5322] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.EpisodeImport.Specifications.UpgradeSpecification.<>c__DisplayClass2_0.<IsSatisfiedBy>b__0(Episode e) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\Specifications\UpgradeSpecification.cs:line 22
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Core.MediaFiles.EpisodeImport.Specifications.UpgradeSpecification.IsSatisfiedBy(LocalEpisode localEpisode, DownloadClientItem downloadClientItem) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\Specifications\UpgradeSpecification.cs:line 22
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.EvaluateSpec(IImportDecisionEngineSpecification spec, LocalEpisode localEpisode, DownloadClientItem downloadClientItem) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportDecisionMaker.cs:line 160

19-6-10 22:31:08.2|Warn|ImportApprovedEpisodes|Couldn't import episode G:\Downloads\completed\The.Handmaids.Tale.S02E01.June.1080p.HULU.WEBRip.AAC2.0.H264-NTb[rarbg]\The.Handmaid's.Tale.S02E01.June.1080p.HULU.WEB-DL.AAC2.0.H.264-NTb.mkv

[v2.0.0.5322] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.<>c.<UpgradeEpisodeFile>b__6_2(EpisodeFile e) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 43
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 40
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 105

19-6-10 22:31:08.2|Warn|DownloadedEpisodesImportService|Non-sample file detected: [G:\Downloads\completed\The.Handmaids.Tale.S02E01.June.1080p.HULU.WEBRip.AAC2.0.H264-NTb[rarbg]\The.Handmaid's.Tale.S02E01.June.1080p.HULU.WEB-DL.AAC2.0.H.264-NTb.mkv]
19-6-10 22:32:21.4|Error|ImportDecisionMaker|Couldn't evaluate decision on G:\Downloads\completed\The.Handmaids.Tale.S02E01.June.1080p.HULU.WEBRip.AAC2.0.H264-NTb[rarbg]\The.Handmaid's.Tale.S02E01.June.1080p.HULU.WEB-DL.AAC2.0.H.264-NTb.mkv

[v2.0.0.5322] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.EpisodeImport.Specifications.SameFileSpecification.IsSatisfiedBy(LocalEpisode localEpisode, DownloadClientItem downloadClientItem) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\Specifications\SameFileSpecification.cs:line 33
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.EvaluateSpec(IImportDecisionEngineSpecification spec, LocalEpisode localEpisode, DownloadClientItem downloadClientItem) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportDecisionMaker.cs:line 160

19-6-10 22:32:21.4|Error|ImportDecisionMaker|Couldn't evaluate decision on G:\Downloads\completed\The.Handmaids.Tale.S02E01.June.1080p.HULU.WEBRip.AAC2.0.H264-NTb[rarbg]\The.Handmaid's.Tale.S02E01.June.1080p.HULU.WEB-DL.AAC2.0.H.264-NTb.mkv

[v2.0.0.5322] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.EpisodeImport.Specifications.UpgradeSpecification.<>c__DisplayClass2_0.<IsSatisfiedBy>b__0(Episode e) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\Specifications\UpgradeSpecification.cs:line 22
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Core.MediaFiles.EpisodeImport.Specifications.UpgradeSpecification.IsSatisfiedBy(LocalEpisode localEpisode, DownloadClientItem downloadClientItem) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\Specifications\UpgradeSpecification.cs:line 22
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.EvaluateSpec(IImportDecisionEngineSpecification spec, LocalEpisode localEpisode, DownloadClientItem downloadClientItem) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportDecisionMaker.cs:line 160
```

**Comment by markus101** [comment]
It looks like this is failing because there was an episode file but it was removed and Sonarr's data is out of sync. Refreshing the affected series or running the housekeeping task should fix it.
