### ISSUE TITLE
Error occurred while executing task DownloadedEpisodesScan: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

### ISSUE THREAD

**Issue by injector22** [Sonarr/Sonarr#3317]
I've been getting the error below and searches now won't return any results. It started happening on version 2.0.0.5338. Not sure if the fact that the exception is showing file paths in the M:\ drive are valid errors or not since I don't have an M: drive.

System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at System.IO.DirectoryInfo..ctor(String path)
   at NzbDrone.Common.Extensions.PathExtensions.IsParentPath(String parentPath, String childPath) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 96
   at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath(String parentPath, String childPath) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 62
   at NzbDrone.Core.MediaFiles.DiskScanService.<>c__DisplayClass16_0.<FilterFiles>b__0(String file) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 166
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.DiskScanService.FilterFiles(String basePath, IEnumerable`1 files) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 166
   at NzbDrone.Core.MediaFiles.DownloadedEpisodesImportService.ProcessFolder(DirectoryInfo directoryInfo, ImportMode importMode, Series series, DownloadClientItem downloadClientItem) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\DownloadedEpisodesImportService.cs:line 160
   at NzbDrone.Core.MediaFiles.DownloadedEpisodesImportService.ProcessFolder(DirectoryInfo directoryInfo, ImportMode importMode, DownloadClientItem downloadClientItem) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\DownloadedEpisodesImportService.cs:line 148
   at NzbDrone.Core.MediaFiles.DownloadedEpisodesImportService.ProcessRootFolder(DirectoryInfo directoryInfo) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\DownloadedEpisodesImportService.cs:line 59
   at NzbDrone.Core.MediaFiles.DownloadedEpisodesCommandService.ProcessDroneFactoryFolder() in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\DownloadedEpisodesCommandService.cs:line 52
   at NzbDrone.Core.MediaFiles.DownloadedEpisodesCommandService.Execute(DownloadedEpisodesScanCommand message) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\DownloadedEpisodesCommandService.cs:line 90
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 95
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

**Comment by injector22** [comment]
Figured it out. There was a file with a filename too long in the downloaded directory.
