### ISSUE TITLE
Interactive search results not showing

### ISSUE THREAD

**Issue by Varnsen** [Sonarr/Sonarr#3377]
**Describe the bug**
Shows added to sonarr with the Series Type 'Anime' don't display results in the manual search UI. Shows still download fine with the automatic search, results just aren't shown on the manual/interactive search UI.

**Logs**
```
19-11-5 04:56:22.8|Info|NzbSearchService|Searching 1 indexers for [Fairy Tail : 18]
19-11-5 04:56:58.0|Info|DownloadDecisionMaker|Processing 775 releases
19-11-5 04:57:11.2|Error|ReleaseModule|Episode search failed: Object reference not set to an instance of an object

[v3.0.3.653] System.NullReferenceException: Object reference not set to an instance of an object
  at Sonarr.Api.V3.Indexers.ReleaseResourceMapper.ToResource (NzbDrone.Core.DecisionEngine.DownloadDecision model) [0x00039] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseResource.cs:84 
  at Sonarr.Api.V3.Indexers.ReleaseModuleBase.MapDecision (NzbDrone.Core.DecisionEngine.DownloadDecision decision, System.Int32 initialWeight) [0x00006] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModuleBase.cs:25 
  at Sonarr.Api.V3.Indexers.ReleaseModule.MapDecision (NzbDrone.Core.DecisionEngine.DownloadDecision decision, System.Int32 initialWeight) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:203 
  at Sonarr.Api.V3.Indexers.ReleaseModuleBase.MapDecisions (System.Collections.Generic.IEnumerable`1[T] decisions) [0x00016] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModuleBase.cs:15 
  at Sonarr.Api.V3.Indexers.ReleaseModule.GetEpisodeReleases (System.Int32 episodeId) [0x0001c] in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:157
```

**System Information**

 - Sonarr Version: 3.0.3.653
 - Operating System: Linux, Sonarr Running in docker (linuxserver/sonarr:preview)

**Additional context**
I've downgraded to version v3.0.3.652 which doesn't have the issue.

**Comment by markus101** [comment]
Please post the entire debug log of the search. That should help us see why it's failing.

**Comment by markus101** [comment]
Debug logs from duplicate GHI: https://pastebin.com/YLTuVttY

**Comment by saulomarchiori** [comment]
Same problem here, but for standard series too. Sonarr 3.0.3.653 @ Windows Service.

19-11-6 14:55:14.9|Error|ReleaseModule|Episode search failed: Object reference not set to an instance of an object.

```
[v3.0.3.653] System.NullReferenceException: Object reference not set to an instance of an object.
   at Sonarr.Api.V3.Indexers.ReleaseResourceMapper.ToResource(DownloadDecision model) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseResource.cs:line 84
   at Sonarr.Api.V3.Indexers.ReleaseModuleBase.MapDecision(DownloadDecision decision, Int32 initialWeight) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModuleBase.cs:line 25
   at Sonarr.Api.V3.Indexers.ReleaseModule.MapDecision(DownloadDecision decision, Int32 initialWeight) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:line 203
   at Sonarr.Api.V3.Indexers.ReleaseModuleBase.MapDecisions(IEnumerable`1 decisions) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModuleBase.cs:line 13
   at Sonarr.Api.V3.Indexers.ReleaseModule.GetEpisodeReleases(Int32 episodeId) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:line 157
```
