### ISSUE TITLE
Moving a grabbed file fails with the message "Unable to find the specified file" on MoveFile.

### ISSUE THREAD

**Issue by Deathspike** [Sonarr/Sonarr#3389]
**Describe the bug**
Moving a grabbed file fails with the message "Unable to find the specified file" on MoveFile.

**Logs**
```
19-11-10 20:06:39.1|Warn|ImportApprovedEpisodes|Couldn't import episode D:\Downloads\MYFOLDERHERE\MYFILEHERE.mkv

[v3.0.3.654] System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal(String source, String destination) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 241
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 228
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 596
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 340
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 215
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile(EpisodeFile episodeFile, Series series, List`1 episodes, String destinationFilePath, TransferMode mode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 119
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.MoveEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 79
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 77
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 111
```

**System Information**
 - Sonarr Version: v3.0.3.654
 - Operating System: Windows 10 (1903)
 - .NET Framework (Windows) Version: [e.g. 4.5 or 5.12]: .NET Framework 4.8

**Additional context**
* Sonarr is running as current user (not as a service). 
* Entering the source path into run will open the file without an issue.
* It's attempting to move the file from D:\ to E:\, thus, it should be moving between disks.
* The user has permissions (full control, both are NTFS) for the source and destination folder. This has also been checked with the advanced security tab in Windows to determine effective access (all permissions granted).
* It used to work some time ago.

**Comment by Deathspike** [comment]
Damn, I figured it out. Turns out Ransomware Protection turned on in a recent Windows 10 update... and it was blocking Sonarr since it was not listed as an "authorized" application. Adding it to the allowed apps solves the issue.
