### ISSUE TITLE
Unable to communicate with SkyHook

### ISSUE THREAD

**Issue by Turge08** [Sonarr/Sonarr#3402]
Tried adding a new show and I'm getting an error "Unable to communicate with SkyHook" when trying to add a new show. Also getting an error checking for updates.

Checked with a friend of mine and he has the same issue. 

I'm able to resolve skyjook.sonarr.tv to IP address "104.25.51.107".

Anyone else?

19-11-15 19:51:59.2|Warn|HttpClient|HTTP Error - Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=tacoma: 404.NotFound
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>

19-11-15 19:52:16.1|Warn|HttpClient|HTTP Error - Res: [GET] https://skyhook.sonarr.tv/v1/tvdb/search/en/?term=tacoma: 404.NotFound
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>

19-11-15 19:53:09.0|Warn|HttpClient|HTTP Error - Res: [GET] https://services.sonarr.tv/v1/update/phantom-develop?version=3.0.3.655&os=windows&runtimeVer=4.8.0: 404.NotFound
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>

19-11-15 19:53:09.0|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v3.0.3.655] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://services.sonarr.tv/v1/update/phantom-develop?version=3.0.3.655&os=windows&runtimeVer=4.8.0]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:line 96
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:line 276
   at NzbDrone.Core.Update.UpdatePackageProvider.GetLatestUpdate(String branch, Version currentVersion) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Update\UpdatePackageProvider.cs:line 46
   at NzbDrone.Core.Update.CheckUpdateService.AvailableUpdate() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Update\UpdateCheckService.cs:line 26
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 207
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 95
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>

**Comment by bakhtiarkamal** [comment]
Same for me as well.

Running Version 2.0.0.5301, Mono Version 5.18.0.240

`Request Failed. GET /api/update: HTTP request failed: [404:NotFound] [GET] at [http://services.sonarr.tv/v1/update/master/changes?version=2.0.0.5301&os=linux&runtimeVer=5.18.0.240]
`

`NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://services.sonarr.tv/v1/update/master/changes?version=2.0.0.5301&os=linux&runtimeVer=5.18.0.240]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00132] in <da318c059b2c4e18a12ce1003b1dc734>:0 
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in <da318c059b2c4e18a12ce1003b1dc734>:0 
  at NzbDrone.Common.Http.HttpClient.Get[T] (NzbDrone.Common.Http.HttpRequest request) [0x00000] in <da318c059b2c4e18a12ce1003b1dc734>:0 
  at NzbDrone.Core.Update.UpdatePackageProvider.GetRecentUpdates (System.String branch, System.Version currentVersion) [0x0006c] in <db6accd1acca4b7b89f971b6407b53be>:0 
  at NzbDrone.Core.Update.RecentUpdateProvider.GetRecentUpdatePackages () [0x00018] in <db6accd1acca4b7b89f971b6407b53be>:0 
  at NzbDrone.Api.Update.UpdateModule.GetRecentUpdates () [0x00000] in <97611c9027bb4885a0ae967db9955f68>:0 
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00006] in <97611c9027bb4885a0ae967db9955f68>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>`

**Comment by markus101** [comment]
Some minor issues after a restart, it's back up now.
