### ISSUE TITLE
Unable to parse file

### ISSUE THREAD

**Issue by mosath-s** [Sonarr/Sonarr#3422]
**Describe the bug**
Sonarr cant parse filename, how can I fix this?

When I try to add it manually got:
`Season must be chosen for each selected file`
**Logs**
```
[AniDub]_Dr_Stone_[01]_[1080p_x264_Aac]_[JAM_Trina_D].mp4
Unable to parse file
```

**System Information**

 - Sonarr Version: [2.0.0.5338]
 - Operating System: [Windows 10]

**Comment by markus101** [comment]
That is a terrible name, the effort to support it may not be worth the effort.

As for manual import the error tells you what to do, select the season so you can import it (then the episode(s)).

**Comment by mosath-s** [comment]
> As for manual import the error tells you what to do, select the season so you can import it (then the episode(s)).
On manual import I see error in logs:
`19-11-24 21:33:56.3|Error|CommandExecutor|Error occurred while executing task ManualImport

[v2.0.0.5338] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Qualities.QualityModelComparer.Compare(QualityModel left, QualityModel right) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Qualities\QualityModelComparer.cs:line 29
   at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 50
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.Execute(ManualImportCommand message) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\MediaFiles\EpisodeImport\Manual\ManualImportService.cs:line 301
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 95
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41
`

**Comment by dm3ch** [comment]
@markus101 Is there any chance to  see support of such terrible naming scheme in Sonarr?

AniDub is very popular Russian anime tracker and suddenly all their releases have same naming scheme and renaming files manually or importing them manually could be very annoying cause sometimes you importing more than 300 series. :(
