### ISSUE TITLE
Blackhole download client unavailable due to failures

### ISSUE THREAD

**Issue by oldominion** [Sonarr/Sonarr#3571]
**Describe the bug**
When using blackhole, and a very long file/folder is created by the download client in the monitored directory, the Refresh Monitored Downloads task fails and won't complete successfully until the folder\file is removed\renamed. Of course, it would be great if the download client wouldn't create invalid files\folders (waiting for a fix), but equally Sonarr should be able to handle the error case by skipping the invalid file\folder instead of failing the whole job.

**To Reproduce**
1. Create a subfolder within the monitored folder of excessive length.
2. Wait for the  task to fail.

**Expected behavior**
Job should handle the invalid long file\folder names gracefully and continue. 

**Screenshots**
N/A

**Logs**
Log:
20-2-11 01:03:09.1|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from Newsleecher

[v0.7.1.1381] System.IO.FileNotFoundException: File doesn't exist: D:\Public\Video\Temp\Downloading\A VERY LONG FOLDERNAME\A VERY LONG FILENAME.mkv
   at NzbDrone.Common.Disk.DiskProviderBase.GetFileSize(String path) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 184
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at NzbDrone.Core.Download.Clients.Blackhole.ScanWatchFolder.<GetDownloadItems>d__6.MoveNext() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Blackhole\ScanWatchFolder.cs:line 74
   at NzbDrone.Core.Download.Clients.Blackhole.ScanWatchFolder.GetItems(String watchFolder, TimeSpan waitPeriod) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Blackhole\ScanWatchFolder.cs:line 41
   at NzbDrone.Core.Download.Clients.Blackhole.UsenetBlackhole.<GetItems>d__9.MoveNext() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\Blackhole\UsenetBlackhole.cs:line 58
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in D:\a\1\s\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 91

Event:
DownloadMonitoringService	Unable to retrieve queue and history items from Newsleecher: File doesn't exist: D:\Public\Video\Temp\Downloading\A VERY LONG FOLDERNAME\A VERY LONG FILENAME.mkv

**System Information**
 - Sonarr Version: 3.0.3.690
 - Operating System: Windows
 - .net Framework (Windows) Version: 4.7.1

**Additional context**

**Comment by markus101** [comment]
Which version of Windows?
If you're using Windows 10 have you enabled long path support? https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/
