### ISSUE TITLE
Deleting files from series page isn't working

### ISSUE THREAD

**Issue by etriebe** [Sonarr/Sonarr#3629]
**Describe the bug**
1. Series page http://localhost:8989/series/seriesname
2. Select a season you want to clean up
3. Click files and click delete

Result: Nothing happens
Expected: Deleting files

**Screenshots**

**Logs**
How do I provide debug or trace log files?

**System Information**

 - Sonarr Version: 3.0.3.731
 - Operating System: Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: 4.8.03752

**UI Bugs:**
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**

**Comment by markus101** [comment]
Deleting works fine in my testing.

Please use the forums or sub-reddit for support/questions. Information on log files is available on the wiki.

**Comment by etriebe** [comment]
I think I figured out why. From logs I found the following.

```
[v3.0.3.731] System.UnauthorizedAccessException: Access to the path 'D:\TV' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at NzbDrone.Common.Disk.DiskProviderBase.GetDirectories(String path) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 148
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(Series series) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 80
   at NzbDrone.Core.Tv.RefreshSeriesService.RescanSeries(Series series, Boolean isNew, CommandTrigger trigger) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\RefreshSeriesService.cs:line 179

```

I granted full permissions to Local Service to that folder and it started working again.
