### ISSUE TITLE
Jackett doesn't work with Sonarr 3.0.3.737 anymore

### ISSUE THREAD

**Issue by kvn1351** [Sonarr/Sonarr#3640]
**Describe the bug**
When I try to add indexers from Jackett the following error appears:
"Unable to connect to indexer, check the log for more details".

On Radarr, however, the very same indexers **work perfectly**.

**Screenshots**
![image](https://user-images.githubusercontent.com/11823348/77239037-44394a00-6bd6-11ea-91e1-9450ef5f3e40.png)

![image](https://user-images.githubusercontent.com/11823348/77238926-64b4d480-6bd5-11ea-8553-39fba062125e.png)

**Logs**

```
20-3-19 04:32:26.9|Error|Torznab|An error occurred while processing feed. http://nas:9117/api/v2.0/indexers/ilcorsaronero/results/torznab?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100

[v3.0.3.731] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Jackett.Common.IndexerException: Exception (ilcorsaronero): Request to https://ilcorsaronero.pw/browse/4 failed (Error GatewayTimeout) - The tracker seems to be down.
 ---> System.Exception: Request to https://ilcorsaronero.pw/browse/4 failed (Error GatewayTimeout) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.CheckTrackerDown(WebClientStringResult response) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 572
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 442
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1321
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430
  at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000b8] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:42 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\RssParser.cs:55 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00052] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:308 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchReleases (System.Func`2[T,TResult] pageableRequestChainSelector, System.Boolean isRecent) [0x000a8] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:143 

```

**System Information**

 - Sonarr Version: 3.0.3.737
 - Operating System: 3.0.3.737-ls188 by linuxserver.io on OMV 4
 - .net Framework (Windows) or mono (macOS/Linux) Version: 5.20.1.34

[logs.zip](https://github.com/Sonarr/Sonarr/files/4364448/logs.zip)

**Comment by markus101** [comment]
Please use the forums for support.

> [v3.0.3.731] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Jackett.Common.IndexerException: Exception (ilcorsaronero): Request to ilcorsaronero.pw/browse/4 failed (Error GatewayTimeout) - The tracker seems to be down.

Jackett is saying the request to the indexer failed, but these are from 2 days ago?

The other logs show Jackett is returning a 404, so something on Jackett's side.

**Comment by kvn1351** [comment]
> Please use the forums for support.
> 
> > [v3.0.3.731] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Jackett.Common.IndexerException: Exception (ilcorsaronero): Request to ilcorsaronero.pw/browse/4 failed (Error GatewayTimeout) - The tracker seems to be down.
> 
> Jackett is saying the request to the indexer failed, but these are from 2 days ago?
> 
> The other logs show Jackett is returning a 404, so something on Jackett's side.

The timestamps are wrong. I have updated the post showing how it works perfectly on Radarr.

**Comment by kvn1351** [comment]
I'm a moron. I didn't turn on advanced settings. The api path was hidden and thus the resulting url was wrong. 

![image](https://user-images.githubusercontent.com/11823348/77239320-d1ca6900-6bd9-11ea-9199-b7a9d17216f9.png)
