### ISSUE TITLE
Interactive Search: No search results showing if parsing a malformed release title fails

### ISSUE THREAD

**Issue by jwoodhouse** [Sonarr/Sonarr#3851]
**Describe the bug**
When performing an interactive search on certain seasons of certain TV shows, the following error is displayed instead of presenting downloadable episodes:

> Search failed because its object reference not set to an instance of an object.. Try refreshing the series info and verify the necessary information is present before searching again

This can happen on both newly added and old TV shows, uncertain what is linking them at the moment.

Happens with both Anime and Standard types.

Episodes that are unsearchable are still grabbed when they Air.

Automatic Search is able to successfully grab a release and send it to the download client on affected episodes.

**Screenshots**
[https://imgur.com/a/H3PDg5a](https://imgur.com/a/H3PDg5a)

**Logs**
Trace Logs when trying to search for Orphan Black S01E01: https://pastebin.com/angdFeny
Trace Logs when trying to search for Kaguya-sama: Love is War S02E12: https://pastebin.com/JVb0znPR

**System Information**

 - Sonarr Version: [3.0.3.896]
 - Operating System: [Windows Server 2016 (Virtualised)]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [.NET Framework 4.8]

**UI Bugs:**
No UI Bugs

**Additional context**
This is likely to be something introduced somewhat recently, as I was previously able to search for eg. Orphan Black S01E01

Let me know if you need any more information - I will try to cooperate as best as I can.

Thanks.

**Comment by ArsamS** [comment]
Having the same issue as well but I've only noticed it for Season Packs only so far. Individual episodes can be searched for but season packs for some shows such as Atlanta fail

**Comment by WindedDragon** [comment]
Also having the same issue however it's only certain episodes, it's also rejecting releasing because of a similar error. When you hover over why a release was rejected you get this error:
"AnimeVersionUpgradeSpecification: Object reference not set to an instance of an object"

There was also two similar errors preventing the episode from being imported:
"SameFileSpecification: Object reference not set to an instance of an object"
"UpgradeSpecification: Object reference not set to an instance of an object"

I'm running Sonarr in a docker container, not sure if that's somehow part of the issue.

**Comment by Taloth** [comment]
@jwoodhouse 

`Orphan.Black.1x01.Selezione.Naturale.ITA.720p.BDMux.x264-NovaRip [01/54] - "orphan.black.1x01.ita.720p.bdmux.x264-novarip.nfo"`

That's not a release title, it's an usenet article name. Check which indexer it comes from and report it to them.
I suspect the other error is because of that release. I'll look into guarding against it in a future version, but you should deal with a bad indexer like that.

at everybody else... "me too" does not contribute, investigate and provide logs.

**Comment by jwoodhouse** [comment]
@Taloth Thanks for the heads up, I'll have a dig around nzbhydra to see where that release is coming from.

Happy to have this closed off if you're fairly confident thats the issue.

Thanks.

**Comment by jwoodhouse** [comment]
Just for clarity, I'd like to confirm that the above is accurate,
After temporarily disabling the indexer where that specific release is coming from, the Interactive search is working as intended.

**Comment by Taloth** [comment]
Thanks for confirming. Leave it open, I've renamed it.
We should be able to detect the problem and at least show the other releases.

_The below information is just from the pastebin so it doesn't get lost._

```
20-7-3 19:55:50.9|Error|Parser|An error has occurred while trying to parse Orphan.Black.1x01.Selezione.Naturale.ITA.720p.BDMux.x264-NovaRip [01/54] - "orphan.black.1x01.ita.720p.bdmux.x264-novarip.nfo"
 
[v3.0.3.896] System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
   at NzbDrone.Core.Parser.QualityParser.ParseQualityName(String name) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Parser\QualityParser.cs:line 344
   at NzbDrone.Core.Parser.QualityParser.ParseQuality(String name) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Parser\QualityParser.cs:line 68
   at NzbDrone.Core.Parser.Parser.ParseTitle(String title) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Parser\Parser.cs:line 507
```

leads to:

```
[v3.0.3.896] System.NullReferenceException: Object reference not set to an instance of an object.
   at Sonarr.Api.V3.Indexers.ReleaseResourceMapper.ToResource(DownloadDecision model) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseResource.cs:line 84
   at Sonarr.Api.V3.Indexers.ReleaseModuleBase.MapDecision(DownloadDecision decision, Int32 initialWeight) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModuleBase.cs:line 25
   at Sonarr.Api.V3.Indexers.ReleaseModule.MapDecision(DownloadDecision decision, Int32 initialWeight) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:line 201
   at Sonarr.Api.V3.Indexers.ReleaseModuleBase.MapDecisions(IEnumerable`1 decisions) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModuleBase.cs:line 13
   at Sonarr.Api.V3.Indexers.ReleaseModule.GetEpisodeReleases(Int32 episodeId) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:line 157
```

and bubbles out to the UI
