### ISSUE TITLE
Sudden issues connecting to Deluge client (Windows 10)

### ISSUE THREAD

**Issue by AthieN** [Sonarr/Sonarr#4015]
**Describe the bug**
Everything was working last night. No updates or software has been installed and this just popped up out of the blue. Suddenly this morning, Sonarr is unable to connect to Deluge (v1.3.15) and is spitting out the error in the logs section below. Any idea what to do to fix it?

This is also occurring in Radarr v3 so I'm guessing it is a system issue and not an application issue? Sorry if that's the case! I'm just not sure what is causing it. :(

**Logs**

[v3.0.4.982] Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'NzbDrone.Common.Http.JsonRpcResponse`1[System.String]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Serializer\Json.cs:line 43
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ExecuteRequest[TResult](JsonRpcRequestBuilder requestBuilder, String method, Object[] arguments) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 245
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult](DelugeSettings settings, String method, Object[] arguments) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 212
   at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.GetVersion(DelugeSettings settings) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 53
   at NzbDrone.Core.Download.Clients.Deluge.Deluge.TestConnection() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:line 228

20-10-13 09:34:35.0|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Unknown exception: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'NzbDrone.Common.Http.JsonRpcResponse`1[System.String]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
20-10-13 09:34:35.0|Debug|Api|[POST] /api/v3/downloadclient/test: 400.BadRequest (23 ms)
20-10-13 09:34:40.5|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
20-10-13 09:34:40.5|Debug|Api|[GET] /api/v3/system/status: 200.OK (2 ms)
20-10-13 09:34:40.6|Debug|Api|[GET] /api/v3/diskspace: 200.OK (45 ms)
20-10-13 09:34:42.0|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)

**System Information**

 - Sonarr Version: v3.0.4.982
 - Operating System: Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: 4.5

**Comment by AthieN** [comment]
I may have opened this too soon. It seems that a reinstall of Deluge may have done the trick and the tests are passing now. Apologies for wasting your time! I'll close this and reopen it if problems return.
Thanks!

**Comment by AthieN** [comment]
Oddly, 10 minutes after closing this, the issue started again. So I an reopening. Any suggestions?

**Comment by markus101** [comment]
Deluge is returning invalid JSON, look at the trace logs for the response, but sudden changes to the JSON sounds like something in Deluge is broken.
