### ISSUE TITLE
Security misconfiguration in download clients throw vague UI errors

### ISSUE THREAD

**Issue by flying-sausages** [Sonarr/Sonarr#4021]
**Describe the bug**
Default v3 -arr behaviour is to do strict checking against local addresses. Whether or not that's a valid choice is a different debate ;) Whenever a user attempts to configure a cleitnwith a self-signed cert, the error on the download client adding interface simply says `bad request` and that's it. There should be an indfication of what went wrong with a link to explanation / solution there maybe.

**To Reproduce**
1. set up rutorrent with a self-signed certificate
2. forward all http traffic to https
3. try set up rutorrent in -arr using `localhost` or `127.0.0.1`
4. Get an error with "bad request"

**Expected behavior**
~~Successful connection, because why would you do strict checking on local addresses to begin with if you cannot get those certs, just change th4e default to not do strict localhost checking /s~~
An appropriate error in the indexer window which would point at the certificate not complying with current security settings, and possibly a link to that -arr settings section.

**Screenshots**
![image](https://user-images.githubusercontent.com/23618693/96386583-4da28900-119c-11eb-89ac-cb650056ce05.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Mono Version: [e.g. Mono 5.8] version agnostic
 - Browser and Version [e.g. chrome, safari] Firefox 81.0.2
 - Radarr version: 3.0.0.3954

**Debug Logs**

```
Oct 19 00:01:59 primary mono[29688]: [Error] X509CertificateValidationService: Certificate validation for https://localhost//rutorrent/plugins/httprpc/action.php failed. RemoteCertificateChainErrors
Oct 19 00:01:59 primary mono[29688]: [Error] RTorrent: Failed to test rTorrent
Oct 19 00:01:59 primary mono[29688]: [v3.0.4.982] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to rTorrent, please check your settings ---> System.Net.WebException: Error: TrustFailure (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
Oct 19 00:01:59 primary mono[29688]:   at /build/mono-L7Ktbc/mono-6.8.0.105+dfsg/external/boringssl/ssl/handshake_client.c:1132
Oct 19 00:01:59 primary mono[29688]:   at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00064] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x00106] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
Oct 19 00:01:59 primary mono[29688]:   at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x0012a] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:    --- End of inner exception stack trace ---
Oct 19 00:01:59 primary mono[29688]:   at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x00346] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at Mono.Net.Security.MonoTlsStream.CreateStream (System.Net.WebConnectionTunnel tunnel, System.Threading.CancellationToken cancellationToken) [0x001f4] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x001f5] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:    --- End of inner exception stack trace ---
Oct 19 00:01:59 primary mono[29688]:   at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x00275] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x0015b] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at System.Net.WebOperation.Run () [0x000b7] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x000b1] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at System.Net.HttpWebRequest.GetRequestStream () [0x00019] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke (System.Object clientObj, System.Reflection.MethodInfo mi, System.Object[] parameters) [0x00077] in <a205b9da6b014c438c362c4bd859d7bc>:0
Oct 19 00:01:59 primary mono[29688]:   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke (System.Reflection.MethodInfo mi, System.Object[] Parameters) [0x00000] in <a205b9da6b014c438c362c4bd859d7bc>:0
Oct 19 00:01:59 primary mono[29688]:   at XmlRpcProxy88777c14-6b1e-4dae-a01c-b01352d7d912.GetVersion () [0x00011] in <efffab5f86fe42d29400a7d59a253a48>:0
Oct 19 00:01:59 primary mono[29688]:   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy+<>c__DisplayClass2_0.<GetVersion>b__0 () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:69
Oct 19 00:01:59 primary mono[29688]:   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.ExecuteRequest[T] (System.Func`1[TResult] task) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:261
Oct 19 00:01:59 primary mono[29688]:    --- End of inner exception stack trace ---
Oct 19 00:01:59 primary mono[29688]:   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.ExecuteRequest[T] (System.Func`1[TResult] task) [0x00017] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:269
Oct 19 00:01:59 primary mono[29688]:   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.GetVersion (NzbDrone.Core.Download.Clients.RTorrent.RTorrentSettings settings) [0x00023] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:69
Oct 19 00:01:59 primary mono[29688]:   at NzbDrone.Core.Download.Clients.RTorrent.RTorrent.TestConnection () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrent.cs:193
Oct 19 00:01:59 primary mono[29688]: [Warn] SonarrErrorPipeline: Invalid request Validation failed:
Oct 19 00:01:59 primary mono[29688]:  -- : Unknown exception: Unable to connect to rTorrent, please check your settings
```

**Comment by markus101** [comment]
Please post the relevant debug logs.

**Comment by flying-sausages** [comment]
sorry for the delay had to fetch them out and you saw this earlier than i thought ha

```Oct 19 00:01:59 primary mono[29688]: [Error] X509CertificateValidationService: Certificate validation for https://localhost//rutorrent/plugins/httprpc/action.php failed. RemoteCertificateChainErrors
Oct 19 00:01:59 primary mono[29688]: [Error] RTorrent: Failed to test rTorrent
Oct 19 00:01:59 primary mono[29688]: [v3.0.4.982] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to rTorrent, please check your settings ---> System.Net.WebException: Error: TrustFailure (Authentication failed, se>
Oct 19 00:01:59 primary mono[29688]:   at /build/mono-L7Ktbc/mono-6.8.0.105+dfsg/external/boringssl/ssl/handshake_client.c:1132
Oct 19 00:01:59 primary mono[29688]:   at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00064] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x00106] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
Oct 19 00:01:59 primary mono[29688]:   at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x0012a] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:    --- End of inner exception stack trace ---
Oct 19 00:01:59 primary mono[29688]:   at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken)>
Oct 19 00:01:59 primary mono[29688]:   at Mono.Net.Security.MonoTlsStream.CreateStream (System.Net.WebConnectionTunnel tunnel, System.Threading.CancellationToken cancellationToken) [0x001f4] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x001f5] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:    --- End of inner exception stack trace ---
Oct 19 00:01:59 primary mono[29688]:   at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x00275] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x0015b] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at System.Net.WebOperation.Run () [0x000b7] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at System.Net.WebCompletionSource`1[T].WaitForCompletion () [0x000b1] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at System.Net.HttpWebRequest.GetRequestStream () [0x00019] in <a85c1a570f9a4f9f9c3d2cfa5504e34f>:0
Oct 19 00:01:59 primary mono[29688]:   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke (System.Object clientObj, System.Reflection.MethodInfo mi, System.Object[] parameters) [0x00077] in <a205b9da6b014c438c362c4bd859d7bc>:0
Oct 19 00:01:59 primary mono[29688]:   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke (System.Reflection.MethodInfo mi, System.Object[] Parameters) [0x00000] in <a205b9da6b014c438c362c4bd859d7bc>:0
Oct 19 00:01:59 primary mono[29688]:   at XmlRpcProxy88777c14-6b1e-4dae-a01c-b01352d7d912.GetVersion () [0x00011] in <efffab5f86fe42d29400a7d59a253a48>:0
Oct 19 00:01:59 primary mono[29688]:   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy+<>c__DisplayClass2_0.<GetVersion>b__0 () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:69
Oct 19 00:01:59 primary mono[29688]:   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.ExecuteRequest[T] (System.Func`1[TResult] task) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.>
Oct 19 00:01:59 primary mono[29688]:    --- End of inner exception stack trace ---
Oct 19 00:01:59 primary mono[29688]:   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.ExecuteRequest[T] (System.Func`1[TResult] task) [0x00017] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.>
Oct 19 00:01:59 primary mono[29688]:   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.GetVersion (NzbDrone.Core.Download.Clients.RTorrent.RTorrentSettings settings) [0x00023] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\>
Oct 19 00:01:59 primary mono[29688]:   at NzbDrone.Core.Download.Clients.RTorrent.RTorrent.TestConnection () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrent.cs:193
Oct 19 00:01:59 primary mono[29688]: [Warn] SonarrErrorPipeline: Invalid request Validation failed:
Oct 19 00:01:59 primary mono[29688]:  -- : Unknown exception: Unable to connect to rTorrent, please check your settings
```

**Comment by flying-sausages** [comment]
Radarr logs where issue is present too

```
Oct 18 21:29:13 primary Radarr[26750]: [Error] X509CertificateValidationService: Certificate validation for https://127.0.0.1//rutorrent/plugins/httprpc/action.php failed. RemoteCertificateNameMismatch
Oct 18 21:29:13 primary Radarr[26750]: [Error] RTorrent: Failed to test rTorrent
Oct 18 21:29:13 primary Radarr[26750]: [v3.0.0.3954] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to rTorrent, please check your settings
Oct 18 21:29:13 primary Radarr[26750]:  ---> System.Net.WebException: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.
Oct 18 21:29:13 primary Radarr[26750]:  ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
Oct 18 21:29:13 primary Radarr[26750]:  ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
Oct 18 21:29:13 primary Radarr[26750]:    --- End of inner exception stack trace ---
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.HttpWebRequest.SendRequest()
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.HttpWebRequest.GetResponse()
Oct 18 21:29:13 primary Radarr[26750]:    --- End of inner exception stack trace ---
Oct 18 21:29:13 primary Radarr[26750]:    at System.Net.HttpWebRequest.GetResponse()
Oct 18 21:29:13 primary Radarr[26750]:    at CookComputing.XmlRpc.XmlRpcClientProtocol.GetWebResponse(WebRequest request)
Oct 18 21:29:13 primary Radarr[26750]:    at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(Object clientObj, MethodInfo mi, Object[] parameters)
Oct 18 21:29:13 primary Radarr[26750]:    at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(MethodInfo mi, Object[] parameters)
Oct 18 21:29:13 primary Radarr[26750]:    at XmlRpcProxy546416c3-c953-4410-8591-69a5a8b55b53.GetVersion()
Oct 18 21:29:13 primary Radarr[26750]:    at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.<>c__DisplayClass2_0.<GetVersion>b__0() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 67
Oct 18 21:29:13 primary Radarr[26750]:    at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.ExecuteRequest[T](Func`1 task) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 262
Oct 18 21:29:13 primary Radarr[26750]:    --- End of inner exception stack trace ---
Oct 18 21:29:13 primary Radarr[26750]:    at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.ExecuteRequest[T](Func`1 task) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 270
Oct 18 21:29:13 primary Radarr[26750]:    at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.GetVersion(RTorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 67
Oct 18 21:29:13 primary Radarr[26750]:    at NzbDrone.Core.Download.Clients.RTorrent.RTorrent.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrent.cs:line 203
Oct 18 21:29:13 primary Radarr[26750]: [Warn] RadarrErrorPipeline: Invalid request Validation failed:
Oct 18 21:29:13 primary Radarr[26750]:  -- : Unknown exception: Unable to connect to rTorrent, please check your settings
```

**Comment by markus101** [comment]
Thanks for the logs, next time please upload and link to the log files.
