### ISSUE TITLE
Unable to connect to indexer: Torznab error detected

### ISSUE THREAD

**Issue by Huza91** [Sonarr/Sonarr#4062]
Hi All,

Currently receiving this error on 4 of my indexers - They were working fine last week however I noticed these errors started occurring this week. I've ensured that I have the latest version of Sonarr and Jackett.

"Unable to connect to indexer: Torznab error detected: kickasstorrent-kathow does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported."

**Logs**
NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: kickasstorrent-kathow does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported.
   at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess(IndexerResponse indexerResponse) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:line 42
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 308
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 334
Sonarr Ver. 2.0.0.5344

**System Information**

 - Sonarr Version: 2.0.0.5344
 - Operating System: Windows 10
 - .net Framework - 4.8.04084

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

You should be able to just reselect your categories on the indexers.  IIRC a recent jacket update caused this.
