### ISSUE TITLE
Cannot Update since Version 3.0.3.971

### ISSUE THREAD

**Issue by lexguy2007** [Sonarr/Sonarr#4141]
**Describe the bug**
Since the update to Version 3.0.3.971 I've noticed I am no longer getting updates. Upon checking for updates manually I see that Version 3.0.4.1023 is released. I have tried numerous times to manually update and each time I get "FAILED".

**Logs**
Checking in EVENTS I see the following:
Error occurred while executing task ApplicationUpdate: The system cannot find the file specified

System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 181
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 149
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 261
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 96
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41

**System Information**

 - Sonarr Version: 3.0.3.971
 - Operating System: Windows 10

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](http://webchat.freenode.net/?channels=#sonarr)for support/questions.

https://forums.sonarr.tv/t/issues-after-updating-to-3-0-3-971/26700
