### ISSUE TITLE
Invalid Recycling Bin path causing "The network path was not found" for imports

### ISSUE THREAD

**Issue by Subrosians** [Sonarr/Sonarr#4163]
If you have an invalid Recycling Bin path (Settings : Media Management : Recycling Bin), the error in the logs will seem like you are having a path issue (Remote Path Mappings) with the new file instead of a path issue with Recycling Bin. 

In my example: 
Recycling Bin = \\Shinku\downloads\Trash\ (Path doesn't exist anymore)
Remote Path Mapping = \\Tsugumi\Downloads\Sync\sonarr\

--- About ---
Version
3.0.4.1026
.net Version
4.8.0
AppData directory
C:\ProgramData\Sonarr
Startup directory
C:\ProgramData\Sonarr\bin

---Error---
Couldn't import episode \\Tsugumi\Downloads\Sync\sonarr\NCIS.New.Orleans.S07E04.We.All.Fall.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv: The network path was not found.

System.IO.IOException: The network path was not found.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at NzbDrone.Common.Disk.DiskProviderBase.CreateFolder(String path) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 190
   at NzbDrone.Core.MediaFiles.RecycleBinProvider.DeleteFile(String path, String subfolder) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RecycleBinProvider.cs:line 96
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 64
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 111

**Comment by RobinDadswell** [comment]
Can you please reproduce and put the trace logs into Pastebin please.
