### ISSUE TITLE
Webhook issue Synology chat

### ISSUE THREAD

**Issue by the-kaiwiin** [Sonarr/Sonarr#4585]
**Expected behavior**
Webhook try with synology chat, says that test is okay, but nothing arrives. 

**Platform Information (please complete the following information):**
 - OS: Windows Server 2019
 - Docker:  No
 - .net Framework (Windows) 4.7.2
 - Browser and Version (Only needed for UI issues): Chrome 
 - Sonarr Version: 3.0.6.1265
 - Sonarr Branch: main

**Trace Logs**
2021-07-18 17:00:46.3|Fatal|SonarrErrorPipeline|Request Failed. POST /api/v3/notification/test

[v3.0.6.1265] System.Net.WebException: Failed to read complete http response ---> System.IO.IOException: Unable to read data from the transport connection: The connection was closed.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at NzbDrone.Common.Extensions.StreamExtensions.ToBytes(Stream input) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Extensions\StreamExtensions.cs:line 13
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 132
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 150
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:line 126
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Core.Notifications.Webhook.WebhookProxy.SendWebhook(WebhookPayload body, WebhookSettings settings) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Notifications\Webhook\WebhookProxy.cs:line 37
   at NzbDrone.Core.Notifications.Webhook.Webhook.SendWebhookTest() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Notifications\Webhook\Webhook.cs:line 157
   at NzbDrone.Core.Notifications.Webhook.Webhook.Test() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Notifications\Webhook\Webhook.cs:line 127
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.Test(TProviderDefinition definition) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 81
   at Sonarr.Api.V3.ProviderModuleBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\ProviderModuleBase.cs:line 191
   at Sonarr.Api.V3.ProviderModuleBase`3.Test(TProviderResource providerResource) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\ProviderModuleBase.cs:line 144
   at Sonarr.Api.V3.ProviderModuleBase`3.<.ctor>b__2_1(Object x) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\ProviderModuleBase.cs:line 29
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRouteInvoker.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRequestDispatcher.<Dispatch>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.NancyEngine.<InvokeRequestLifeCycle>d__22.MoveNext()

**Comment by bakerboy448** [comment]
Please read the wiki link for how to provide logs that was in the template.  A single line of error spew is not helpful and sharing said spew directly in the post is difficult to read.

https://wiki.servarr.com/sonarr/troubleshooting#logging-and-log-files

**Comment by markus101** [comment]
Webhooks are in a specific format, you can’t use them to send to Synology chat because it expects things in a completely different unsupported format. You’ll need to build your own bridge between Sonarr’s webhooks and synology chat.

**Comment by the-kaiwiin** [comment]
@markus101 Thanks for your feedback ! 
Have a nice day
