### ISSUE TITLE
Error when launching Sonarr - "Specified cast is not Valid"

### ISSUE THREAD

**Issue by AbstractUmbra** [Sonarr/Sonarr#4678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On launch of the app, a dialog window appears with the following message: 
![Sonarr_2021-10-04_01-51-12](https://user-images.githubusercontent.com/16031716/135779568-72ea19a2-3cdc-49dc-ad34-fc656a292e82.png)

It then crashes, no app tray icon either.
 

### Expected Behavior

The app to launch and run as normal.

### Steps To Reproduce

1. Launch the app.

### Environment

```markdown
- OS: Windows 10 (10.0.19042 Build 19042)
- Sonarr: (Cannot launch the app to check, should be latest stable 3.x)
- Docker Install: No
- Using Reverse Proxy: Yes but N/A here.
- Browser: Chrome/Firefox but N/A here.
```

### What branch are you running?

Main

### Error logs

```
2021-10-04 01:51:10.3|Info|Bootstrap|Starting Sonarr - C:\ProgramData\Sonarr\bin\Sonarr.exe - Version 3.0.6.1347
2021-10-04 01:51:10.6|Info|Router|Application mode: Interactive
2021-10-04 01:51:10.7|Info|MigrationLogger|*** Checking database for required migrations data source=C:\ProgramData\Sonarr\sonarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2021-10-04 01:51:10.8|Info|MigrationLogger|*** 162: release_profile_to_array migrating ***
2021-10-04 01:51:10.8|Info|release_profile_to_array|Starting migration of Main DB to 162
2021-10-04 01:51:10.8|Error|MigrationLogger|System.InvalidCastException: Specified cast is not valid.
   at System.Data.SQLite.SQLiteDataReader.VerifyType(Int32 i, DbType typ)
   at System.Data.SQLite.SQLiteDataReader.GetString(Int32 i)
   at NzbDrone.Core.Datastore.Migration.release_profile_to_array.ChangeRequiredIgnoredTypes(IDbConnection conn, IDbTransaction tran) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\Migration\162_release_profile_to_array.cs:line 31
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(PerformDBOperationExpression expression)
   at FluentMigrator.Builders.Execute.PerformDBOperationExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass72_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)

[v3.0.6.1347] System.InvalidCastException: Specified cast is not valid.
   at System.Data.SQLite.SQLiteDataReader.VerifyType(Int32 i, DbType typ)
   at System.Data.SQLite.SQLiteDataReader.GetString(Int32 i)
   at NzbDrone.Core.Datastore.Migration.release_profile_to_array.ChangeRequiredIgnoredTypes(IDbConnection conn, IDbTransaction tran) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\Migration\162_release_profile_to_array.cs:line 31
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(PerformDBOperationExpression expression)
   at FluentMigrator.Builders.Execute.PerformDBOperationExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass72_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)

2021-10-04 01:51:10.9|Fatal|WindowsApp|EPIC FAIL

[v3.0.6.1347] System.InvalidCastException: Specified cast is not valid.
   at System.Data.SQLite.SQLiteDataReader.VerifyType(Int32 i, DbType typ)
   at System.Data.SQLite.SQLiteDataReader.GetString(Int32 i)
   at NzbDrone.Core.Datastore.Migration.release_profile_to_array.ChangeRequiredIgnoredTypes(IDbConnection conn, IDbTransaction tran) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\Migration\162_release_profile_to_array.cs:line 31
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(PerformDBOperationExpression expression)
   at FluentMigrator.Builders.Execute.PerformDBOperationExpression.ExecuteWith(IMigrationProcessor processor)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass72_0.<ExecuteExpressions>b__1()
   at FluentMigrator.Runner.StopWatch.Time(Action action)
   at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
   at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\Migration\Framework\MigrationController.cs:line 51
   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\DbFactory.cs:line 117
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\DbFactory.cs:line 82
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationType migrationType) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\DbFactory.cs:line 70
   at NzbDrone.Core.Datastore.DbFactory.RegisterDatabase(IContainer container) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\DbFactory.cs:line 48
   at NzbDrone.Host.NzbDroneServiceFactory.Start() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Host\ApplicationServer.cs:line 60
   at NzbDrone.Host.Router.Route(ApplicationModes applicationModes) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Host\Router.cs:line 56
   at NzbDrone.Host.Bootstrap.Start(ApplicationModes applicationModes, StartupContext startupContext) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Host\Bootstrap.cs:line 78
   at NzbDrone.Host.Bootstrap.Start(StartupContext startupContext, IUserAlert userAlert, Action`1 startCallback) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Host\Bootstrap.cs:line 41
   at NzbDrone.WindowsApp.Main(String[] args) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone\WindowsApp.cs:line 23
```

**Comment by bakerboy448** [comment]
Update; just fixed https://github.com/Sonarr/Sonarr/commit/deed85d2f9147e6180014507ef4f5af3695b0c61

**Comment by krystiancharubin** [comment]
Hey, this fix had the unintended effect of overwriting all the must not contain terms with must contain terms due to a typo in the code.

**Comment by bakerboy448** [comment]
Indeed it did 
![B2F5E7B8-7C5A-4506-842D-211175034479](https://user-images.githubusercontent.com/55419169/135857716-bb544d5f-4d69-44cd-91c1-5cfdf17dc74f.jpeg)

line 39 has a typo
https://github.com/Sonarr/Sonarr/commit/deed85d2f9147e6180014507ef4f5af3695b0c61#diff-d93147d971ed72a945d625cd7c30e3cd92effb2b338872ccf78cf2be8351edfdR39

**Comment by markus101** [comment]
Well, shit. Sorry folks, pushed a fix, to resolve once available you’ll probably want to restore your previous DB and let Sonarr migrate it properly. Or alternative manually restore the values.
