### ISSUE TITLE
Unable to connect to indexer (YGG)

### ISSUE THREAD

**Issue by mushuthecat** [Sonarr/Sonarr#4739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since Yesterday im not able to connect properly to my jackett indexer YGG ( It works using radarr with the same jackett and indexer configuration)

### Expected Behavior

Connect to YGG indexer using jackett

### Environment

```markdown
- OS: DEBIAN RASPBERRY
- Sonarr: 3.0.6.1342
- Docker Install: YES
- Using Reverse Proxy: NO
- Browser: Firefox
```

### What branch are you running?

Main

### Anything else?

```

[v3.0.6.1342] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Jackett.Common.IndexerException: Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.nz/ using form selector #user-login
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www3.yggtorrent.nz/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 573
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1474
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 782
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1623
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 759
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/(removed)/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 397
  at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000b8] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:42 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\RssParser.cs:55 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00052] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:308 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00044] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:343 
```

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.

Jackett is not logged in to YGG. This is not a Sonarr issue at all.

**Comment by mushuthecat** [comment]
> 
> 
> Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.
> 
> Jackett is not logged in to YGG. This is not a Sonarr issue at all.
> 
> also just the error spew is almost helpful and certainly are not trace logs
 

I understand but how do you explain that my radarr work perfectly with the same indexer configuration ?

Regards
