### ISSUE TITLE
Sonarr doesn't like the bracket after the title and in front of the season when grabbing releases, causing errors

### ISSUE THREAD

**Issue by Dare2Code** [Sonarr/Sonarr#4771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So am trying to manually grab an anime title from a release with titles like

```
So I'm a Spider, So What? | Kumo Desu ga, Nani ka? [Season 1 + EXTRA] [BD 1080p x265 HEVC OPUS] [Dual-Audio]
[Cleo] Kumo Desu ga, Nani ka? | So I'm a Spider, So What? [Dual Audio 10bit 1080p][HEVC-x265]
[Judas] Kumo Desu ga Nanika (So I'm a Spider, So What?) (Season 1) [1080p][HEVC x265 10bit][Multi-Subs] (Batch)
```

it errors out and when I hover over the red cloud it says "Value cannot be null. Parameter name: input" 

### Expected Behavior

Grab the release as requested by user

### Steps To Reproduce

1. In Sonarr 3.0.6.1342 first request anime "So I'm a Spider, So What?"
2. Now with Index Nyaa (in my instance) we will see above mentioned release titles and App will not grab these releases.

### Environment

```markdown
- OS: Windows 10 Education Version:(21H1) Build: (19043.1348)
- Sonarr: 3.0.6.1342
- Docker Install: NO
- Using Reverse Proxy: NO
- Browser: Google Chrome Version 96.0.4664.45 (Official Build) (64-bit)
```

### What branch are you running?

Main

### Trace Logs?

```
2021-11-30 20:45:30.6|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthModule
2021-11-30 20:45:30.6|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthModule
2021-11-30 20:45:30.6|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthModule
2021-11-30 20:45:30.6|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2021-11-30 20:45:30.6|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2021-11-30 20:45:30.6|Trace|Http|Req: 2437 [GET] /api/v3/health (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36)
2021-11-30 20:45:30.6|Trace|Http|Res: 2437 [GET] /api/v3/health: 200.OK (1 ms)
2021-11-30 20:45:30.6|Debug|Api|[GET] /api/v3/health: 200.OK (1 ms)
2021-11-30 20:45:30.6|Trace|Http|Req: 2438 [GET] /api/v3/health (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36)
2021-11-30 20:45:30.6|Trace|Http|Res: 2438 [GET] /api/v3/health: 200.OK (0 ms)
2021-11-30 20:45:30.6|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2021-11-30 20:45:34.4|Trace|Http|Req: 2439 [POST] /api/v3/release (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36)
2021-11-30 20:45:34.4|Trace|SonarrErrorPipeline|Handling Exception
2021-11-30 20:45:34.4|Fatal|SonarrErrorPipeline|Request Failed. POST /api/v3/release
 
[v3.0.6.1342] System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at NzbDrone.Core.Parser.Parser.CleanSeriesTitle(String title) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Parser\Parser.cs:line 650
   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingService.FindMappings(String seriesTitle, String releaseTitle) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\DataAugmentation\Scene\SceneMappingService.cs:line 185
   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingService.FindSceneMapping(String seriesTitle, String releaseTitle, Int32 sceneSeasonNumber) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\DataAugmentation\Scene\SceneMappingService.cs:line 95
   at NzbDrone.Core.Parser.ParsingService.Map(ParsedEpisodeInfo parsedEpisodeInfo, Int32 tvdbId, Int32 tvRageId, Series series, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Parser\ParsingService.cs:line 140
   at NzbDrone.Core.Parser.ParsingService.GetEpisodes(ParsedEpisodeInfo parsedEpisodeInfo, Series series, Boolean sceneSource, SearchCriteriaBase searchCriteria) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Parser\ParsingService.cs:line 198
   at Sonarr.Api.V3.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:line 95
   at Sonarr.Api.V3.Indexers.ReleaseModule.<.ctor>b__10_2(Object x) in M:\BuildAgent\work\63739567f01dbcc2\src\Sonarr.Api.V3\Indexers\ReleaseModule.cs:line 65
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRouteInvoker.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRequestDispatcher.<Dispatch>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.NancyEngine.<InvokeRequestLifeCycle>d__22.MoveNext()
 
2021-11-30 20:45:34.4|Trace|Http|Res: 2439 [POST] /api/v3/release: 500.InternalServerError (10 ms)
2021-11-30 20:45:34.4|Debug|Api|[POST] /api/v3/release: 500.InternalServerError (10 ms)
2021-11-30 20:45:41.4|Trace|Http|Req: 2440 [PUT] /api/v3/config/host (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36)
2021-11-30 20:45:41.4|Trace|EventAggregator|Publishing ConfigFileSavedEvent
```
### Anything else?

had a chat in Discord Support channel on **2021-11-30 9:20 PM EST** and we concluded to throw it into bug reports.

**Comment by markus101** [comment]
`[Cleo] Kumo Desu ga, Nani ka? | So I'm a Spider, So What? [Dual Audio 10bit 1080p][HEVC-x265]` is never going to be parsable, it lacks season and episode information; Sonarr does not support releases.
