### ISSUE TITLE
Sonarr 3.0 import issue

### ISSUE THREAD

**Issue by SmoothAdmin** [Sonarr/Sonarr#4880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After migrating to 3.0 from 2.0 Sonarr has downloaded new content and is trying to import it into the same folder it downloaded it to instead of the folder which the TV shows resides in; I have checked the TV show itself and it shows up as the correct drive/folder.

Couldn't import episode C:\Torrents\Alaskan.Killer.Bigfoot.S01E08.Nantinaqs.Exorcism.1080p.HEVC.x265-MeGusta\Alaskan.Killer.Bigfoot.S01E08.Nantinaqs.Exorcism.1080p.HEVC.x265-MeGusta.mkv: Access to the path 'C:\Torrents\Alaskan.Killer.Bigfoot.S01E08.Nantinaqs.Exorcism.1080p.HEVC.x265-MeGusta\Alaskan.Killer.Bigfoot.S01E08.Nantinaqs.Exorcism.1080p.HEVC.x265-MeGusta.mkv' is denied.

System.UnauthorizedAccessException: Access to the path 'C:\Torrents\Alaskan.Killer.Bigfoot.S01E08.Nantinaqs.Exorcism.1080p.HEVC.x265-MeGusta\Alaskan.Killer.Bigfoot.S01E08.Nantinaqs.Exorcism.1080p.HEVC.x265-MeGusta.mkv' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.SetAttributes(String path, FileAttributes fileAttributes)
   at NzbDrone.Common.Disk.DiskProviderBase.RemoveReadOnly(String path) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 366
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 254
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 487
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 367
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile(EpisodeFile episodeFile, Series series, List`1 episodes, String destinationFilePath, TransferMode mode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 116
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.MoveEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 77
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 77
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 109

-- In this case the default download folder for this TV show is D:\Plex\tvshows\Alaskan Killer Bigfoot when I view the settings on the TV Show under series.  This working in 2.0 perfectly, its only switching to 3.0 that its broken.

### Expected Behavior

see above

### Environment

```markdown
- OS: Windows 2019 Server SE
- Sonarr: 3.0.6.1342
- Docker Install: none
- Using Reverse Proxy: none
- Browser: MS Edge
```

### What branch are you running?

Main

### Trace Logs?

none

### Anything else?

nope

**Comment by bakerboy448** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr)for support/questions.
