### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException: Error converting value "com.plexapp.agents.thetvdb:

### ISSUE THREAD

**Issue by austinwbest** [Sonarr/Sonarr#4914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trace log is full of this

```
2022-02-23 08:47:40.0|Trace|PreferredWordService|Determined preferred word matches for 'DuckTales_S02E10_Money to Burn'. Count 0
2022-02-23 08:47:40.0|Debug|EpisodeFileMovingService|Moving episode file: D:\Disney+\DuckTales\S02\DuckTales_S02E10_Money to Burn.mkv to D:\Plex\TV Shows\DuckTales\Season 2\DuckTales - S02E10 - Super Ducktales (5) - Money to Burn WEBDL-480p.mkv
2022-02-23 08:47:40.0|Warn|NotificationService|Unable to process notification queue for Plex Updater

[v3.0.6.1470] Newtonsoft.Json.JsonSerializationException: Error converting value "com.plexapp.agents.thetvdb://75931?lang=en" to type 'System.Collections.Generic.List`1[NzbDrone.Core.Notifications.Plex.Server.PlexSectionItemGuid]'. Path 'MediaContainer.Metadata[0].guid', line 1, position 564. ---> System.ArgumentException: Could not cast or convert from System.String to System.Collections.Generic.List`1[NzbDrone.Core.Notifications.Plex.Server.PlexSectionItemGuid].
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Serializer\Json.cs:line 43
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerProxy.GetMetadataId(Int32 sectionId, Int32 tvdbId, String language, PlexServerSettings settings) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerProxy.cs:line 138
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerService.GetMetadataId(Int32 sectionId, Series series, String language, PlexServerSettings settings) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerService.cs:line 179
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerService.UpdatePartialSection(Series series, List`1 sections, PlexServerSettings settings) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerService.cs:line 159
   at NzbDrone.Core.Notifications.Plex.Server.PlexServerService.UpdateLibrary(IEnumerable`1 multipleSeries, PlexServerSettings settings) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Notifications\Plex\Server\PlexServerService.cs:line 87
   at NzbDrone.Core.Notifications.Plex.Server.PlexServer.ProcessQueue() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Notifications\Plex\Server\PlexServer.cs:line 125
   at NzbDrone.Core.Notifications.NotificationService.ProcessQueue() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Notifications\NotificationService.cs:line 318

2022-02-23 08:47:40.1|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
```

### Expected Behavior

Properly handle the plex api response

### Steps To Reproduce

I guess enable the plex scanner with using the tvdb agent in plex?

### Environment

```markdown
- OS: Windows
- Sonarr: 3.0.6.1470
- Docker Install: No
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Develop

### Trace Logs?

Posted above.

### Anything else?

Nope.

**Comment by markus101** [comment]
> I guess enable the plex scanner with using the tvdb agent in plex?

What are the exact settings for the affected library on your Plex server?
Which version of PMS?

I've been unable to reproduce with:
![image](https://user-images.githubusercontent.com/413544/155636363-b0f141b0-b390-4068-92d8-e016a33f68e6.png)

**Comment by austinwbest** [comment]
Version 1.25.2.5319

![image](https://user-images.githubusercontent.com/8321115/155650382-ff032a72-44c0-4b50-89de-4f953a23b85f.png)

My guess is it is related to guid (str) and Guid (list) which i have never used the plex agent and have not updated my entire library so it doesnt have Guid available and is assuming guid is Guid.

**Comment by Shawneau** [comment]
Experiencing similar issue, same set up

**Comment by thesmj** [comment]
I'm also seeing the same issue.

**Comment by austinwbest** [comment]
Should i just disable the plex connect at this point?

**Comment by thesmj** [comment]
I'm no longer seeing the error. I *think* what fixed it is I had Plex update the libraries from the "legacy style" to the current, new style, which is found in Plex's settings page under the "Libraries" list.

I'm not sure if that's what fixed the problem, but I know I did that update last week and I haven't seen the error in Sonarr for a while.
