### ISSUE TITLE
System.IO.IOException: Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by austinwbest** [Sonarr/Sonarr#4981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to move a series from one root folder to another says it already exists. Either this is the wrong error being thrown or more context might be needed.

Screenshot below shows there is no folder yet in the destination

### Expected Behavior

Files to be moved. I dont care to move them manually but would be nice to know *why* it is needing manual assistance in this case

### Steps To Reproduce

I'm just trying to move a series. Usually works, currently isn't.

### Environment

```markdown
- OS: Windows
- Sonarr: 3.0.7.1503
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

```
2022-04-13 17:20:50.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-04-13 17:20:50.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-04-13 17:20:50.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-04-13 17:20:50.0|Trace|Http|Req: 8704 [GET] /api/v3/tag?apikey=(removed) (from 127.0.0.1 Bazarr/1.0.3)
2022-04-13 17:20:50.0|Trace|Http|Res: 8704 [GET] /api/v3/tag?apikey=(removed) 200.OK (1 ms)
2022-04-13 17:20:50.0|Info|MoveSeriesService|Moving Moon Knight from 'D:\Plex\Gretchen\TV Shows\Moon Knight' to 'D:\Plex\TV Shows\Moon Knight'
2022-04-13 17:20:50.0|Debug|Api|[GET] /api/v3/tag?apikey=(removed) 200.OK (1 ms)
2022-04-13 17:20:50.0|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-04-13 17:20:50.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-04-13 17:20:50.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-04-13 17:20:50.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-04-13 17:20:50.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-04-13 17:20:50.0|Debug|DiskTransferService|Move Directory [D:\Plex\Gretchen\TV Shows\Moon Knight] > [D:\Plex\TV Shows\Moon Knight]
2022-04-13 17:20:50.0|Debug|DiskTransferService|Rename Directory [D:\Plex\Gretchen\TV Shows\Moon Knight] > [D:\Plex\TV Shows\Moon Knight]
2022-04-13 17:20:50.1|Error|MoveSeriesService|Unable to move series from 'D:\Plex\Gretchen\TV Shows\Moon Knight' to 'D:\Plex\TV Shows\Moon Knight'. Try moving files manually

[v3.0.7.1503] System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFolder(String source, String destination) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 263
   at NzbDrone.Common.Disk.DiskTransferService.TransferFolder(String sourcePath, String targetPath, TransferMode mode) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 88
   at NzbDrone.Core.Tv.MoveSeriesService.MoveSingleSeries(Series series, String sourcePath, String destinationPath, Nullable`1 index, Nullable`1 total) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\MoveSeriesService.cs:line 59

2022-04-13 17:20:50.2|Trace|EventAggregator|Publishing SeriesEditedEvent
2022-04-13 17:20:50.2|Trace|EventAggregator|SeriesEditedEvent -> SeriesEditedService
2022-04-13 17:20:50.2|Trace|EventAggregator|SeriesEditedEvent <- SeriesEditedService
2022-04-13 17:20:50.2|Trace|EventAggregator|SeriesEditedEvent -> SeriesModule
2022-04-13 17:20:50.2|Trace|EventAggregator|SeriesEditedEvent <- SeriesModule
2022-04-13 17:20:50.2|Trace|EventAggregator|SeriesEditedEvent -> SeriesModule
2022-04-13 17:20:50.2|Trace|EventAggregator|SeriesEditedEvent <- SeriesModule
2022-04-13 17:20:50.2|Trace|CommandQueueManager|Updating command status
2022-04-13 17:20:50.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-04-13 17:20:50.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-04-13 17:20:50.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-04-13 17:20:50.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2022-04-13 17:20:50.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2022-04-13 17:20:50.2|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-04-13 17:20:50.2|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-04-13 17:20:50.2|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-04-13 17:20:50.2|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
2022-04-13 17:20:50.2|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
2022-04-13 17:20:50.2|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
2022-04-13 17:20:50.2|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
2022-04-13 17:20:50.2|Trace|CommandExecutor|MoveSeriesCommand <- MoveSeriesService [00:00:00.3436864]
```

### Anything else?

![image](https://user-images.githubusercontent.com/8321115/163274095-454f3731-7ede-4ac2-b98a-ca79c914bcfb.png)

**Comment by Taloth** [comment]
Looks like a mounted drive, what's special remotely?  Is `Gretchen` anything special? Like a mount, rclone, anything?
It's probably an error thrown by samba.

What happens if you MOVE the series folder via windows explorer. does it happen instantly or slowly or do you get an error?

**Comment by Taloth** [comment]
Anyway, answer those questions on discord support.

**Comment by austinwbest** [comment]
D is a local windows mount, nothing special about that folder. It has been a root folder in sonarr for quite sometime.

D is a pool of drives via drivepool (also been this way for years)

Thanks for the response but I have no desire to rejoin the Sonarr discord bud.

Thanks anyways & I'll just fix it manually and move on.
