### ISSUE TITLE
Sonarr Windows (radarr is fine, same settings) - Path issue for Download Client, nothing I'm doing fixes this

### ISSUE THREAD

**Issue by andsoitgoes** [Sonarr/Sonarr#5171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to specify the directory/category in the Download Client section (using Transmission) I constantly get the following error:

```
Message
Unknown error occured in DownloadClientRootFolderCheck HealthCheck: value [/data]  is not a valid Windows path. paths must be a full path eg. C:\Windows
Parameter name: path
Exception
System.ArgumentException: value [/data]  is not a valid Windows path. paths must be a full path eg. C:\Windows
Parameter name: path
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsValidPath(Param`1 param) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\EnsureThat\EnsureStringExtensions.cs:line 106
   at NzbDrone.Common.Extensions.PathExtensions.CleanFilePath(String path) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 33
   at NzbDrone.Common.Extensions.PathExtensions.PathEquals(String firstPath, String secondPath, Nullable`1 comparison) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 58
   at NzbDrone.Core.HealthCheck.Checks.DownloadClientRootFolderCheck.<>c__DisplayClass4_0.<Check>b__0(RootFolder r) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\HealthCheck\Checks\DownloadClientRootFolderCheck.cs:line 48
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Core.HealthCheck.Checks.DownloadClientRootFolderCheck.Check() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\HealthCheck\Checks\DownloadClientRootFolderCheck.cs:line 48
```

I've deleted the directory, readded it. Nothing.

My current remote path mappings looks like this:

Remote Path Mappings
Host
10.0.0.5

Remote Path
/data/TVHD

Local Path
\\10.0.0.3\media\downloads\TVHD\

Transmission settings look as follows (again, this matches Radarr):

![sonarr troubleshooting](https://user-images.githubusercontent.com/7328857/193145378-247dcca3-02d3-4f28-8a03-32982e0b5f87.png)

The only difference between Sonarr and Radarr here are the additions of the URL Base and directory, which I've left as default and have tried modifying. It seems the event error log I posted above pulls from the Download Client settings, as when I change that or modify that, the error matches that directory. Here's an example of the error when I mirror Radarr (and just to clarify, I have tried to even use Radarr's movie directory:

`Unknown error occured in DownloadClientRootFolderCheck HealthCheck: value [/data/.moviesHD]  is not a valid Windows path. paths must be a full path eg. C:\Windows
Parameter name: path
Exception
System.ArgumentException: value [/data/.moviesHD]  is not a valid Windows path. paths must be a full path eg. C:\Windows
Parameter name: path
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsValidPath(Param`1 param) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\EnsureThat\EnsureStringExtensions.cs:line 106
   at NzbDrone.Common.Extensions.PathExtensions.CleanFilePath(String path) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 33
   at NzbDrone.Common.Extensions.PathExtensions.PathEquals(String firstPath, String secondPath, Nullable`1 comparison) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 58
   at NzbDrone.Core.HealthCheck.Checks.DownloadClientRootFolderCheck.<>c__DisplayClass4_0.<Check>b__0(RootFolder r) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\HealthCheck\Checks\DownloadClientRootFolderCheck.cs:line 48
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Core.HealthCheck.Checks.DownloadClientRootFolderCheck.Check() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\HealthCheck\Checks\DownloadClientRootFolder`

I've also redone the user account on both Radarr and Sonarr within Services, making sure I'm using the same exact info - yet still, only Sonarr throws an error.

The oddest thing is that it is still grabbing and moving stuff, I was confused as I still had the error but yet everything worked mostly normally, I haven't done much as this is a separate instance with Radarr on a Windows PC.

### Expected Behavior

Not throwing this error in the logs

### Steps To Reproduce

Set a download category (or not) 
saving
error.

### Environment

```markdown
- OS: Windows 10 Pro
- Sonarr: 3.0.9.1549
- Docker Install: n/a
- Using Reverse Proxy: no
- Browser: Any
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/9679213/sonarr.trace.txt)

### Anything else?

All logs are attached, I've tried everything - yet I can't seem to sort this out.

I don't understand why virtually the same settings in Radarr work, when I get the errors in Sonarr.

I've gone through loads of troubleshooting for people that have path issues to noavail, I've tried everything known to man but yet still, I'm here. Any help or advice would be greatly appreciated.

Thanks!

**Comment by andsoitgoes** [comment]
A minor update, I tried downloading a season just to see what happened, so here's what did:

The season got moved, correctly, into the right folder. The activity was cleared and everything is where it should be.

The logs, however, tell a different story:

`Series' root folder (\\nas\media\tv\HD) is empty.`

Except this is what's listed in the series:

`\\nas\media\TVHD\Letterkenny`

I changed the root folders eons ago and I have zero reference to TV/HD (which I realize now was an idiotic directory choice)

WTF?

Also, I deleted the root folder in library import and added it back, this error came to say hi:

`Message
Unknown error occured in DownloadClientRootFolderCheck HealthCheck: value [/data/.TVHD]  is not a valid Windows path. paths must be a full path eg. C:\Windows
Parameter name: path
Exception
System.ArgumentException: value [/data/.TVHD]  is not a valid Windows path. paths must be a full path eg. C:\Windows
Parameter name: path
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsValidPath(Param`1 param) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\EnsureThat\EnsureStringExtensions.cs:line 106
   at NzbDrone.Common.Extensions.PathExtensions.CleanFilePath(String path) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 33
   at NzbDrone.Common.Extensions.PathExtensions.PathEquals(String firstPath, String secondPath, Nullable`1 comparison) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 58
   at NzbDrone.Core.HealthCheck.Checks.DownloadClientRootFolderCheck.<>c__DisplayClass4_0.<Check>b__0(RootFolder r) in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\HealthCheck\Checks\DownloadClientRootFolderCheck.cs:line 48
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Core.HealthCheck.Checks.DownloadClientRootFolderCheck.Check() in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\HealthCheck\Checks\DownloadClientRootFolderCheck.cs:line 48`

I've started to go grey...er after all of this.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

I see you already opened a thread on the forums, so I won’t add anything here about possible causes.
