### ISSUE TITLE
Update should download to --data dir

### ISSUE THREAD

**Issue by brianjmurrell** [Sonarr/Sonarr#5264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Downloading a Sonarr update downloads to `/tmp/` (on Linux).

### Expected Behavior

Should download somewhere that would have more space available.  `/var/tmp/` is one candidate, but Sonarr's own `--data` dir is another.

### Environment

```markdown
- OS: Fedora 37
- Sonarr: 4.0.0.189
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome (but not really applicable)
```

### What branch are you running?

Develop

### Trace Logs?

```
2022-12-02 08:33:42.3|Info|InstallUpdateService|Downloading update 4.0.0.205
2022-12-02 08:34:04.2|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v4.0.0.189] System.Net.WebException: Failed to read complete http response
 ---> System.IO.IOException: No space left on device : '/tmp/sonarr_update/Sonarr.develop.4.0.0.205.linux-x64.tar.gz.part'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.OSFileStreamStrategy.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Strategies.BufferedFileStreamStrategy.WriteSpan(ReadOnlySpan`1 source, ArraySegment`1 arraySegment)
   at System.IO.MemoryStream.CopyTo(Stream destination, Int32 bufferSize)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 121
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 138
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\HttpClient.cs:line 127
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\HttpClient.cs:line 62
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\HttpClient.cs:line 255
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 120
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 283
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

### Anything else?

Is $TMPDIR honoured at all, as a workaround/solution?

**Comment by thezoggy** [comment]
$TMPDIR used to be in mono days, probably still so? try it and see. but also why would your /tmp mount not have any space?

**Comment by markus101** [comment]
Sonarr uses `Path.GetTempPath()`, which is documented here: https://learn.microsoft.com/en-us/dotnet/api/system.io.path.gettemppath?view=net-7.0&tabs=linux

Which is checked in this order:

> 1. The path specified by the `TMPDIR` environment variable.
> 2. The path `/tmp/`.

We do not have plans to move this from the temp folder to another location, but it can be controlled by you if necessary.

**Comment by brianjmurrell** [comment]
Setting `$TMPDIR` seems like a reasonable work-around and it works.
