### ISSUE TITLE
Still get Failed to Load Queue

### ISSUE THREAD

**Issue by SuperDOS** [Sonarr/Sonarr#5282]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

On version 4.0.0.255 when Clicking Activity/Queue I get Failed to load Queue

2022-12-09 12:50:41.3|Fatal|SonarrErrorPipeline|Request Failed. GET /api/v3/queue

[v4.0.0.255] NzbDrone.Core.Exceptions.BadRequestException: Invalid sort key episode.title
   at Sonarr.Http.Extensions.RequestExtensions.ReadPagingResourceFromRequest[TResource](HttpRequest request) in M:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Extensions\RequestExtensions.cs:line 89
   at Sonarr.Api.V3.Queue.QueueController.GetQueue(Boolean includeUnknownSeriesItems, Boolean includeSeries, Boolean includeEpisode) in M:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Api.V3\Queue\QueueController.cs:line 101
   at lambda_method478(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in M:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in M:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in M:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in M:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in M:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

### Describe the solution you'd like

The Activity Queue should load

### Describe alternatives you've considered

A fix was submitted but didn't seem to work.

### Anything else?

Previous ticket [https://github.com/Sonarr/Sonarr/issues/5257](url)

**Comment by jrac86** [comment]
This is happening for me as well on newest version 4.0.0.258. In addition to not loading the activity section, sonarr is not importing anything. It sends the download over to sabnzbd, but never imports the file once it's done.

**Comment by jimbob1986** [comment]
same i woke to find nothing was getting imported from sab. i running the v4 on windows

**Comment by jpdsc** [comment]
Same here.

```
Version
4.0.0.256
Package Version
v4-7ff35cb by [hotio](https://github.com/hotio)
.Net Version
Yes (6.0.8)
AppData directory
/config
Startup directory
/app/bin
Mode
Console
Uptime
```

**Comment by TurboCheetah** [comment]
Same here

Version 4.0.0.258
Package Version v4-51d6e2a by [hotio](https://github.com/hotio)

**Comment by Qstick** [comment]
You guys are mixing up issues, create another for the 258 issue
