### ISSUE TITLE
4.0.0.265 - broke history/series

### ISSUE THREAD

**Issue by thezoggy** [Sonarr/Sonarr#5286]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

if you try to view series history, it no longer loads due to api endpoint broken: /api/v3/history/series

### Expected Behavior

return history

### Steps To Reproduce

go to series, click the view history button

### Environment

```markdown
- OS: windows 10
- Sonarr: 4.0.0.265
- Docker Install: no
- Using Reverse Proxy: no
- Browser: firefox 107.1
```

### What branch are you running?

Develop

### Trace Logs?

```
2022-12-09 13:11:40.9|Fatal|SonarrErrorPipeline|Request Failed. GET /api/v3/history/series

[v4.0.0.265] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.CustomFormats.CustomFormatCalculationService.ParseCustomFormat(EpisodeHistory history, Series series) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\CustomFormats\CustomFormatCalculationService.cs:line 81
   at Sonarr.Api.V3.History.HistoryResourceMapper.ToResource(EpisodeHistory model, ICustomFormatCalculationService formatCalculator) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Api.V3\History\HistoryResource.cs:line 43
   at Sonarr.Api.V3.History.HistoryController.MapToResource(EpisodeHistory model, Boolean includeSeries, Boolean includeEpisode) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Api.V3\History\HistoryController.cs:line 55
   at Sonarr.Api.V3.History.HistoryController.<>c__DisplayClass8_0.<GetSeriesHistory>b__0(EpisodeHistory h) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Api.V3\History\HistoryController.cs:line 103
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Sonarr.Api.V3.History.HistoryController.GetSeriesHistory(Int32 seriesId, Nullable`1 seasonNumber, Nullable`1 eventType, Boolean includeSeries, Boolean includeEpisode) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Api.V3\History\HistoryController.cs:line 103
   at lambda_method343(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2022-12-09 13:11:40.9|Trace|Http|Res: 115 [GET] /api/v3/history/series?seriesId=593&seasonNumber=1: 500.InternalServerError (27 ms)
2022-12-09 13:11:40.9|Debug|Api|[GET] /api/v3/history/series?seriesId=593&seasonNumber=1: 500.InternalServerError (27 ms)
```

### Anything else?

shared from discord

**Comment by Glenn332** [comment]
Same issue here,

[Link](https://github.com/Sonarr/Sonarr/commit/6216a71f8c813ac3480b5fd95b3ef6a37c666d0d#diff-805f680f6dd6b0cf13a227ecc9415812025f41ee6c8bf6751063ede70bcdb3c2R85) seems to be related to this commit / line.

**Comment by Glenn332** [comment]
Bug has not been resolved, look at my earlier comment. The missing include of series is happening on multiple endpoints, namely the "historysince" I mentioned.

It might also be a better idea to include the series entity during retrieval of the Episodehistory in the Episodehistory repository Since method as this is more performant than retrieving the series for each item individually, but that is up to you.

**Comment by markus101** [comment]
The original bug that was report was resolved, history/since has the same symptom with a different cause, but like I said in Discord, we'll get that sorted.

**Comment by markus101** [comment]
history/since will be fixed in https://github.com/Sonarr/Sonarr/commit/60470b653a3298891e4a7023f4022c84fdebe345
