### ISSUE TITLE
[v4.0.0.303] System.Data.DataException: Error parsing column 12 (AirDateUtc=1 - Int64) ---> System.FormatException: String '

### ISSUE THREAD

**Issue by dodgen247** [Sonarr/Sonarr#5318]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Imports are failing with the below error:
2022-12-22 08:42:00.1|Warn|ImportApprovedEpisodes|Couldn't import episode /share/episodename.mkv

[v4.0.0.303] System.Data.DataException: Error parsing column 12 (AirDateUtc=1 - Int64)
---> System.FormatException: String '
]
},
{
' was not recognized as a valid DateTime.
at System.DateTimeParse.ParseExactMultiple(ReadOnlySpan1 s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style) at System.Data.SQLite.SQLiteConvert.ToDateTime(String dateText, SQLiteDateFormats format, DateTimeKind kind, String formatString) at System.Data.SQLite.SQLite3.GetDateTime(SQLiteStatement stmt, Int32 index) at System.Data.SQLite.SQLite3.GetValue(SQLiteStatement stmt, SQLiteConnectionFlags flags, Int32 index, SQLiteType typ) at System.Data.SQLite.SQLiteDataReader.GetValue(Int32 i) at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader ) --- End of inner exception stack trace --- at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706 at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader ) at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() at System.Collections.Generic.List1..ctor(IEnumerable1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable1 commandTimeout, Nullable1 commandType)
at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
at NzbDrone.Core.Datastore.TableMapping.<>c.b__5_34(IDatabase db, EpisodeFile parent)
at NzbDrone.Core.Datastore.LazyLoaded2.LazyLoad() at NzbDrone.Core.MediaFiles.MediaFileService.Delete(EpisodeFile episodeFile, DeleteMediaFileReason reason) at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode)

### Expected Behavior

Files to be automatically imported after download has completed.

### Steps To Reproduce

I am running the docker image: Linuxserver.io version:- 4.0.0.303-ls359 Build-date:- 2022-12-20T21:29:42+01:00
Sonarr tries to import a completed download.
Error: Downloaded - Unable to import: Check logs for more details

### Environment

```markdown
- OS: CentOS
- Sonarr: 4.0.0.307-ls362 Build-date:- 2022-12-21T19:10:11+01:00
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: firefox
```

### What branch are you running?

Develop

### Trace Logs?

Is there an existing issue for this?

    I have searched the existing issues

Current Behavior

Imports are failing with the below error:
2022-12-22 08:42:00.1|Warn|ImportApprovedEpisodes|Couldn't import episode /share/episodename.mkv

[v4.0.0.303] System.Data.DataException: Error parsing column 12 (AirDateUtc=1 - Int64)
---> System.FormatException: String '
]
},
{
' was not recognized as a valid DateTime.
at System.DateTimeParse.ParseExactMultiple(ReadOnlySpan1 s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style) at System.Data.SQLite.SQLiteConvert.ToDateTime(String dateText, SQLiteDateFormats format, DateTimeKind kind, String formatString) at System.Data.SQLite.SQLite3.GetDateTime(SQLiteStatement stmt, Int32 index) at System.Data.SQLite.SQLite3.GetValue(SQLiteStatement stmt, SQLiteConnectionFlags flags, Int32 index, SQLiteType typ) at System.Data.SQLite.SQLiteDataReader.GetValue(Int32 i) at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader ) --- End of inner exception stack trace --- at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706 at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader ) at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() at System.Collections.Generic.List1..ctor(IEnumerable1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable1 commandTimeout, Nullable1 commandType)
at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
at NzbDrone.Core.Datastore.TableMapping.<>c.b__5_34(IDatabase db, EpisodeFile parent)
at NzbDrone.Core.Datastore.LazyLoaded2.LazyLoad() at NzbDrone.Core.MediaFiles.MediaFileService.Delete(EpisodeFile episodeFile, DeleteMediaFileReason reason) at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode)
Expected Behavior

Files to be automatically imported after download has completed.
Steps To Reproduce

I am running the docker image: Linuxserver.io version:- 4.0.0.303-ls359 Build-date:- 2022-12-20T21:29:42+01:00
Sonarr tries to import a completed download.
Error: Downloaded - Unable to import: Check logs for more details
Environment

- OS: CentOS 7 hosting docker compose 4.0.0.303-ls359 Build-date:- 2022-12-20T21:29:42+01:00
- How docker service was installed: yum

CPU architecture

x86-64
Docker creation

docker-compose up -d

version: "3.3"
services:
  sonarr:
    image: linuxserver/sonarr:develop
    container_name: sonarr
    volumes:
      - /path1/sonarr:/config
      - /path2/share:/share
      - /path3/ssl:/ssl
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Los_Angeles
      - PGID=number
      - PUID=number
    ports:
      - "port:8989"
    restart: unless-stopped

Container logs

2022-12-22 08:44:00.9|Warn|ImportApprovedEpisodes|Couldn't import episode /share/file.mkv

[v4.0.0.303] System.Data.DataException: Error parsing column 12 (AirDateUtc=1 - Int64)
 ---> System.FormatException: String '
    ]
  },
  {
    ' was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExactMultiple(ReadOnlySpan`1 s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.Data.SQLite.SQLiteConvert.ToDateTime(String dateText, SQLiteDateFormats format, DateTimeKind kind, String formatString)
   at System.Data.SQLite.SQLite3.GetDateTime(SQLiteStatement stmt, Int32 index)
   at System.Data.SQLite.SQLite3.GetValue(SQLiteStatement stmt, SQLiteConnectionFlags flags, Int32 index, SQLiteType typ)
   at System.Data.SQLite.SQLiteDataReader.GetValue(Int32 i)
   at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
   at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader )
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
   at NzbDrone.Core.Datastore.TableMapping.<>c.<Map>b__5_34(IDatabase db, EpisodeFile parent)
   at NzbDrone.Core.Datastore.LazyLoaded`2.LazyLoad()
   at NzbDrone.Core.MediaFiles.MediaFileService.Delete(EpisodeFile episodeFile, DeleteMediaFileReason reason)
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly)
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode)

2022-12-22 08:44:01.2|Warn|ImportApprovedEpisodes|Couldn't import episode /share/file2.mkv

[v4.0.0.303] System.Data.DataException: Error parsing column 12 (AirDateUtc=1 - Int64)
 ---> System.FormatException: String '
    ]
  },
  {
    ' was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExactMultiple(ReadOnlySpan`1 s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.Data.SQLite.SQLiteConvert.ToDateTime(String dateText, SQLiteDateFormats format, DateTimeKind kind, String formatString)
   at System.Data.SQLite.SQLite3.GetDateTime(SQLiteStatement stmt, Int32 index)
   at System.Data.SQLite.SQLite3.GetValue(SQLiteStatement stmt, SQLiteConnectionFlags flags, Int32 index, SQLiteType typ)
   at System.Data.SQLite.SQLiteDataReader.GetValue(Int32 i)
   at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
   at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader )
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
   at NzbDrone.Core.Datastore.TableMapping.<>c.<Map>b__5_34(IDatabase db, EpisodeFile parent)
   at NzbDrone.Core.Datastore.LazyLoaded`2.LazyLoad()
   at NzbDrone.Core.MediaFiles.MediaFileService.Delete(EpisodeFile episodeFile, DeleteMediaFileReason reason)
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly)
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode)

2022-12-22 08:44:01.5|Warn|ImportApprovedEpisodes|Couldn't import episode /share/file.mkv

[v4.0.0.303] System.Data.DataException: Error parsing column 12 (AirDateUtc=1 - Int64)
 ---> System.FormatException: String '
    ]
  },
  {
    ' was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExactMultiple(ReadOnlySpan`1 s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.Data.SQLite.SQLiteConvert.ToDateTime(String dateText, SQLiteDateFormats format, DateTimeKind kind, String formatString)
   at System.Data.SQLite.SQLite3.GetDateTime(SQLiteStatement stmt, Int32 index)
   at System.Data.SQLite.SQLite3.GetValue(SQLiteStatement stmt, SQLiteConnectionFlags flags, Int32 index, SQLiteType typ)
   at System.Data.SQLite.SQLiteDataReader.GetValue(Int32 i)
   at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
   at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader )
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
   at NzbDrone.Core.Datastore.TableMapping.<>c.<Map>b__5_34(IDatabase db, EpisodeFile parent)
   at NzbDrone.Core.Datastore.LazyLoaded`2.LazyLoad()
   at NzbDrone.Core.MediaFiles.MediaFileService.Delete(EpisodeFile episodeFile, DeleteMediaFileReason reason)
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly)
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode)

2022-12-22 08:44:01.7|Warn|ImportApprovedEpisodes|Couldn't import episode /share/file.mkv

[v4.0.0.303] System.Data.DataException: Error parsing column 12 (AirDateUtc=1 - Int64)
 ---> System.FormatException: String '
    ]
  },
  {
    ' was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExactMultiple(ReadOnlySpan`1 s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.Data.SQLite.SQLiteConvert.ToDateTime(String dateText, SQLiteDateFormats format, DateTimeKind kind, String formatString)
   at System.Data.SQLite.SQLite3.GetDateTime(SQLiteStatement stmt, Int32 index)
   at System.Data.SQLite.SQLite3.GetValue(SQLiteStatement stmt, SQLiteConnectionFlags flags, Int32 index, SQLiteType typ)
   at System.Data.SQLite.SQLiteDataReader.GetValue(Int32 i)
   at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
   at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader )
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
   at NzbDrone.Core.Datastore.TableMapping.<>c.<Map>b__5_34(IDatabase db, EpisodeFile parent)
   at NzbDrone.Core.Datastore.LazyLoaded`2.LazyLoad()
   at NzbDrone.Core.MediaFiles.MediaFileService.Delete(EpisodeFile episodeFile, DeleteMediaFileReason reason)
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly)
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode)

2022-12-22 08:44:02.1|Warn|ImportApprovedEpisodes|Couldn't import episode /share/file.mkv

[v4.0.0.303] System.Data.DataException: Error parsing column 12 (AirDateUtc=1 - Int64)
 ---> System.FormatException: String '
    ]
  },
  {
    ' was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExactMultiple(ReadOnlySpan`1 s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.Data.SQLite.SQLiteConvert.ToDateTime(String dateText, SQLiteDateFormats format, DateTimeKind kind, String formatString)
   at System.Data.SQLite.SQLite3.GetDateTime(SQLiteStatement stmt, Int32 index)
   at System.Data.SQLite.SQLite3.GetValue(SQLiteStatement stmt, SQLiteConnectionFlags flags, Int32 index, SQLiteType typ)
   at System.Data.SQLite.SQLiteDataReader.GetValue(Int32 i)
   at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
   at Deserialize7480a3ba-8f47-41ba-85a7-0b8c4f9daa2d(IDataReader )
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
   at NzbDrone.Core.Datastore.TableMapping.<>c.<Map>b__5_34(IDatabase db, EpisodeFile parent)
   at NzbDrone.Core.Datastore.LazyLoaded`2.LazyLoad()
   at NzbDrone.Core.MediaFiles.MediaFileService.Delete(EpisodeFile episodeFile, DeleteMediaFileReason reason)
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly)
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Looks like your database is corrupt and instead of a date Sonarr is getting back a number. You can probably hunt down the offending row with `SELECT * FROM Episodes WHERE AirDateUtc = 1` in a sqlite tool of your choice.
