### ISSUE TITLE
Unable to load Quality Profiles after Removing Custom Format

### ISSUE THREAD

**Issue by newadventure079** [Sonarr/Sonarr#5323]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr will not open.  All that is displayed is 
```
The given key '59' was not present in the dictionary.
Version 4.0.0.312
```

### Expected Behavior

For Sonarr to load

### Steps To Reproduce

1.  Have a custom format set
2. Use the custom format in a profile
3. Delete the custom format
4. Sonarr will not load

### Environment

```markdown
- OS: Docker
- Sonarr: 4.0.0.312
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Edge
```

### What branch are you running?

Main

### Trace Logs?

```
2022-12-23 14:28:54.0|Fatal|SonarrErrorPipeline|Request Failed. GET /api/v3/qualityprofile

[v4.0.0.312] System.Collections.Generic.KeyNotFoundException: The given key '59' was not present in the dictionary.
   at NzbDrone.Core.Profiles.Qualities.QualityProfileRepository.Query(SqlBuilder builder) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Profiles\Qualities\QualityProfileRepository.cs:line 28
   at NzbDrone.Core.Profiles.Qualities.QualityProfileService.All() in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Profiles\Qualities\QualityProfileService.cs:line 72
   at lambda_method307(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

### Anything else?

I can't get the trace logs because Sonarr wont load for me to switch the config over to trace logs

**Comment by markus101** [comment]
> I can't get the trace logs because Sonarr wont load for me to switch the config over to trace logs

From the wiki: `Turn Logging up to Trace (Settings => General => Log Level or Edit The Config File`

Editing the config file to set the logging level is there for cases where you can't access the UI.
