### ISSUE TITLE
Series delete doesn't work

### ISSUE THREAD

**Issue by azkar0** [Sonarr/Sonarr#5333]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When trying to delete a series, from the series page, the 'add list exclusion' option cannot be toggled, and clicking 'delete' does nothing. Deleting from the mass editor page works as expected.

### Expected Behavior

'Add list exclusion' can be toggled on or off, and series is deleted when you click 'delete'.

### Steps To Reproduce

1. Navigate to a series page
2. Click the trash can
3. Try to change the 'add list exclusion option'
4. Try to click 'delete'

### Environment

```markdown
- OS: Windows 11
- Sonarr:4.0.0.326
- Docker Install:No
- Using Reverse Proxy: No
- Browser: Chrome 108.0.5359.100
```

### What branch are you running?

Main

### Trace Logs?

https://gist.github.com/azkar0/b4de901b3d856a8ccd7491629c9c5c7f

**Comment by klogg416** [comment]
I'm seeing this as well.

### Steps To Reproduce
#### 1. From root Series navigator
Hover over poster, wrench icon / `Edit Series`
`Delete` button on first pop up
`Delete` button on second pop up
Second delete isn't recognised. Nothing happens and no activity in the log.

#### 2. From root Series navigator
Hover over poster, wrench icon / `Edit Series`
`Delete` button on first pop up
Select `Delete X Episode Files`, file and size count updates correctly.
`Delete` button on second pop up
Second delete isn't recognised. Nothing happens and no activity in the log.

Same behaviour applies when starting in the individual series pages.

### Environment
```
- OS: unraid / linux 
- Sonarr: 4.0.0.326
- Docker Install:Yes
- Using Reverse Proxy: No
- Browser: Brave 1.46.144 (Chromium 108.0.5359.128
```

### What branch are you running?
Development

Trace log attached. 
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/10328902/sonarr.trace.txt)

**Comment by stevietv** [comment]
dev console error when pressing add list exclusion:

```
helpers.js:89 

Uncaught TypeError: r.props.onChange is not a function
    at r.toggleChecked (CheckInput.js:56:18)
    at r.onClick (CheckInput.js:80:10)
    at Object.We (react-dom.production.min.js:52:317)
    at $e (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at jr (react-dom.production.min.js:100:68)
    at Lr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Ye (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57
    at Ar (react-dom.production.min.js:105:469)
    at Jt (react-dom.production.min.js:75:265)
    at Xt (react-dom.production.min.js:74:124)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Vo (react-dom.production.min.js:122:325)
    at Pe (react-dom.production.min.js:292:48)
    at Zt (react-dom.production.min.js:73:352)
    at HTMLDivElement.o (helpers.js:74:23)
toggleChecked	@	CheckInput.js:56
r.onClick	@	CheckInput.js:80
We	@	react-dom.production.min.js:52
$e	@	react-dom.production.min.js:52
(anonymous)	@	react-dom.production.min.js:53
jr	@	react-dom.production.min.js:100
Lr	@	react-dom.production.min.js:101
(anonymous)	@	react-dom.production.min.js:113
Ye	@	react-dom.production.min.js:292
(anonymous)	@	react-dom.production.min.js:50
Ar	@	react-dom.production.min.js:105
Jt	@	react-dom.production.min.js:75
Xt	@	react-dom.production.min.js:74
t.unstable_runWithPriority	@	scheduler.production.min.js:18
Vo	@	react-dom.production.min.js:122
Pe	@	react-dom.production.min.js:292
Zt	@	react-dom.production.min.js:73
o	@	helpers.js:74
```

when pressing delete on the modal:

```
helpers.js:89 
Uncaught TypeError: r.props.onDeletePress is not a function
    at r.onDeleteSeriesConfirmed (DeleteSeriesModalContent.js:41:16)
    at onClick (Link.js:19:7)
    at Object.We (react-dom.production.min.js:52:317)
    at $e (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at jr (react-dom.production.min.js:100:68)
    at Lr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Ye (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57
    at Ar (react-dom.production.min.js:105:469)
    at Jt (react-dom.production.min.js:75:265)
    at Xt (react-dom.production.min.js:74:124)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Vo (react-dom.production.min.js:122:325)
    at Pe (react-dom.production.min.js:292:48)
    at Zt (react-dom.production.min.js:73:352)
    at HTMLDivElement.o (helpers.js:74:23)
```
