### ISSUE TITLE
qBittorrent Not Working On Development v4 Branch

### ISSUE THREAD

**Issue by JackW6809** [Sonarr/Sonarr#5354]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr does not connect to the qBittorrent client after updating to Development branch from Stable. I have tried running it as administrator with no luck, non administrator no luck. Exiting and opening both clients does not fix the issue. Tried re-creating the configuration for the download client, does not change anything either.

### Expected Behavior

Just for Sonarr to connect to the qBittorrent client like it did on v3.

### Steps To Reproduce

1. Ensure you are running v4 (development)
2. Ensure both Sonarr and qBittorrent are working and qBittorrent has the Web UI enabled
3. Launch Sonarr and either the error should appear straight away on System -> Status or run a test.
4. Should return with the error "Unable to connect to qBittorrent" even though it worked moments before in v3.

### Environment

```markdown
- OS: Windows 11
- Sonarr: 4.0.0.334
- Docker Install: No
- Using Reverse Proxy: No
```

### What branch are you running?

Develop

### Trace Logs?
```
2023-01-07 18:47:31.5|Error|ManagedHttpDispatcher|HttpClient error

[v4.0.0.334] System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 109

2023-01-07 18:47:31.7|Error|QBittorrent|Unable to test qBittorrent

[v4.0.0.334] System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 109
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\HttpClient.cs:line 127
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\HttpClient.cs:line 62
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.IsApiSupported(QBittorrentSettings settings) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxyV2.cs:line 36
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.FetchProxy(QBittorrentSettings settings) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 86
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.<>c__DisplayClass7_0.<GetProxyCache>b__0() in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 81
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Cache\Cached.cs:line 104
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxyCache(QBittorrentSettings settings, Boolean force) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 81
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxy(QBittorrentSettings settings, Boolean force) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxySelector.cs:line 64
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.TestConnection() in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 391

2023-01-07 18:47:31.9|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.0.0.334] FluentValidation.ValidationException: Validation failed: 
 -- Host: Unable to connect to qBittorrent
   at Sonarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Api.V3\ProviderControllerBase.cs:line 211
   at Sonarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Api.V3\ProviderControllerBase.cs:line 202
   at Sonarr.Api.V3.ProviderControllerBase`3.Test(TProviderResource providerResource) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Api.V3\ProviderControllerBase.cs:line 147
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\BufferingMiddleware.cs:line 27
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\VersionMiddleware.cs:line 27
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2023-01-07 18:47:31.9|Trace|SonarrErrorPipeline|Handling Exception
2023-01-07 18:47:31.9|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Host: Unable to connect to qBittorrent
2023-01-07 18:47:32.0|Trace|Http|Res: 30 [POST] /api/v3/downloadclient/test: 400.BadRequest (518 ms)
2023-01-07 18:47:32.0|Debug|Api|[POST] /api/v3/downloadclient/test: 400.BadRequest (518 ms)
```
### Anything else?

qBittorrent is updated to the latest version v4.5.0
![image](https://user-images.githubusercontent.com/53652452/211166311-ffacebfa-fd8d-4a22-8e51-b92b0867f5fe.png)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

No issues connecting to qbit in v4 from either Windows 11 or Docker.
