### ISSUE TITLE
API Requests Being Processed While Application is Starting

### ISSUE THREAD

**Issue by KyleSanderson** [Sonarr/Sonarr#5402]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Requests start coming in from the API before Sonarr has even started... hitting locked Databases and similar which obviously causes other issues. 

```
[Info] Bootstrap: Starting Sonarr - /app/bin/Sonarr - Version 4.0.0.362
[Debug] Bootstrap: Console selected
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Debug] Microsoft.Extensions.Hosting.Internal.Host: Hosting starting
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] MigrationController: *** Migrating data source=/config/sonarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] Microsoft.Hosting.Lifetime: Now listening on: http://[::]:8989
[Info] SceneMappingService: Updating Scene mappings
[Info] ReleasePushController: Release pushed: Survivor.Of.Bakerboy.S10E01.1080p.HDTV.H264-FERENGI - https://digitalcore.club/api/v1/torrents/download
[Info] RssSyncService: Starting RSS Sync
[Info] DownloadDecisionMaker: Processing 1 releases
[Info] RefreshSeriesService: Skipping refresh of series: 1883
[Info] DiskScanService: Scanning 1883
[Info] DiskScanService: Completed scanning disk for 1883
[Info] ReleasePushController: Release pushed: Survivor.Of.Bakerboy.S10E01.1080p.HDTV.H264-FERENGI - https://www.acid-lounge.org.uk/rssdownload.php?
[Info] ExistingMetadataImporter: Found 0 existing metadata files
[Info] DownloadDecisionMaker: Processing 1 releases
[Info] ExistingSubtitleImporter: Found 0 existing subtitle files
[Info] ExistingOtherExtraImporter: Found 0 existing other extra files
[Info] ExistingExtraFileService: Found 9 possible extra files, imported 9 files.
[Info] RefreshSeriesService: Skipping refresh of series: 1899
[Info] DiskScanService: Scanning 1899
[Info] DiskScanService: Completed scanning disk for 1899
[Info] ExistingMetadataImporter: Found 0 existing metadata files
[Info] ExistingSubtitleImporter: Found 0 existing subtitle files
[Info] ExistingOtherExtraImporter: Found 0 existing other extra files
[Info] ExistingExtraFileService: Found 0 possible extra files, imported 0 files.
[Info] RefreshSeriesService: Updating 1923
[Info] RefreshEpisodeService: Starting episode info refresh for: [416491][1923]
[Error] FileList: An error occurred while processing feed. https://filelist.io/api.php?action=latest-torrents

[v4.0.0.362] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2848
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 452
   at NzbDrone.Core.Datastore.BasicRepository`1.UpdateFields(IDbConnection connection, IDbTransaction transaction, TModel model, List`1 propertiesToUpdate) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 378
   at NzbDrone.Core.Datastore.BasicRepository`1.Update(TModel model) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 221
   at NzbDrone.Core.Datastore.BasicRepository`1.Upsert(TModel model) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 288
   at NzbDrone.Core.Indexers.IndexerStatusService.UpdateRssSyncStatus(Int32 indexerId, ReleaseInfo releaseInfo) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Indexers\IndexerStatusService.cs:line 36
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 201

[Info] DownloadDecisionMaker: Processing 400 releases
[Error] RefreshSeriesService: Couldn't refresh info for [416491][1923]

[v4.0.0.362] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 563
   at NzbDrone.Core.Datastore.BasicRepository`1.UpdateFields(IDbConnection connection, IDbTransaction transaction, IList`1 models, List`1 propertiesToUpdate) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 390
   at NzbDrone.Core.Datastore.BasicRepository`1.UpdateMany(IList`1 models) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 238
   at NzbDrone.Core.Tv.EpisodeService.UpdateMany(List`1 episodes) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Tv\EpisodeService.cs:line 210
   at NzbDrone.Core.Tv.RefreshEpisodeService.RefreshEpisodeInfo(Series series, IEnumerable`1 remoteEpisodes) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Tv\RefreshEpisodeService.cs:line 100
   at NzbDrone.Core.Tv.RefreshSeriesService.RefreshSeriesInfo(Int32 seriesId) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Tv\RefreshSeriesService.cs:line 125
   at NzbDrone.Core.Tv.RefreshSeriesService.Execute(RefreshSeriesCommand message) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Tv\RefreshSeriesService.cs:line 264

[Info] DiskScanService: Scanning 1923
[Info] DownloadService: Report sent to qBittorrent. Indexer BroadcastheNet. Quantum.Baker.2022.S01E11.720p.HDTV.x264-SYNCOPY
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down.
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production
[Info] Microsoft.Hosting.Lifetime: Content root path: /
[Info] DiskScanService: Completed scanning disk for 1923
[Info] ExistingMetadataImporter: Found 2 existing metadata files
[Info] ExistingSubtitleImporter: Found 0 existing subtitle files
[Info] ExistingOtherExtraImporter: Found 0 existing other extra files
[Info] ExistingExtraFileService: Found 1 possible extra files, imported 2 files.
[Info] RefreshSeriesService: Skipping refresh of series: 24
[Info] DiskScanService: Scanning 24
[Info] DiskScanService: Completed scanning disk for 24
[Info] MetadataService: Series folder does not exist, skipping metadata creation
[Info] RefreshSeriesService: Skipping refresh of series: 24: Legacy
[Info] DiskScanService: Scanning 24: Legacy
[Info] DiskScanService: Completed scanning disk for 24: Legacy
[Info] MetadataService: Series folder does not exist, skipping metadata creation
[Info] RefreshSeriesService: Updating 60 Minutes
[Info] RefreshEpisodeService: Starting episode info refresh for: [73290][60 Minutes]
[Info] RssSyncService: RSS Sync Completed. Reports found: 400, Reports grabbed: 1, Reports pending: 2
```

### Expected Behavior

The network should come up last, not first.

### Steps To Reproduce

Start the application.

### Environment

```markdown
- OS: nix
- Sonarr: v4-4.0.0.362
- Docker Install: y
```

### What branch are you running?

Main

### Trace Logs?

see above.

**Comment by markus101** [comment]
Those aren't trace logs, please link the appropriate trace logs.

**Comment by KyleSanderson** [comment]
> Those aren't trace logs, please link the appropriate trace logs.

Are you seeing different behaviour on your system? Just want to know what I'm looking for to reduce the amount of noise from them. I've already lost my database twice from issues like this.

```
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down.
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production
[Info] Microsoft.Hosting.Lifetime: Content root path: /
```

**Comment by markus101** [comment]
The database being locked on it's own isn't an error. The DB migration has already been performed and Sonarr is in the process of running any tasks it runs on startup.

But no, I don't have this issue with my system.

**Comment by KyleSanderson** [comment]
> The database being locked on it's own isn't an error. The DB migration has already been performed and Sonarr is in the process of running any tasks it runs on startup.
> 
> But no, I don't have this issue with my system.

Very weird your startup order doesn't do this. I've spun up a brand new Sonarr install, and here are the complete logs showing the ordering is still very much so broken.

[logs.txt](https://github.com/Sonarr/Sonarr/files/10551363/noshit.txt)

**Comment by markus101** [comment]
Once again, please provide the trace logs (from Sonarr's log files), following the instructions you should have when you opened this issue.

**Comment by markus101** [comment]
Actually, looks like trace logs are unnecessary this time. It comes down to how web host is initialized, which is handled outside of Sonarr.

`Now listening on: http://[::]:8989` gets logged during startup when the web server starts, but it's not until a bit later that Sonarr's internal start-up processes kick off.

It's not later when Sonarr handles the `ApplicationStarted` event from ASP.net and ASP.net's own services handle the `ApplicationStarted` event when Sonarr runs it's on startup tasks and their logging logs that the application has started:

```
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down.
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production
[Info] Microsoft.Hosting.Lifetime: Content root path: <PATH>
```

When the web server is online, Sonarr is started enough to handle requests, it just hasn't completed all it's startup routines.

**Comment by KyleSanderson** [comment]
Thank you
