### ISSUE TITLE
Error message for indexer test incorrect after recent commit

### ISSUE THREAD

**Issue by stevietv** [Sonarr/Sonarr#5461]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When testing an indexer with an error, the lates error message commit (e968919) isn't doing what it should:

![image](https://user-images.githubusercontent.com/1117625/221953499-0004419d-3b06-4cdb-9231-8ecde00c53e5.png)

maybe @bakerboy448 needs to take another pass at it?

### Expected Behavior

{ex.message} is populated with a message

### Environment

```markdown
- OS: Ubuntu
- Sonarr: 4.0.0.391
- Docker Install: yes 
- Using Reverse Proxy: yes
- Browser: chrome
```

### What branch are you running?

Develop

### Trace Logs?

```2023-02-28 20:01:26.1|Warn|Newznab|Unable to connect to indexer

[v4.0.0.391] NzbDrone.Common.Http.TooManyRequestsException: HTTP request failed: [429:TooManyRequests] [GET] at [http://prowlarr:9696/3/api?t=tvsearch&cat=5000,5020,5040,5050,5030,5045,5070&extended=1&apikey=(removed)&offset=0&limit=100]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Http\HttpClient.cs:line 100
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 327
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 312
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 396
<?xml version="1.0" encoding="UTF-8"?>
<error code="429" description="Indexer is disabled till 02/28/2023 20:03:36 due to recent failures." />

2023-02-28 20:01:26.1|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.0.0.391] FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer: {ex.Message}. Check the log surrounding this error for details
   at Sonarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Api.V3\ProviderControllerBase.cs:line 216
   at Sonarr.Api.V3.ProviderControllerBase`3.Test(TProviderResource providerResource) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Api.V3\ProviderControllerBase.cs:line 147
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\StartingUpMiddleware.cs:line 41
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in C:\BuildAgent\work\13f3e374fa512e16\src\Sonarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2023-02-28 20:01:26.1|Trace|SonarrErrorPipeline|Handling Exception
2023-02-28 20:01:26.1|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer: {ex.Message}. Check the log surrounding this error for details
2023-02-28 20:01:26.2|Trace|Http|Res: 15481 [POST] /api/v3/indexer/test: 400.BadRequest (49 ms)
2023-02-28 20:01:26.2|Debug|Api|[POST] /api/v3/indexer/test: 400.BadRequest (49 ms)```

### Anything else?

_No response_

**Comment by markus101** [comment]
@bakerboy448 looks like they're missing the `$` for string interpolation.
