### ISSUE TITLE
Imports from read-only source randomly fail

### ISSUE THREAD

**Issue by edrock200** [Sonarr/Sonarr#5537]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Randomly, if an entry can't auto-import after download, and I click the manual import button from Queue, then import, it won't import. Its not consistent though, even though its from the same read-only mount. Sometimes it works, sometimes it doesn't.

### Expected Behavior

File imports correctly.

### Steps To Reproduce

1. Have settings set to Hardlink files (in my case, the source and destination are not the same volume, so this should just end up being a copy)
2. Have a torrent download client path mapped to a read only mount
3. Add a download that cannot "auto import" because match couldn't be determined
4. Manually import said item
5. It may succeed, it may not

### Environment

```markdown
- OS: Ubuntu 18.04
- Sonarr: 4.0.0.433
- Docker Install: linuxserver.io flavor
- Using Reverse Proxy: Yes, Nginx proxy with SSL
- Browser: Chrome Version 111.0.5563.147 (Official Build) (64-bit)
```

### What branch are you running?

Develop

### Trace Logs?

Couldn't import episode /mnt/unionfs/downloads/santorrents/~mar/ShowXYZ.S01E03.720p.WEB-DL.AAC2.0.H.264-WH.mkv: Read-only file system : '/mnt/unionfs/downloads/santorrents/~mar/ShowXYZ.S01E03.720p.WEB-DL.AAC2.0.H.264-WH.mkv'

System.IO.IOException: Read-only file system : '/mnt/unionfs/downloads/santorrents/~mar/Show.XYZ.S01E03.720p.WEB-DL.AAC2.0.H.264-WH.mkv'
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at NzbDrone.Mono.Disk.DiskProvider.TransferFilePatched(String source, String destination, Boolean overwrite, Boolean move) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 342
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 245
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified(String sourcePath, String targetPath, Int64 originalSize) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 506
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 296
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile(EpisodeFile episodeFile, Series series, List`1 episodes, String destinationFilePath, TransferMode mode) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 140
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 77
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 114

### Anything else?

Unfortunately the download was removed due to seeding fulfillment before I could capture trace logs. I will attempt to reproduce with trace logs and paste in this bug if the above is insufficient.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Based on the logs Sonarr tried to move a file, which from a read only file system would fail. If the download had finished seeding, but had not yet been removed then Sonarr would move the files instead of copying them, which is by design if it can't because the file system is read only that's not a bug. Same thing if it was import from Wanted: Missing and told to move or Activity: Queue and finished seeding, Sonarr will move files when the download client is done with it.

**Comment by edrock200** [comment]
Welp. Disregard. I made two errors above, I was on version 4.0.0.431, not 4.0.0.433. Updated to 4.0.0.433, the "yellow" entry for the 25 episode series showed up, I imported, it worked this time. Go figure. Sorry for the waste of time.

**Comment by markus101** [comment]
Ahh, that’d do it, there was a briefly lived bug yesterday that applied the wrong import mode for imports from activity: queue it was fixed in .432 or .433.

**Comment by edrock200** [comment]
> Ahh, that’d do it, there was a briefly lived bug yesterday that applied the wrong import mode for imports from activity: queue it was fixed in .432 or .433.

Thank you as always!!
