### ISSUE TITLE
Skip trying to ffprobe .iso

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#5567]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

```
2023-04-19 10:47:24.2|Debug|VideoFileInfoReader|Getting media info from /data/media/usenet/tv/The.Rookie.S05E21.HDTV.x264-PHOENiX/The.Rookie.S05E21.HDTV.x264-PHOENiX.iso
2023-04-19 10:47:24.2|Error|VideoFileInfoReader|Unable to parse media info from file: /data/media/usenet/tv/The.Rookie.S05E21.HDTV.x264-PHOENiX/The.Rookie.S05E21.HDTV.x264-PHOENiX.iso

[v4.0.0.449] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - /data/media/usenet/tv/The.Rookie.S05E21.HDTV.x264-PHOENiX/The.Rookie.S05E21.HDTV.x264-PHOENiX.iso: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in C:\BuildAgent\work\13f3e374fa512e16\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:line 135

2023-04-19 10:47:24.2|Error|DetectSample|Failed to get runtime from the file, make sure ffprobe is available
```

### Describe the solution you'd like

Skip proving ISOs 

### Describe alternatives you've considered

N/a

**Comment by markus101** [comment]
They're supported in a limited fashion, I don't see a strong reason to drop them at this stage. We can prevent ffprobe from trying to analyze disk image files since it doesn't handle them gracefully.
