### ISSUE TITLE
Quality Profiles not loading

### ISSUE THREAD

**Issue by merqwury** [Sonarr/Sonarr#5588]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When clicking on any profile, I get the following popup with error "There was an error loading this item"

![image](https://user-images.githubusercontent.com/25183069/235091155-5fc06514-645f-4a6d-bd88-ee5d9cb3abff.png)

### Expected Behavior

The Quality Profile to open as usual

### Steps To Reproduce

1. Go to Quality Profiles
2. Click on any quality profile

### Environment

```markdown
- OS: UnRaid
- Sonarr: 4.0.0.464
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 112.0.1
```

### What branch are you running?

Develop

### Trace Logs?

I could not find any logs related to the issue, but attaching the trace logs in any case.
[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/11351431/sonarr.trace.txt)

**Comment by stevietv** [comment]
for posterity, the error provided on discord was:

```
Spread syntax requires ...iterable[Symbol.iterator] to be a function
  at getCustomFormatRender (webpack://sonarr/frontend/src/Settings/Profiles/Quality/EditQualityProfileModalContent.js:244:27)
  at qi (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:187:187)
  at pi (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:186:172)
  at a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:269:426)
  at Pj (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:250:346)
  at Pj (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:250:277)
  at Pj (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:250:137)
  at Lj (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:243:162)
  at jg (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:123:114)
  at unstable_next (webpack://sonarr/node_modules/scheduler/cjs/scheduler.production.min.js:18:342)
  at eg (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:122:324)
  at jg (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:123:60)
  at eg (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:122:427)
  at Hb (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:292:100)
  at $c (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:73:351)
  at args.map(function (webpack://sonarr/node_modules/@sentry/browser/esm/helpers.js:74:22)
  
```

**Comment by Venom84** [comment]
Thanks for raising this one and fixing it :-)
Im having the same issue and was just about to raise it as an issue.

**Comment by astalush** [comment]
Thanks for the fix!
