### ISSUE TITLE
DownloadDecisionMaker failes due to nullable indexer

### ISSUE THREAD

**Issue by mynameisbogdan** [Sonarr/Sonarr#5608]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When pushing to `release/push` similar titles without an indexerId, a NullReferenceException is thrown in https://github.com/Sonarr/Sonarr/blob/b0773ae7e3f860ff381d8d98d23d612609048e38/src/NzbDrone.Core/Blocklisting/BlocklistService.cs#L128

### Expected Behavior

Not a NullReferenceException

### Steps To Reproduce

use the `/api/v3/release/push` endpoint to push a few similar releases without an indexer defined.

```json
{
    "title": "Barry.S04E04.it.takes.a.psycho.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb",
    "infoUrl": "http://example.org/Barry-S04E04",
    "downloadUrl": "http://example.org/Barry.S04E04.it.takes.a.psycho.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.torrent",
    "protocol": "torrent",
    "publishDate": "2023-05-01T04:08:36.886Z",
    "size": 1073741824
}
```

### Environment

```markdown
- OS: 
- Sonarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

```
[v10.0.0.13411] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Blocklisting.BlocklistService.SameTorrent(Blocklist item, TorrentInfo release) in ~/RiderProjects/Sonarr/src/NzbDrone.Core/Blocklisting/BlocklistService.cs:line 128
   at NzbDrone.Core.Blocklisting.BlocklistService.<>c__DisplayClass2_1.<Blocklisted>b__3(Blocklist b) in ~/RiderProjects/Sonarr/src/NzbDrone.Core/Blocklisting/BlocklistService.cs:line 52
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Core.Blocklisting.BlocklistService.Blocklisted(Int32 seriesId, ReleaseInfo release) in ~/RiderProjects/Sonarr/src/NzbDrone.Core/Blocklisting/BlocklistService.cs:line 51
   at NzbDrone.Core.DecisionEngine.Specifications.BlocklistSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in ~/RiderProjects/Sonarr/src/NzbDrone.Core/DecisionEngine/Specifications/BlocklistSpecification.cs:line 24
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in ~/RiderProjects/Sonarr/src/NzbDrone.Core/DecisionEngine/DownloadDecisionMaker.cs:line 216
```

**Comment by bakerboy448** [comment]
Related to #5606
