### ISSUE TITLE
Exceptions being thrown for failed parsing

### ISSUE THREAD

**Issue by mynameisbogdan** [Sonarr/Sonarr#5690]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

```
2023-05-26 16:00:59.2|Info|ReleasePushController|Release pushed: Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai - http://example.org/example.torrent
2023-05-26 16:00:59.2|Debug|ReleasePushController|Push Release Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai not associated with an indexer.
2023-05-26 16:00:59.2|Info|DownloadDecisionMaker|Processing 1 releases
2023-05-26 16:00:59.2|Trace|DownloadDecisionMaker|Processing release 1/1
2023-05-26 16:00:59.2|Debug|DownloadDecisionMaker|Processing release 'Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai' from ''
2023-05-26 16:00:59.2|Debug|Parser|Parsing string 'Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai'
2023-05-26 16:00:59.2|Debug|Parser|Unable to parse Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai
2023-05-26 16:00:59.2|Debug|Parser|Parsing string 'Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai'
2023-05-26 16:00:59.2|Debug|Parser|Unable to parse Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai
2023-05-26 16:00:59.2|Debug|ParsingService|No matching series Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai
2023-05-26 16:00:59.2|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v10.0.0.28650] FluentValidation.ValidationException: Validation failed: 
 -- Title: Unable to parse
   at Sonarr.Api.V3.Indexers.ReleasePushController.Create(ReleaseResource release) in ./Sonarr.Api.V3/Indexers/ReleasePushController.cs:line 72
   at lambda_method156(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/BufferingMiddleware.cs:line 27
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/IfModifiedMiddleware.cs:line 40
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/CacheHeaderMiddleware.cs:line 32
   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/StartingUpMiddleware.cs:line 37
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/UrlBaseMiddleware.cs:line 26
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2023-05-26 16:00:59.2|Trace|SonarrErrorPipeline|Handling Exception
2023-05-26 16:00:59.2|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Title: Unable to parse
2023-05-26 16:00:59.2|Trace|Http|Res: 53 [POST] /api/v3/release/push?apikey=(removed) 400.BadRequest (27 ms)
2023-05-26 16:00:59.2|Debug|Api|[POST] /api/v3/release/push?apikey=(removed) 400.BadRequest (27 ms)
```

### Expected Behavior

Log the failure without the exception stack (upstream does this) as this floods the logs non stop with unnecessary text.

When watching log files for critical errors, this one flags hundreds of times per day sending notifications that are not relevant.

v3.0.10 returns
```
2023-05-26 16:03:44.6|Info|ReleasePushModule|Release pushed: Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai - http://example.org/example.torrent
2023-05-26 16:03:44.6|Debug|ReleasePushModule|Push Release Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai not associated with an indexer.
2023-05-26 16:03:44.6|Info|DownloadDecisionMaker|Processing 1 releases
2023-05-26 16:03:44.6|Trace|DownloadDecisionMaker|Processing release 1/1
2023-05-26 16:03:44.6|Debug|DownloadDecisionMaker|Processing release 'Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai' from ''
2023-05-26 16:03:44.6|Debug|Parser|Parsing string 'Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai'
2023-05-26 16:03:44.6|Debug|Parser|Unable to parse Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai
2023-05-26 16:03:44.6|Debug|Parser|Parsing string 'Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai'
2023-05-26 16:03:44.6|Debug|Parser|Unable to parse Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai
2023-05-26 16:03:44.6|Debug|ParsingService|No matching series Lupin the Third The Mystery of Mamo (1978) Bluray-1080p.FLAC-2.0.[JA+EN].10bit.x264-Akai
2023-05-26 16:03:44.6|Trace|SonarrErrorPipeline|Handling Exception
2023-05-26 16:03:44.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Title: Unable to parse
2023-05-26 16:03:44.6|Trace|Http|Res: 10199 [POST] /api/v3/release/push?apikey=(removed) 400.BadRequest (15 ms)
2023-05-26 16:03:44.6|Debug|Api|[POST] /api/v3/release/push?apikey=(removed) 400.BadRequest (15 ms)
```

### Steps To Reproduce

Push something to the `/release/push` endpoint that won't be able to parse, eg. a movie title.

### Environment

```markdown
- OS: -
- Sonarr: 4.0.0.521 (or as of https://github.com/Sonarr/Sonarr/commit/3ac5edeb0904b65ec8035f5a3c8a79b5458fa0a2)
- Docker Install: -
- Using Reverse Proxy: -
- Browser: -
```

### What branch are you running?

Develop

### Trace Logs?

Already provided.

### Anything else?

https://github.com/Radarr/Radarr/issues/8593

**Comment by PearsonFlyer** [comment]
This is not a valid version of Sonarr, and indicates you've built it yourself from source. This type of install is not supported.

**Comment by PearsonFlyer** [comment]
lol, didn't see that this was you, bog :) Sorry, I'm sure you're reporting a valid issue, and I take back what I said above.
