### ISSUE TITLE
NullReferenceException in BroadcastheNetParser.ParseResponse when the number of search results should be 100, 200, 300...

### ISSUE THREAD

**Issue by gazelle-1177** [Sonarr/Sonarr#5796]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When running an interactive search with the BroadcastheNet indexer for a season that should have 100 search results (or 100, 200, 300... -- 100 is the search page size), the search fails with "No results found", a `NullReferenceException` is logged in `BroadcastheNetParser.ParseResponse`, and the BroadcastheNet indexer becomes "temporarily unavailable due to recent indexer errors".

### Expected Behavior

The search should succeed and show 100 search results (or 100, 200, 300...). Searches do succeed for every other season of the same series. This bug happens with seasons where the number of search results is nonzero and a multiple of 100, the search page size.

### Steps To Reproduce

1. Configure a BroadcastheNet indexer with interactive search enabled, API URL `https://api.broadcasthe.net/`, and tags empty (those are the default settings)
2. Add or find a series where running an interactive search for a particular season should return 100, 200, or 300... search results from BroadcastheNet
3. Run an interactive search for that particular season
4. See the search fail with "No results found"
5. See the BroadcastheNet indexer become "temporarily unavailable due to recent indexer errors"
6. See other seson searches begin to fail with "No results found" because the BroadcastheNet indexer is temporarily unavailable

### Environment

```markdown
- OS: Windows 11
- Sonarr: Sonarr 3.0.10.1567
- Docker Install: No
- Using Reverse Proxy: No
```

### What branch are you running?

Main

### Trace Logs?

```
2023-07-11 17:37:55.3|Info|ReleaseSearchService|Searching indexers for [REDACTEDSERIESNAME : S01]. 1 active indexers
2023-07-11 17:37:55.3|Debug|BroadcastheNet|Downloading Feed https://api.broadcasthe.net/: getTorrents("(removed)", {"Category":"Season","Name":"Season 1%","Tvdb":"REDACTEDTVDBID"}, 100, 0)
2023-07-11 17:37:55.3|Trace|HttpClient|Req: [POST] https://api.broadcasthe.net/: getTorrents("(removed)", {"Category":"Season","Name":"Season 1%","Tvdb":"REDACTEDTVDBID"}, 100, 0)
2023-07-11 17:37:55.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-07-11 17:37:56.1|Trace|HttpClient|Res: [POST] https://api.broadcasthe.net/: 200.OK (82886 bytes) (824 ms)
2023-07-11 17:37:56.1|Debug|BroadcastheNet|Downloading Feed https://api.broadcasthe.net/: getTorrents("(removed)", {"Category":"Season","Name":"Season 1%","Tvdb":"REDACTEDTVDBID"}, 100, 100)
2023-07-11 17:37:56.1|Trace|RateLimitService|Rate Limit triggered, delaying 'api.broadcasthe.net' for 1.170 sec
2023-07-11 17:37:57.3|Trace|HttpClient|Req: [POST] https://api.broadcasthe.net/: getTorrents("(removed)", {"Category":"Season","Name":"Season 1%","Tvdb":"REDACTEDTVDBID"}, 100, 100)
2023-07-11 17:37:57.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-07-11 17:37:57.8|Trace|HttpClient|Res: [POST] https://api.broadcasthe.net/: 200.OK (44 bytes) (532 ms)
2023-07-11 17:37:57.8|Trace|BroadcastheNet|Unexpected Response content (44 bytes): {"id":"93e0483a","result":{"results":"100"}}
2023-07-11 17:37:57.8|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IIndexer>
2023-07-11 17:37:57.8|Error|BroadcastheNet|An error occurred while processing feed. https://api.broadcasthe.net/

[v3.0.10.1567] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Indexers.BroadcastheNet.BroadcastheNetParser.ParseResponse(IndexerResponse indexerResponse) in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\BroadcastheNet\BroadcastheNetParser.cs:line 58
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 309
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 143

2023-07-11 17:37:57.8|Debug|ReleaseSearchService|Total of 0 reports were found for [REDACTEDSERIESNAME : S01] from 1 indexers
2023-07-11 17:37:57.8|Debug|ReleaseSearchService|Setting last search time to: 7/11/2023 10:37:57 PM
2023-07-11 17:37:57.8|Debug|IndexerFactory|Temporarily ignoring indexer BroadcastheNet till 7/11/2023 5:42:57 PM due to recent failures.
2023-07-11 17:37:57.8|Info|DownloadDecisionMaker|No results found
```

### Anything else?

The `BroadcastheNetParser.ParseResponse` method has a bug in how it interprets the `BroadcastheNetTorrents.Results` property. The `BroadcastheNetTorrents` class represents a page of search results. The `BroadcastheNetTorrents.Torrents` property is a dictionary containing the individual search results for the page. The `BroadcastheNetTorrents.Results` property is a number specifying the total number of search results. `BroadcastheNetParser.ParseResponse` wrongly interprets `BroadcastheNetTorrents.Results` as being the number of search results for the page, i.e. it considers it to be the same number as `BroadcastheNetTorrents.Torrents?.Count ?? 0`.

This means that the `if (jsonResponse.Result.Results == 0)` `if`-block is buggy. This `if`-block is meant to test whether the page of search results is empty, and if so, to skip processing `BroadcastheNetTorrents.Torrents`, which it would then expect to be `null`. When the total number of search results is nonzero and a multiple of the page size (e.g. 100, 200, 300...), the final page that `BroadcastheNetParser.ParseResponse` will process for the search will be empty, but the `if (jsonResponse.Result.Results == 0)` `if`-condition will be `false`, since `BroadcastheNetTorrents.Results` is the total number of search results. So `BroadcastheNetParser.ParseResponse` will continue on to process `BroadcastheNetTorrents.Torrents`, which is `null`, but the buggy code assumes it not to be `null` at this point. The code that causes the `NullReferenceException` is `foreach (var torrent in jsonResponse.Result.Torrents.Values)`.

Source link to buggy `if (jsonResponse.Result.Results == 0)` early-`return` `if`-block:
https://github.com/Sonarr/Sonarr/blob/96b7aa6585c76cbe1b9dd02bd8ec25ed8c929e28/src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetParser.cs#L53

Source link to `foreach (var torrent in jsonResponse.Result.Torrents.Values)` code that triggers the `NullReferenceException`:
https://github.com/Sonarr/Sonarr/blob/96b7aa6585c76cbe1b9dd02bd8ec25ed8c929e28/src/NzbDrone.Core/Indexers/BroadcastheNet/BroadcastheNetParser.cs#L60

## Recommended Fix
Change `if (jsonResponse.Result.Results == 0)` to `if ((jsonResponse.Result.Torrents?.Count ?? 0) == 0)`

**Comment by markus101** [comment]
This has already been fixed in develop. https://github.com/Sonarr/Sonarr/commit/45336389e6b08381b34d2b157c718a2e87c7b0e7
