### ISSUE TITLE
Jellyfin notification API changes

### ISSUE THREAD

**Issue by JeWe37** [Sonarr/Sonarr#5828]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

With jellyfin/jellyfin#9147 having been merged notifications will not be sent to Jellyfin properly anymore.

### Expected Behavior

This should likely be updated to use the Events API.

### Steps To Reproduce

1. Run the jellyfin/jellyfin:unstable docker container
2. Add a connection to it from Sonarr
3. Add something that would cause a notification
4. See that no notifications are sent

### Environment

```markdown
- OS: Irrelevant
- Sonarr: develop
- Docker Install: Irrelevant
- Using Reverse Proxy: Irrelevant
- Browser: Irrelevant
```

### What branch are you running?

Develop

### Trace Logs?

```
[v10.0.0.6501] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [POST] at [https://jellyfin.jendrik.malined.com:443/Notifications/Admin]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 108
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 318
   at NzbDrone.Core.Notifications.Emby.MediaBrowserProxy.ProcessRequest(HttpRequest request, MediaBrowserSettings settings) in ./Sonarr.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs:line 97
   at NzbDrone.Core.Notifications.Emby.MediaBrowserProxy.Notify(MediaBrowserSettings settings, String title, String message) in ./Sonarr.Core/Notifications/MediaBrowser/MediaBrowserProxy.cs:line 32
   at NzbDrone.Core.Notifications.Emby.MediaBrowserService.Notify(MediaBrowserSettings settings, String title, String message) in ./Sonarr.Core/Notifications/MediaBrowser/MediaBrowserService.cs:line 30
   at NzbDrone.Core.Notifications.Emby.MediaBrowser.OnEpisodeFileDelete(EpisodeDeleteMessage deleteMessage) in ./Sonarr.Core/Notifications/MediaBrowser/MediaBrowser.cs:line 54
   at NzbDrone.Core.Notifications.NotificationService.Handle(EpisodeFileDeletedEvent message) in ./Sonarr.Core/Notifications/NotificationService.cs:line 280
```

### Anything else?

Noticed while looking to prepare a PR for #5826.

**Comment by augustuen** [comment]
Are the changes this merge brings documented somewhere? I don't know what sort of time-frame we're looking at for these changes to come to stable JF, but if we want we might be able to do something akin to what we do with the qbittorrent API and support both versions.

**Comment by JeWe37** [comment]
I can't say I know. As things stand there is simply no functional notification functionality in the stable version. Jellyfin is a little slow with releases, this is probably best left as is for now. I just happened to notice this while testing other things, and figured that this was bound to become a problem in the future.

**Comment by JeWe37** [comment]
Also I dug around a little more, prior to the PR I mentioned apparently jellyfin/jellyfin#8952 was introduced, which cut out the part of the functionality that Sonarr actually uses.

**Comment by augustuen** [comment]
Well, if the notifications API has been removed entirely we could just yank those parts of the code out. It doesn't look like api.jellyfin.org has been updated with these changes, since it still refers to the notification endpoints. Feel free to hit me up on Discord to discuss more back-and-forth.

**Comment by JeWe37** [comment]
I'm guessing those are still present in Emby, so likely best kept around unchanged. The path based updates also still work(and are very useful if you have no inotify support) and are actually what got me here.
