### ISSUE TITLE
Importer sometimes fails to remove folder, gets stuck in activity queue

### ISSUE THREAD

**Issue by ch3vr0n5** [Sonarr/Sonarr#5937]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Periodically my queue increases with imports stuck in "Downloaded - Importing".
These are files that have already been moved/renamed but the item remains in the queue and the source folder on the disk.
I usually have select them all and force remove them, which also removes the source folder.

The exception in the log indicates that the folder is not empty when Sonarr attempts to remove it. 
When I check the folders manually, they are empty. `ls -a` doesn't show anything.
The log also indicates that the folder contains 0 video files before it attempts to remove it, and since the downloads in question contain nothing else, the folder should be empty and removable.

I suspect perhaps either NZBGet or Sonarr has a process that is still touching the folder for a moment that causes the error.

### Expected Behavior

This exception needs to be handled when attempting to remove a directory during DownloadedEpisodesImportService process, after the file has been moved. Perhaps include a delay to try again. Then place it in a different state other than "Downloaded - Importing" where Sonarr can then try again to clean up after itself automatically.

### Environment

```markdown
- OS: Unraid 6.12.2
- Sonarr: 3.0.10.1567
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 116.0.2
```

### What branch are you running?

Main

### Trace Logs?

2023-08-17 23:49:21.0|Debug|EpisodeFileMovingService|Moving episode file: /media/downloads/completed/Series/Billions.S07E02.1080p.WEB.h264-EDITH/5f34e347ab67494a80b353417ff1500c.mkv to /media/TV/Billions (2016) {imdb-tt4270492}/Season 07/Billions (2016) S07E02 Original Sin.mkv
2023-08-17 23:49:21.0|Debug|DiskTransferService|Move [/media/downloads/completed/Series/Billions.S07E02.1080p.WEB.h264-EDITH/5f34e347ab67494a80b353417ff1500c.mkv] > [/media/TV/Billions (2016) {imdb-tt4270492}/Season 07/Billions (2016) S07E02 Original Sin.mkv]
2023-08-17 23:49:21.1|Debug|EpisodeService|Linking [Season 07/Billions (2016) S07E02 Original Sin.mkv] > [[71936]Original Sin]
2023-08-17 23:49:21.2|Debug|DiskScanService|Scanning '/media/downloads/completed/Series/Billions.S07E02.1080p.WEB.h264-EDITH' for video files
2023-08-17 23:49:21.2|Debug|DiskScanService|0 video files were found in /media/downloads/completed/Series/Billions.S07E02.1080p.WEB.h264-EDITH
2023-08-17 23:49:21.2|Debug|DownloadedEpisodesImportService|Deleting folder after importing valid files
2023-08-17 23:49:21.2|Debug|DownloadProcessingService|Failed to process download: Billions.S07E02.1080p.WEB.h264-EDITH

[v3.0.10.1567] System.IO.IOException: Directory not empty
  at System.IO.FileSystem.RemoveDirectoryInternal (System.IO.DirectoryInfo directory, System.Boolean recursive, System.Boolean throwOnTopLevelDirectoryNotFound) [0x00114] in <d636f104d58046fd9b195699bcb1a744>:0 
  at System.IO.FileSystem.RemoveDirectory (System.String fullPath, System.Boolean recursive) [0x0000c] in <d636f104d58046fd9b195699bcb1a744>:0 
  at System.IO.Directory.Delete (System.String path, System.Boolean recursive) [0x00006] in <d636f104d58046fd9b195699bcb1a744>:0 
  at NzbDrone.Common.Disk.DiskProviderBase.DeleteFolder (System.String path, System.Boolean recursive) [0x00071] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:290 
  at NzbDrone.Core.MediaFiles.DownloadedEpisodesImportService.ProcessFolder (System.IO.DirectoryInfo directoryInfo, NzbDrone.Core.MediaFiles.EpisodeImport.ImportMode importMode, NzbDrone.Core.Tv.Series series, NzbDrone.Core.Download.DownloadClientItem downloadClientItem) [0x00136] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\DownloadedEpisodesImportService.cs:211 
  at NzbDrone.Core.MediaFiles.DownloadedEpisodesImportService.ProcessPath (System.String path, NzbDrone.Core.MediaFiles.EpisodeImport.ImportMode importMode, NzbDrone.Core.Tv.Series series, NzbDrone.Core.Download.DownloadClientItem downloadClientItem) [0x00034] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\DownloadedEpisodesImportService.cs:89 
  at NzbDrone.Core.Download.CompletedDownloadService.Import (NzbDrone.Core.Download.TrackedDownloads.TrackedDownload trackedDownload) [0x00045] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\CompletedDownloadService.cs:131 
  at NzbDrone.Core.Download.DownloadProcessingService.Execute (NzbDrone.Core.Download.ProcessMonitoredDownloadsCommand message) [0x00075] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\DownloadProcessingService.cs:65 

### Anything else?

![image](https://github.com/Sonarr/Sonarr/assets/987282/b2278cf1-879f-4ae0-b900-2430a4fac624)

**Comment by bakerboy448** [comment]
`sudo ls -lha /media/downloads/completed/Series/Billions.S07E02.1080p.WEB.h264-EDITH` ?

**Comment by ch3vr0n5** [comment]
> 

I spun up an instance of the develop branch, v4.0.0.630
The same thing already happened there:

```
2023-08-18 14:03:08.8|Debug|DiskScanService|Scanning '/media/downloads/completed/Series/doctor.who.2005.S00E83.50th.anniversary.special.1080p.bluray.x264-shortbrehd-BUYMORE' for video files
2023-08-18 14:03:08.8|Trace|DiskScanService|5 files were found in /media/downloads/completed/Series/doctor.who.2005.S00E83.50th.anniversary.special.1080p.bluray.x264-shortbrehd-BUYMORE
2023-08-18 14:03:08.8|Debug|DiskScanService|0 video files were found in /media/downloads/completed/Series/doctor.who.2005.S00E83.50th.anniversary.special.1080p.bluray.x264-shortbrehd-BUYMORE
2023-08-18 14:03:08.8|Debug|DownloadedEpisodesImportService|Deleting folder after importing valid files
2023-08-18 14:03:08.8|Debug|DownloadProcessingService|Failed to process download: doctor.who.2005.S00E83.50th.anniversary.special.1080p.bluray.x264-shortbrehd-BUYMORE

[v4.0.0.630] System.IO.IOException: Directory not empty : '/media/downloads/completed/Series/doctor.who.2005.S00E83.50th.anniversary.special.1080p.bluray.x264-shortbrehd-BUYMORE'
   at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at NzbDrone.Common.Disk.DiskProviderBase.DeleteFolder(String path, Boolean recursive) in ./Sonarr.Common/Disk/DiskProviderBase.cs:line 300
   at NzbDrone.Core.MediaFiles.DownloadedEpisodesImportService.ProcessFolder(DirectoryInfo directoryInfo, ImportMode importMode, Series series, DownloadClientItem downloadClientItem) in ./Sonarr.Core/MediaFiles/DownloadedEpisodesImportService.cs:line 215
   at NzbDrone.Core.MediaFiles.DownloadedEpisodesImportService.ProcessPath(String path, ImportMode importMode, Series series, DownloadClientItem downloadClientItem) in ./Sonarr.Core/MediaFiles/DownloadedEpisodesImportService.cs:line 90
   at NzbDrone.Core.Download.CompletedDownloadService.Import(TrackedDownload trackedDownload) in ./Sonarr.Core/Download/CompletedDownloadService.cs:line 145
   at NzbDrone.Core.Download.DownloadProcessingService.Execute(ProcessMonitoredDownloadsCommand message) in ./Sonarr.Core/Download/DownloadProcessingService.cs:line 64
```

**Comment by ch3vr0n5** [comment]
Didn't mean to close this...
