### ISSUE TITLE
Can't set "Enable RageID Lookup" value on Torznab Indexers

### ISSUE THREAD

**Issue by MangoScango** [Sonarr/Sonarr#599]
This is the error the log gives when you try, using 2.0.0.3212. Seems like a simple lack of casting.

Message
Request Failed: Object of type 'System.String' cannot be converted to type 'System.Boolean'.

Exception
System.ArgumentException: Object of type 'System.String' cannot be converted to type 'System.Boolean'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at NzbDrone.Api.ClientSchema.SchemaBuilder.ReadFormSchema(List`1 fields, Type targetType, Object defaults) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\ClientSchema\SchemaBuilder.cs:line 123
   at NzbDrone.Api.ProviderModuleBase`3.GetDefinition(TProviderResource providerResource, Boolean includeWarnings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\ProviderModuleBase.cs:line 113
   at NzbDrone.Api.ProviderModuleBase`3.UpdateProvider(TProviderResource providerResource) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\ProviderModuleBase.cs:line 91
   at NzbDrone.Api.REST.RestModule`1.<set_UpdateResource>b__14(Object options) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\REST\RestModule.cs:line 178
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by Taloth** [comment]
Hmm, thought I already fixed that when I worked on it. Maybe a merge error, I'll fix it on develop when I get to it.
Meanwhile, setting it to either 'true' or 'false' should allow it to be saved.

**Comment by MangoScango** [comment]
I don't understand what you mean, I can't set it to anything because this happens. Trying to set it to "false" was what gave me this error.

**Comment by Kayomani** [comment]
Your fix never made it in to master and isn't included in the last release.

**Comment by Taloth** [comment]
Actually, we  haven't release to master yet. The last two master versions were hotfixes.

**Comment by Kayomani** [comment]
That would explain it :)

**Comment by wesleyegbertsen** [comment]
This bug is still present, will this be fixed?

**Comment by Taloth** [comment]
Sry guys, still no master release. That's a good thing coz we had some potentially unstable stuff in develop. 
Soon (tm)
