### ISSUE TITLE
Sonarr causing System Crash

### ISSUE THREAD

**Issue by sameep22** [Sonarr/Sonarr#6100]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hi all,

I would like to apologise in advance if this is not the right place to report this. However, I have searched online, and don't fully understand the problem. Also, though, I am not uncomfortable with some minor tinkering, I am no expert.

At random intervals, usually in the process of importing files from the download directory, the docker container of sonarr hangs. This for some reason, then locks up the entire system, and there is no other way except to manually restart the system. I am not sure, but looking at some logs, it seems that the CPU cores are also locking up. 

I have noticed this behaviour only since I upgraded to sonarr v4. 

I am not sure which logs would help find the root cause of this problem. However, this is what I see on sonarr

### Expected Behavior

Even if sonarr crashes, it should automatically restart, without affecting the system

### Steps To Reproduce

Happens at seemingly random intervals

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS / Docker version 24.0.6, build ed223bc
- Sonarr: v4
```

### What branch are you running?

Develop

### Trace Logs?

[Info] DiskScanService: Completed scanning disk for Succession 
[Info] ExistingMetadataImporter: Found 0 existing metadata files 
[Info] ExistingSubtitleImporter: Found 0 existing subtitle files 
[Info] ExistingOtherExtraImporter: Found 0 existing other extra files 
[Info] ExistingExtraFileService: Found 1 possible extra files, imported 1 files. 
[Info] RefreshSeriesService: Skipping refresh of series: Swat Kats: The Radical Squadron 
[Info] DiskScanService: Scanning Swat Kats: The Radical Squadron 
[Info] DiskScanService: Completed scanning disk for Swat Kats: The Radical Squadron 
[Info] ExistingMetadataImporter: Found 0 existing metadata files 
[Info] ExistingSubtitleImporter: Found 0 existing subtitle files 
[Info] ExistingOtherExtraImporter: Found 0 existing other extra files 
[Info] ExistingExtraFileService: Found 1 possible extra files, imported 1 files. 
[Info] RefreshSeriesService: Updating Taj: Divided by Blood 
[Info] RefreshEpisodeService: Starting episode info refresh for: [431276][Taj: Divided by Blood] 
[Info] RefreshEpisodeService: Finished episode refresh for series: [431276][Taj: Divided by Blood]. 
[Info] DiskScanService: Scanning Taj: Divided by Blood 
[Info] DiskScanService: Completed scanning disk for Taj: Divided by Blood 
[Info] ExistingMetadataImporter: Found 0 existing metadata files 
[Info] ExistingSubtitleImporter: Found 0 existing subtitle files 
[Info] ExistingOtherExtraImporter: Found 0 existing other extra files 
[Info] ExistingExtraFileService: Found 1 possible extra files, imported 1 files. 
[Info] RefreshSeriesService: Skipping refresh of series: Tandav 
[Info] DiskScanService: Scanning Tandav 
[Info] DiskScanService: Completed scanning disk for Tandav 
[Info] ExistingMetadataImporter: Found 0 existing metadata files 
[Info] ExistingSubtitleImporter: Found 0 existing subtitle files 
[Info] ExistingOtherExtraImporter: Found 0 existing other extra files 
[Info] ExistingExtraFileService: Found 1 possible extra files, imported 1 files. 
[Info] RefreshSeriesService: Skipping refresh of series: Tom and Jerry 
[Info] DiskScanService: Scanning Tom and Jerry 
[Info] ReleasePushController: Release pushed: Good Luck Charlie S04E07 XviD-AFG - https://ipt.cool/download.php/5557783/Good+Luck+Charlie+S04E07+XviD-AFG.torrent?torrent_pass=xxx 
[Info] DownloadDecisionMaker: Processing 1 releases 
[Info] ReleasePushController: Release pushed: The Next Marijuana Millionaire S01E08 480p x264-mSD - https://ipt.cool/download.php/5557786/The+Next+Marijuana+Millionaire+S01E08+480p+x264-mSD.torrent?torrent_pass=xxx 
[Info] DownloadDecisionMaker: Processing 1 releases 
[Info] ReleasePushController: Release pushed: John Carpenters Suburban Screams S01E06 XviD-AFG - https://ipt.cool/download.php/5557788/John+Carpenters+Suburban+Screams+S01E06+XviD-AFG.torrent?torrent_pass=xxx 
[Info] DownloadDecisionMaker: Processing 1 releases 
[Info] ReleasePushController: Release pushed: The Next Marijuana Millionaire S01E09 480p x264-mSD - https://ipt.cool/download.php/5557790/The+Next+Marijuana+Millionaire+S01E09+480p+x264-mSD.torrent?torrent_pass=xxx 
[Info] DownloadDecisionMaker: Processing 1 releases 
[Info] ReleasePushController: Release pushed: The Next Marijuana Millionaire S01E07 480p x264-mSD - https://ipt.cool/download.php/5557792/The+Next+Marijuana+Millionaire+S01E07+480p+x264-mSD.torrent?torrent_pass=xxx 
[Info] DownloadDecisionMaker: Processing 1 releases 
[Info] ReleaseSearchService: Searching indexers for [Gen V : S01E05]. 4 active indexers 
[Info] ReleasePushController: Release pushed: The Next Marijuana Millionaire S01E06 480p x264-mSD - https://ipt.cool/download.php/5557793/The+Next+Marijuana+Millionaire+S01E06+480p+x264-mSD.torrent?torrent_pass=xxx 
[Info] DownloadDecisionMaker: Processing 1 releases 
[Warn] Torznab: Unable to connect to indexer, possibly due to a timeout. http://192.168.1.152:9696/2/api?t=tvsearch&cat=5000,5040,5030&extended=1&apikey=xxx&offset=0&limit=100&q=Generation%20V&season=1&ep=5 
[v4.0.0.697] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Sonarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 105
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Sonarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 359
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 334
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 160
[Warn] Torznab: Unable to connect to indexer, possibly due to a timeout. http://192.168.1.152:9696/4/api?t=tvsearch&cat=5000,5050,5040,5045&extended=1&apikey=xxx&offset=0&limit=100&q=Generation%20V&season=1&ep=5 
[v4.0.0.697] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Sonarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 105
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Sonarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 359
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 334
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 160
[Warn] Torznab: Unable to connect to indexer, possibly due to a timeout. http://192.168.1.152:9696/8/api?t=tvsearch&cat=5000&extended=1&apikey=xxx&offset=0&limit=100&q=Generation%20V&season=1&ep=5 
[v4.0.0.697] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Sonarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 105
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Sonarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 359
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 334
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 160

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Your logs don't show anything related to an import (just a network request failing).

Sonarr in a docker container is compartmentalized and should be unable to affect the host system itself, but seems plausible that a hardware issue is leading to these issues. Memory is usually a good place to start (memtest86), but since it's around the import time potentially it's storage related.
