### ISSUE TITLE
Plex watchlist import not working (Each item in the RSS feed must have a guid element with a TVDB ID)

### ISSUE THREAD

**Issue by as367** [Sonarr/Sonarr#6105]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sonarr cannot import Plex Watchlist RSS. This message appears in the event log:

Import list feed is not supported: Each item in the RSS feed must have a guid element with a TVDB ID

### Expected Behavior

Sonarr should import the Plex RSS list. 

### Steps To Reproduce

If this item is present in the Plex RSS XML the error will occur:

```
<item>
      <title>The Wheel of Time: Origins (2021)</title>
      <pubDate>Thu, 12 Oct 2023 22:45:26 GMT</pubDate>
      <link>https://watch.plex.tv/show/the-wheel-of-time-origins</link>
      <description>Experience the Origin Stories of the Wheel of Time as they bring you deeper into the world and its vast history and subjects.</description>
      <category>show</category>
      <media:credit role="actor">Ida May</media:credit>
      <media:credit role="actor">Rupert Degas</media:credit>
      <media:credit role="actor">Steven Hartley</media:credit>
      <media:credit role="actor">Evelyn Miller</media:credit>
      <media:credit role="director">Dan DiFelice</media:credit>
      <media:credit role="producer">Jakub Chilczuk</media:credit>
      <media:credit role="producer">Rory Knight-Jones</media:credit>
      <media:credit role="writer">Rammy Park</media:credit>
      <media:thumbnail url="https://images.plex.tv/photo?url=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2F4LMvwHuBP7NKyUiMTpq4yY21s5T.jpg"/>
      <media:keywords>animation, drama, fantasy</media:keywords>
      <media:rating scheme="urn:v-chip">tv-14</media:rating>
      <guid isPermaLink="false">imdb://tt16358754</guid>
    </item>
```

### Environment

```markdown
- OS: MacOS 14
- Sonarr: 4.0.0.697
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox 118
- Database: Sqlite 3.36.0
```

### What branch are you running?

Develop

### Trace Logs?

[v4.0.0.697] NzbDrone.Core.Indexers.Exceptions.UnsupportedFeedException: Each item in the RSS feed must have a guid element with a TVDB ID
   at NzbDrone.Core.ImportLists.Rss.Plex.PlexRssImportParser.ProcessItem(XElement item) in ./Sonarr.Core/ImportLists/Rss/Plex/PlexRssImportParser.cs:line 39
   at NzbDrone.Core.ImportLists.Rss.RssImportBaseParser.ParseResponse(ImportListResponse importResponse) in ./Sonarr.Core/ImportLists/Rss/RssImportBaseParser.cs:line 42
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in ./Sonarr.Core/ImportLists/HttpImportListBase.cs:line 185
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in ./Sonarr.Core/ImportLists/HttpImportListBase.cs:line 246

2023-10-15 01:40:00.0|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IImportList>
2023-10-15 01:40:00.0|Trace|SonarrErrorPipeline|Handling Exception
2023-10-15 01:40:00.0|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Import list feed is not supported: Each item in the RSS feed must have a guid element with a TVDB ID
2023-10-15 01:40:00.0|Trace|Http|Res: 2416 [POST] /api/v3/importlist/test: 400.BadRequest (793 ms)
2023-10-15 01:40:00.0|Debug|Api|[POST] /api/v3/importlist/test: 400.BadRequest (793 ms)
2023-10-15 01:40:03.4|Trace|Http|Req: 2417 [GET] /api/v3/health (from 127.0.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0)
2023-10-15 01:40:03.4|Trace|Http|Res: 2417 [GET] /api/v3/health: 200.OK (1 ms)
2023-10-15 01:40:03.4|Trace|Http|Req: 2418 [GET] /api/v3/diskspace (from 127.0.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0)

### Anything else?

This issue appears to be the same as reported at the radarr project here:

https://github.com/Radarr/Radarr/issues/9208

**Comment by drondeseries** [comment]
Please add support for TMDB in Plex Watchlist RSS.
<item>
<title>Kitchen Nightmares (2023)</title>
<pubDate>Sat, 11 Nov 2023 15:08:46 GMT</pubDate>
<link>https://watch.plex.tv/show/kitchen-nightmares</link>
<description>Chef Gordon Ramsay hits the road to help struggling restaurants all over the United States turn their luck around. Ramsay examines the problems each establishment faces, from unsanitary refrigerators to lazy or inexperienced staff, and searches for resolutions. With help from his team, Ramsay redecorates each eatery to give it a fresh new look and updates the menu as needed. Ramsay's ultimate goal is to make the restaurants he visits popular and profitable, but it's up to the restaurateurs to take his advice and turn their business nightmare into the American dream.</description>
<category>show</category>
<media:credit role="actor">Gordon Ramsay</media:credit>
<media:credit role="director">Paul Newton</media:credit>
<media:credit role="producer">Jessica Bertulis</media:credit>
<media:credit role="producer">Javi Sulaiman</media:credit>
<media:credit role="producer">Rachel Job</media:credit>
<media:credit role="producer">Gordon Ramsay</media:credit>
<media:credit role="producer">David De Angelis</media:credit>
<media:thumbnail url="https://images.plex.tv/photo?url=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2F7A1oUuJzIj3Wb3wGnLmrefZKxdb.jpg"/>
<media:keywords>reality</media:keywords>
<media:rating scheme="urn:v-chip">tv-14</media:rating>
<guid isPermaLink="false">tmdb://235884</guid>
</item>
