### ISSUE TITLE
Sonarr v4 in Kubernetes can't resolve PostgresHost

### ISSUE THREAD

**Issue by ppoloskov** [Sonarr/Sonarr#6225]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm running Sonarr v.4.0.0.733 in k3s Kubernetes. My config is trivial:
```
<Config>
    <UrlBase>/sonarr</UrlBase>
    <PostgresPort>5432</PostgresPort>
    <PostgresUser>sonarr</PostgresUser>
    <PostgresPassword>s0narr</PostgresPassword>
    <PostgresHost>postgres.db.svc.cluster.local</PostgresHost>
    <PostgresMainDb>sonarrdb</PostgresMainDb>
    <PostgresLogDb>sonarrlogsdb</PostgresLogDb>
</Config>
```

When I start Sonarr I receive following error (see below). However, I installed `pgcli` in the same container and was able to connect to the database using the same credentials. 
```
/ # pgcli -p 5432 -u sonarr -h postgres.db.svc.cluster.local sonarrdb
Password for sonarr: 
Server: PostgreSQL 14.0
Version: 3.5.0
Home: http://pgcli.com
sonarr@postgres:sonarrdb>
```

The only way to connect from Sonarr to the DB is to setup DB service as LoadBalancer and connect via DB ip address.
Update: 
1. I ran tcpdump and there're no attempts to connect to the port 5432 or relevant dns lookups
2. Looks like system wants a "real" domain name. For example, it tries to connect to <PostgresHost>google.com</PostgresHost>, but fails as below on whatever.home.arpa or kube's standard postgres.db.svc.cluster.local or postgres.db

### Expected Behavior

Sonarr is able to connect to the DB.

### Environment

```markdown
- OS: k3s
- Sonarr: 4.0.0.733
- Docker Install: Kubernetes, cr.hotio.dev/hotio/sonarr:nightly
- Using Reverse Proxy: N/A
- Browser: N/A
- Database: Postgres 14 and 16
```

### What branch are you running?

Develop

### Trace Logs?

LogLevel makes no difference.

```
/ # /app/bin/Sonarr --data=/config
[Info] Bootstrap: Starting Sonarr - /app/bin/Sonarr - Version 4.0.0.733 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] MigrationController: *** Migrating Database=sonarr-main;Host=postgres.db.svc.cluster.local;Username=sonarr;Password=s0narr;Port=5432;Enlist=False *** 


[Fatal] ConsoleApp: EPIC FAIL! 

[v4.0.0.733] NzbDrone.Common.Exceptions.SonarrStartupException: Sonarr failed to start: Error creating main database
 ---> System.ArgumentException: Data Source cannot be empty.  Use :memory: to open an in-memory database
   at System.Data.SQLite.SQLiteConnection.Open()
   at FluentMigrator.Runner.Processors.GenericProcessorBase.<>c__DisplayClass6_1.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at FluentMigrator.Runner.Processors.GenericProcessorBase.get_Connection()
   at FluentMigrator.Runner.Processors.GenericProcessorBase.EnsureConnectionIsOpen()
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Exists(String template, Object[] args)
   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.TableExists(String schemaName, String tableName)
   at FluentMigrator.Runner.VersionLoader.get_AlreadyCreatedVersionTable()
   at FluentMigrator.Runner.VersionLoader.LoadVersionInfo()
   at FluentMigrator.Runner.VersionLoader..ctor(IProcessorAccessor processorAccessor, IConventionSet conventionSet, IMigrationRunnerConventions conventions, IVersionTableMetaData versionTableMetaData, IMigrationRunner runner)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.FluentMigratorServiceCollectionExtensions.<>c.<AddFluentMigratorCore>b__0_6(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at FluentMigrator.Runner.MigrationRunner.get_VersionLoader()
   at FluentMigrator.Runner.MigrationRunner.IsMigrationStepNeededForUpMigration(IMigrationInfo migration, Int64 targetVersion)
   at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass60_0.<GetUpMigrationsToApply>b__0(KeyValuePair`2 pair)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
   at FluentMigrator.Runner.MigrationRunner.MigrateUp()
   at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext) in ./Sonarr.Core/Datastore/Migration/Framework/MigrationController.cs:line 79
   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in ./Sonarr.Core/Datastore/DbFactory.cs:line 116
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext) in ./Sonarr.Core/Datastore/DbFactory.cs:line 164
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in ./Sonarr.Core/Datastore/DbFactory.cs:line 71
   at NzbDrone.Core.Datastore.DbFactory.Create(MigrationType migrationType) in ./Sonarr.Core/Datastore/DbFactory.cs:line 59
   at NzbDrone.Core.Datastore.Extensions.CompositionExtensions.<>c.<AddDatabase>b__0_0(IDbFactory f) in ./Sonarr.Core/Datastore/Extensions/CompositionExtensions.cs:line 10
   at DryIoc.Registrator.ToFuncWithObjParams[D1,TService](Func`2 f, Object d1) in /_/src/DryIoc/Container.cs:line 8046
   at DryIoc.Interpreter.TryInterpretFuncInvoke(IResolverContext r, MethodCallExpression e, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3706
   at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, MethodCallExpression callExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3504
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3155
   at DryIoc.Interpreter.TryInterpretSingletonAndUnwrapContainerException(IResolverContext r, Expression expr, ImMapEntry`1 itemRef, Object& result) in /_/src/DryIoc/Container.cs:line 3084
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 11110
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11029
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 12056
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11012
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 12056
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11012
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 12056
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11012
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 423
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 389
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 8581
   at Sonarr.Http.ClientSchema.SchemaBuilder.Initialize(IContainer container) in ./Sonarr.Http/ClientSchema/SchemaBuilder.cs:line 24
   at NzbDrone.Host.Bootstrap.<>c__DisplayClass3_0.<CreateConsoleHostBuilder>b__2(IContainer c) in ./Sonarr.Host/Bootstrap.cs:line 150
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass10_0`1.<ConfigureContainer>b__0(HostBuilderContext context, TContainerBuilder builder)
   at Microsoft.Extensions.Hosting.Internal.ConfigureContainerAdapter`1.ConfigureContainer(HostBuilderContext hostContext, Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in ./Sonarr.Host/Bootstrap.cs:line 80
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in ./Sonarr.Console/ConsoleApp.cs:line 45
```

**Comment by bakerboy448** [comment]
-database name doesn't appear to be getting picked up from the config file
- wonder if the .db in the url is causing issues
- Appears it's falling back to SQLite

**Comment by ppoloskov** [comment]
> -database name doesn't appear to be getting picked up from the config file
> - wonder if the .db in the url is causing issues
> - Appears it's falling back to SQLite

No, it's not the db part. I've tried to remove it. Looks like it's a top level domain

**Comment by Qstick** [comment]
This line is the issue

```
var db = connectionString.Contains(".db") ? "sqlite" : "postgres";
```

Your host name tricks Sonarr into thinking it's SQLite
