### ISSUE TITLE
Sonarr cannot handle incomplete video files for manual import

### ISSUE THREAD

**Issue by PythonCoderAS** [Sonarr/Sonarr#6293]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Sometimes, I download a torrent of an entire season just to upgrade 2-3 episodes in the season, so in the download client I uncheck the episodes I already have. However, this leads to the download client filling in those files with zero bytes, which then crashes the manual importer.

### Expected Behavior

Invalid files should be ignored or all values should be completely blanked

### Steps To Reproduce

1. Download an entire season torrent
2. Wait 30 seconds
3. Uncheck some episodes

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.0.749
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome 120
- Database: PostgreSQL 16
```

### What branch are you running?

Develop

### Trace Logs?

```
2024-01-02 15:49:42.6|Error|VideoFileInfoReader|Unable to parse media info from file: /data/downloads/tv-sonarr/2160p/Jujutsu Kaisen (2020) S02E12.4k.h264.mkv

[v4.0.0.749] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - [matroska,webm @ 0x2ea16c0] 0x00 at pos 0 (0x0) invalid as first byte of an EBML number
[matroska,webm @ 0x2ea16c0] EBML header parsing failed
/data/downloads/tv-sonarr/2160p/Jujutsu Kaisen (2020) S02E12.4k.h264.mkv: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Sonarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140

2024-01-02 15:49:45.5|Error|DetectSample|Failed to get runtime from the file, make sure ffprobe is available
2024-01-02 15:49:45.7|Error|VideoFileInfoReader|Unable to parse media info from file: /data/downloads/tv-sonarr/2160p/Jujutsu Kaisen (2020) S02E12.4k.h264.mkv

[v4.0.0.749] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - [matroska,webm @ 0x2ab66c0] 0x00 at pos 0 (0x0) invalid as first byte of an EBML number
[matroska,webm @ 0x2ab66c0] EBML header parsing failed
/data/downloads/tv-sonarr/2160p/Jujutsu Kaisen (2020) S02E12.4k.h264.mkv: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Sonarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140

2024-01-02 15:49:45.8|Error|VideoFileInfoReader|Unable to parse media info from file: /data/downloads/tv-sonarr/2160p/Jujutsu Kaisen (2020) S02E12.4k.h264.mkv

[v4.0.0.749] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - [matroska,webm @ 0x33aa6c0] 0x00 at pos 0 (0x0) invalid as first byte of an EBML number
[matroska,webm @ 0x33aa6c0] EBML header parsing failed
/data/downloads/tv-sonarr/2160p/Jujutsu Kaisen (2020) S02E12.4k.h264.mkv: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Sonarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140

2024-01-02 15:49:45.8|Error|DetectSample|Failed to get runtime from the file, make sure ffprobe is available
2024-01-02 15:49:47.4|Error|VideoFileInfoReader|Unable to parse media info from file: /data/downloads/tv-sonarr/2160p/Jujutsu Kaisen (2020) S02E07.4k.h264.mkv

[v4.0.0.749] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - [matroska,webm @ 0x36846c0] 0x00 at pos 0 (0x0) invalid as first byte of an EBML number
[matroska,webm @ 0x36846c0] EBML header parsing failed
/data/downloads/tv-sonarr/2160p/Jujutsu Kaisen (2020) S02E07.4k.h264.mkv: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Sonarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140

2024-01-02 15:49:47.4|Error|DetectSample|Failed to get runtime from the file, make sure ffprobe is available
2024-01-02 15:49:47.5|Error|VideoFileInfoReader|Unable to parse media info from file: /data/downloads/tv-sonarr/2160p/Jujutsu Kaisen (2020) S02E07.4k.h264.mkv

[v4.0.0.749] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - [matroska,webm @ 0x35e96c0] 0x00 at pos 0 (0x0) invalid as first byte of an EBML number
[matroska,webm @ 0x35e96c0] EBML header parsing failed
/data/downloads/tv-sonarr/2160p/Jujutsu Kaisen (2020) S02E07.4k.h264.mkv: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Sonarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140

2024-01-02 15:49:47.6|Error|VideoFileInfoReader|Unable to parse media info from file: /data/downloads/tv-sonarr/2160p/Jujutsu Kaisen (2020) S02E07.4k.h264.mkv

[v4.0.0.749] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - [matroska,webm @ 0x21d66c0] 0x00 at pos 0 (0x0) invalid as first byte of an EBML number
[matroska,webm @ 0x21d66c0] EBML header parsing failed
/data/downloads/tv-sonarr/2160p/Jujutsu Kaisen (2020) S02E07.4k.h264.mkv: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in ./Sonarr.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs:line 140

2024-01-02 15:49:47.6|Error|DetectSample|Failed to get runtime from the file, make sure ffprobe is available
```

**Comment by thezoggy** [comment]
why you telling it to manually import files that arent ready to be imported?

**Comment by markus101** [comment]
> However, this leads to the download client filling in those files with zero bytes, which then crashes the manual importer.

What exactly do you mean by this? If manual import is failing to load and shows and error then please post the _trace_ logs of the full request/response so we can see.

Just getting an error in the logs if the file is invalid is expected though.

**Comment by bakerboy448** [comment]
Sounds like the client is configured to pre-allocate the files or pre-create them.  OP is downloading a season pack and unchecked most all except a few specific files to download and the import - unclear if auto or manual...could be auto with the torrent reporting 100% - fails due to the pre-allocated 0 byte files

**Comment by markus101** [comment]
I've tested with a 0 byte file that has a `.mkv` extension and otherwise appears like a valid file in the release and Sonarr is unable to determine if it's a sample because ffprobe fails, but Manual Import opens correctly and I can see that it was correctly rejected.

In the case of a partial season pack you'll need to tell Sonarr to ignore the rest of the episode files because Sonarr will not treat a partially imported season pack as complete even if you select only some of the files.

**Comment by PythonCoderAS** [comment]
> why you telling it to manually import files that arent ready to be imported?

This is because the torrent has very ambiguous file names (folder was "2160p") and because I had two torrents that had the same folder name (two different torrents both called "2160p" so the two sets of files from different torrents got shoved into the same folder). The error in particular was a 504 Gateway Timeout.
