### ISSUE TITLE
System.Text.Json.JsonException on launch when running into 0x0A

### ISSUE THREAD

**Issue by TChilderhose** [Sonarr/Sonarr#6313]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When launching Sonarr an exception is being thrown

```
---> System.Text.Json.JsonException: '0x0A' is invalid within a JSON string. The string should be correctly escaped. Path: $[1] | LineNumber: 14 | BytePositionInLine: 9.
 ---> System.Text.Json.JsonReaderException: '0x0A' is invalid within a JSON string. The string should be correctly escaped. LineNumber: 14 | BytePositionInLine: 9.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumePropertyName()
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
```

I have tried rolling back to older `4.0.0.X` builds but the result is the same. My guess is that some info for `Judi Love` was changed on TVDB or something that triggered it. I know `0x0A` is new line, so not sure where in the pipeline encoding messed up to cause the issue.

### Expected Behavior

Handle/ignore the exception or try tweaking encoding or maybe regex replace?

### Environment

```markdown
- OS: Unraid 6.12.6
- Sonarr: 4.0.0.752
- Docker Install: Yes
- Using Reverse Proxy: Yes (nginx)
- Browser: Chrome 120.0.6099.131
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/13851219/sonarr.trace.txt)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Your DB is partially corrupt
