### ISSUE TITLE
Email notification attempts TLS negotiation even when setting is disabled

### ISSUE THREAD

**Issue by aureq** [Sonarr/Sonarr#6380]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm trying to configure Sonarr to send emails to my local SMTP server. Since the SMTP server is local, it doesn't have a TLS certificate. So, in the settings page for that service, I haven't checked the `Require Encryption` checkbox.

However, it fails when I test the service and the console shows the following error.

Expectedly, Postfix complains about receiving a `STARTTLS` command.

```
[v4.0.0.748] MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The host name did not match the name given in the server's SSL certificate.

 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at NzbDrone.Core.Notifications.Email.Email.Send(MimeMessage email, EmailSettings settings) in ./Sonarr.Core/Notifications/Email/Email.cs:line 152
   at NzbDrone.Core.Notifications.Email.Email.SendEmail(EmailSettings settings, String subject, String body, Boolean htmlBody) in ./Sonarr.Core/Notifications/Email/Email.cs:line 116
   at NzbDrone.Core.Notifications.Email.Email.Test(EmailSettings settings) in ./Sonarr.Core/Notifications/Email/Email.cs:line 178

[Warn] SonarrErrorPipeline: Invalid request Validation failed:
 -- Server: Unable to send test email
```

![image](https://github.com/Sonarr/Sonarr/assets/1161681/41e07577-bda9-43ef-9acb-99fe9bac743c)

Postfix logs
```
Jan 19 07:44:29 mail postfix/smtpd[7307]: connect from 10-42-0-173.sonarr.home-services.svc.cluster.local[10.42.0.173]
Jan 19 07:44:29 mail postfix/smtpd[7307]: lost connection after STARTTLS from 10-42-0-173.sonarr.home-services.svc.cluster.local[10.42.0.173]
Jan 19 07:44:29 mail postfix/smtpd[7307]: disconnect from 10-42-0-173.sonarr.home-services.svc.cluster.local[10.42.0.173] ehlo=1 starttls=1 commands=2
```

### Expected Behavior

Sonarr shouldn't attempt to initiate a TLS connection when the setting isn't active.

### Steps To Reproduce

1. Install Sonarr
2. Have a valid SMTP server running
3. Add a new notification service
4. Do not check the `Require Encryption` setting
5. Try to validate the settings

You should get a failure at step 5.

### Environment

```markdown
- OS: Linux, Debian
- Sonarr: v4.0.0.748
- Docker Install: Kubernetes
- Using Reverse Proxy: Nginx
- Browser: FF
- Database: Sqlite 3.40.1 (as provided by Debian)
```

### What branch are you running?

Main

### Trace Logs?

```
2024-01-19 08:12:37.0|Trace|Http|Req: 796 [POST] /sonarr/api/v3/notification/test (from 192.168.2.2 Mozilla/5.0 (Windows NT 10.0; rv:121.0) Gecko/20100101 Firefox/121.0)
2024-01-19 08:12:37.0|Debug|Email|Sending email Subject: Sonarr - Test Notification
2024-01-19 08:12:37.0|Debug|Email|Connecting to mail server
2024-01-19 08:12:37.6|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2024-01-19 08:12:37.6|Error|X509CertificateValidationService|Certificate validation for smtp.mail-services.svc failed. RemoteCertificateNameMismatch, RemoteCertificateChainErrors
2024-01-19 08:12:37.6|Error|Email|Error sending email. Subject: Sonarr - Test Notification
2024-01-19 08:12:37.6|Debug|Email|An error occurred while attempting to establish an SSL or TLS connection.

The host name did not match the name given in the server's SSL certificate.


[v4.0.0.748] MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The host name did not match the name given in the server's SSL certificate.

 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at NzbDrone.Core.Notifications.Email.Email.Send(MimeMessage email, EmailSettings settings) in ./Sonarr.Core/Notifications/Email/Email.cs:line 152
   at NzbDrone.Core.Notifications.Email.Email.SendEmail(EmailSettings settings, String subject, String body, Boolean htmlBody) in ./Sonarr.Core/Notifications/Email/Email.cs:line 116

2024-01-19 08:12:37.6|Error|Email|Unable to send test email

[v4.0.0.748] MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The host name did not match the name given in the server's SSL certificate.

 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at NzbDrone.Core.Notifications.Email.Email.Send(MimeMessage email, EmailSettings settings) in ./Sonarr.Core/Notifications/Email/Email.cs:line 152
   at NzbDrone.Core.Notifications.Email.Email.SendEmail(EmailSettings settings, String subject, String body, Boolean htmlBody) in ./Sonarr.Core/Notifications/Email/Email.cs:line 116
   at NzbDrone.Core.Notifications.Email.Email.Test(EmailSettings settings) in ./Sonarr.Core/Notifications/Email/Email.cs:line 178

2024-01-19 08:12:37.6|Trace|SonarrErrorPipeline|Handling Exception
2024-01-19 08:12:37.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Server: Unable to send test email
2024-01-19 08:12:37.6|Trace|Http|Res: 796 [POST] /sonarr/api/v3/notification/test: 400.BadRequest (563 ms)
```

### Anything else?

This used to work in v3 since I had the notification previously saved. I removed the notification service and attempted to recreate but no success.

**Comment by markus101** [comment]
I missed that it worked in v3, but not not working in v4. The behaviour between v3 and v4 is the same. If requires encryption is enabled encryption is always use, otherwise it attempts to encrypt the connection and falls back to none if not configured on the mail server.

The documentation is:

> Allow the [IMailService](http://www.mimekit.net/docs/html/T_MailKit_IMailService.htm) to decide which SSL or TLS options to use (default). If the server does not support SSL or TLS, then the connection will continue without any encryption.

In this case your server appears to support for a secure connection, but fails validation with your settings. I'm not sure if the validation is also controlled by `Certificate Validation` in Settings: General: Security, but possibly that's different between v3 and v4 in your setup.

**Comment by bakerboy448** [comment]
Downstream bug and comment with workaround https://github.com/Radarr/Radarr/issues/7174#issuecomment-1086649511

**Comment by aureq** [comment]
@markus101 Thanks a lot for your reply. A few more information.

You're 100% right, my SMTP server returns `250-STARTTLS` in the `EHLO` command. So it clearly advertise TLS is available. Furthermore, it's a self-signed certificate so validation will fail.

That said though, since the setting `Require Encryption` isn't ticked, I was under the impression Sonarr wouldn't do the check at all.
Looking at the code `auto` is used in the code https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Notifications/Email/Email.cs#L137-L149. Should this be set the appropriate value to indicate no TLS negotiation should be attempted?

**Comment by bakerboy448** [comment]
That is the same fix I suggested downstream; don't use auto by default and do it based on the checkbox

**Comment by markus101** [comment]
Auto determines whether encryption should be used or not based on the mail server's configuration. Requiring encryption requires encryption whether the server is properly configured for it or not as well as supports servers that have unencrypted connections disabled (Gmail IIRC). If the server does not claim to support encryption when it's not properly configured then automatically determining should have no negative impact.

For existing users changing from `auto` to `none` when requires encryption is disabled could break connections that are auto negotiating properly or convert what were previously secure connections to insecure connections.

**Comment by aureq** [comment]
I fix my SMTP configuration and it uses a properly issued certificate. And while using the SMTP internal hostname, I disabled the `Certficate Validation` setting for local addresses and it works. So I have a workaround (though not very secure).

That said, if the `Require Encryption` could have 3 states (yes, no, auto), instead of 2 that would be great. The reason is because, my SMTP server as seen from the internet advertise the STARTTLS. However, when accessed internally, the hostname set in Sonarr setting won't match the Name set in the certificate (the public hostname isn't accessible from the inside). This would allow the global setting to remain enabled, and the STARTTLS nego to be disabled within Sonarr.

Maybe something similar to https://css-tricks.com/indeterminate-checkboxes/

Though, I do understand this creates more work for the maintainers (happy to help if there's an interest to get this implemented).

**Comment by markus101** [comment]
> So I have a workaround (though not very secure).

That really depends on what else you're running over secure connections on your local network and how much you trust the devices on that network, but probably avoidable as well.

> The reason is because, my SMTP server as seen from the internet advertise the STARTTLS. However, when accessed internally, the hostname set in Sonarr setting won't match the Name set in the certificate (the public hostname isn't accessible from the inside). 

Would split DNS not resolve this? That's the common way to treat DNS inside the network separately from external and you can use the same hostname on both sides without issue.

Converting it a drop down with three options is what I was in the middle of when I responded. Using an indeterminate checkbox for that would be pretty awkward UX though.

**Comment by aureq** [comment]
I saw the pull request, thank you @markus101 I agree that the drop down looks better.

The issue I currently have is not DNS but routing. I run sonaar and a mail server inside kubernetes. The SMTP service should be accessible via the deployment load balancer, but unfortunately that service isn't available from inside the cluster. If it was, the TLS certificate validation would work perfectly well.
