### ISSUE TITLE
Upgrade from 933 -> 953 fails with `System.OverflowException: Value was either too large or too small for an Int32.`

### ISSUE THREAD

**Issue by sjdaws** [Sonarr/Sonarr#6409]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When using the latest develop there is an issue with the sub migration which causes Sonarr to fail on startup. 

I can confirm rolling back to 933 has fixed the issue. Deleting the last subtitle file shown in the log did not fix the issue.

### Expected Behavior

Sonarr should start as normal

### Environment

```markdown
- OS: openSUSE Tumbleweed
- Sonarr: 4.0.1.953 (4.0.1-develop tag via linuxserver)
- Docker Install: Yes
- Using Reverse Proxy: N/A
- Browser: N/A
- Database: Unknown
```

### What branch are you running?

Develop

### Trace Logs?

```
+ sonarr sonarr-0 › sonarr
sonarr sonarr-0 sonarr [migrations] started
sonarr sonarr-0 sonarr [migrations] no migrations found
sonarr sonarr-0 sonarr ───────────────────────────────────────
sonarr sonarr-0 sonarr
sonarr sonarr-0 sonarr       ██╗     ███████╗██╗ ██████╗
sonarr sonarr-0 sonarr       ██║     ██╔════╝██║██╔═══██╗
sonarr sonarr-0 sonarr       ██║     ███████╗██║██║   ██║
sonarr sonarr-0 sonarr       ██║     ╚════██║██║██║   ██║
sonarr sonarr-0 sonarr       ███████╗███████║██║╚██████╔╝
sonarr sonarr-0 sonarr       ╚══════╝╚══════╝╚═╝ ╚═════╝
sonarr sonarr-0 sonarr
sonarr sonarr-0 sonarr    Brought to you by linuxserver.io
sonarr sonarr-0 sonarr ───────────────────────────────────────
sonarr sonarr-0 sonarr
sonarr sonarr-0 sonarr To support the app dev(s) visit:
sonarr sonarr-0 sonarr Sonarr: https://sonarr.tv/donate
sonarr sonarr-0 sonarr
sonarr sonarr-0 sonarr To support LSIO projects visit:
sonarr sonarr-0 sonarr https://www.linuxserver.io/donate/
sonarr sonarr-0 sonarr
sonarr sonarr-0 sonarr ───────────────────────────────────────
sonarr sonarr-0 sonarr GID/UID
sonarr sonarr-0 sonarr ───────────────────────────────────────
sonarr sonarr-0 sonarr
sonarr sonarr-0 sonarr User UID:    65534
sonarr sonarr-0 sonarr User GID:    65534
sonarr sonarr-0 sonarr ───────────────────────────────────────
sonarr sonarr-0 sonarr
sonarr sonarr-0 sonarr [custom-init] No custom files found, skipping...
sonarr sonarr-0 sonarr [Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/Sonarr - Version 4.0.1.953
sonarr sonarr-0 sonarr [Info] AppFolderInfo: Data directory is being overridden to [/config]
sonarr sonarr-0 sonarr [Debug] Bootstrap: Console selected
sonarr sonarr-0 sonarr [Info] AppFolderInfo: Data directory is being overridden to [/config]
sonarr sonarr-0 sonarr [Info] AppFolderInfo: Data directory is being overridden to [/config]
sonarr sonarr-0 sonarr [Info] MigrationController: *** Migrating data source=/config/sonarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 ***
sonarr sonarr-0 sonarr [Info] FluentMigrator.Runner.MigrationRunner: 198: parse_title_from_existing_subtitle_files migrating
sonarr sonarr-0 sonarr [Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Beginning Transaction
sonarr sonarr-0 sonarr [Info] parse_title_from_existing_subtitle_files: Starting migration of Main DB to 198
sonarr sonarr-0 sonarr [Info] FluentMigrator.Runner.MigrationRunner: AlterTable SubtitleFiles
sonarr sonarr-0 sonarr [Info] FluentMigrator.Runner.MigrationRunner: => 0.0008215s
sonarr sonarr-0 sonarr [Info] FluentMigrator.Runner.MigrationRunner: CreateColumn SubtitleFiles Title String
sonarr sonarr-0 sonarr [Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: ALTER TABLE "SubtitleFiles" ADD COLUMN "Title" TEXT
sonarr sonarr-0 sonarr [Info] FluentMigrator.Runner.MigrationRunner: => 0.0440259s
sonarr sonarr-0 sonarr [Info] FluentMigrator.Runner.MigrationRunner: AlterTable SubtitleFiles
sonarr sonarr-0 sonarr [Info] FluentMigrator.Runner.MigrationRunner: => 2.57E-05s
sonarr sonarr-0 sonarr [Info] FluentMigrator.Runner.MigrationRunner: CreateColumn SubtitleFiles Copy Int32
sonarr sonarr-0 sonarr [Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: ALTER TABLE "SubtitleFiles" ADD COLUMN "Copy" INTEGER NOT NULL DEFAULT 0
sonarr sonarr-0 sonarr [Info] FluentMigrator.Runner.MigrationRunner: => 0.0025981s
sonarr sonarr-0 sonarr [Info] FluentMigrator.Runner.MigrationRunner: PerformDBOperation
sonarr sonarr-0 sonarr [Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Performing DB Operation
sonarr sonarr-0 sonarr [Debug] AggregateSubtitleInfo: Subtitle title 'x265-MeGusta-xpost - 547bd573e63242db9c12559b388030d0' is in episode file title 'S21E01 - 8.Out.Of.10.Cats.S21E01.1080p.HEVC.x265-MeGusta-xpost - 547bd573e63242db9c12559b388030d0'. Removing from subtitle title.
sonarr sonarr-0 sonarr [Debug] LanguageParser: Parsing language from subtitle file: Season 21/S21E01 - 8.Out.Of.10.Cats.S21E01.1080p.HEVC.x265-MeGusta-xpost - 547bd573e63242db9c12559b388030d0.en.srt

... heaps of subtitles (~8000 lines of debug logs)

sonarr sonarr-0 sonarr [Debug] AggregateSubtitleInfo: Subtitle title 'x265-MeGusta - 0609901d2ea34acd81c9e3d98f4e6b65' is in episode file title 'S01E03 - Tom.Clancys.Jack.Ryan.S01E03.REAL.PROPER.1080p.HEVC.x265-MeGusta - 0609901d2ea34acd81c9e3d98f4e6b65'. Removing from subtitle title.
sonarr sonarr-0 sonarr [Debug] LanguageParser: Parsing language from subtitle file: Season 01/S01E03 - Tom.Clancys.Jack.Ryan.S01E03.REAL.PROPER.1080p.HEVC.x265-MeGusta - 0609901d2ea34acd81c9e3d98f4e6b65.en.forced.srt
sonarr sonarr-0 sonarr [Error] FluentMigrator.Runner.MigrationRunner: Value was either too large or too small for an Int32.
sonarr sonarr-0 sonarr
sonarr sonarr-0 sonarr [v4.0.1.953] System.OverflowException: Value was either too large or too small for an Int32.
sonarr sonarr-0 sonarr    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
sonarr sonarr-0 sonarr    at System.Int32.Parse(String s)
sonarr sonarr-0 sonarr    at NzbDrone.Core.Parser.LanguageParser.UpdateTitleAndCopyFromTitle(SubtitleTitleInfo subtitleTitleInfo) in ./Sonarr.Core/Parser/LanguageParser.cs:line 314
sonarr sonarr-0 sonarr    at NzbDrone.Core.Parser.LanguageParser.ParseSubtitleLanguageInformation(String fileName) in ./Sonarr.Core/Parser/LanguageParser.cs:line 291
sonarr sonarr-0 sonarr    at NzbDrone.Core.Datastore.Migration.parse_title_from_existing_subtitle_files.CleanSubtitleTitleInfo(String relativePath, String originalFilePath, String path)
sonarr sonarr-0 sonarr    at NzbDrone.Core.Datastore.Migration.parse_title_from_existing_subtitle_files.UpdateTitles(IDbConnection conn, IDbTransaction tran) in ./Sonarr.Core/Datastore/Migration/198_parse_titles_from_existing_subtitle_files.cs:line 46
sonarr sonarr-0 sonarr    at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(PerformDBOperationExpression expression)
sonarr sonarr-0 sonarr    at FluentMigrator.Expressions.PerformDBOperationExpression.ExecuteWith(IMigrationProcessor processor)
sonarr sonarr-0 sonarr    at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass80_0.<ExecuteExpressions>b__1()
sonarr sonarr-0 sonarr    at FluentMigrator.Runner.StopWatch.Time(Action action)
sonarr sonarr-0 sonarr    at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
sonarr sonarr-0 sonarr
sonarr sonarr-0 sonarr [Info] NzbDrone.Core.Datastore.Migration.Framework.NzbDroneSQLiteProcessor: Rolling back transaction
sonarr sonarr-0 sonarr
sonarr sonarr-0 sonarr
sonarr sonarr-0 sonarr [Fatal] ConsoleApp: EPIC FAIL!
sonarr sonarr-0 sonarr
sonarr sonarr-0 sonarr [v4.0.1.953] NzbDrone.Common.Exceptions.SonarrStartupException: Sonarr failed to start: Error creating main database
sonarr sonarr-0 sonarr  ---> System.OverflowException: Value was either too large or too small for an Int32.
sonarr sonarr-0 sonarr    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
sonarr sonarr-0 sonarr    at System.Int32.Parse(String s)
sonarr sonarr-0 sonarr    at NzbDrone.Core.Parser.LanguageParser.UpdateTitleAndCopyFromTitle(SubtitleTitleInfo subtitleTitleInfo) in ./Sonarr.Core/Parser/LanguageParser.cs:line 314
sonarr sonarr-0 sonarr    at NzbDrone.Core.Parser.LanguageParser.ParseSubtitleLanguageInformation(String fileName) in ./Sonarr.Core/Parser/LanguageParser.cs:line 291
sonarr sonarr-0 sonarr    at NzbDrone.Core.Datastore.Migration.parse_title_from_existing_subtitle_files.CleanSubtitleTitleInfo(String relativePath, String originalFilePath, String path)
sonarr sonarr-0 sonarr    at NzbDrone.Core.Datastore.Migration.parse_title_from_existing_subtitle_files.UpdateTitles(IDbConnection conn, IDbTransaction tran) in ./Sonarr.Core/Datastore/Migration/198_parse_titles_from_existing_subtitle_files.cs:line 46
sonarr sonarr-0 sonarr    at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Process(PerformDBOperationExpression expression)
sonarr sonarr-0 sonarr    at FluentMigrator.Expressions.PerformDBOperationExpression.ExecuteWith(IMigrationProcessor processor)
sonarr sonarr-0 sonarr    at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass80_0.<ExecuteExpressions>b__1()
sonarr sonarr-0 sonarr    at FluentMigrator.Runner.StopWatch.Time(Action action)
sonarr sonarr-0 sonarr    at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
sonarr sonarr-0 sonarr    at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
sonarr sonarr-0 sonarr    at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
sonarr sonarr-0 sonarr    at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
sonarr sonarr-0 sonarr    at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
sonarr sonarr-0 sonarr    at FluentMigrator.Runner.MigrationRunner.MigrateUp()
sonarr sonarr-0 sonarr    at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate(String connectionString, MigrationContext migrationContext, DatabaseType databaseType) in ./Sonarr.Core/Datastore/Migration/Framework/MigrationController.cs:line 79
sonarr sonarr-0 sonarr    at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext, DatabaseType databaseType) in ./Sonarr.Core/Datastore/DbFactory.cs:line 116
sonarr sonarr-0 sonarr    --- End of inner exception stack trace ---
sonarr sonarr-0 sonarr    at NzbDrone.Core.Datastore.DbFactory.CreateMain(String connectionString, MigrationContext migrationContext, DatabaseType databaseType) in ./Sonarr.Core/Datastore/DbFactory.cs:line 164
sonarr sonarr-0 sonarr    at NzbDrone.Core.Datastore.DbFactory.Create(MigrationContext migrationContext) in ./Sonarr.Core/Datastore/DbFactory.cs:line 71
sonarr sonarr-0 sonarr    at NzbDrone.Core.Datastore.DbFactory.Create(MigrationType migrationType) in ./Sonarr.Core/Datastore/DbFactory.cs:line 59
sonarr sonarr-0 sonarr    at NzbDrone.Core.Datastore.Extensions.CompositionExtensions.<>c.<AddDatabase>b__0_0(IDbFactory f) in ./Sonarr.Core/Datastore/Extensions/CompositionExtensions.cs:line 10
sonarr sonarr-0 sonarr    at DryIoc.Registrator.ToFuncWithObjParams[D1,TService](Func`2 f, Object d1) in /_/src/DryIoc/Container.cs:line 8046
sonarr sonarr-0 sonarr    at DryIoc.Interpreter.TryInterpretFuncInvoke(IResolverContext r, MethodCallExpression e, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3706
sonarr sonarr-0 sonarr    at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, MethodCallExpression callExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3504
sonarr sonarr-0 sonarr    at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result) in /_/src/DryIoc/Container.cs:line 3155
sonarr sonarr-0 sonarr    at DryIoc.Interpreter.TryInterpretSingletonAndUnwrapContainerException(IResolverContext r, Expression expr, ImMapEntry`1 itemRef, Object& result) in /_/src/DryIoc/Container.cs:line 3084
sonarr sonarr-0 sonarr    at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 11110
sonarr sonarr-0 sonarr    at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11029
sonarr sonarr-0 sonarr    at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 12056
sonarr sonarr-0 sonarr    at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11012
sonarr sonarr-0 sonarr    at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 12056
sonarr sonarr-0 sonarr    at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11012
sonarr sonarr-0 sonarr    at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 12056
sonarr sonarr-0 sonarr    at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11012
sonarr sonarr-0 sonarr    at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 423
sonarr sonarr-0 sonarr    at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 389
sonarr sonarr-0 sonarr    at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 8581
sonarr sonarr-0 sonarr    at Sonarr.Http.ClientSchema.SchemaBuilder.Initialize(IContainer container) in ./Sonarr.Http/ClientSchema/SchemaBuilder.cs:line 24
sonarr sonarr-0 sonarr    at NzbDrone.Host.Bootstrap.<>c__DisplayClass3_0.<CreateConsoleHostBuilder>b__2(IContainer c) in ./Sonarr.Host/Bootstrap.cs:line 150
sonarr sonarr-0 sonarr    at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass10_0`1.<ConfigureContainer>b__0(HostBuilderContext context, TContainerBuilder builder)
sonarr sonarr-0 sonarr    at Microsoft.Extensions.Hosting.Internal.ConfigureContainerAdapter`1.ConfigureContainer(HostBuilderContext hostContext, Object containerBuilder)
sonarr sonarr-0 sonarr    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
sonarr sonarr-0 sonarr    at Microsoft.Extensions.Hosting.HostBuilder.Build()
sonarr sonarr-0 sonarr    at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in ./Sonarr.Host/Bootstrap.cs:line 80
sonarr sonarr-0 sonarr    at NzbDrone.Console.ConsoleApp.Main(String[] args) in ./Sonarr.Console/ConsoleApp.cs:line 45
sonarr sonarr-0 sonarr
sonarr sonarr-0 sonarr Press enter to exit...
sonarr sonarr-0 sonarr Non-recoverable failure, waiting for user intervention...
```

**Comment by markus101** [comment]
What is `0609901d2ea34acd81c9e3d98f4e6b65` in the filename? Some sort of hash?

**Comment by sjdaws** [comment]
Naming scheme is `S{season:00}E{episode:00} - {Original Title}`, so it would be the original usenet filename.
