### ISSUE TITLE
TaskExtensions: Task Error 

### ISSUE THREAD

**Issue by VampiricAlien** [Sonarr/Sonarr#6428]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Errors on start up

### Expected Behavior

No errors

### Environment

```markdown
- OS: Alpine Linux 
- Sonarr: 4.0.1.929
- Docker Install: yes
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Main

### Trace Logs?

[Error] TaskExtensions: Task Error 

[v4.0.1.929] System.NullReferenceException: Object reference not set to an instance of an object.

   at NzbDrone.Core.Configuration.ConfigFileProvider.SetValue(String key, Object value) in ./Sonarr.Core/Configuration/ConfigFileProvider.cs:line 307

   at NzbDrone.Core.Configuration.ConfigFileProvider.<>c__DisplayClass80_0.<GetValue>b__0() in ./Sonarr.Core/Configuration/ConfigFileProvider.cs:line 297

   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Sonarr.Common/Cache/Cached.cs:line 98

   at NzbDrone.Core.Configuration.ConfigFileProvider.GetValue(String key, Object defaultValue, Boolean persist) in ./Sonarr.Core/Configuration/ConfigFileProvider.cs:line 280

   at NzbDrone.Core.Configuration.ConfigFileProvider.MigrateConfigFile() in ./Sonarr.Core/Configuration/ConfigFileProvider.cs:line 350

   at NzbDrone.Core.Configuration.ConfigFileProvider.HandleAsync(ApplicationStartedEvent message) in ./Sonarr.Core/Configuration/ConfigFileProvider.cs:line 427

   at NzbDrone.Core.Messaging.Events.EventAggregator.<>c__DisplayClass6_2`1.<PublishEvent>b__2() in ./Sonarr.Core/Messaging/Events/EventAggregator.cs:line 120

   at System.Threading.Tasks.Task.InnerInvoke()

   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)

   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

**Comment by stevietv** [comment]
go into your config.xml and set `<EnableSSL>` to false then restart sonarr.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
