### ISSUE TITLE
MediaInfo.rawStreamData cannot be parsed

### ISSUE THREAD

**Issue by jlkalberer** [Sonarr/Sonarr#6582]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Metadata is not loading correctly after parsing data for some shows -- this also happens on my Radarr instance for some other files so I'm guessing you're using the same method for scraping `rawStreamData`

The workaround is to manually edit the sqlite DB and remove the metadata -- then download a different file. 
This isn't really reasonable though :) 

I'm getting the following exception in the event log:
```
System.Data.DataException: Error parsing column 8 (MediaInfo={
  "rawStreamData": "{    \u0022streams\u0022: [        {            \u0022index\u0022: 0,            \u0022codec_name\u0022: \u0022h264\u0022,            \u0022codec_long_name\u0022: \u0022H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\u0022,            \u0022profile\u0022: \u0022High\u0022,            \u0022codec_type\u0022: \u0022video\u0022,            \u0022codec_tag_string\u0022: \u0022[0][0][0][0]\u0022,            \u0022codec_tag\u0022: \u00220x0000\u0022,            \u0022width\u0022: 1920,            \u0022height\u0022: 1080,            \u0022coded_width\u0022: 1920,            \u0022coded_height\u0022: 1080,            \u0022closed_captions\u0022: 0,   `        \u0022film_grain\u0022: 0,            \u0022has_b_frames\u0022: 1,            \u0022sample_aspect_ratio\u0022: \u00221:1\u0022,            \u0022display_aspect_ratio\u0022: \u002216:9\u0022,            \u0022pix_fmt\u0022: \u0022yuv420p\u0022,            \u0022level\u0022: 40,            \u0022color_range\u0022: \u0022tv\u0022,            \u0022color_space\u0022: \u0022bt709\u0022,            \u0022color_transfer\u0022: \u0022bt709\u0022,            \u0022color_primaries\u0022: \u0022bt709\u0022,            \u0022chroma_location\u0022: \u0022topleft\u0022,            \u0022field_order\u0022: \u0022progressive\u0022,            \u0022refs\u0022: 1,            \u0022is_avc\u0022: \u0022true\u0022,            \u0022nal_length_size\u0022: \u00224\u0022,            \u0022r_frame_rate\u0022: \u002224000/1001\u0022,            \u0022avg_frame_rate\u0022: \u002224000/1001\u0022,            \u0022time_base\u0022: \u00221/1000\u0022,            \u0022start_pts\u0022: 0,            \u0022start_time\u0022: \u00220:00:00.000000\u0022,            \u0022bits_per_raw_sample\u0022: \u00228\u0022,            \u0022extradata_size\u0022: 43,            \u0022disposition\u0022: {                \u0022default\u0022: 1,                \u0022dub\u0022: 0,                \u00:2original\u0022: 0,                \u0022comment\u0022: 0,                \u0022lyrics\u0022: 0,                \u0022karaoke\u0022: 0,                \u0022forced\u0022: 0,                \u0022hearing_impaired\u0022: 0,                \u0022visual_impaired\u0022: 0,                \u0022clean_effects\u0022: 0,                \u0022attached_pic\u0022: 0,                \u0022timed_thumbnails\u0022: 0,                \u0022captions\u0022: 0,                \u0022descriptions\u0022: 0,                \u0022metadata\u0022: 0,                \u0022dependent\u0022: 0,                \u0022still_image\u0022: 0            },            \u0022tags\u0022: {                \u0022language\u0022: \u0022eng\u0022,                \u0022BPS\u0022: \u00225426911\u0022,                \u0022BPS-eng\u0022: \u00225426911\u0022,                \u0022DURATION\u0022: \u002200:11:17.760000000\u0022,                \u0022DURATION-eng\u0022: \u002200:11:17.760000000\u0022,                \u0022NUMBER_OF_FRAMES\u0022: \u002216250\u0022,                \u0022NUMBER_OF_FRAMES-eng\u0022: \u002216250\u0022,                \u0022NUMBER_OF_BYTES\u0022: \u0022459767946\u0022,                \u0022NUMBER_OF_BYTES-eng\u0022: \u0022459767946\u0022,                \u0022_STATISTICS_WRITING_APP\u0022: \u0022mkvmerge v9.4.2 (\u0027So High\u0027) 64bit\u0022,                \u0022_STATISTICS_WRITING_APP-eng\u0022: \u0022mkvmerge v9.4.2 (\u0027So High\u0027) 64bit\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC\u0022: \u00222016-10-04 11:32:06\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC-eng\u0022: \u00222016-10-04 11:32:06\u0022,                \u0022_STATISTICS_TAGS\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022,                \u0022_STATISTICS_TAGS-eng\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022            }        },        {            \u0022index\u0022: 1,            \u0022codec_name\u0022: \u0022aac\u0022,            \u0022codec_long_name\u0022: \u0022AAC (Advanced Audio Coding)\u0022,            \u0022profile\u0022: \u0022LC\u0022,            \u0022codec_type\u0022: \u0022audio\u0022,            \u0022codec_tag_string\u0022: \u0022[0][0][0][0]\u0022,            \u0022codec_tag\u0022: \u00220x0000\u0022,            \u0022sample_fmt\u0022: \u0022fltp\u0022,            \u0022sample_rate\u0022: \u002248000\u0022,            \u0022channels\u0022: 2,            \u0022channel_layout\u0022: \u0022stereo\u0022,            \u0022bits_per_sample\u0022: 0,            \u0022r_frame_rate\u0022: \u00220/0\u0022,            \u0022avg_frame_rate\u0022: \u00220/0\u0022,            \u0022time_base\u0022: \u00221/1000\u0022,            \u0022start_pts\u0022: 18,            \u0022start_time\u0022: \u00220:00:00.018000\u0022,            \u0022extradata_size\u0022: 2,            \u0022disposition\u0022: {                \u0022default\u0022: 1,                \u0022dub\u0022: 0,                \u0022original\u0022: 0,                \u0022comment\u0022: 0,                \u0022lyrics\u0022: 0,                \u0022karaoke\u0022: 0,                \u0022forced\u0022: 0,                \u0022hearing_impaired\u0022: 0,                \u0022visual_impaired\u0022: 0,                \u0022clean_effects\u0022: 0,                \u0022attached_pic\u0022: 0,                \u0022timed_thumbnails\u0022: 0,                \u0022captions\u0022: 0,                \u0022descriptions\u0022: 0,                \u0022metadata\u0022: 0,                \u0022dependent\u0022: 0,                \u0022still_image\u0022: 0            },            \u0022tags\u0022: {                \u0022language\u0022: \u0022eng\u0022,                \u0022BPS\u0022: \u0022154682\u0022,                \u0022BPS-eng\u0022: \u0022154682\u0022,                \u0022DURATION\u0022: \u002200:11:17.802000000\u0022,                \u0022DURATION-eng\u0022: \u002200:11:17.802000000\u0022,                \u0022NUMBER_OF_FRAMES\u0022: \u002231772\u0022,                \u0022NUMBER_OF_FRAMES-eng\u0022: \u002231772\u0022,                \u0022NUMBER_OF_BYTES\u0022: \u002213105520\u0022,                \u0022NUMBER_OF_BYTES-eng\u0022: \u002213105520\u0022,                \u0022_STATISTICS_WRITING_APP\u0022: \u0022mkvmerge v9.4.2 (\u0027So High\u0027) 64bit\u0022,                \u0022_STATISTICS_WRITING_APP-eng\u0022: \u0022mkvmerge v9.4.2 (\u0027So High\u0027) 64bit\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC\u0022: \u00222016-10-04 11:32:06\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC-eng\u0022: \u00222016-10-04 11:32:06\u0022,                \u0022_STATISTICS_TAGS\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022,                \u0022_STATISTICS_TAGS-eng\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022            }        },        {            \u0022index\u0022: 2,            \u0022codec_name\u0022: \u0022subrip\u0022,            \u0022codec_long_name\u0022: \u0022SubRip subtitle\u0022,            \u0022codec_type\u0022: \u0022subtitle\u0022,            \u0022codec_tag_string\u0022: \u0022[0][0][0][0]\u0022,            \u0022codec_tag\u0022: \u00220x0000\u0022,            \u0022r_frame_rate\u0022: \u00220/0\u0022,            \u0022avg_frame_rate\u0022: \u00220/0\u0022,            \u0022time_base\u0022: \u00221/1000\u0022,            \u0022start_pts\u0022: 0,            \u0022start_time\u0022: \u00220:00:00.000000\u0022,            \u0022duration_ts\u0022: 677820,            \u0022duration\u0022: \u00220:11:17.820000\u0022,            \u0022disposition\u0022: {                \u0022default\u0022: 1,                \u0022dub\u0022: 0,                \u0022original\u0022: 0,                \u0022comment\u0022: 0,                \u0022lyrics\u0022: 0,                \u0022karaoke\u0022: 0,                \u0022forced\u0022: 0,                \u0022hearing_impaired\u0022: 0,                \u0022visual_impaired\u0022: 0,                \u0022clean_effects\u0022: 0,                \u0022attached_pic\u0022: 0,                \u0022timed_thumbnails\u0022: 0,                \u0022captions\u0022: 0,                \u0022descriptions\u0022: 0,                \u0022metadata\u0022: 0,                \u0022dependent\u0022: 0,                \u0022still_image\u0022: 0            },            \u0022tags\u0022: {                \u0022language\u0022: \u0022eng\u0022,                \u0022BPS\u0022: \u002293\u0022,                \u0022BPS-eng\u0022: \u002293\u0022,                \u0022DURATION\u0022: \u002200:10:51.282000000\u0022,                \u0022DURATION-eng\u0022: \u002200:10:51.282000000\u0022,                \u0022NUMBER_OF_FRAMES\u0022: \u0022259\u0022,                \u0022NUMBER_OF_FRAMES-eng\u0022: \u0022259\u0022,                \u0022NUMBER_OF_BYTES\u0022: \u00227606\u0022,                \u0022NUMBER_OF_BYTES-eng\u0022: \u00227606\u0022,                \u0022_STATISTICS_WRITING_APP\u0022: \u0022mkvmerge v9.4.2 (\u0027So High\u0027) 64bit\u0022,                \u0022_STATISTICS_WRITING_APP-eng\u0022: \u0022mkvmerge v9.4.2 (\u0027So High\u0027) 64bit\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC\u0022: \u00222016-10-04 11:32:06\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC-eng\u0022: \u00222016-10-04 11:32:06\u0022,                \u0022_STATISTICS_TAGS\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022,                \u0022_STATISTICS_TAGS-eng\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022            }        }    ],    \u0022format\u0022: {        \u0022filename\u0022: \u0022/anime/Regular Show/Season 8/Regular Show - S08E08 - The Brain of Evil WEBDL-1080p.mkv\u0022,        \u0022nb_streams\u0022: 3,        \u0022nb_programs\u0022: 0,        \u0022format_name\u0022: \u0022matroska,webm\u0022,        \u0022format_long_name\u0022: \u0022Matroska / WebM\u0022,        \u0022start_time\u0022: \u00220:00:00.000000\u0022,        \u0022duration\u0022: \u00220:11:17.820000\u0022,        \u0022size\u0022: \u0022473104715\u0022,        \u0022bit_rate\u0022: \u00225583838\u0022,        \u0022probe_score\u0022: 100,        \u0022tags\u0022: {            \u0022encoder\u0022: \u0022libebml v1.3.4 \u002B libmatroska v1.4.5\u0022,            \u0022creation_time\u0022: \u00222016-10-04T11:32:06.000000Z\u0022        }    }}",
  "schemaRevision": 9,
  "containerFormat": "matroska,webm",
  "videoFormat": "h264",
  "videoCodecID": "[0][0][0][0]",
  "videoProfile": "High",
  "videoBitrate": 0,
  "videoBitDepth": 8,
  "videoColourPrimaries": "bt709",
  "videoTransferCharacteristics": "bt709",
  "videoHdrFormat": "none",
  "height": 1080,
  "width": 1920,
  "audioFormat": "aac",
  "audioCodecID": "[0][0][0][0]",
  "audioProfile": "LC",
  "audioBitrate": 0,
  "runTime": "00:11:17.8200000",
  "audioStreamCount": 1,
  "audioChannels": 2,
  "audioChannelPositions": "stereo",
  "videoFps": 23.976023976023976023976023976,
  "audioLanguages": [
    "eng"
  ],
  "subtitles": [
    "eng"
  ],
  "scanType": "Progressive"
} - String)
 ---> System.Text.Json.JsonException: ':' is not a hex digit following '\u' within a JSON string. The string should be correctly escaped. Path: $.rawStreamData | LineNumber: 1 | BytePositionInLine: 1946.
 ---> System.Text.Json.JsonReaderException: ':' is not a hex digit following '\u' within a JSON string. The string should be correctly escaped. LineNumber: 1 | BytePositionInLine: 1946.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ValidateHexDigits(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Dapper.SqlMapper.TypeHandler`1.Dapper.SqlMapper.ITypeHandler.Parse(Type destinationType, Object value) in /_/Dapper/SqlMapper.TypeHandler.cs:line 42
   at Dapper.SqlMapper.TypeHandlerCache`1.Parse(Object value) in /_/Dapper/SqlMapper.TypeHandlerCache.cs:line 23
   at Deserialize3135faaa-142f-4792-8571-d17ef30ea63d(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
   at Deserialize3135faaa-142f-4792-8571-d17ef30ea63d(IDataReader )
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
   at NzbDrone.Core.Datastore.BasicRepository`1.Query(SqlBuilder builder)
   at NzbDrone.Core.MediaFiles.MediaFileRepository.GetFilesBySeries(Int32 seriesId)
   at Sonarr.Api.V3.EpisodeFiles.EpisodeFileController.GetEpisodeFiles(Nullable`1 seriesId, List`1 episodeFileIds)
   at lambda_method149(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context)
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context)
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context)
   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context)
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context)
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

```

### Expected Behavior

After fetching `rawStreamData`, invalid unicode characters are removed from the string or simply change the type so that it supports these characters.

### Steps To Reproduce

I deleted the episode so I can't make an example video with the metadata but you should be able to just modify the sqlite DB to get the same result.

1. Store this JSON in `MediaInfo` for an episode (I'm not sure what table this is in)
```
{
  "rawStreamData": "{    \u0022streams\u0022: [        {            \u0022index\u0022: 0,            \u0022codec_name\u0022: \u0022h264\u0022,            \u0022codec_long_name\u0022: \u0022H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\u0022,            \u0022profile\u0022: \u0022High\u0022,            \u0022codec_type\u0022: \u0022video\u0022,            \u0022codec_tag_string\u0022: \u0022[0][0][0][0]\u0022,            \u0022codec_tag\u0022: \u00220x0000\u0022,            \u0022width\u0022: 1920,            \u0022height\u0022: 1080,            \u0022coded_width\u0022: 1920,            \u0022coded_height\u0022: 1080,            \u0022closed_captions\u0022: 0,   `        \u0022film_grain\u0022: 0,            \u0022has_b_frames\u0022: 1,            \u0022sample_aspect_ratio\u0022: \u00221:1\u0022,            \u0022display_aspect_ratio\u0022: \u002216:9\u0022,            \u0022pix_fmt\u0022: \u0022yuv420p\u0022,            \u0022level\u0022: 40,            \u0022color_range\u0022: \u0022tv\u0022,            \u0022color_space\u0022: \u0022bt709\u0022,            \u0022color_transfer\u0022: \u0022bt709\u0022,            \u0022color_primaries\u0022: \u0022bt709\u0022,            \u0022chroma_location\u0022: \u0022topleft\u0022,            \u0022field_order\u0022: \u0022progressive\u0022,            \u0022refs\u0022: 1,            \u0022is_avc\u0022: \u0022true\u0022,            \u0022nal_length_size\u0022: \u00224\u0022,            \u0022r_frame_rate\u0022: \u002224000/1001\u0022,            \u0022avg_frame_rate\u0022: \u002224000/1001\u0022,            \u0022time_base\u0022: \u00221/1000\u0022,            \u0022start_pts\u0022: 0,            \u0022start_time\u0022: \u00220:00:00.000000\u0022,            \u0022bits_per_raw_sample\u0022: \u00228\u0022,            \u0022extradata_size\u0022: 43,            \u0022disposition\u0022: {                \u0022default\u0022: 1,                \u0022dub\u0022: 0,                \u00:2original\u0022: 0,                \u0022comment\u0022: 0,                \u0022lyrics\u0022: 0,                \u0022karaoke\u0022: 0,                \u0022forced\u0022: 0,                \u0022hearing_impaired\u0022: 0,                \u0022visual_impaired\u0022: 0,                \u0022clean_effects\u0022: 0,                \u0022attached_pic\u0022: 0,                \u0022timed_thumbnails\u0022: 0,                \u0022captions\u0022: 0,                \u0022descriptions\u0022: 0,                \u0022metadata\u0022: 0,                \u0022dependent\u0022: 0,                \u0022still_image\u0022: 0            },            \u0022tags\u0022: {                \u0022language\u0022: \u0022eng\u0022,                \u0022BPS\u0022: \u00225426911\u0022,                \u0022BPS-eng\u0022: \u00225426911\u0022,                \u0022DURATION\u0022: \u002200:11:17.760000000\u0022,                \u0022DURATION-eng\u0022: \u002200:11:17.760000000\u0022,                \u0022NUMBER_OF_FRAMES\u0022: \u002216250\u0022,                \u0022NUMBER_OF_FRAMES-eng\u0022: \u002216250\u0022,                \u0022NUMBER_OF_BYTES\u0022: \u0022459767946\u0022,                \u0022NUMBER_OF_BYTES-eng\u0022: \u0022459767946\u0022,                \u0022_STATISTICS_WRITING_APP\u0022: \u0022mkvmerge v9.4.2 (\u0027So High\u0027) 64bit\u0022,                \u0022_STATISTICS_WRITING_APP-eng\u0022: \u0022mkvmerge v9.4.2 (\u0027So High\u0027) 64bit\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC\u0022: \u00222016-10-04 11:32:06\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC-eng\u0022: \u00222016-10-04 11:32:06\u0022,                \u0022_STATISTICS_TAGS\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022,                \u0022_STATISTICS_TAGS-eng\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022            }        },        {            \u0022index\u0022: 1,            \u0022codec_name\u0022: \u0022aac\u0022,            \u0022codec_long_name\u0022: \u0022AAC (Advanced Audio Coding)\u0022,            \u0022profile\u0022: \u0022LC\u0022,            \u0022codec_type\u0022: \u0022audio\u0022,            \u0022codec_tag_string\u0022: \u0022[0][0][0][0]\u0022,            \u0022codec_tag\u0022: \u00220x0000\u0022,            \u0022sample_fmt\u0022: \u0022fltp\u0022,            \u0022sample_rate\u0022: \u002248000\u0022,            \u0022channels\u0022: 2,            \u0022channel_layout\u0022: \u0022stereo\u0022,            \u0022bits_per_sample\u0022: 0,            \u0022r_frame_rate\u0022: \u00220/0\u0022,            \u0022avg_frame_rate\u0022: \u00220/0\u0022,            \u0022time_base\u0022: \u00221/1000\u0022,            \u0022start_pts\u0022: 18,            \u0022start_time\u0022: \u00220:00:00.018000\u0022,            \u0022extradata_size\u0022: 2,            \u0022disposition\u0022: {                \u0022default\u0022: 1,                \u0022dub\u0022: 0,                \u0022original\u0022: 0,                \u0022comment\u0022: 0,                \u0022lyrics\u0022: 0,                \u0022karaoke\u0022: 0,                \u0022forced\u0022: 0,                \u0022hearing_impaired\u0022: 0,                \u0022visual_impaired\u0022: 0,                \u0022clean_effects\u0022: 0,                \u0022attached_pic\u0022: 0,                \u0022timed_thumbnails\u0022: 0,                \u0022captions\u0022: 0,                \u0022descriptions\u0022: 0,                \u0022metadata\u0022: 0,                \u0022dependent\u0022: 0,                \u0022still_image\u0022: 0            },            \u0022tags\u0022: {                \u0022language\u0022: \u0022eng\u0022,                \u0022BPS\u0022: \u0022154682\u0022,                \u0022BPS-eng\u0022: \u0022154682\u0022,                \u0022DURATION\u0022: \u002200:11:17.802000000\u0022,                \u0022DURATION-eng\u0022: \u002200:11:17.802000000\u0022,                \u0022NUMBER_OF_FRAMES\u0022: \u002231772\u0022,                \u0022NUMBER_OF_FRAMES-eng\u0022: \u002231772\u0022,                \u0022NUMBER_OF_BYTES\u0022: \u002213105520\u0022,                \u0022NUMBER_OF_BYTES-eng\u0022: \u002213105520\u0022,                \u0022_STATISTICS_WRITING_APP\u0022: \u0022mkvmerge v9.4.2 (\u0027So High\u0027) 64bit\u0022,                \u0022_STATISTICS_WRITING_APP-eng\u0022: \u0022mkvmerge v9.4.2 (\u0027So High\u0027) 64bit\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC\u0022: \u00222016-10-04 11:32:06\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC-eng\u0022: \u00222016-10-04 11:32:06\u0022,                \u0022_STATISTICS_TAGS\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022,                \u0022_STATISTICS_TAGS-eng\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022            }        },        {            \u0022index\u0022: 2,            \u0022codec_name\u0022: \u0022subrip\u0022,            \u0022codec_long_name\u0022: \u0022SubRip subtitle\u0022,            \u0022codec_type\u0022: \u0022subtitle\u0022,            \u0022codec_tag_string\u0022: \u0022[0][0][0][0]\u0022,            \u0022codec_tag\u0022: \u00220x0000\u0022,            \u0022r_frame_rate\u0022: \u00220/0\u0022,            \u0022avg_frame_rate\u0022: \u00220/0\u0022,            \u0022time_base\u0022: \u00221/1000\u0022,            \u0022start_pts\u0022: 0,            \u0022start_time\u0022: \u00220:00:00.000000\u0022,            \u0022duration_ts\u0022: 677820,            \u0022duration\u0022: \u00220:11:17.820000\u0022,            \u0022disposition\u0022: {                \u0022default\u0022: 1,                \u0022dub\u0022: 0,                \u0022original\u0022: 0,                \u0022comment\u0022: 0,                \u0022lyrics\u0022: 0,                \u0022karaoke\u0022: 0,                \u0022forced\u0022: 0,                \u0022hearing_impaired\u0022: 0,                \u0022visual_impaired\u0022: 0,                \u0022clean_effects\u0022: 0,                \u0022attached_pic\u0022: 0,                \u0022timed_thumbnails\u0022: 0,                \u0022captions\u0022: 0,                \u0022descriptions\u0022: 0,                \u0022metadata\u0022: 0,                \u0022dependent\u0022: 0,                \u0022still_image\u0022: 0            },            \u0022tags\u0022: {                \u0022language\u0022: \u0022eng\u0022,                \u0022BPS\u0022: \u002293\u0022,                \u0022BPS-eng\u0022: \u002293\u0022,                \u0022DURATION\u0022: \u002200:10:51.282000000\u0022,                \u0022DURATION-eng\u0022: \u002200:10:51.282000000\u0022,                \u0022NUMBER_OF_FRAMES\u0022: \u0022259\u0022,                \u0022NUMBER_OF_FRAMES-eng\u0022: \u0022259\u0022,                \u0022NUMBER_OF_BYTES\u0022: \u00227606\u0022,                \u0022NUMBER_OF_BYTES-eng\u0022: \u00227606\u0022,                \u0022_STATISTICS_WRITING_APP\u0022: \u0022mkvmerge v9.4.2 (\u0027So High\u0027) 64bit\u0022,                \u0022_STATISTICS_WRITING_APP-eng\u0022: \u0022mkvmerge v9.4.2 (\u0027So High\u0027) 64bit\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC\u0022: \u00222016-10-04 11:32:06\u0022,                \u0022_STATISTICS_WRITING_DATE_UTC-eng\u0022: \u00222016-10-04 11:32:06\u0022,                \u0022_STATISTICS_TAGS\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022,                \u0022_STATISTICS_TAGS-eng\u0022: \u0022BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES\u0022            }        }    ],    \u0022format\u0022: {        \u0022filename\u0022: \u0022/anime/Regular Show/Season 8/Regular Show - S08E08 - The Brain of Evil WEBDL-1080p.mkv\u0022,        \u0022nb_streams\u0022: 3,        \u0022nb_programs\u0022: 0,        \u0022format_name\u0022: \u0022matroska,webm\u0022,        \u0022format_long_name\u0022: \u0022Matroska / WebM\u0022,        \u0022start_time\u0022: \u00220:00:00.000000\u0022,        \u0022duration\u0022: \u00220:11:17.820000\u0022,        \u0022size\u0022: \u0022473104715\u0022,        \u0022bit_rate\u0022: \u00225583838\u0022,        \u0022probe_score\u0022: 100,        \u0022tags\u0022: {            \u0022encoder\u0022: \u0022libebml v1.3.4 \u002B libmatroska v1.4.5\u0022,            \u0022creation_time\u0022: \u00222016-10-04T11:32:06.000000Z\u0022        }    }}",
  "schemaRevision": 9,
  "containerFormat": "matroska,webm",
  "videoFormat": "h264",
  "videoCodecID": "[0][0][0][0]",
  "videoProfile": "High",
  "videoBitrate": 0,
  "videoBitDepth": 8,
  "videoColourPrimaries": "bt709",
  "videoTransferCharacteristics": "bt709",
  "videoHdrFormat": "none",
  "height": 1080,
  "width": 1920,
  "audioFormat": "aac",
  "audioCodecID": "[0][0][0][0]",
  "audioProfile": "LC",
  "audioBitrate": 0,
  "runTime": "00:11:17.8200000",
  "audioStreamCount": 1,
  "audioChannels": 2,
  "audioChannelPositions": "stereo",
  "videoFps": 23.976023976023976023976023976,
  "audioLanguages": [
    "eng"
  ],
  "subtitles": [
    "eng"
  ],
  "scanType": "Progressive"
}
```
2. Go to series
3. Click "Refresh and Scan"
4. An error will show up in the event log

### Environment

```markdown
- OS: Unraid
- Sonarr: 4.0.2.1183
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome
- Database: not sure -- whatever is in `linuxserver/radarr@latest`
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/14470207/sonarr.trace.txt)

**Comment by markus101** [comment]
If you store invalid JSON retrieving it as parsing it will fail, but this looks like corruption within the database that lead to the issue. If you have a file (preferably just a sample from a larger file) that reproduces this, we can look into it further, but otherwise there isn't a lot we're going to be able to do outside of log the failure and have a human resolve the issue.
