### ISSUE TITLE
Retry for pushed releases

### ISSUE THREAD

**Issue by NLZ** [Sonarr/Sonarr#6752]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When a release is pushed to Sonarr (via autobrr) sometimes grabbing the release can fail because of the tracker returns error 500.
In these cases it seems like the grab fails and there is no retry.
Found #6238 but I see no retry in the logs so probably unrelated.

And there is no indication of this failure on the Sonarr UI, only visible in the logs.

### Describe the solution you'd like

It would be nice if Sonarr would retry the pushed grab when it fails to download them.

Also when it ultimately fails it would be handy to see it in the History page, to know what I need to check on.

It would also be great if the error would also be returned to the api call, because right now autobrr thinks it was a success.

(maybe I should split these into a separate feature request, please tell me if it's better that way)

### Describe alternatives you've considered

I can compare autobrr approved pushes with the Sonarr grabs to see if something is amiss.

### Anything else?

Sanitized non-trace logs, not sure if helpful.
```
2024-04-09 06:07:02.7|Info|ReleasePushController|Release pushed: Release 2024 S01E01-GROUP - https://tracker/download/link
2024-04-09 06:07:02.8|Info|DownloadDecisionMaker|Processing 1 releases
2024-04-09 06:07:03.9|Warn|HttpClient|HTTP Error - Res: HTTP/2.0 [GET] https://tracker/download/link: 500.InternalServerError (1558 bytes)
<!DOCTYPE html>
<html lang="en">
...
</html>

2024-04-09 06:07:03.9|Error|QBittorrent|Downloading torrent file for episode 'Release 2024 S01E01-GROUP' failed (https://tracker/download/link)

[v4.0.3.1413] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://tracker/download/link]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Core.Download.TorrentClientBase`1.<>c.<<DownloadFromWebUrl>b__11_0>d.MoveNext() in ./Sonarr.Core/Download/TorrentClientBase.cs:line 143
--- End of stack trace from previous location ---
   at Polly.ResiliencePipeline.<>c__9`2.<<ExecuteAsync>b__9_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Outcome`1.GetResultOrRethrow()
   at Polly.ResiliencePipeline.ExecuteAsync[TResult,TState](Func`3 callback, TState state, CancellationToken cancellationToken)
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteEpisode remoteEpisode, IIndexer indexer, String torrentUrl) in ./Sonarr.Core/Download/TorrentClientBase.cs:line 215
<!DOCTYPE html>
<html lang="en">
...
</html>


2024-04-09 06:07:03.9|Warn|ProcessDownloadDecisions|Couldn't add release 'Release 2024 S01E01-GROUP' from Indexer (redacted) to download queue.

[v4.0.3.1413] NzbDrone.Core.Exceptions.ReleaseDownloadException: Downloading torrent failed
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://tracker/download/link]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Core.Download.TorrentClientBase`1.<>c.<<DownloadFromWebUrl>b__11_0>d.MoveNext() in ./Sonarr.Core/Download/TorrentClientBase.cs:line 143
--- End of stack trace from previous location ---
   at Polly.ResiliencePipeline.<>c__9`2.<<ExecuteAsync>b__9_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Outcome`1.GetResultOrRethrow()
   at Polly.ResiliencePipeline.ExecuteAsync[TResult,TState](Func`3 callback, TState state, CancellationToken cancellationToken)
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteEpisode remoteEpisode, IIndexer indexer, String torrentUrl) in ./Sonarr.Core/Download/TorrentClientBase.cs:line 215
<!DOCTYPE html>
<html lang="en">
    <head>
...
</html>

   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteEpisode remoteEpisode, IIndexer indexer, String torrentUrl) in ./Sonarr.Core/Download/TorrentClientBase.cs:line 215
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteEpisode remoteEpisode, IIndexer indexer) in ./Sonarr.Core/Download/TorrentClientBase.cs:line 129
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteEpisode remoteEpisode, IDownloadClient downloadClient) in ./Sonarr.Core/Download/DownloadService.cs:line 143
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteEpisode remoteEpisode, Nullable`1 downloadClientId) in ./Sonarr.Core/Download/DownloadService.cs:line 64
   at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisionInternal(DownloadDecision decision, Nullable`1 downloadClientId) in ./Sonarr.Core/Download/ProcessDownloadDecisions.cs:line 204

2024-04-09 06:07:10.1|Info|ReleasePushController|Release pushed: Next Release...
```

**Comment by NLZ** [comment]
Oh, I see, so there is retry (I assumed it's just duplicated logging), but it's happening immediately and fails as well.
I managed to reproduce it with another popular release, maybe the tracker is overloaded so retrying immediately is futile.
Would it make sense to add some delay before the retry? Like retry 1s later and then 5s later?

Here are the trace logs:
https://logs.notifiarr.com/?c93bd6691e5225fc#7W1CKHY2C6MvntmXjFQDeytxXFLBvcL6MM9d7wY2x7VM

The trace logs also shows that /api/v3/release/push returned 200 after failure, should I split that into another request?

**Comment by NLZ** [comment]
Nope, no mention of `Retrying in` in the trace logs anywhere.

I'm on latest stable 4.0.4.1491

**Comment by NLZ** [comment]
thank you
