### ISSUE TITLE
Database Locked

### ISSUE THREAD

**Issue by threespoons** [Sonarr/Sonarr#6769]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Database locking every few minutes, giving poor performance and responsiveness

### Expected Behavior

No database locking

### Steps To Reproduce

Any task run such as adding media, renaming, searching etc. can lead to database lock

### Environment

```markdown
- OS: DSM 7
- Sonarr: 4.0.4.1491
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Safari, Chrome, Edge
- Database: SQLite3
```

### What branch are you running?

Main

### Trace Logs?

v4.0.4.1491] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1033
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1009
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 189
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 146
   at NzbDrone.Core.Download.History.DownloadHistoryService.Handle(EpisodeImportedEvent message) in ./Sonarr.Core/Download/History/DownloadHistoryService.cs:line 162
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)

2024-04-29 22:03:51.0|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /Spoonflix/TVShows/Parks and Recreation/Season 7/Parks and Recreation - S07E02 - Ron and Jammy WEBDL-1080p.mkv
2024-04-29 22:03:57.3|Info|RefreshEpisodeService|Finished episode refresh for series: [422091][Dark Side of Comedy].
2024-04-29 22:03:58.2|Info|RefreshSeriesService|Updating Dark Side of Football
2024-04-29 22:04:04.7|Warn|ImportListExclusionController|API call made to deprecated endpoint from http4s-ember/0.23.23
2024-04-29 22:04:18.5|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /Spoonflix/TVShows/Parks and Recreation/Season 7/Parks and Recreation - S07E02 - Ron and Jammy WEBDL-1080p.en.srt
2024-04-29 22:04:20.0|Info|RefreshEpisodeService|Starting episode info refresh for: [400950][Dark Side of Football]
2024-04-29 22:04:32.5|Info|RefreshEpisodeService|Finished episode refresh for series: [400950][Dark Side of Football].
2024-04-29 22:04:32.5|Info|RefreshSeriesService|Updating Dark Side of the 2000s
2024-04-29 22:04:39.6|Error|Torznab|An error occurred while processing feed. http://10.0.0.2:9696/63/api?t=tvsearch&cat=5000,5070&extended=1&apikey=(removed)&offset=0&limit=100

[v4.0.4.1491] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2858
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
   at NzbDrone.Core.Datastore.BasicRepository`1.UpdateFields(IDbConnection connection, IDbTransaction transaction, TModel model, List`1 propertiesToUpdate) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 385
   at NzbDrone.Core.Datastore.BasicRepository`1.Update(TModel model) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 227
   at NzbDrone.Core.Datastore.BasicRepository`1.Upsert(TModel model) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 294
   at NzbDrone.Core.Indexers.IndexerStatusService.UpdateRssSyncStatus(Int32 indexerId, ReleaseInfo releaseInfo) in ./Sonarr.Core/Indexers/IndexerStatusService.cs:line 36
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 219

2024-04-29 22:04:39.6|Info|DownloadDecisionMaker|Processing 349 releases
2024-04-29 22:04:44.0|Info|RefreshEpisodeService|Starting episode info refresh for: [436801][Dark Side of the 2000s]
2024-04-29 22:04:52.3|Info|RssSyncService|RSS Sync Completed. Reports found: 349, Reports grabbed: 0, Reports pending: 1
2024-04-29 22:05:04.6|Info|RefreshEpisodeService|Finished episode refresh for series: [436801][Dark Side of the 2000s].
2024-04-29 22:05:04.6|Info|RefreshSeriesService|Updating Dark Side of the 90's
2024-04-29 22:05:13.6|Info|RefreshEpisodeService|Starting episode info refresh for: [406212][Dark Side of the 90's]
2024-04-29 22:05:20.8|Warn|ImportListExclusionController|API call made to deprecated endpoint from http4s-ember/0.23.23
2024-04-29 22:05:26.1|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /Spoonflix/TVShows/Parks and Recreation/Season 7/Parks and Recreation - S07E03 - William Henry Harrison WEBDL-1080p.mkv
2024-04-29 22:05:51.8|Info|RefreshEpisodeService|Finished episode refresh for series: [406212][Dark Side of the 90's].
2024-04-29 22:05:51.8|Info|RefreshSeriesService|Updating Dark Side of the Ring
2024-04-29 22:06:01.5|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /Spoonflix/TVShows/Parks and Recreation/Season 7/Parks and Recreation - S07E03 - William Henry Harrison WEBDL-1080p.en.srt
2024-04-29 22:06:07.2|Info|RefreshEpisodeService|Starting episode info refresh for: [361761][Dark Side of the Ring]

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.
