### ISSUE TITLE
Series History - Cannot read properties of undefined (reading 'seasonNumber')

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#6782]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Series => Series History
There was an error loading this item 
```
Cannot read properties of undefined (reading 'seasonNumber')
  at seasonNumber (webpack://sonarr/frontend/src/Series/History/SeriesHistoryRow.js:98:34)
  at qi (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:187:187)
  at pi (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:186:172)
  at a=b.pendingProps;f=e._init;e=f(e._payload);b.type=e;f=b.tag=hk(e);a=lg(e,a);switch (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:269:426)
  at Pj (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:250:346)
  at Pj (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:250:277)
  at Pj (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:250:137)
  at Lj (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:243:162)
  at jg (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:123:114)
  at unstable_next (webpack://sonarr/node_modules/scheduler/cjs/scheduler.production.min.js:18:342)
  at eg (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:122:324)
  at jg (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:123:60)
  at eg (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:122:427)
  at Hb (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:292:100)
  at $c (webpack://sonarr/node_modules/react-dom/cjs/react-dom.production.min.js:73:351)
  at Array.prototype.slice.call (webpack://sonarr/node_modules/@sentry/browser/esm/helpers.js:91:16)
Version: 4.0.4.1572
```

### Expected Behavior

Series History Loads without issues

### Steps To Reproduce

1. Series with multiple Seasons => History => Error

### Environment

```markdown
- OS: ubuntu 22.04
- Sonarr: 4.0.4.1572
- Docker Install: yes lsio
- Using Reverse Proxy: yes
- Browser: chrome 124.0.6367.92 
- Database: Postgresql 16.2 / Migration 205
```

### What branch are you running?

Develop

### Trace Logs?

N/A - UI.
No Errors in logs for this item.

**Comment by bakerboy448** [comment]
gah forgot to note it and checking through now, appears it's more specific than multi-season

**Comment by markus101** [comment]
History for an episode that doesn't exist, either because it was added and the UI doesn't have it or it was removed, if it's the latter housekeeping would eventually resolve it, otherwise a refresh would.

**Comment by bakerboy448** [comment]
Markus that would check out given the importing / rescanning / deleting that would have been occurring at this time
