### ISSUE TITLE
Can't auth with Transmission running on router

### ISSUE THREAD

**Issue by betterthanever2** [Sonarr/Sonarr#6824]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When adding/enabling Transmission client in the settings, I'm getting `Authentication Failure`

### Expected Behavior

Transmission client is successfully enabled

### Environment

```markdown
- OS: Ubuntu 24.04
- Sonarr: 4.0.4.1491
- Docker Install: no
- Using Reverse Proxy: no
- Browser: Firefox 
- Database: Sqlite 3.45.1
```

### What branch are you running?

Main

### Trace Logs?

2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'rsssyncinterval' defaultValue:'15'
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2024-05-18 07:10:49.0|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2024-05-18 07:10:49.0|Trace|EventAggregator|ConfigSavedEvent <~ TaskManager
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'certificatevalidation' defaultValue:'Enabled'
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'backupfolder' defaultValue:'Backups'
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'backupinterval' defaultValue:'7'
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'backupretention' defaultValue:'28'
2024-05-18 07:10:49.0|Trace|ConfigService|Using default config value for 'applicationurl' defaultValue:''
2024-05-18 07:10:49.0|Trace|Http|Res: 2699 [PUT] /api/v3/config/host: 202.Accepted (6 ms)
2024-05-18 07:10:49.0|Debug|Api|[PUT] /api/v3/config/host: 202.Accepted (6 ms)
2024-05-18 07:10:51.4|Trace|Http|Req: 2700 [GET] /api/v3/downloadclient (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)
2024-05-18 07:10:51.4|Trace|Http|Req: 2701 [GET] /api/v3/config/downloadclient (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)
2024-05-18 07:10:51.4|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
2024-05-18 07:10:51.4|Trace|ConfigService|Using default config value for 'autoredownloadfailed' defaultValue:'True'
2024-05-18 07:10:51.4|Trace|ConfigService|Using default config value for 'autoredownloadfailedfrominteractivesearch' defaultValue:'True'
2024-05-18 07:10:51.4|Trace|Http|Res: 2701 [GET] /api/v3/config/downloadclient: 200.OK (0 ms)
2024-05-18 07:10:51.4|Trace|Http|Res: 2700 [GET] /api/v3/downloadclient: 200.OK (1 ms)
2024-05-18 07:10:51.4|Trace|Http|Req: 2702 [GET] /api/v3/remotepathmapping (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)
2024-05-18 07:10:51.4|Debug|Api|[GET] /api/v3/config/downloadclient: 200.OK (0 ms)
2024-05-18 07:10:51.4|Debug|Api|[GET] /api/v3/downloadclient: 200.OK (1 ms)
2024-05-18 07:10:51.4|Trace|Http|Res: 2702 [GET] /api/v3/remotepathmapping: 200.OK (0 ms)
2024-05-18 07:10:51.4|Debug|Api|[GET] /api/v3/remotepathmapping: 200.OK (0 ms)
2024-05-18 07:10:54.0|Trace|HealthCheckService|Check health -> UpdateCheck
2024-05-18 07:10:54.0|Trace|HttpClient|Req: [GET] https://services.sonarr.tv/v1/update/main?version=4.0.4.1491&os=linux&arch=X64&runtime=netcore&runtimeVer=6.0.13&dbType=SQLite&active=false
2024-05-18 07:10:54.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-05-18 07:10:54.3|Trace|HttpClient|Res: HTTP/2.0 [GET] https://services.sonarr.tv/v1/update/main?version=4.0.4.1491&os=linux&arch=X64&runtime=netcore&runtimeVer=6.0.13&dbType=SQLite&active=false: 200.OK (19 bytes) (268 ms)
2024-05-18 07:10:54.3|Trace|HealthCheckService|Check health <- UpdateCheck
2024-05-18 07:10:54.3|Trace|HealthCheckService|Check health -> ApiKeyValidationCheck
2024-05-18 07:10:54.3|Trace|HealthCheckService|Check health <- ApiKeyValidationCheck
2024-05-18 07:10:54.3|Trace|HealthCheckService|Check health -> ImportMechanismCheck
2024-05-18 07:10:54.3|Trace|HealthCheckService|Check health <- ImportMechanismCheck
2024-05-18 07:10:54.3|Trace|HealthCheckService|Check health -> ProxyCheck
2024-05-18 07:10:54.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-05-18 07:10:54.3|Trace|HealthCheckService|Check health <- ProxyCheck
2024-05-18 07:10:54.3|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2024-05-18 07:10:54.3|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2024-05-18 07:10:54.3|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2024-05-18 07:10:54.3|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2024-05-18 07:10:54.3|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2024-05-18 07:10:54.3|Trace|Http|Req: 2703 [GET] /api/v3/health (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)
2024-05-18 07:10:54.3|Trace|Http|Res: 2703 [GET] /api/v3/health: 200.OK (0 ms)
2024-05-18 07:10:54.3|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2024-05-18 07:10:57.2|Trace|Http|Req: 2704 [POST] /api/v3/downloadclient/test (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)
2024-05-18 07:10:57.2|Trace|HttpClient|Req: [GET] http://192.168.1.1:50090/transmission/rpc
2024-05-18 07:10:57.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-05-18 07:10:57.2|Trace|HttpClient|Res: HTTP/1.1 [GET] http://192.168.1.1:50090/transmission/rpc: 405.MethodNotAllowed (32 bytes)
<h1>405: Method Not Allowed</h1> (2 ms)
2024-05-18 07:10:57.2|Trace|HttpClient|Response content (32 bytes): <h1>405: Method Not Allowed</h1>
2024-05-18 07:10:57.2|Error|Transmission|Failed to authenticate with Transmission.

[v4.0.4.1491] NzbDrone.Core.Download.Clients.DownloadClientAuthenticationException: Failed to authenticate with Transmission.
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, TransmissionSettings settings, Boolean reauthenticate) in ./Sonarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 241
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.ProcessRequest(String action, Object arguments, TransmissionSettings settings) in ./Sonarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 317
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.GetConfig(TransmissionSettings settings) in ./Sonarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 120
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.GetClientVersion(TransmissionSettings settings) in ./Sonarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 112
   at NzbDrone.Core.Download.Clients.Transmission.Transmission.ValidateVersion() in ./Sonarr.Core/Download/Clients/Transmission/Transmission.cs:line 45
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionBase.TestConnection() in ./Sonarr.Core/Download/Clients/Transmission/TransmissionBase.cs:line 297

2024-05-18 07:10:57.2|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2024-05-18 07:10:57.3|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2024-05-18 07:10:57.3|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IDownloadClient>
2024-05-18 07:10:57.3|Trace|SonarrErrorPipeline|Handling Exception
2024-05-18 07:10:57.3|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Username: Authentication Failure
2024-05-18 07:10:57.3|Trace|Http|Res: 2704 [POST] /api/v3/downloadclient/test: 400.BadRequest (9 ms)
2024-05-18 07:10:57.3|Debug|Api|[POST] /api/v3/downloadclient/test: 400.BadRequest (9 ms)
2024-05-18 07:10:59.1|Trace|Scheduler|Pending Tasks: 0
2024-05-18 07:11:02.3|Trace|HealthCheckService|Check health -> DownloadClientCheck
2024-05-18 07:11:02.3|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2024-05-18 07:11:02.3|Trace|HealthCheckService|Check health <- DownloadClientCheck
2024-05-18 07:11:02.3|Trace|HealthCheckService|Check health -> DownloadClientStatusCheck
2024-05-18 07:11:02.3|Trace|HealthCheckService|Check health <- DownloadClientStatusCheck
2024-05-18 07:11:02.3|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2024-05-18 07:11:02.3|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2024-05-18 07:11:02.3|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2024-05-18 07:11:02.3|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2024-05-18 07:11:02.3|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2024-05-18 07:11:02.3|Trace|Http|Req: 2705 [GET] /api/v3/health (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)
2024-05-18 07:11:02.3|Trace|Http|Res: 2705 [GET] /api/v3/health: 200.OK (0 ms)
2024-05-18 07:11:02.3|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2024-05-18 07:11:05.4|Trace|Http|Req: 2706 [POST] /api/v3/downloadclient/test (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)
2024-05-18 07:11:05.4|Trace|HttpClient|Req: [GET] http://192.168.1.1:50090/transmission/rpc
2024-05-18 07:11:05.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-05-18 07:11:06.6|Trace|HttpClient|Res: HTTP/1.1 [GET] http://192.168.1.1:50090/transmission/rpc: 401.Unauthorized (82 bytes)
<h1>401: Unauthorized</h1><p>Unauthorized User. 1 unsuccessful login attempts.</p> (1203 ms)
2024-05-18 07:11:06.6|Trace|HttpClient|Response content (82 bytes): <h1>401: Unauthorized</h1><p>Unauthorized User. 1 unsuccessful login attempts.</p>
2024-05-18 07:11:06.6|Error|Transmission|Failed to authenticate with Transmission.

[v4.0.4.1491] NzbDrone.Core.Download.Clients.DownloadClientAuthenticationException: Failed to authenticate with Transmission.
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.AuthenticateClient(HttpRequestBuilder requestBuilder, TransmissionSettings settings, Boolean reauthenticate) in ./Sonarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 241
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.ProcessRequest(String action, Object arguments, TransmissionSettings settings) in ./Sonarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 317
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.GetConfig(TransmissionSettings settings) in ./Sonarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 120
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.GetClientVersion(TransmissionSettings settings) in ./Sonarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 112
   at NzbDrone.Core.Download.Clients.Transmission.Transmission.ValidateVersion() in ./Sonarr.Core/Download/Clients/Transmission/Transmission.cs:line 45
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionBase.TestConnection() in ./Sonarr.Core/Download/Clients/Transmission/TransmissionBase.cs:line 297

2024-05-18 07:11:06.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2024-05-18 07:11:06.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2024-05-18 07:11:06.6|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IDownloadClient>
2024-05-18 07:11:06.6|Trace|SonarrErrorPipeline|Handling Exception
2024-05-18 07:11:06.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Username: Authentication Failure
2024-05-18 07:11:06.6|Trace|Http|Res: 2706 [POST] /api/v3/downloadclient/test: 400.BadRequest (1208 ms)
2024-05-18 07:11:06.6|Debug|Api|[POST] /api/v3/downloadclient/test: 400.BadRequest (1208 ms)
2024-05-18 07:11:08.7|Trace|Http|Req: 2707 [PUT] /api/v3/downloadclient/1 (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)
2024-05-18 07:11:08.7|Trace|EventAggregator|Publishing ProviderUpdatedEvent<IDownloadClient>
2024-05-18 07:11:08.7|Trace|Http|Res: 2707 [PUT] /api/v3/downloadclient/1: 202.Accepted (3 ms)
2024-05-18 07:11:08.7|Debug|Api|[PUT] /api/v3/downloadclient/1: 202.Accepted (3 ms)
2024-05-18 07:11:10.9|Trace|Http|Req: 2708 [GET] /api/v3/health (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)
2024-05-18 07:11:10.9|Trace|Http|Req: 2709 [GET] /api/v3/diskspace (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)
2024-05-18 07:11:10.9|Trace|Http|Res: 2708 [GET] /api/v3/health: 200.OK (0 ms)
2024-05-18 07:11:10.9|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2024-05-18 07:11:10.9|Trace|Http|Req: 2710 [GET] /api/v3/system/status (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)
2024-05-18 07:11:10.9|Trace|Http|Res: 2710 [GET] /api/v3/system/status: 200.OK (0 ms)
2024-05-18 07:11:10.9|Debug|Api|[GET] /api/v3/system/status: 200.OK (0 ms)
2024-05-18 07:11:10.9|Trace|Http|Res: 2709 [GET] /api/v3/diskspace: 200.OK (10 ms)
2024-05-18 07:11:10.9|Debug|Api|[GET] /api/v3/diskspace: 200.OK (10 ms)
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health -> DownloadClientCheck
2024-05-18 07:11:11.6|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health <- DownloadClientCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health -> DownloadClientStatusCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health <- DownloadClientStatusCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health -> DownloadClientRemovesCompletedDownloadsCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health <- DownloadClientRemovesCompletedDownloadsCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health -> DownloadClientRootFolderCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health <- DownloadClientRootFolderCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health -> DownloadClientSortingCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health <- DownloadClientSortingCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health -> ImportMechanismCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health <- ImportMechanismCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health -> IndexerDownloadClientCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health <- IndexerDownloadClientCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health -> RemotePathMappingCheck
2024-05-18 07:11:11.6|Trace|HealthCheckService|Check health <- RemotePathMappingCheck
2024-05-18 07:11:11.6|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2024-05-18 07:11:11.6|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2024-05-18 07:11:11.6|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2024-05-18 07:11:11.6|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2024-05-18 07:11:11.6|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2024-05-18 07:11:11.6|Trace|Http|Req: 2711 [GET] /api/v3/health (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)
2024-05-18 07:11:11.6|Trace|Http|Res: 2711 [GET] /api/v3/health: 200.OK (0 ms)
2024-05-18 07:11:11.6|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2024-05-18 07:11:13.2|Trace|Http|Req: 2712 [GET] /api/v3/log/file (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)
2024-05-18 07:11:13.2|Trace|Http|Res: 2712 [GET] /api/v3/log/file: 200.OK (1 ms)
2024-05-18 07:11:13.2|Debug|Api|[GET] /api/v3/log/file: 200.OK (1 ms)
2024-05-18 07:11:16.5|Trace|Http|Req: 2713 [GET] /logfile/sonarr.trace.txt (from 192.168.1.45 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0)

### Anything else?

I have Keenetic router, which has a Transmission client running directly on it. The router's admin panel is accessible at 192.168.1.1, and the transmission's interface is enabled on port 8090 (by default). Besides the default `admin` user, I created another one specifically for this. Neither of the 2 users can be authorized.

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

Looks like this is an issue with the version of Transmission running on your device, https://forums.sonarr.tv/t/authentication-failure-trying-to-add-transmission-dl-client/30182

**Comment by betterthanever2** [comment]
Thanks @markus101 
So, this means that the client cannot be added at all? In the Transmission's `about` popup I see `Transmission: 3.00 (ab47000043), RPC: 16`. Thread at your link mentioned that the client doesn't have full RPC support. Can you please point me to some resourse that would help me understand what it means?
