### ISSUE TITLE
PostgresHost config field is broken in v4.0.5.1719

### ISSUE THREAD

**Issue by ppoloskov** [Sonarr/Sonarr#6860]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Postgres settings are correctly set in the 'config.xml' file, but when I run Sonarr I get following error (btw, same for Radarr):

### Expected Behavior

Sonarr gets and uses Postgres settings

### Environment

```markdown
Alpine Docker image from onedr0p
```

### What branch are you running?

Develop

### Trace Logs?

[v4.0.5.1719] System.Exception: Could not resolve a service of type 'NzbDrone.Core.Instrumentation.DatabaseTarget' for the parameter 'dbTarget' of method 'Configure' on type 'NzbDrone.Host.Startup'.
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Configuration.ConfigFileProvider.<>c__DisplayClass87_0.<GetValue>b__0() in ./Sonarr.Core/Configuration/ConfigFileProvider.cs:line 308
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Sonarr.Common/Cache/Cached.cs:line 98
   at NzbDrone.Core.Configuration.ConfigFileProvider.GetValue(String key, Object defaultValue, Boolean persist) in ./Sonarr.Core/Configuration/ConfigFileProvider.cs:line 305
   at NzbDrone.Core.Configuration.ConfigFileProvider.get_PostgresHost() in ./Sonarr.Core/Configuration/ConfigFileProvider.cs:line 228
   at NzbDrone.Core.Datastore.ConnectionStringFactory..ctor(IAppFolderInfo appFolderInfo, IConfigFileProvider configFileProvider) in ./Sonarr.Core/Datastore/ConnectionStringFactory.cs:line 25
   at DryIoc.Interpreter.TryInterpretSingletonAndUnwrapContainerException(IResolverContext r, Expression expr, ImMapEntry`1 itemRef, Object& result) in /_/src/DryIoc/Container.cs:line 3110
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 11136
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11055
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 12082
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11038
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 426
   at DryIoc.Container.System.IServiceProvider.GetService(Type serviceType) in /_/src/DryIoc/Container.cs:line 344
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)

**Comment by markus101** [comment]
Sounds like your config file is invalid or otherwise corrupt and it's missing the `<Config>` block.

If you still think this is a bug please post your full configuration file minus your API key.

**Comment by ppoloskov** [comment]
Thank you for reply, Markus. The problem disappered once I rolled-back to 4.0.4, so it's not config related.  I also had to roll Radarr back to 5.5.3. Prowlarr has no problem.

PS: @onedr0p you may be interested, as I use your images

**Comment by onedr0p** [comment]
@ppoloskov did you see this? https://github.com/onedr0p/containers/issues/1013

**Comment by ppoloskov** [comment]
Yes, I saw that. I don't use environment variables, I generate static config.xml using init-container.

7 June 2024 21:00:04 Devin Buhl ***@***.***>:

**Comment by onedr0p** [comment]
> I generate static config.xml using init-container.

Why though? You can literally avoid that jank and reduce complexity by using env vars.

**Comment by markus101** [comment]
We'll improve the logging, but will let you sort out the underlying issue.
