### ISSUE TITLE
Error|DownloadMonitoringService|Couldn't process tracked download   [v4.0.5.1710] System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by BoBeR182** [Sonarr/Sonarr#6885]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Not keeping track with Deluge client.

### Expected Behavior

Track downloads from Deluge

### Steps To Reproduce

Have Deluge crash, restart Sonarr and Deluge, try to readd it by validating Client via "test" and "save" from settings. See this error in log.

### Environment

```markdown
- OS: Arch Linux
- Sonarr: v4.0.5.1710
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox
- Database:
```

### What branch are you running?

Main

### Trace Logs?

2024-06-16 20:46:27.9|Error|DownloadMonitoringService|Couldn't process tracked download 

[v4.0.5.1710] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Parser.Parser.ParseTitle(String title) in ./Sonarr.Core/Parser/Parser.cs:line 789
   at NzbDrone.Core.Parser.ParsingService.GetSeries(String title) in ./Sonarr.Core/Parser/ParsingService.cs:line 72
   at NzbDrone.Core.Download.CompletedDownloadService.Check(TrackedDownload trackedDownload) in ./Sonarr.Core/Download/CompletedDownloadService.cs:line 117
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientItem(IDownloadClient downloadClient, DownloadClientItem downloadItem) in ./Sonarr.Core/Download/TrackedDownloads/DownloadMonitoringService.cs:line 136

**Comment by BoBeR182** [comment]
Amongst the hundreds of the error above.
There is two entries with the following.

```
Message
QueueService failed while processing [TrackedDownloadRefreshedEvent]: Value cannot be null. (Parameter 'input')
Exception
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at NzbDrone.Core.Parser.Parser.RemoveFileExtension(String title) in ./Sonarr.Core/Parser/Parser.cs:line 938
   at NzbDrone.Core.Queue.QueueService.MapQueueItem(TrackedDownload trackedDownload, Episode episode) in ./Sonarr.Core/Queue/QueueService.cs:line 62
   at NzbDrone.Core.Queue.QueueService.MapQueue(TrackedDownload trackedDownload)+MoveNext() in ./Sonarr.Core/Queue/QueueService.cs:line 56
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at NzbDrone.Core.Queue.QueueService.Handle(TrackedDownloadRefreshedEvent message) in ./Sonarr.Core/Queue/QueueService.cs:line 99
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)
```

**Comment by markus101** [comment]
A single error isn't sufficient for trace logs, the seconds error helps more, but still misses on the response from Deluge. Looks like there is an item in Deluge that has no title, which presumably shouldn't happen, so this "crash" you speak of seems to render Deluge quite useless.

If you can provide trace logs, with this response from Deluge so we can see what it is sending back we can see how we might want to fix it.

**Comment by BoBeR182** [comment]
I restarted both sonarr, and deluge, and the re-test and saved the download client.
I cannot reproduce the error anymore.

Attached is the journalctl log if it helps.

```
Jun 16 20:49:15 hostname deluged[3597338]: Traceback (most recent call last):
Jun 16 20:49:15 hostname deluged[3597338]: KeyError: 'a9ffa03c6192769f8a680e172927592614a8d222'
Jun 16 20:49:15 hostname deluged[3597338]:            ~~~~~~~~~~~~~^^^^^^^^^^^^
Jun 16 20:49:15 hostname deluged[3597338]:     return self.torrents[torrent_id]
Jun 16 20:49:15 hostname deluged[3597338]:   File "/usr/lib/python3.12/site-packages/deluge/core/torrentmanager.py", line 308, in __getitem__
Jun 16 20:49:15 hostname deluged[3597338]:              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
Jun 16 20:49:15 hostname deluged[3597338]:     status = self.torrentmanager[torrent_id].get_status(
Jun 16 20:49:15 hostname deluged[3597338]:   File "/usr/lib/python3.12/site-packages/deluge/core/core.py", line 733, in create_torrent_status
Jun 16 20:49:15 hostname deluged[3597338]: Traceback (most recent call last):
Jun 16 20:18:42 hostname deluged[3597338]: Exception: type <class 'deluge.error.AddTorrentError'> not handled
Jun 16 20:18:42 hostname deluged[3597338]:   File "rencode/rencode.pyx", line 322, in rencode._rencode.encode
Jun 16 20:18:42 hostname deluged[3597338]:   File "rencode/rencode.pyx", line 249, in rencode._rencode.encode_list
Jun 16 20:18:42 hostname deluged[3597338]:   File "rencode/rencode.pyx", line 316, in rencode._rencode.encode
Jun 16 20:18:42 hostname deluged[3597338]:   File "rencode/rencode.pyx", line 249, in rencode._rencode.encode_list
Jun 16 20:18:42 hostname deluged[3597338]:   File "rencode/rencode.pyx", line 316, in rencode._rencode.encode
Jun 16 20:18:42 hostname deluged[3597338]:   File "rencode/rencode.pyx", line 336, in rencode._rencode.dumps
Jun 16 20:18:42 hostname deluged[3597338]:                          ^^^^^^^^^^^^^^^^^^^
Jun 16 20:18:42 hostname deluged[3597338]:     body = zlib.compress(rencode.dumps(data))
Jun 16 20:18:42 hostname deluged[3597338]:   File "/usr/lib/python3.12/site-packages/deluge/transfer.py", line 53, in transfer_message
Jun 16 20:18:42 hostname deluged[3597338]:     self.transfer_message(data)
Jun 16 20:18:42 hostname deluged[3597338]:   File "/usr/lib/python3.12/site-packages/deluge/core/rpcserver.py", line 168, in sendData
Jun 16 20:18:42 hostname deluged[3597338]: Traceback (most recent call last):
Jun 16 20:18:42 hostname deluged[3597338]: 20:18:42 [ERROR   ][deluge.core.rpcserver         :1672] type <class 'deluge.error.AddTorrentError'> not handled
```

**Comment by stevietv** [comment]
please do a refresh of the activity queue in Sonarr and share a more complete trace log of that refresh
