### ISSUE TITLE
IMDB Import lists are failing, started few days ago.

### ISSUE THREAD

**Issue by Sokpan** [Sonarr/Sonarr#6915]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

For past 2 days, any IMDB Import List is failing.  It worked up till then, all shows added to IMDB Lists were imported without any issues.
When clicking TEST import list the following error appears "Unable to connect to import list: Radarr API call resulted in an unexpected StatusCode [NotFound]. Check the log surrounding this error for details."

### Expected Behavior

Have IMDB Import List work again, and auto import movies.

### Steps To Reproduce

1. Go to Settings > Import List > + > Other List > IMDB Lists
2. Fill the required field, with for example ls540367013 in List/User ID
3. Click Test or Save

### Environment

```markdown
- OS: Docker
- Sonarr: 4.0.5.1710
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Edge 127.0.2651.8 
- Database: Sqlite 3.44.2
```

### What branch are you running?

Main

### Trace Logs?

[v4.0.5.1710] NzbDrone.Core.ImportLists.Exceptions.ImportListException: Imdb call resulted in an unexpected StatusCode [NotFound]
   at NzbDrone.Core.ImportLists.Imdb.ImdbListParser.PreProcess(ImportListResponse listResponse) in ./Sonarr.Core/ImportLists/Imdb/ImdbListParser.cs:line 46
   at NzbDrone.Core.ImportLists.Imdb.ImdbListParser.ParseResponse(ImportListResponse importListResponse) in ./Sonarr.Core/ImportLists/Imdb/ImdbListParser.cs:line 29
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in ./Sonarr.Core/ImportLists/HttpImportListBase.cs:line 188
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in ./Sonarr.Core/ImportLists/HttpImportListBase.cs:line 216

### Anything else?

Looks like Radarr having same issue, possible IMDB changed their export method. 

Testing IMDB export page https://www.imdb.com/list/ls540367013/export returns 404.

**Comment by markus101** [comment]
Please post the trace logs, not just the exception and link them here.

**Comment by Sokpan** [comment]
> Please post the trace logs, not just the exception and link them here.

Here is the trace logs, tested 3 different IMDB lists.  https://drive.google.com/file/d/1KvPVdq8ujeB7YtTm5kpcmAyTfStAPApt/view?usp=drive_link

**Comment by drwison** [comment]
Seeing the same in 4.0.6.1805.  Looks like the export URL may have changed. Opening the feed URL shown in a browser results in 404. Log excerpt (list no. obfuscated):

```
2024-07-03 11:14:15.8|Debug|ImdbListImport|Downloading Feed https://www.imdb.com/list/ls5413xxxxx/export
2024-07-03 11:14:16.4|Warn|ImdbListImport|Unable to connect to import list

[v4.0.6.1805] NzbDrone.Core.ImportLists.Exceptions.ImportListException: Imdb call resulted in an unexpected StatusCode [NotFound]
   at NzbDrone.Core.ImportLists.Imdb.ImdbListParser.PreProcess(ImportListResponse listResponse) in ./Sonarr.Core/ImportLists/Imdb/ImdbListParser.cs:line 36
   at NzbDrone.Core.ImportLists.Imdb.ImdbListParser.ParseResponse(ImportListResponse importListResponse) in ./Sonarr.Core/ImportLists/Imdb/ImdbListParser.cs:line 19
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.FetchPage(ImportListRequest request, IParseImportListResponse parser) in ./Sonarr.Core/ImportLists/HttpImportListBase.cs:line 190
   at NzbDrone.Core.ImportLists.HttpImportListBase`1.TestConnection() in ./Sonarr.Core/ImportLists/HttpImportListBase.cs:line 216
```

**Comment by drwison** [comment]
Looks like same issue as Radarr issue [#10121](https://github.com/Radarr/Radarr/issues/10121)

**Comment by markus101** [comment]
Based on https://www.reddit.com/r/imdb/comments/1dqi940/bulk_downloading_lists_via_the_export_endpoint_no/ they've removed the export functionality from the UI and then killed the actual export route. Unless they implement another option that doesn't require a user in a browser to interact with the page IMDB lists will no longer be supported.

**Comment by wifiuk** [comment]
the fix in radarr was to switch to using the user's urXXXXXXXX ID number instead of using the lsXXXXXXX number

**Comment by Sokpan** [comment]
> the fix in radarr was to switch to using the user's urXXXXXXXX ID number instead of using the lsXXXXXXX number

That is more of a temporary workaround for users like me who have multiple lists.  For example I have lists based on different Quality Profiles, so if I use User ID, it will pull all the entries under same Profile.

For now I just manually add any new IMDb entry manually into Sonarr/Radarr and hope this is easily fixed soon.

**Comment by petefinch** [comment]
I would like to add I'm also experiencing this issue. 
not sure what I can do to assist the devs but I get the same error as OP

2024-07-08 09:59:22.8|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to import list: Radarr API call resulted in an unexpected StatusCode [NotFound]. Check the log surrounding this error for details.
2024-07-08 09:59:29.7|Warn|IMDbListImport|Unable to connect to list

If you need logs or another beta tester, let me know
cheers for your efforts :)
Pete

**Comment by DaveAlton** [comment]
Can we implement what Radarr has so at least we can import "ur" lists for users' watchlists?

**Comment by DaveAlton** [comment]
> AFAIK not possible directly.

I'm confused. How is Radarr doing it, and we couldn't?

**Comment by markus101** [comment]
User watchlists are weird, they have a regular list behind the scenes which you can get then use directly ([example](https://www.reddit.com/r/radarr/comments/7pdk66/how_to_add_an_imdb_watchlist_in_radarr/)), but that relies on the regular export method and from my testing fails in the same way because the export route is dead.

In my testing with a user watchlist in Radarr, is it's reports that the list is empty, but the request itself doesn't fail because it's routing through Radarr's servers and not hitting IMDB directly. Either it's broken in Radarr too, but in a less obvious way or it's working there and they're getting that data via another unofficial mechanism.

**Comment by petefinch** [comment]
This issue is evident in Sonarr
the UR## works now in Radarr (as of 09.07.24) but the LS# in Sonarr fails with the same error as used to fail in Radarr:
Unable to connect to import list: Imdb call resulted in an unexpected StatusCode [NotFound]. Check the log surrounding this error for details.

**Comment by andreid1303** [comment]
Still no fix? I can confirm that urxxx list is working in Radarr.

**Comment by Crypt0xin** [comment]
" Same, Radarr is working, using the "ur" list prefix.  Would love Sonarr to add this.

**Comment by sup3rmark** [comment]
is there any movement towards a solution for this, or is the imdb list functionality going to be deprecated now?

**Comment by Sokpan** [comment]
> is there any movement towards a solution for this, or is the imdb list functionality going to be deprecated now?

Don't think anyone is working on solution from Sonarr side.  Unless IMDb fixes it on their side, not much we can do but wait.

Not even sure I should close this bug,, since no fix will be done from Sonarr side.

**Comment by DaveAlton** [comment]
Could we not adopt Radarr's implementation so we could still use 'ur' lists?

**Comment by markus101** [comment]
IMDB does not have a free public API, we're not going to use any existing APIs they do have, this includes solutions to make `ur` lists work in Sonarr. Scraping is a non-starter, beyond the fact that it could be banned, it's not something we're going to maintain, no different from not supporting indexers that don't have APIs or RSS feeds that require third party solutions.

A service that translates things into Sonarr's Custom List format would probably be the best path forward without losing the functionality completely.

**Comment by Sokpan** [comment]
Apologies as this is the first bug I have reported, Just wondering as the one reported the bug, what is my next action if I do have any.

So what are next steps? 
Does this need to be escalated to someone on the dev team?
Will someone from dev team be assigned this to review and implement a solution, or will this be closed as a non-solution bug?
Is there a review that needs to be done to discuss possible solutions?

**Comment by markus101** [comment]
Us devs have already responded several times in this thread, there is nothing to escalate. There are no solutions to review at this time because without a publicly available API endpoint there is no way for us to get this information in a fashion we will support. If IMDB makes something available then we'll have to see if it's feasible to support, but as of right now this issue will remain open to avoid duplicate issues and for the eventual removal of IMDB list support.

**Comment by Sokpan** [comment]
> Us devs have already responded several times in this thread, there is nothing to escalate. There are no solutions to review at this time because without a publicly available API endpoint there is no way for us to get this information in a fashion we will support. If IMDB makes something available then we'll have to see if it's feasible to support, but as of right now this issue will remain open to avoid duplicate issues and for the eventual removal of IMDB list support.

Ok, good to know.  So no action on my part, we just leave this issue as Open for others to review if needed.  

Thanks.

**Comment by madAndroid** [comment]
May I ask why the existing Radarr functionality for `ur` IMDB lists isn't being brought in to Sonarr?

**Comment by markus101** [comment]
There is no way to get that information without using an unsupported/unauthorized API.

**Comment by bigdant** [comment]
Any updates on this bug ? Any chance you can slip in the fix thats working for Radarr ?

I know its an IMDB issue, however if they are not looking to move things back to the way they were. whats the plan going forwards ?

Cheers

A massive fan of your work !

**Comment by bigdant** [comment]
Any updates guys ?

Cheers

D.

**Comment by Sokpan** [comment]
> Any updates guys ?
> 
> Cheers
> 
> D.

Since Sonarr team can't do anything, till IMDb fixes the sync issue on their side, I moved my lists to Trakt, and imported everything from IMDb, so far everything working great.  However looking at somehow synching IMDb to Trakt, so can use both.
