### ISSUE TITLE
Finding Parent Path Fails on non-Windows

### ISSUE THREAD

**Issue by AlanMW** [Sonarr/Sonarr#6953]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Minor issue I noticed, posting for visibility and just in case someone else has the issue.

After moving from a windows install to a linux install, my directory for media files changed. 
I expected that because the folders and directory were already in the same folder structure and location, I could select `"No, I will move the files myself"` to avoid sonarr trying to find a non existent drive.
However, if you do, you get the error message below. Instead choose `"yes, move the files"` the root directory update will work. 

```
2024-07-10 23:32:27.5|Fatal|SonarrErrorPipeline|Request Failed. PUT /api/v3/series/editor

[v4.0.6.1805] NzbDrone.Common.Disk.NotParentException: H:\Media\TV Shows\The 100 is not a child of H:\Media\TV Shows
   at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath(String parentPath, String childPath) in ./Sonarr.Common/Extensions/PathExtensions.cs:line 87
   at NzbDrone.Core.Tv.SeriesPathBuilder.GetExistingRelativePath(Series series) in ./Sonarr.Core/Tv/SeriesPathBuilder.cs:line 45
   at NzbDrone.Core.Tv.SeriesPathBuilder.BuildPath(Series series, Boolean useExistingRelativeFolder) in ./Sonarr.Core/Tv/SeriesPathBuilder.cs:line 34
   at NzbDrone.Core.Tv.SeriesService.UpdateSeries(List`1 series, Boolean useExistingRelativeFolder) in ./Sonarr.Core/Tv/SeriesService.cs:line 228
   at Sonarr.Api.V3.Series.SeriesEditorController.SaveAll(SeriesEditorResource resource) in ./Sonarr.Api.V3/Series/SeriesEditorController.cs:line 96
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/BufferingMiddleware.cs:line 27
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/IfModifiedMiddleware.cs:line 40
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/CacheHeaderMiddleware.cs:line 32
   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/StartingUpMiddleware.cs:line 37
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/UrlBaseMiddleware.cs:line 26
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

The directory that I was trying to switch the root to is `/mnt/PlexMedia/TV Shows/` I would expect that because the folders and directory were already in the same folder structure and location, I could select `"No, I will move the files myself"`

### Expected Behavior

`"No, I will move the files myself"` should update the root directory without considering the validity of the preexisting/outdated root directory.

### Steps To Reproduce

from the local web ui:

 Series>Select Series>Select All>Edit>Root Folder>Select the new root folder

### Environment

```markdown
- OS: Ubuntu 22.04 Server
- Sonarr: 4.0.6.1805-ls244 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox
- Database:
```

### What branch are you running?

Main

### Trace Logs?

2024-07-10 23:54:38.2|Trace|Http|Res: 54 [GET] /api/v3/health: 200.OK (0 ms)
2024-07-10 23:54:38.2|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2024-07-10 23:54:42.5|Trace|Scheduler|Pending Tasks: 0
2024-07-10 23:54:42.8|Trace|Http|Req: 55 [GET] /api/v3/filesystem?path=&allowFoldersWithoutTrailingSlashes=true&includeFiles=false (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-10 23:54:42.8|Trace|Http|Res: 55 [GET] /api/v3/filesystem?path=&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (10 ms)
2024-07-10 23:54:42.8|Debug|Api|[GET] /api/v3/filesystem?path=&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (10 ms)
2024-07-10 23:54:45.6|Trace|Http|Req: 56 [GET] /api/v3/filesystem?path=%2Fmnt%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-10 23:54:45.6|Trace|Http|Res: 56 [GET] /api/v3/filesystem?path=%2Fmnt%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (1 ms)
2024-07-10 23:54:45.6|Debug|Api|[GET] /api/v3/filesystem?path=%2Fmnt%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (1 ms)
2024-07-10 23:54:48.3|Trace|Http|Req: 57 [GET] /api/v3/filesystem?path=%2Fmnt%2FPlexMedia%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-10 23:54:48.3|Trace|Http|Res: 57 [GET] /api/v3/filesystem?path=%2Fmnt%2FPlexMedia%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (0 ms)
2024-07-10 23:54:48.3|Debug|Api|[GET] /api/v3/filesystem?path=%2Fmnt%2FPlexMedia%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (0 ms)
2024-07-10 23:54:49.1|Trace|Http|Req: 58 [GET] /api/v3/filesystem?path=%2Fmnt%2FPlexMedia%2FTV%20Shows%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-10 23:54:49.1|Trace|Http|Res: 58 [GET] /api/v3/filesystem?path=%2Fmnt%2FPlexMedia%2FTV%20Shows%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (4 ms)
2024-07-10 23:54:49.1|Debug|Api|[GET] /api/v3/filesystem?path=%2Fmnt%2FPlexMedia%2FTV%20Shows%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (4 ms)
2024-07-10 23:54:50.2|Trace|Http|Req: 59 [POST] /api/v3/rootFolder (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-10 23:54:50.2|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2024-07-10 23:54:50.3|Trace|EventAggregator|Publishing ModelEvent<RootFolder>
2024-07-10 23:54:50.3|Trace|EventAggregator|ModelEvent<RootFolder> -> RootFolderController
2024-07-10 23:54:50.3|Debug|RootFolderService|Generating list of unmapped folders
2024-07-10 23:54:50.3|Debug|RootFolderService|144 unmapped folders detected.
2024-07-10 23:54:50.3|Trace|EventAggregator|ModelEvent<RootFolder> <- RootFolderController
2024-07-10 23:54:50.3|Debug|RootFolderService|Generating list of unmapped folders
2024-07-10 23:54:50.3|Debug|RootFolderService|144 unmapped folders detected.
2024-07-10 23:54:50.3|Trace|Http|Req: 60 [GET] /api/v3/rootFolder (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-10 23:54:50.3|Debug|RootFolderService|Generating list of unmapped folders
2024-07-10 23:54:50.3|Debug|RootFolderService|Generating list of unmapped folders
2024-07-10 23:54:50.3|Debug|RootFolderService|144 unmapped folders detected.
2024-07-10 23:54:50.3|Debug|RootFolderService|144 unmapped folders detected.
2024-07-10 23:54:50.3|Trace|Http|Res: 59 [POST] /api/v3/rootFolder: 201.Created (144 ms)
2024-07-10 23:54:50.3|Debug|Api|[POST] /api/v3/rootFolder: 201.Created (144 ms)
2024-07-10 23:54:50.3|Trace|Http|Res: 60 [GET] /api/v3/rootFolder: 200.OK (5 ms)
2024-07-10 23:54:50.3|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (5 ms)
2024-07-10 23:54:52.5|Trace|Http|Req: 61 [PUT] /api/v3/series/editor (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-10 23:54:52.5|Debug|SeriesService|Updating 156 series
2024-07-10 23:54:52.5|Trace|SeriesService|Updating: One Piece
2024-07-10 23:54:52.5|Trace|SonarrErrorPipeline|Handling Exception
2024-07-10 23:54:52.5|Fatal|SonarrErrorPipeline|Request Failed. PUT /api/v3/series/editor

[v4.0.6.1805] NzbDrone.Common.Disk.NotParentException: /app/sonarr/bin/H:\Media\TV Shows\One Piece (1999) is not a child of /app/sonarr/bin/H:/Media/TV Shows
   at NzbDrone.Common.Extensions.PathExtensions.GetRelativePath(String parentPath, String childPath) in ./Sonarr.Common/Extensions/PathExtensions.cs:line 87
   at NzbDrone.Core.Tv.SeriesPathBuilder.GetExistingRelativePath(Series series) in ./Sonarr.Core/Tv/SeriesPathBuilder.cs:line 45
   at NzbDrone.Core.Tv.SeriesPathBuilder.BuildPath(Series series, Boolean useExistingRelativeFolder) in ./Sonarr.Core/Tv/SeriesPathBuilder.cs:line 34
   at NzbDrone.Core.Tv.SeriesService.UpdateSeries(List`1 series, Boolean useExistingRelativeFolder) in ./Sonarr.Core/Tv/SeriesService.cs:line 228
   at Sonarr.Api.V3.Series.SeriesEditorController.SaveAll(SeriesEditorResource resource) in ./Sonarr.Api.V3/Series/SeriesEditorController.cs:line 96
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2024-07-10 23:54:52.5|Trace|Http|Res: 61 [PUT] /api/v3/series/editor: 500.InternalServerError (42 ms)
2024-07-10 23:54:52.5|Debug|Api|[PUT] /api/v3/series/editor: 500.InternalServerError (42 ms)
2024-07-10 23:54:55.3|Trace|HealthCheckService|Check health -> DownloadClientRemovesCompletedDownloadsCheck
2024-07-10 23:54:55.3|Debug|DownloadClientProvider|Temporarily ignoring client Deluge WebUI till 07/10/2024 23:59:12 due to recent failures.
2024-07-10 23:54:55.3|Trace|HealthCheckService|Check health <- DownloadClientRemovesCompletedDownloadsCheck
2024-07-10 23:54:55.3|Trace|HealthCheckService|Check health -> DownloadClientRootFolderCheck
2024-07-10 23:54:55.3|Debug|DownloadClientProvider|Temporarily ignoring client Deluge WebUI till 07/10/2024 23:59:12 due to recent failures.
2024-07-10 23:54:55.3|Trace|HealthCheckService|Check health <- DownloadClientRootFolderCheck
2024-07-10 23:54:55.3|Trace|HealthCheckService|Check health -> DownloadClientSortingCheck
2024-07-10 23:54:55.3|Debug|DownloadClientProvider|Temporarily ignoring client Deluge WebUI till 07/10/2024 23:59:12 due to recent failures.
2024-07-10 23:54:55.3|Trace|HealthCheckService|Check health <- DownloadClientSortingCheck
2024-07-10 23:54:55.3|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2024-07-10 23:54:55.3|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2024-07-10 23:54:55.3|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2024-07-10 23:54:55.3|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2024-07-10 23:54:55.3|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2024-07-10 23:54:55.3|Trace|Http|Req: 62 [GET] /api/v3/health (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-10 23:54:55.3|Trace|Http|Req: 63 [GET] /api/v3/diskspace (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-10 23:54:55.3|Trace|Http|Res: 62 [GET] /api/v3/health: 200.OK (0 ms)
2024-07-10 23:54:55.3|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2024-07-10 23:54:55.3|Trace|Http|Req: 64 [GET] /api/v3/system/status (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-10 23:54:55.3|Trace|Http|Res: 64 [GET] /api/v3/system/status: 200.OK (2 ms)
2024-07-10 23:54:55.3|Debug|Api|[GET] /api/v3/system/status: 200.OK (2 ms)
2024-07-10 23:54:55.3|Trace|Http|Req: 65 [GET] /api/v3/health (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-10 23:54:55.3|Trace|Http|Res: 63 [GET] /api/v3/diskspace: 200.OK (5 ms)
2024-07-10 23:54:55.3|Debug|Api|[GET] /api/v3/diskspace: 200.OK (5 ms)
2024-07-10 23:54:55.3|Trace|Http|Res: 65 [GET] /api/v3/health: 200.OK (0 ms)
2024-07-10 23:54:55.3|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2024-07-10 23:54:56.5|Trace|Http|Req: 66 [GET] /api/v3/log/file (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-10 23:54:56.5|Trace|Http|Res: 66 [GET] /api/v3/log/file: 200.OK (0 ms)
2024-07-10 23:54:56.5|Debug|Api|[GET] /api/v3/log/file: 200.OK (0 ms)
2024-07-10 23:55:03.4|Trace|Http|Req: 67 [GET] /api/v3/log/file (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-10 23:55:03.4|Trace|Http|Res: 67 [GET] /api/v3/log/file: 200.OK (2 ms)
2024-07-10 23:55:03.4|Debug|Api|[GET] /api/v3/log/file: 200.OK (2 ms)
2024-07-10 23:55:04.7|Trace|Http|Req: 68 [GET] /logfile/sonarr.trace.txt (from 192.168.1.24 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0)

### Anything else?

one of the attempts it actually updated all the directories with `/app/sonarr/bin/` before the existing directory

**Comment by bakerboy448** [comment]
while you await this to be acted upon and triaged.

Toolbarr can handle the DB path changes for ya https://github.com/Notifiarr/toolbarr
