### ISSUE TITLE
Sonarr taking too much time to import titles

### ISSUE THREAD

**Issue by ManuXD32** [Sonarr/Sonarr#6968]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have noticed that Sonarr has been importing slowly than usual, a couple of days ago it just started going this slow. I have set up a radiz2 with 5 HDDs of 8TB each, I know this config is not the fastest, but still it shouldn't be this slow, as everything is happening inside those drives, the downloads from transmission and the root tv folder of Sonarr.

Is anything I can do to speed it up?
![image](https://github.com/user-attachments/assets/a9e880d0-eca5-4f5a-9791-9850fa19a070)

Thanks in advance!

### Expected Behavior

Imports taking less time

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.7.1863
- Docker Install: yes 
- Using Reverse Proxy: No 
- Browser: 
- Database: Sqlite
```

### What branch are you running?

Main

### Trace Logs?

./Sonarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 318
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.GetTorrentStatus(IEnumerable`1 hashStrings, TransmissionSettings settings) in ./Sonarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 195
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.GetTorrents(TransmissionSettings settings) in ./Sonarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 43
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionBase.GetItems() in ./Sonarr.Core/Download/Clients/Transmission/TransmissionBase.cs:line 40
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in ./Sonarr.Core/Download/TrackedDownloads/DownloadMonitoringService.cs:line 90

2024-07-15 16:06:11.2|Info|SceneMappingService|Updating Scene mappings
2024-07-15 16:09:21.3|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from Transmission

[v4.0.7.1863] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to Transmission, please check your settings
 ---> System.Net.WebException: Http request timed out
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Sonarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 144
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Sonarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionProxy.ProcessRequest(String action, Object arguments, TransmissionSettings settings) in ./Sonarr.Core/Download/Clients/Transmission/TransmissionProxy.cs:line 318
   --- End of inner exception stack trace ---

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by ManuXD32** [comment]
Solved, for anyone else with this problem, just map one volume, for example "/data:/data" inside "/data" in your host you should have the downloads folder of your torrent provider and the TV folder of your shows. Follow the trash guides for more in depth info.
