### ISSUE TITLE
Unable to import From Download Client if path contains leading or trailing spaces

### ISSUE THREAD

**Issue by ItzDerock** [Sonarr/Sonarr#6971]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Currently, Sonarr does not allow files with leading/trailing spaces and rejects them as non-valid *NIX paths. The behavior was added #6735 in response to issue #6709 which claimed that paths with untrimmed spaces lead Sonarr "to use a fallback such as `/tv/B5SWE7~C`".

To my knowledge, this is false. The garbled folder is actually [an SMB "feature"](<https://superuser.com/questions/458995/files-folders-get-weird-names-and-become-inaccessible-on-samba-share>), and is completely unrelated to UNIX systems and Sonarr. Samba was originally designed for Windows and older DOS-systems which have strict filename requirements. UNIX systems, in comparison, have much more relaxed requirements, so when running a samba server on a UNIX system, it is possible to have folders that break Windows folder naming rules. This is where samba's [name mangling](<https://www.oreilly.com/openbook/samba/book/ch05_04.html>) feature comes into play. It "translates" those Windows-invalid but *NIX-correct paths into something Windows can understand. The translation is very messy and the documentation labels a few examples of this translation:
```
virtuosity.dat                       VIRTU~F1.DAT
.htaccess                            HTACC~U0._ _ _
hello.java                           HELLO~1F.JAV
team.config.txt                      TEAMC~04.TXT
antidisestablishmentarianism.txt     ANTID~E3.TXT
antidiseast.txt                      ANTID~9K.TXT
```

The format of the resulting paths match very closely to examples provided in #6709.

Furthermore, if you boot up a Linux machine, you can clearly observe that trailing spaces are in-fact allowed:
![image](https://github.com/user-attachments/assets/2c202f60-4baa-4d73-8d51-5b97c169b266)

### Expected Behavior

Paths with leading/trailing spaces should not be rejected as being an invalid *nix path. 

```
[Warn] ArgumentValidator: value [/media/TV/My Show/Season 1/Trailing Space / Leading Space.mp4]  is not a valid *nix path. paths must start with / 
```

### Environment

```markdown
- OS: Debian 12
- Sonarr: 4.0.7.1863
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: N/A
- Database: Sqlite 3.45.3
```

### What branch are you running?

Main

### Trace Logs?

n/a

### Anything else?

For those who stream their content from a folder managed by Sonarr on Linux via Samba on Windows devices, maybe add an option to enable the stricter check. This way, those who do not use Windows + Samba (i.e. people who stream from jellyfin running on Linux) can keep this option disabled.

Would also like to add that the current check will cause certain downloads from qbittorrent to never be imported, since qbittorrent will happily create files and folders with untrimmed whitespace. I happened to run into this issue and had a hard time figuring out what was happening.

~~The current workaround for this is to manually rename the files in the qbittorrent GUI and remove the excess whitespace.~~ nvm, does not work

**Comment by markus101** [comment]
Requiring a user that hosts SMB on Linux and accesses it on Windows to enable a setting in order to access files without them being mangled is not something we're going to invest time into implementing.

> Would also like to add that the current check will cause certain downloads from qbittorrent to never be imported, since qbittorrent will happily create files and folders with untrimmed whitespace. I happened to run into this issue and had a hard time figuring out what was happening.

This is a valid issue, but requires trace logs to investigate.

**Comment by thezoggy** [comment]
Seen a few people with truenas core/omv, they just had to set  `mangled names = no` in their  smb.conf to stop the mangling.

**Comment by ItzDerock** [comment]
> Requiring a user that hosts SMB on Linux and accesses it on Windows to enable a setting in order to access files without them being mangled is not something we're going to invest time into implementing.

I get what you're trying to say here, but I also do think it is misleading to mark valid *NIX paths as invalid in order to cater for SMB users and SMB limitations. Maybe that setting can be defaulted to on for simplicity, and users who do not use Windows/SMB and want to use valid *NIX paths can explicitly disable it. Even something as simple as an environment variable would be enough.

**Comment by ItzDerock** [comment]
> This is a valid issue, but requires trace logs to investigate.

The logs do not have much apart from this error. Relevant parts:
```
2024-07-15 22:25:59.2|Debug|DownloadedEpisodesImportService|Processing path: /media/Downloads/[Erai-raws] Oshi no Ko 2nd Season - 01 [1080p][Multiple Subtitle][6F122B65].mkv
2024-07-15 22:25:59.2|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2024-07-15 22:25:59.2|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2024-07-15 22:25:59.2|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2024-07-15 22:25:59.2|Trace|EventAggregator|CommandExecutedEvent -> QualityDefinitionController
2024-07-15 22:25:59.2|Trace|EventAggregator|CommandExecutedEvent <- QualityDefinitionController
2024-07-15 22:25:59.2|Trace|CommandExecutor|RefreshMonitoredDownloadsCommand <- DownloadMonitoringService [00:00:01.6420744]
2024-07-15 22:25:59.2|Warn|ArgumentValidator|value [/media/Anime/Oshi no Ko/Season 1/[Lilith-Raws] [我推的孩子] / Oshi no Ko - 11 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4]  is not a valid *nix path. paths must start with /
2024-07-15 22:25:59.2|Trace|Http|Req: 61 [GET] /api/v3/command (from 192.168.176.1 Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0)
2024-07-15 22:25:59.2|Trace|CommandQueueManager|Getting all commands
2024-07-15 22:25:59.2|Debug|DownloadProcessingService|Failed to process download: [Erai-raws] Oshi no Ko 2nd Season - 01 [1080p][Multiple Subtitle] [ENG][FRE]

[v4.0.7.1863] System.ArgumentException: value [/media/Anime/Oshi no Ko/Season 1/[Lilith-Raws] [我推的孩子] / Oshi no Ko - 11 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4]  is not a valid *nix path. paths must start with / (Parameter 'path')
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsValidPath(Param`1 param, PathValidationType validationType) in ./Sonarr.Common/EnsureThat/EnsureStringExtensions.cs:line 119
   at NzbDrone.Common.Extensions.PathExtensions.CleanFilePath(String path) in ./Sonarr.Common/Extensions/PathExtensions.cs:line 39
   at NzbDrone.Common.PathEqualityComparer.GetHashCode(String obj) in ./Sonarr.Common/PathEqualityComparer.cs:line 27
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ExceptIterator[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.MediaFileService.FilterExistingFiles(List`1 files, List`1 seriesFiles, Series series) in ./Sonarr.Core/MediaFiles/MediaFileService.cs:line 125
   at NzbDrone.Core.MediaFiles.MediaFileService.FilterExistingFiles(List`1 files, Series series) in ./Sonarr.Core/MediaFiles/MediaFileService.cs:line 93
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.GetImportDecisions(List`1 videoFiles, Series series, DownloadClientItem downloadClientItem, ParsedEpisodeInfo folderInfo, Boolean sceneSource, Boolean filterExistingFiles) in ./Sonarr.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs:line 69
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.GetImportDecisions(List`1 videoFiles, Series series, DownloadClientItem downloadClientItem, ParsedEpisodeInfo folderInfo, Boolean sceneSource) in ./Sonarr.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs:line 64
   at NzbDrone.Core.MediaFiles.DownloadedEpisodesImportService.ProcessFile(FileInfo fileInfo, ImportMode importMode, Series series, DownloadClientItem downloadClientItem) in ./Sonarr.Core/MediaFiles/DownloadedEpisodesImportService.cs:line 287
   at NzbDrone.Core.MediaFiles.DownloadedEpisodesImportService.ProcessPath(String path, ImportMode importMode, Series series, DownloadClientItem downloadClientItem) in ./Sonarr.Core/MediaFiles/DownloadedEpisodesImportService.cs:line 102
   at NzbDrone.Core.Download.CompletedDownloadService.Import(TrackedDownload trackedDownload) in ./Sonarr.Core/Download/CompletedDownloadService.cs:line 146
   at NzbDrone.Core.Download.DownloadProcessingService.Execute(ProcessMonitoredDownloadsCommand message) in ./Sonarr.Core/Download/DownloadProcessingService.cs:line 64

2024-07-15 22:25:59.2|Debug|DownloadedEpisodesImportService|Processing path: /media/Downloads/Oshi.No.Ko.S02E02.Chinese.Whispers.2160p.B-Global.WEB-DL.JPN.AAC2.0.H.264.MSubs-ToonsHub.mkv
2024-07-15 22:25:59.2|Trace|Http|Res: 61 [GET] /api/v3/command: 200.OK (5 ms)
2024-07-15 22:25:59.2|Debug|Api|[GET] /api/v3/command: 200.OK (5 ms)
2024-07-15 22:25:59.2|Warn|ArgumentValidator|value [/media/Anime/Oshi no Ko/Season 1/[Lilith-Raws] [我推的孩子] / Oshi no Ko - 11 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4]  is not a valid *nix path. paths must start with /
2024-07-15 22:25:59.2|Debug|DownloadProcessingService|Failed to process download: Oshi.No.Ko.S02E02.Chinese.Whispers.2160p.B-Global.WEB-DL.JPN.AAC2.0.H.264.MSubs-ToonsHub.mkv

[v4.0.7.1863] System.ArgumentException: value [/media/Anime/Oshi no Ko/Season 1/[Lilith-Raws] [我推的孩子] / Oshi no Ko - 11 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4]  is not a valid *nix path. paths must start with / (Parameter 'path')
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsValidPath(Param`1 param, PathValidationType validationType) in ./Sonarr.Common/EnsureThat/EnsureStringExtensions.cs:line 119
   at NzbDrone.Common.Extensions.PathExtensions.CleanFilePath(String path) in ./Sonarr.Common/Extensions/PathExtensions.cs:line 39
   at NzbDrone.Common.PathEqualityComparer.GetHashCode(String obj) in ./Sonarr.Common/PathEqualityComparer.cs:line 27
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ExceptIterator[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.MediaFileService.FilterExistingFiles(List`1 files, List`1 seriesFiles, Series series) in ./Sonarr.Core/MediaFiles/MediaFileService.cs:line 125
   at NzbDrone.Core.MediaFiles.MediaFileService.FilterExistingFiles(List`1 files, Series series) in ./Sonarr.Core/MediaFiles/MediaFileService.cs:line 93
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.GetImportDecisions(List`1 videoFiles, Series series, DownloadClientItem downloadClientItem, ParsedEpisodeInfo folderInfo, Boolean sceneSource, Boolean filterExistingFiles) in ./Sonarr.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs:line 69
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.GetImportDecisions(List`1 videoFiles, Series series, DownloadClientItem downloadClientItem, ParsedEpisodeInfo folderInfo, Boolean sceneSource) in ./Sonarr.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs:line 64
   at NzbDrone.Core.MediaFiles.DownloadedEpisodesImportService.ProcessFile(FileInfo fileInfo, ImportMode importMode, Series series, DownloadClientItem downloadClientItem) in ./Sonarr.Core/MediaFiles/DownloadedEpisodesImportService.cs:line 287
   at NzbDrone.Core.MediaFiles.DownloadedEpisodesImportService.ProcessPath(String path, ImportMode importMode, Series series, DownloadClientItem downloadClientItem) in ./Sonarr.Core/MediaFiles/DownloadedEpisodesImportService.cs:line 102
   at NzbDrone.Core.Download.CompletedDownloadService.Import(TrackedDownload trackedDownload) in ./Sonarr.Core/Download/CompletedDownloadService.cs:line 146
   at NzbDrone.Core.Download.DownloadProcessingService.Execute(ProcessMonitoredDownloadsCommand message) in ./Sonarr.Core/Download/DownloadProcessingService.cs:line 64

2024-07-15 22:25:59.2|Trace|EventAggregator|Publishing DownloadsProcessedEvent
2024-07-15 22:25:59.2|Trace|EventAggregator|DownloadsProcessedEvent -> DownloadMonitoringService
2024-07-15 22:25:59.2|Trace|EventAggregator|Publishing TrackedDownloadRefreshedEvent
2024-07-15 22:25:59.2|Trace|EventAggregator|TrackedDownloadRefreshedEvent -> QueueService
2024-07-15 22:25:59.2|Trace|EventAggregator|Publishing QueueUpdatedEvent
2024-07-15 22:25:59.2|Trace|EventAggregator|QueueUpdatedEvent -> QueueController
2024-07-15 22:25:59.2|Trace|EventAggregator|QueueUpdatedEvent <- QueueController
2024-07-15 22:25:59.2|Trace|EventAggregator|QueueUpdatedEvent -> QueueDetailsController
2024-07-15 22:25:59.2|Trace|EventAggregator|QueueUpdatedEvent <- QueueDetailsController
2024-07-15 22:25:59.2|Trace|EventAggregator|QueueUpdatedEvent -> QueueStatusController
2024-07-15 22:25:59.2|Trace|EventAggregator|QueueUpdatedEvent <- QueueStatusController
2024-07-15 22:25:59.2|Trace|EventAggregator|TrackedDownloadRefreshedEvent <- QueueService
2024-07-15 22:25:59.2|Trace|EventAggregator|DownloadsProcessedEvent <- DownloadMonitoringService
2024-07-15 22:25:59.2|Trace|EventAggregator|DownloadsProcessedEvent ~> NotificationService
2024-07-15 22:25:59.2|Trace|CommandQueueManager|Updating command status
```

Path set in sonarr: `/media/Anime/Oshi no Ko`

**Comment by tmsholy** [comment]
I've just run into this issue as well. I'm running Sonarr 4.0.8.1902 on Debian. My issue was a trailing whitespace on a folder.

```
[Warn] ArgumentValidator: value [/data/downloads/torrent/sonarr/The Book of Boba Fett (2021) S01 (2160p DSNP WEB-DL Hybrid H265 DV HDR DDP Atmos 5.1 English - HONE) ]  is not a valid *nix path. paths must start with / 
```
I fixed it by renaming the folder in qBittorrent web UI and restarting Sonarr.
