### ISSUE TITLE
Refresh Series Running for 4+ hours

### ISSUE THREAD

**Issue by ceadd** [Sonarr/Sonarr#7056]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Refresh Series	12 hours	15 hours ago	04:22:42	now

### Expected Behavior

On average it takes my library 2 hours to refresh, since the last update its taking 4+

### Environment

```markdown
- OS: Synology DSM 7.2.1-69057 Update 5
- Sonarr: 4.0.8.1874-ls248 by linuxserver.io
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Firefox
- Database: Sqlite 3.45.3
```

### What branch are you running?

Main

### Trace Logs?

2024-08-01 17:36:21.2|Info|RefreshEpisodeService|Starting episode info refresh for: [411173][That '90s Show]
2024-08-01 17:36:30.9|Info|RefreshEpisodeService|Finished episode refresh for series: [411173][That '90s Show].
2024-08-01 17:36:30.9|Info|RefreshSeriesService|Updating That Time I Got Reincarnated as a Slime
2024-08-01 17:36:31.7|Info|RefreshEpisodeService|Starting episode info refresh for: [352408][That Time I Got Reincarnated as a Slime]
2024-08-01 17:37:03.8|Info|RefreshEpisodeService|Finished episode refresh for series: [352408][That Time I Got Reincarnated as a Slime].
2024-08-01 17:37:29.6|Info|RefreshSeriesService|Skipping refresh of series: The Titans That Built America
2024-08-01 17:37:29.6|Info|RefreshSeriesService|Updating TMZ Investigates
2024-08-01 17:37:30.0|Info|RefreshEpisodeService|Starting episode info refresh for: [445142][TMZ Investigates]
2024-08-01 17:37:38.0|Info|RefreshEpisodeService|Finished episode refresh for series: [445142][TMZ Investigates].
2024-08-01 17:37:38.0|Info|RefreshSeriesService|Updating To Catch a Smuggler
2024-08-01 17:37:38.7|Info|RefreshEpisodeService|Starting episode info refresh for: [264244][To Catch a Smuggler]
2024-08-01 17:38:07.0|Info|RefreshEpisodeService|Finished episode refresh for series: [264244][To Catch a Smuggler].
2024-08-01 17:38:07.0|Info|RefreshSeriesService|Updating The Tonight Show Starring Jimmy Fallon
2024-08-01 17:38:07.5|Info|RefreshEpisodeService|Starting episode info refresh for: [270261][The Tonight Show Starring Jimmy Fallon]
2024-08-01 17:40:28.4|Error|TaskExtensions|Task Error

[v4.0.8.1874] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1058
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 188
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 151
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push[TCommand](TCommand command, CommandPriority priority, CommandTrigger trigger) in ./Sonarr.Core/Messaging/Commands/CommandQueueManager.cs:line 138
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push(String commandName, Nullable`1 lastExecutionTime, Nullable`1 lastStartTime, CommandPriority priority, CommandTrigger trigger) in ./Sonarr.Core/Messaging/Commands/CommandQueueManager.cs:line 142
   at NzbDrone.Core.Jobs.Scheduler.ExecuteCommands() in ./Sonarr.Core/Jobs/Scheduler.cs:line 42
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2024-08-01 17:42:08.9|Error|CommandExecutor|Error occurred while executing task ProcessMonitoredDownloads

[v4.0.8.1874] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2858
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
   at NzbDrone.Core.Datastore.BasicRepository`1.UpdateFields(IDbConnection connection, IDbTransaction transaction, TModel model, List`1 propertiesToUpdate) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 385
   at NzbDrone.Core.Datastore.BasicRepository`1.SetFields(TModel model, Expression`1[] properties) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 335
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in ./Sonarr.Core/Messaging/Commands/CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in ./Sonarr.Core/Messaging/Commands/CommandExecutor.cs:line 42

2024-08-01 17:42:42.9|Error|TaskExtensions|Task Error

[v4.0.8.1874] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1058
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 188
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 151
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push[TCommand](TCommand command, CommandPriority priority, CommandTrigger trigger) in ./Sonarr.Core/Messaging/Commands/CommandQueueManager.cs:line 138
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push(String commandName, Nullable`1 lastExecutionTime, Nullable`1 lastStartTime, CommandPriority priority, CommandTrigger trigger) in ./Sonarr.Core/Messaging/Commands/CommandQueueManager.cs:line 142
   at NzbDrone.Core.Jobs.Scheduler.ExecuteCommands() in ./Sonarr.Core/Jobs/Scheduler.cs:line 42
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2024-08-01 17:45:30.1|Error|TaskExtensions|Task Error

[v4.0.8.1874] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1058
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 188
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 151
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push[TCommand](TCommand command, CommandPriority priority, CommandTrigger trigger) in ./Sonarr.Core/Messaging/Commands/CommandQueueManager.cs:line 138
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push(String commandName, Nullable`1 lastExecutionTime, Nullable`1 lastStartTime, CommandPriority priority, CommandTrigger trigger) in ./Sonarr.Core/Messaging/Commands/CommandQueueManager.cs:line 142
   at NzbDrone.Core.Jobs.Scheduler.ExecuteCommands() in ./Sonarr.Core/Jobs/Scheduler.cs:line 42
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

2024-08-01 17:48:57.9|Error|CommandExecutor|Error occurred while executing task ProcessMonitoredDownloads

[v4.0.8.1874] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2858
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
   at NzbDrone.Core.Datastore.BasicRepository`1.UpdateFields(IDbConnection connection, IDbTransaction transaction, TModel model, List`1 propertiesToUpdate) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 385
   at NzbDrone.Core.Datastore.BasicRepository`1.SetFields(TModel model, Expression`1[] properties) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 335
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Update(CommandModel command, CommandStatus status, String message) in ./Sonarr.Core/Messaging/Commands/CommandQueueManager.cs:line 258
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Complete(CommandModel command, String message) in ./Sonarr.Core/Messaging/Commands/CommandQueueManager.cs:line 206
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in ./Sonarr.Core/Messaging/Commands/CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in ./Sonarr.Core/Messaging/Commands/CommandExecutor.cs:line 42

2024-08-01 17:49:07.5|Info|RefreshEpisodeService|Finished episode refresh for series: [270261][The Tonight Show Starring Jimmy Fallon].
2024-08-01 17:49:07.5|Info|RefreshSeriesService|Skipping refresh of series: The Toys That Built America
2024-08-01 17:49:07.5|Info|RefreshSeriesService|Updating True Detective
2024-08-01 17:49:08.1|Info|RefreshEpisodeService|Starting episode info refresh for: [270633][True Detective]
2024-08-01 17:49:20.8|Info|RefreshEpisodeService|Finished episode refresh for series: [270633][True Detective].
2024-08-01 17:49:20.8|Info|RefreshSeriesService|Updating Tulsa King
2024-08-01 17:49:21.5|Info|RefreshEpisodeService|Starting episode info refresh for: [413215][Tulsa King]
2024-08-01 17:49:27.2|Info|RefreshEpisodeService|Finished episode refresh for series: [413215][Tulsa King].
2024-08-01 17:49:27.2|Info|RefreshSeriesService|Updating The Umbrella Academy
2024-08-01 17:49:27.3|Info|RefreshEpisodeService|Starting episode info refresh for: [353764][The Umbrella Academy]
2024-08-01 17:49:39.2|Info|RefreshEpisodeService|Finished episode refresh for series: [353764][The Umbrella Academy].
2024-08-01 17:49:39.2|Info|RefreshSeriesService|Updating The UnBelievable with Dan Aykroyd
2024-08-01 17:49:39.6|Info|RssSyncService|Starting RSS Sync
2024-08-01 17:49:45.6|Info|RefreshEpisodeService|Starting episode info refresh for: [441983][The UnBelievable with Dan Aykroyd]
2024-08-01 17:49:50.1|Info|RefreshEpisodeService|Finished episode refresh for series: [441983][The UnBelievable with Dan Aykroyd].
2024-08-01 17:49:50.1|Info|RefreshSeriesService|Updating Unearthed (2016)
2024-08-01 17:49:53.7|Info|DownloadDecisionMaker|Processing 515 releases
2024-08-01 17:49:54.0|Info|RefreshEpisodeService|Starting episode info refresh for: [314158][Unearthed (2016)]
2024-08-01 17:49:54.8|Info|RssSyncService|RSS Sync Completed. Reports found: 515, Reports grabbed: 0
2024-08-01 17:50:21.5|Info|RssSyncService|Starting RSS Sync
2024-08-01 17:50:36.5|Info|DownloadDecisionMaker|Processing 515 releases
2024-08-01 17:50:37.4|Info|RssSyncService|RSS Sync Completed. Reports found: 515, Reports grabbed: 0
2024-08-01 17:50:46.5|Info|RefreshEpisodeService|Finished episode refresh for series: [314158][Unearthed (2016)].
2024-08-01 17:50:46.5|Info|RefreshSeriesService|Updating Unsolved Mysteries
2024-08-01 17:50:52.6|Info|RefreshEpisodeService|Starting episode info refresh for: [76644][Unsolved Mysteries]
2024-08-01 17:52:07.7|Error|CommandExecutor|Error occurred while executing task RefreshMonitoredDownloads

[v4.0.8.1874] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2858
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
   at NzbDrone.Core.Datastore.BasicRepository`1.UpdateFields(IDbConnection connection, IDbTransaction transaction, TModel model, List`1 propertiesToUpdate) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 385
   at NzbDrone.Core.Datastore.BasicRepository`1.SetFields(TModel model, Expression`1[] properties) in ./Sonarr.Core/Datastore/BasicRepository.cs:line 335
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Update(CommandModel command, CommandStatus status, String message) in ./Sonarr.Core/Messaging/Commands/CommandQueueManager.cs:line 258
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Fail(CommandModel command, String message, Exception e) in ./Sonarr.Core/Messaging/Commands/CommandQueueManager.cs:line 215
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in ./Sonarr.Core/Messaging/Commands/CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in ./Sonarr.Core/Messaging/Commands/CommandExecutor.cs:line 42

### Anything else?

I know this isn't a favourite request but... do we really need refresh series to run every 12 hours?

**Comment by thezoggy** [comment]
> On average it takes my library 2 hours to refresh, since the last update its taking 4+

That is a you problem that you should look into. If you have underpowered/oversubscribed machine you need to throw more resources at it or look at why things are being so taxed.

i'll give you this as reference (and for most people) refreshing your series should be only a few minutes:
![firefox_2024-08-02_11-31-39](https://github.com/user-attachments/assets/d29f7930-11c6-4fe2-8fac-1090800e2b09)

now if your doing funky things like storing your files remotely on some far end server on the other side of the planet, that will add delays. but none of this is a sonarr bug, go join sonarr discord/support areas and we can nitpick at your setup to try and tell you whats suboptimal (most likely how your doing your docker volumes) or perhaps its purely where/how your storing your sonarr db..as you have a bunch of locks happening.

**Comment by thezoggy** [comment]
you really should join sonarr discord and share your setup, if radarr isnt having problems and only sonarr.. then prob just something on how you configured your sonarr one and the suboptimal nature rears its head because sonarr does more db stuff (series + episodes total is prob larger than your movies total).  and getting an ssd will only mask the issue somewhat (not that you shoudlnt have an ssd in the first place, but its not going to magically fix badly configured paths)

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) if you continue to experience issues.
