### ISSUE TITLE
On Download Webhook Fails

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#7149]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Webhook base fails with System.NullReferenceException: Object reference not set to an instance of an object. 

### Expected Behavior

Regression

### Environment

```markdown
- OS: 22.04
- Sonarr: v4.0.9.2278
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: n/a
- Database: 
Postgresql 16.4
Database Migration
211
```

### What branch are you running?

Develop

### Trace Logs?

```
2024-08-27 02:07:04.9|Debug|DiskTransferService|HardLinkOrCopy [/mnt/data/torrents/tv/Only.Murders.in.the.Building.S04E01.Once.Upon.a.Time.in.the.West.1080p.DSNP.WEB-DL.DDP5.1.H.264-FLUX.mkv] > [/mnt/data/media/tv/Only Murders in the Building (2021) {imdb-tt11691774}/Season 04/Only Murders in the Building (2021) - S04E01 - Once Upon a Time in the West [DSNP WEBDL-1080p][EAC3 5.1][h264]-FLUX.mkv]
2024-08-27 02:07:04.9|Trace|ConfigService|Using default config value for 'filedate' defaultValue:'None'
2024-08-27 02:07:04.9|Trace|ConfigService|Using default config value for 'setpermissionslinux' defaultValue:'False'
2024-08-27 02:07:04.9|Trace|EventAggregator|Publishing EpisodeFileAddedEvent
2024-08-27 02:07:04.9|Trace|EventAggregator|EpisodeFileAddedEvent -> EpisodeService
2024-08-27 02:07:05.0|Trace|EventAggregator|Publishing ModelEvent<Episode>
2024-08-27 02:07:05.0|Trace|EventAggregator|ModelEvent<Episode> -> CutoffController
2024-08-27 02:07:05.0|Trace|CustomFormatCalculationService|Using scene name for release title: Only.Murders.in.the.Building.S04E01.Once.Upon.a.Time.in.the.West.1080p.DSNP.WEB-DL.DDP5.1.H.264-FLUX
2024-08-27 02:07:05.0|Trace|EventAggregator|ModelEvent<Episode> <- CutoffController
2024-08-27 02:07:05.0|Trace|EventAggregator|ModelEvent<Episode> -> MissingController
2024-08-27 02:07:05.0|Trace|CustomFormatCalculationService|Using scene name for release title: Only.Murders.in.the.Building.S04E01.Once.Upon.a.Time.in.the.West.1080p.DSNP.WEB-DL.DDP5.1.H.264-FLUX
2024-08-27 02:07:05.0|Trace|EventAggregator|ModelEvent<Episode> <- MissingController
2024-08-27 02:07:05.0|Trace|EventAggregator|ModelEvent<Episode> -> EpisodeController
2024-08-27 02:07:05.0|Trace|CustomFormatCalculationService|Using scene name for release title: Only.Murders.in.the.Building.S04E01.Once.Upon.a.Time.in.the.West.1080p.DSNP.WEB-DL.DDP5.1.H.264-FLUX
2024-08-27 02:07:05.0|Trace|EventAggregator|ModelEvent<Episode> <- EpisodeController
2024-08-27 02:07:05.0|Trace|EventAggregator|ModelEvent<Episode> -> CalendarController
2024-08-27 02:07:05.0|Trace|CustomFormatCalculationService|Using scene name for release title: Only.Murders.in.the.Building.S04E01.Once.Upon.a.Time.in.the.West.1080p.DSNP.WEB-DL.DDP5.1.H.264-FLUX
2024-08-27 02:07:05.0|Trace|EventAggregator|ModelEvent<Episode> <- CalendarController
2024-08-27 02:07:05.0|Debug|EpisodeService|Linking [Season 04/Only Murders in the Building (2021) - S04E01 - Once Upon a Time in the West [DSNP WEBDL-1080p][EAC3 5.1][h264]-FLUX.mkv] > [[90226]Once Upon a Time in the West]
2024-08-27 02:07:05.0|Trace|EventAggregator|EpisodeFileAddedEvent <- EpisodeService
2024-08-27 02:07:05.0|Trace|EventAggregator|EpisodeFileAddedEvent -> EpisodeFileController
2024-08-27 02:07:05.0|Trace|CustomFormatCalculationService|Using scene name for release title: Only.Murders.in.the.Building.S04E01.Once.Upon.a.Time.in.the.West.1080p.DSNP.WEB-DL.DDP5.1.H.264-FLUX
2024-08-27 02:07:05.0|Trace|EventAggregator|EpisodeFileAddedEvent <- EpisodeFileController
2024-08-27 02:07:05.0|Trace|ConfigService|Using default config value for 'extrafileextensions' defaultValue:'srt'
2024-08-27 02:07:05.0|Trace|EventAggregator|Publishing EpisodeImportedEvent
2024-08-27 02:07:05.0|Trace|EventAggregator|EpisodeImportedEvent -> NotificationService
2024-08-27 02:07:05.0|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2024-08-27 02:07:05.0|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'1'
2024-08-27 02:07:05.0|Debug|NotificationService|No tags set for this notification.
2024-08-27 02:07:05.1|Trace|Http|Req: 1801 [GET] /sonarr/api/v3/episode/90226?apikey=(removed) (from 172.23.0.19 Bazarr/1.4.4-beta.34)
2024-08-27 02:07:05.1|Debug|Sonarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-08-27 02:07:05.1|Trace|CustomFormatCalculationService|Using scene name for release title: Only.Murders.in.the.Building.S04E01.Once.Upon.a.Time.in.the.West.1080p.DSNP.WEB-DL.DDP5.1.H.264-FLUX
2024-08-27 02:07:05.1|Trace|Http|Res: 1801 [GET] /sonarr/api/v3/episode/90226?apikey=(removed) 200.OK (8 ms)
2024-08-27 02:07:05.1|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<INotification>
2024-08-27 02:07:05.1|Warn|NotificationService|Unable to send OnDownload notification to: Notifiarr - Direct

[v4.0.9.2278] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Notifications.Webhook.WebhookEpisodeFile..ctor(EpisodeFile episodeFile) in ./Sonarr.Core/Notifications/Webhook/WebhookEpisodeFile.cs:line 16
   at NzbDrone.Core.Notifications.Webhook.WebhookBase`1.BuildOnDownloadPayload(DownloadMessage message) in ./Sonarr.Core/Notifications/Webhook/WebhookBase.cs:line 56
   at NzbDrone.Core.Notifications.Notifiarr.Notifiarr.OnDownload(DownloadMessage message) in ./Sonarr.Core/Notifications/Notifiarr/Notifiarr.cs:line 35
   at NzbDrone.Core.Notifications.NotificationService.Handle(EpisodeImportedEvent message) in ./Sonarr.Core/Notifications/NotificationService.cs:line 199

2024-08-27 02:07:05.2|Trace|EventAggregator|EpisodeImportedEvent <- NotificationService
2024-08-27 02:07:05.2|Trace|EventAggregator|EpisodeImportedEvent -> HistoryService
2024-08-27 02:07:05.3|Trace|EventAggregator|EpisodeImportedEvent <- HistoryService
2024-08-27 02:07:05.3|Trace|EventAggregator|EpisodeImportedEvent -> DownloadMonitoringService
2024-08-27 02:07:05.3|Trace|EventAggregator|EpisodeImportedEvent <- DownloadMonitoringService
2024-08-27 02:07:05.3|Trace|EventAggregator|EpisodeImportedEvent -> DownloadHistoryService
2024-08-27 02:07:05.4|Trace|EventAggregator|EpisodeImportedEvent <- DownloadHistoryService
2024-08-27 02:07:05.4|Trace|EventAggregator|EpisodeImportedEvent -> CutoffController
2024-08-27 02:07:05.4|Trace|CustomFormatCalculationService|Using scene name for release title: Only.Murders.in.the.Building.S04E01.Once.Upon.a.Time.in.the.West.1080p.DSNP.WEB-DL.DDP5.1.H.264-FLUX
2024-08-27 02:07:05.4|Trace|EventAggregator|EpisodeImportedEvent <- CutoffController
2024-08-27 02:07:05.4|Trace|EventAggregator|EpisodeImportedEvent -> MissingController
2024-08-27 02:07:05.4|Trace|CustomFormatCalculationService|Using scene name for release title: Only.Murders.in.the.Building.S04E01.Once.Upon.a.Time.in.the.West.1080p.DSNP.WEB-DL.DDP5.1.H.264-FLUX
2024-08-27 02:07:05.4|Trace|EventAggregator|EpisodeImportedEvent <- MissingController
2024-08-27 02:07:05.4|Trace|EventAggregator|EpisodeImportedEvent -> SeriesController
2024-08-27 02:07:05.4|Trace|EventAggregator|EpisodeImportedEvent <- SeriesController
2024-08-27 02:07:05.4|Trace|EventAggregator|EpisodeImportedEvent -> EpisodeController
```

**Comment by bakerboy448** [comment]
Appears to have regressed from https://github.com/Sonarr/Sonarr/commit/a9b93dd9c686a11ee16e717ca4e8698629a44ef7 cc @mynameisbogdan

**Comment by soleous** [comment]
I've also been fit by this bug today after updating to version 4.0.9.2278.
