### ISSUE TITLE
Bad filename encoding prevents any file in series folder from being processed

### ISSUE THREAD

**Issue by mroach** [Sonarr/Sonarr#7157]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I was surprised to see Sonarr thought I had 0 episodes of a TV show even though I had nearly all of them on disk. No matter what I did, it showed I was missing all epsiodes.

I looked at the logs and found something surprising: a filename with a question mark char, indicating an unknown Unicode codepoint. 

```
System.IO.FileNotFoundException: File doesn't exist: /tv/South Park/S14/South Park - S14E14 - Cr�me Fraiche.mkv
```

I recently moved all my files from an old system to a new one, and some transfers were done over FTP for the sake of speed versus an SSH-based solution, so I'm not surprised there was an encoding error found in there.

When I renamed the file to remove the offending char, I could re-scan the show and it correctly identified all of the epsiodes on disk.

### Expected Behavior

When scanning an entire show, I'd expect a single bad file not to stop/kill the whole scan, but only fail that one file.

### Steps To Reproduce

Create a file with a bad codepoint in the name e.g.:

```
touch South.Park.S14E14.Cr$'\350'me.Fraiche.mkv
# if that doesn't work maybe:
touch South.Park.S14E14.Cr�me.Fraiche.mkv
```

Try to index this with Sonarr. 

### Environment

```markdown
- OS: Debian 12
- Sonarr: 4.0.9.2244 (LinuxServer)
- Docker Install: 27.1.2
- Using Reverse Proxy: Yes
- Browser: Any
- Database: Default
```

### What branch are you running?

Main

### Trace Logs?

```
[Info] DiskScanService: Scanning South Park 
[Error] CommandExecutor: Error occurred while executing task RescanSeries 

[v4.0.9.2244] System.IO.FileNotFoundException: File doesn't exist: /tv/South Park/S14/South Park - S14E14 - Cr�me Fraiche.mkv
   at NzbDrone.Common.Disk.DiskProviderBase.GetFileSize(String path) in ./Sonarr.Common/Disk/DiskProviderBase.cs:line 188
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.GetDecision(LocalEpisode localEpisode, DownloadClientItem downloadClientItem, Boolean otherFiles) in ./Sonarr.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs:line 192
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.GetImportDecisions(List`1 videoFiles, Series series, DownloadClientItem downloadClientItem, ParsedEpisodeInfo folderInfo, Boolean sceneSource, Boolean filterExistingFiles) in ./Sonarr.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs:line 104
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.GetImportDecisions(List`1 videoFiles, Series series, Boolean filterExistingFiles) in ./Sonarr.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs:line 63
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(Series series) in ./Sonarr.Core/MediaFiles/DiskScanService.cs:line 140
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanSeriesCommand message) in ./Sonarr.Core/MediaFiles/DiskScanService.cs:line 284
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in ./Sonarr.Core/Messaging/Commands/CommandExecutor.cs:line 116
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in ./Sonarr.Core/Messaging/Commands/CommandExecutor.cs:line 42
```

**Comment by mroach** [comment]
The original file system was btrfs, and I copied it over to different machine and a zfs. Sonarr is running on the same physical system as the zfs pool and the volume is mounted into Docker. Something like `docker run -v /tank/media/tv:/tv linuxserver/sonarr`
