### ISSUE TITLE
Cant open UI because of bad banner image

### ISSUE THREAD

**Issue by omrish5** [Sonarr/Sonarr#7206]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

UI doesnt load and gives this error:
```
Error parsing column 10 (Images=[ { "coverType": "banner", "remoteUrl": "https://artworks.thetvdb.com/banners/graphical/298130-g.jpg" }, { "coverType": "poster", "remoteUrl": "https://artworks.thetvdb.com/banners/v4/series/298130/po - String)
```

### Expected Behavior

UI to load

### Steps To Reproduce

Just open the webUI

### Environment

```markdown
- OS: Unraid
- Sonarr: 4.0.9.2244
- Docker Install: Yes (linuxserver)
- Using Reverse Proxy: 
- Browser: chrome  128.0.6613.120
- Database: dont know (the built in one, so probably sqlite)
```

### What branch are you running?

Main

### Trace Logs?

```
[Fatal] SonarrErrorPipeline: Request Failed. GET /api/v3/series 

[v4.0.9.2244] System.Data.DataException: Error parsing column 10 (Images=[
  {
    "coverType": "banner",
    "remoteUrl": "https://artworks.thetvdb.com/banners/graphical/298130-g.jpg"
  },
  {
    "coverType": "poster",
    "remoteUrl": "https://artworks.thetvdb.com/banners/v4/series/298130/po - String)
 ---> System.Text.Json.JsonException: '0x00' is invalid within a JSON string. The string should be correctly escaped. Path: $[1].remoteUrl | LineNumber: 7 | BytePositionInLine: 74.
 ---> System.Text.Json.JsonReaderException: '0x00' is invalid within a JSON string. The string should be correctly escaped. LineNumber: 7 | BytePositionInLine: 74.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Dapper.SqlMapper.TypeHandler`1.Dapper.SqlMapper.ITypeHandler.Parse(Type destinationType, Object value) in /_/Dapper/SqlMapper.TypeHandler.cs:line 42
   at Dapper.SqlMapper.TypeHandlerCache`1.Parse(Object value) in /_/Dapper/SqlMapper.TypeHandlerCache.cs:line 23
   at Deserialize57209073-5411-4683-a2b0-cc9756bc4153(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
   at Deserialize57209073-5411-4683-a2b0-cc9756bc4153(IDataReader )
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
   at NzbDrone.Core.Datastore.BasicRepository`1.Query(SqlBuilder builder)
   at NzbDrone.Core.Tv.SeriesService.GetAllSeries()
   at Sonarr.Api.V3.Series.SeriesController.AllSeries(Nullable`1 tvdbId, Boolean includeSeasonImages)
   at lambda_method22(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context)
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context)
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context)
   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context)
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context)
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

### Anything else?

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/ee37b9fc-83df-48c3-a0db-cc09a632013c">

**Comment by augustuen** [comment]
At the moment, this looks more like a support issue.

Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by omri-shilton** [comment]
> At the moment, this looks more like a support issue.
> 
> Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions. 

To me is sounds like sonarr should not crash when a bad tvdb file is present, and just ignore it. So imo it is a bug..

I already went to support and they said either restore a backup (which I don't know how without a UI)
Or modify the db (which I also don't know how and they couldn't help me with that)

Thats why I came to GitHub to get more help and people here might know how to help me.

**Comment by stevietv** [comment]
> To me is sounds like sonarr should not crash when a bad tvdb file is present, and just ignore it. So imo it is a bug..

It's not a bad image, its that the field in the database is incomplete. It ends early when it shouldn't. Something went wrong in your DB.

You can restore a backup from the filesystem like this: https://wiki.servarr.com/en/sonarr/faq#how-do-i-backuprestore-my-sonarr

We can help you out further on Discord.
