### ISSUE TITLE
Error sending notifications to telegram

### ISSUE THREAD

**Issue by naxeras** [Sonarr/Sonarr#7240]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Manual interaction requiered is not sended to telegram but test its working great.

The error is:

Unable to send OnManualInteractionRequired notification to Telegram Bot: Object reference not set to an instance of an object.

Exception:

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Notifications.Telegram.TelegramProxy.SendNotification(String title, String message, List`1 links, TelegramSettings settings) in ./Sonarr.Core/Notifications/Telegram/TelegramProxy.cs:line 38
   at NzbDrone.Core.Notifications.Telegram.Telegram.OnManualInteractionRequired(ManualInteractionRequiredMessage message) in ./Sonarr.Core/Notifications/Telegram/Telegram.cs:line 93
   at NzbDrone.Core.Notifications.NotificationService.Handle(ManualInteractionRequiredEvent message) in ./Sonarr.Core/Notifications/NotificationService.cs:line 381

### Expected Behavior

Send the notification to telegram.

### Steps To Reproduce

Configure a telegram notification and enable only a "On Manual Interaction Requiered" notification.
Its produced when a complete season is downloaded and requere a Manual Interaction.

### Environment

```markdown
- OS: Ubuntu 22.04
- Sonarr: 4.0.9.2244-ls255 by linuxserver.io
- Docker Install: yes
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.41.2
```

### What branch are you running?

Main

### Trace Logs?

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Notifications.Telegram.TelegramProxy.SendNotification(String title, String message, List`1 links, TelegramSettings settings) in ./Sonarr.Core/Notifications/Telegram/TelegramProxy.cs:line 38
   at NzbDrone.Core.Notifications.Telegram.Telegram.OnManualInteractionRequired(ManualInteractionRequiredMessage message) in ./Sonarr.Core/Notifications/Telegram/Telegram.cs:line 93
   at NzbDrone.Core.Notifications.NotificationService.Handle(ManualInteractionRequiredEvent message) in ./Sonarr.Core/Notifications/NotificationService.cs:line 381

**Comment by shomilsaini** [comment]
Same for me on UnRaid docker, always shows this error even when notifications work fine.
![image](https://github.com/user-attachments/assets/9f431309-188d-4334-b320-2997e14b22f9)

```
Version
4.0.9.2244
Package Version
4.0.9.2244-1 by [sonarr](https://aur.archlinux.org/packages/sonarr/)
.NET
Yes (6.0.13)
Docker
Yes
Database
Sqlite 3.46.0
Database Migration
211
```
