### ISSUE TITLE
Output paths with unicode characters break on combining 2 OsPaths

### ISSUE THREAD

**Issue by mynameisbogdan** [Sonarr/Sonarr#7270]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Transmission with folder names like `Pokémon.S21E01.720p.HDTV.x264-W4F` is failing to get the items list due to the backslash in `Pok\u00e9mon` thinking it's a Windows path combined with unix path.

### Expected Behavior

Being able to do a path combine between 2 OsPaths `'/data/downloads/tv' + 'Pok\u00e9mon.S21E01.720p.HDTV.x264-W4F'` > `'/data/downloads/tv/Pok\u00e9mon.S21E01.720p.HDTV.x264-W4F'`.

### Steps To Reproduce

Grab a torrent with unicode characters in the title like `Pokémon.S21E01.720p.HDTV.x264-W4F` in Transmission.

### Environment

```markdown
- OS: Unraid
- Sonarr: v4.0.9.2457
- Docker Install: Y
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

```
2024-09-28 22:11:47.1|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from Transmission

[v4.0.9.2457] System.Exception: Cannot combine OsPaths of different platforms ('/data/downloads/tv' + 'Pok\u00e9mon.S21E01.720p.HDTV.x264-W4F')
   at NzbDrone.Common.Disk.OsPath.op_Addition(OsPath left, OsPath right) in ./Sonarr.Common/Disk/OsPath.cs:line 414
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionBase.GetOutputPath(OsPath outputPath, TransmissionTorrent torrent) in ./Sonarr.Core/Download/Clients/Transmission/TransmissionBase.cs:line 245
   at NzbDrone.Core.Download.Clients.Transmission.TransmissionBase.GetItems() in ./Sonarr.Core/Download/Clients/Transmission/TransmissionBase.cs:line 73
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in ./Sonarr.Core/Download/TrackedDownloads/DownloadMonitoringService.cs:line 90
```

**Comment by markus101** [comment]
What's the response from Transmission look like?

**Comment by markus101** [comment]
Yeah similar thing here: `American.Dad.S18E01.Who.Smarted.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[TGx]+\u2b50`,  transmission is returning `+\\u2b50`, which gets converted to `+\u2b50` and `OsPath` finds the backslash and treats it as Windows.

We just need to convert all the unicode characters in the title ourselves due to how it comes through in the JSON.

**Comment by Taloth** [comment]
This means the source sends the wrong data, its double encoded. The \u part
is JSON encoding, in the string in memory this would be the actual unicode
char. It sending \\u means its double encoded JSON.

**Comment by Taloth** [comment]
That's a html entity in a url, which 100% is incorrect, that's likely just the indexer messing up.

**Comment by Taloth** [comment]
I think those kind of hacks are questionable, coz you can come up with plenty of titles that look encoded, but aren't. It's better to find out which source/indexer is messed up and have it addressed there.

**Comment by Taloth** [comment]
no, coz the magnet url contains title overrides from indexers. Which can be VERY important to use.

**Comment by markus101** [comment]
No guarantee that the title in the feed matches the overridden magnet title, since Jackett or Prowlarr could alter it so I'm not sure there is a ton of value in maintaining whatever the indexer overrides it with.

**Comment by markus101** [comment]
Does Transmission expect `dn` to use `%20` instead of `+` for spaces?

**Comment by markus101** [comment]
That's fun, encoding [System.Uri.EscapeDataString](https://learn.microsoft.com/en-us/dotnet/api/system.uri.escapedatastring) should use `%20` instead, but we'd need to build add `dn` to the magnet URL ourselves to change the encoding, also not sure what other clients are expecting and if they're move flexible than Transmission 🤔

**Comment by Taloth** [comment]
> No guarantee that the title in the feed matches the overridden magnet title, since Jackett or Prowlarr could alter it so I'm not sure there is a ton of value in maintaining whatever the indexer overrides it with.

A ton of indexers do it too and override like abbreviated torrent titles with proper names.

**Comment by markus101** [comment]
Nice, seems like a good candidate for v5.

**Comment by 0xdevalias** [comment]
> Yeah similar thing here: `American.Dad.S18E01.Who.Smarted.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[TGx]+\u2b50`, transmission is returning `+\\u2b50`, which gets converted to `+\u2b50` and `OsPath` finds the backslash and treats it as Windows.

Similar, but coming from Deluge:

```
Unable to communicate with Deluge. Cannot combine OsPaths of different platforms ('/downloads/incomplete/deluge' + 'REDACTED[REDACTED] \u2b50')
```

```shell
⇒ curl -s --cookie cookies.txt -X POST -H "Content-Type: application/json" \
-d '{
  "method": "core.get_torrents_status",
  "params": [{}, ["name"]],
  "id": 3
}' http://REDACTED:8112/json
```

```json5
{
    "result":
    {
        // ..snip..
        "REDACTED":
        {
            "name": "REDACTED[REDACTED] \\u2b50"
        }
    },
    "error": null,
    "id": 3
}
```
