### ISSUE TITLE
Not downloading new episodes, when root folders are missing (FreeSpaceSpecification)

### ISSUE THREAD

**Issue by eeyoredk** [Sonarr/Sonarr#7273]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have my shows on a disk server (root folders) that goes to sleep when not in use. Lately Sonarr stopped downloading new episodes when the disk server is sleeping (root folders are missing).

### Expected Behavior

Sonarr should still download new episodes, eventhough the root folders are missing.

### Environment

```markdown
- OS: Windows 11
- Sonarr: 4.0.9.2457
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Edge
- Database: ?
```

### What branch are you running?

Develop

### Trace Logs?

System.IO.DirectoryNotFoundException: \\XXXXXXX\XXXXXX
   at NzbDrone.Windows.Disk.DiskProvider.GetAvailableSpace(String path) in ./Sonarr.Windows/Disk/DiskProvider.cs:line 53
   at NzbDrone.Core.DecisionEngine.Specifications.FreeSpaceSpecification.IsSatisfiedBy(RemoteEpisode subject, SearchCriteriaBase searchCriteria) in ./Sonarr.Core/DecisionEngine/Specifications/FreeSpaceSpecification.cs:line 28
   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteEpisode remoteEpisode, SearchCriteriaBase searchCriteriaBase) in ./Sonarr.Core/DecisionEngine/DownloadDecisionMaker.cs:line 233

**Comment by eeyoredk** [comment]
Hi
You can close the topic. I found a fix for it. I don't know why it is necessary to check this now, but it solves the issue.
![image](https://github.com/user-attachments/assets/11263884-2417-433a-a321-f78b23ab5a55)

**Comment by markus101** [comment]
That check shouldn't fail if the series folder can't be accessed, that'll be fixed.
