### ISSUE TITLE
Test should_get_version_info fails

### ISSUE THREAD

**Issue by txtsd** [Sonarr/Sonarr#7299]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When running tests with `dotnet test ./_tests/net6.0/linux-x64/publish/Sonarr.*.Test.dll --framework net6.0 --runtime linux-x64 --configuration Release --filter "Category!=ManualTest&Category!=WINDOWS&Category!=IntegrationTest&Category!=AutomationTest" --logger "nunit;LogFilePath=TestResultUnit.xml"` the test fails.

Is it an error on my part?

### Expected Behavior

Tests should not fail

### Environment

```markdown
- OS: Arch Linux
- Sonarr: 4.0.9.2244
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Main

### Trace Logs?

```
The following arguments have been ignored : "--runtime linux-x64 --configuration Release"
Microsoft (R) Test Execution Command Line Tool Version 17.0.3+cc7fb0593127e24f55ce016fb3ac85b5b2857fec
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 10 test files matched the specified pattern.
No test matches the given testcase filter `Category!=ManualTest&Category!=WINDOWS&Category!=IntegrationTest&Category!=AutomationTest` in /build/sonarr/src/Sonarr/./_tests/net6.0/linux-x64/publish/Sonarr.Automation.Test.dll
  Skipped CopyFolder_should_detect_caseinsensitive_folder [12 ms]
  Skipped CopyFolder_should_detect_caseinsensitive_parents [5 ms]
  Skipped MoveFolder_should_detect_caseinsensitive_parents [5 ms]
  Skipped MoveFolder_should_rename_caseinsensitive_folder [6 ms]
  Skipped EnsureWindowsPath("p:\\TV Shows\\file with, comma.mkv") [< 1 ms]
  Skipped EnsureWindowsPath("\\\\serer\\share\\file with, comma.mkv") [< 1 ms]
  Skipped Clean_Path_Windows("c:\\test\\","c:\\test") [< 1 ms]
  Skipped Clean_Path_Windows("c:\\\\test\\\\","c:\\test") [1 ms]
  Skipped Clean_Path_Windows("C:\\\\Test\\\\","C:\\Test") [< 1 ms]
  Skipped Clean_Path_Windows("C:\\\\Test\\\\Test\\","C:\\Test\\Test") [< 1 ms]
  Skipped Clean_Path_Windows("\\\\Testserver\\Test\\","\\\\Testserver\\Test") [< 1 ms]
  Skipped Clean_Path_Windows("\\\\Testserver\\\\Test\\","\\\\Testserver\\Test") [< 1 ms]
  Skipped Clean_Path_Windows("\\\\Testserver\\Test\\file.ext","\\\\Testserver\\Test\\file.ext") [< 1 ms]
  Skipped Clean_Path_Windows("\\\\Testserver\\Test\\file.ext\\\\","\\\\Testserver\\Test\\file.ext") [< 1 ms]
  Skipped Clean_Path_Windows("\\\\Testserver\\Test\\file.ext   ","\\\\Testserver\\Test\\file.ext") [< 1 ms]
  Skipped Clean_Path_Windows("//CAPITAL//lower// ","\\\\CAPITAL\\lower") [< 1 ms]
  Skipped get_actual_casing_for_none_existing_file_return_partially_fixed_result [< 1 ms]
  Skipped get_actual_casing_for_none_existing_folder_return_partially_fixed_result [< 1 ms]
  Skipped get_actual_casing_should_return_actual_casing_for_local_dir_in_windows [< 1 ms]
  Skipped get_actual_casing_should_return_actual_casing_for_local_file_in_windows [< 1 ms]
  Skipped GetAncestorFolders_should_return_all_ancestors_in_path_Windows [< 1 ms]
  Skipped IsPathValid_should_be_false_on_windows("C:\\Test \\") [< 1 ms]
  Skipped IsPathValid_should_be_false_on_windows("C:\\Test ") [< 1 ms]
  Skipped IsPathValid_should_be_false_on_windows("C:\\ Test\\") [< 1 ms]
  Skipped IsPathValid_should_be_false_on_windows("C:\\ Test") [< 1 ms]
  Skipped IsPathValid_should_be_false_on_windows("C:\\Test \\TV") [< 1 ms]
  Skipped IsPathValid_should_be_false_on_windows("C:\\ Test\\TV") [< 1 ms]
  Skipped IsPathValid_should_be_false_on_windows("C:\\Test \\TV\\") [< 1 ms]
  Skipped IsPathValid_should_be_false_on_windows("C:\\ Test\\TV\\") [< 1 ms]
  Skipped IsPathValid_should_be_false_on_windows(" C:\\Test\\TV\\") [< 1 ms]
  Skipped IsPathValid_should_be_false_on_windows(" C:\\Test\\TV") [< 1 ms]
  Skipped should_be_equal_windows_only("c:\\","C:\\") [< 1 ms]
  Skipped should_not_be_parent_when_it_is_grandparent [< 1 ms]
  Skipped Should_be_able_to_start_python [1 ms]
  Skipped Exists_should_find_existing_service [1 ms]
  Skipped Exists_should_not_find_random_service [4 ms]
  Skipped Service_should_be_installed_and_then_uninstalled [< 1 ms]
  Skipped Should_log_warn_if_on_stop_if_service_is_already_stopped [< 1 ms]
  Skipped should_throw_if_starting_a_running_service [< 1 ms]
  Skipped should_return_null_config_if_config_is_empty(null) [1 ms]
  Skipped should_return_null_config_if_config_is_empty("") [1 ms]
  Skipped should_return_null_config_if_config_is_null [1 ms]
  Skipped should_handle_injected_radarr_migration [< 1 ms]
  Skipped should_fix_forward_slashes [5 ms]
  Skipped should_combine_drive_letter [2 ms]
  Skipped should_fix_forward_slashes [2 ms]
  Skipped should_have_correct_output_directory_for_multifile_torrents [2 ms]
  Skipped should_have_correct_output_directory_for_singlefile_torrents [2 ms]
  Skipped should_return_error_if_series_path_is_for_posix_os [1 ms]
  Skipped should_reject_rss_settings_for_AwesomeHD [< 1 ms]
  Skipped should_catch_InvalidOperationException_during_folder_inheritance [7 ms]
  Skipped should_catch_UnauthorizedAccessException_during_folder_inheritance [2 ms]
  Skipped should_get_relative_path_when_there_is_no_grandparent_for_UNC_path [2 ms]
  Skipped should_get_relative_path_when_there_is_no_grandparent_windows [3 ms]
  Skipped should_return_true_when_in_old_working_folder [< 1 ms]
  Skipped filter_should_return_none_existing_files_ignoring_case [< 1 ms]
  Skipped should_not_be_valid_if_from_is_invalid("sonarr") [< 1 ms]
  Skipped should_not_be_valid_if_from_is_invalid("email.me") [< 1 ms]
  Skipped should_remove_duplicate_non_word_characters [< 1 ms]
  Skipped should_call_fileSetLastWriteTime_for_each_file [< 1 ms]
  Skipped should_call_fileSetLastWriteTime_for_each_file [< 1 ms]
  Skipped should_get_parent_path_from_os_path_if_matching_root_folder_is_not_found_for_posix_path [< 1 ms]
  Skipped should_get_episode_including_specials [< 1 ms]
  Skipped should_not_be_valid_if_child_of_windows_folder [< 1 ms]
  Skipped should_not_be_valid_if_set_to_windows_folder [< 1 ms]
  Skipped Route_should_call_install_service_when_application_mode_is_install [7 ms]
  Skipped Route_should_call_uninstall_service_when_application_mode_is_uninstall [< 1 ms]
  Skipped show_error_on_install_if_service_already_exist [< 1 ms]
  Skipped show_error_on_uninstall_if_service_doesnt_exist [< 1 ms]
No test matches the given testcase filter `Category!=ManualTest&Category!=WINDOWS&Category!=IntegrationTest&Category!=AutomationTest` in /build/sonarr/src/Sonarr/./_tests/net6.0/linux-x64/publish/Sonarr.Integration.Test.dll
  Skipped directory_exist_should_be_able_to_find_existing_unc_share [32 ms]
  Skipped should_not_be_able_to_rename_open_hardlinks_with_fileshare_none [< 1 ms]
  Skipped should_not_be_able_to_rename_open_hardlinks_with_fileshare_write [< 1 ms]
  Skipped should_be_able_to_check_space_on_ramdrive [< 1 ms]
  Skipped should_get_version_info [< 1 ms]
  Skipped should_get_framework_version [< 1 ms]
  Failed should_get_version_info [104 ms]
  Error Message:
   Expected string not to be <null> or whitespace, but found "".
  Stack Trace:
     at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.StringAssertions`1.NotBeNullOrWhiteSpace(String because, Object[] becauseArgs)
   at NzbDrone.Mono.Test.EnvironmentInfo.ReleaseFileVersionAdapterFixture.should_get_version_info() in ./Sonarr.Mono.Test/EnvironmentInfo/ReleaseFileVersionAdapterFixture.cs:line 28

  Standard Output Messages:
 21:05:20.4 Info: --- Start: NzbDrone.Mono.Test.EnvironmentInfo.ReleaseFileVersionAdapterFixture.should_get_version_info --- 
 21:05:20.5 Info: --- End: NzbDrone.Mono.Test.EnvironmentInfo.ReleaseFileVersionAdapterFixture.should_get_version_info --- 


  Skipped directory_exist_should_be_able_to_find_existing_folder [6 ms]
  Skipped directory_exist_should_be_able_to_find_existing_unc_share [7 ms]
  Skipped directory_exist_should_not_be_able_to_find_none_existing_folder [7 ms]
  Skipped empty_folder_should_return_folder_modified_date [7 ms]
  Skipped folder_should_return_correct_value_for_last_write [7 ms]
  Skipped FolderWritable_should_return_false_for_unwritable_directory [7 ms]
  Skipped FolderWritable_should_return_true_for_writable_directory [7 ms]
  Skipped GetParentFolder_should_remove_trailing_slash_before_getting_parent_folder [7 ms]
  Skipped MoveFile_should_not_move_overwrite_itself [7 ms]
  Skipped MoveFile_should_overwrite_existing_file [7 ms]
  Skipped RemoveEmptySubfolders_should_not_remove_nested_nonempty_folder [7 ms]
  Skipped RemoveEmptySubfolders_should_remove_nested_empty_folder [7 ms]
  Skipped should_be_able_to_delete_directory_with_read_only_file [7 ms]
  Skipped should_be_able_to_move_read_only_file [7 ms]
  Skipped should_be_able_to_rename_open_hardlinks_with_fileshare_delete [7 ms]
  Skipped should_be_able_to_set_permission_from_parrent [7 ms]
  Skipped should_be_set_last_file_write [7 ms]
  Skipped should_not_be_able_to_rename_open_hardlinks_with_fileshare_none [7 ms]
  Skipped should_not_be_able_to_rename_open_hardlinks_with_fileshare_write [7 ms]
  Skipped should_return_false_for_unlocked_and_readonly_file [7 ms]
  Skipped should_return_false_for_unlocked_file [7 ms]
  Skipped should_return_true_for_unlocked_file [7 ms]
  Skipped writealltext_should_truncate_existing [7 ms]
  Skipped should_be_able_to_get_space_on_folder_that_doesnt_exist [< 1 ms]
  Skipped should_be_able_to_get_space_on_unc [< 1 ms]
  Skipped should_get_free_space_for_folder [< 1 ms]
  Skipped should_get_free_space_for_folder_that_doesnt_exist [< 1 ms]
  Skipped should_return_free_disk_space [< 1 ms]
  Skipped should_throw_if_drive_doesnt_exist [< 1 ms]
  Skipped should_get_framework_version [< 1 ms]
  Skipped should_get_windows_version [< 1 ms]
Results File: TestResultUnit.xml

Passed!  - Failed:     0, Passed:  4548, Skipped:    26, Total:  4574, Duration: 3 m 13 s - /build/sonarr/src/Sonarr/./_tests/net6.0/linux-x64/publish/Sonarr.Core.Test.dll (net6.0)
Passed!  - Failed:     0, Passed:   501, Skipped:    39, Total:   540, Duration: 36 s - /build/sonarr/src/Sonarr/./_tests/net6.0/linux-x64/publish/Sonarr.Common.Test.dll (net6.0)
None     - Failed:     0, Passed:     0, Skipped:     0, Total:     0, Duration: 11 ms - /build/sonarr/src/Sonarr/./_tests/net6.0/linux-x64/publish/Sonarr.Windows.Test.dll (net6.0)
Failed!  - Failed:     1, Passed:    50, Skipped:     5, Total:    56, Duration: 716 ms - /build/sonarr/src/Sonarr/./_tests/net6.0/linux-x64/publish/Sonarr.Mono.Test.dll (net6.0)
Passed!  - Failed:     0, Passed:    10, Skipped:     4, Total:    14, Duration: 1 s - /build/sonarr/src/Sonarr/./_tests/net6.0/linux-x64/publish/Sonarr.Host.Test.dll (net6.0)
Passed!  - Failed:     0, Passed:    17, Skipped:     0, Total:    17, Duration: 480 ms - /build/sonarr/src/Sonarr/./_tests/net6.0/linux-x64/publish/Sonarr.Update.Test.dll (net6.0)
Passed!  - Failed:     0, Passed:     7, Skipped:     0, Total:     7, Duration: 517 ms - /build/sonarr/src/Sonarr/./_tests/net6.0/linux-x64/publish/Sonarr.Api.Test.dll (net6.0)
Passed!  - Failed:     0, Passed:     2, Skipped:     0, Total:     2, Duration: 243 ms - /build/sonarr/src/Sonarr/./_tests/net6.0/linux-x64/publish/Sonarr.Libraries.Test.dll (net6.0)
==> ERROR: A failure occurred in check().    Aborting...
```

**Comment by txtsd** [comment]
It's a rolling release distro, so there won't ever be a `VERSION_ID` :(

**Comment by txtsd** [comment]
Thank you!

I also found disabling the test manually, in addition to `should_get_version_info_from_actual_linux` does the trick.

```
&FullyQualifiedName!~should_get_version_info
&FullyQualifiedName!~should_get_version_info_from_actual_linux
```
