### ISSUE TITLE
Kometa Metadata - Sequence contains no elements

### ISSUE THREAD

**Issue by bakerboy448** [Sonarr/Sonarr#7381]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Throws Sequence contains no elements

### Expected Behavior

Handle errors gracefully

### Environment

```markdown
- OS: Ubuntu 24.04
- Sonarr: v4.0.10.2624
- Docker Install: yes
- Using Reverse Proxy: n/a
- Browser: n/a
- Database: 
Database
Postgresql 16.4
Database Migration
215
```

### What branch are you running?

Develop

### Trace Logs?

```
2024-11-11 12:01:33.0|Debug|MetadataService|Episode image already exists: /mnt/data/media/tv/Yellowstone (2018) {imdb-tt4236770}/S01E09.jpg
2024-11-11 12:01:33.0|Error|KometaMetadata|Unable to process episode image for file: /mnt/data/media/tv/Yellowstone (2018) {imdb-tt4236770}/Season 03/Yellowstone (2018) - S03E10 - The World Is Purple [AMZN WEBDL-1080p][EAC3 2.0][h264]-NTb.mkv

[v4.0.10.2624] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Extras.Metadata.Consumers.Kometa.KometaMetadata.EpisodeImages(Series series, EpisodeFile episodeFile) in ./Sonarr.Core/Extras/Metadata/Consumers/Kometa/KometaMetadata.cs:line 153

2024-11-11 12:01:33.0|Trace|Http|Req: 34479 [GET] /sonarr/api/v3/episode?seriesId=243&apikey=(removed) (from 172.23.0.32 Bazarr/1.4.6-beta.16)
2024-11-11 12:01:33.0|Debug|MetadataService|Episode image already exists: /mnt/data/media/tv/Yellowstone (2018) {imdb-tt4236770}/S05E08.jpg
2024-11-11 12:01:33.0|Debug|Sonarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-11-11 12:01:33.0|Debug|MetadataService|Episode image already exists: /mnt/data/media/tv/Yellowstone (2018) {imdb-tt4236770}/S05E06.jpg
2024-11-11 12:01:33.0|Debug|MetadataService|Episode image already exists: /mnt/data/media/tv/Yellowstone (2018) {imdb-tt4236770}/S02E02.jpg
```

**Comment by markus101** [comment]
The exception is being handled and logs an error.

From the logs it's not clear what actually caused it to throw because the line number doesn't match the code, but best guess you have an episode file that doesn't actually have episodes linked to it and it fails, which would be expected since that is unexpected...

https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Extras/Metadata/Consumers/Kometa/KometaMetadata.cs#L134

**Comment by bakerboy448** [comment]
Nailed it. Unknowingly ended up some time ago with duplicate files after a rename

```

-rw-rw-r-- 3 bakerboy448 media 3.3G Jan 15  2022 '/mnt/data/media/tv/Yellowstone (2018) {imdb-tt4236770}/Season 03/Yellowstone (2018) - S03E10 - The World is Purple [AMZN WEBDL-1080p][EAC3 2.0][h264]-NTb.mkv'
-rw-rw-r-- 3 bakerboy448 media 3.3G Jan 15  2022 '/mnt/data/media/tv/Yellowstone (2018) {imdb-tt4236770}/Season 03/Yellowstone (2018) - S03E10 - The World Is Purple [AMZN WEBDL-1080p][EAC3 2.0][h264]-NTb.mkv'
```

**Comment by stevietv** [comment]
Its being handled the same way in https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Extras/Metadata/Consumers/Xbmc/XbmcMetadata.cs so any fix should also tackle it there
