### ISSUE TITLE
Activity queue not loading using Transmission

### ISSUE THREAD

**Issue by little030** [Sonarr/Sonarr#7384]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I click on Activity it shows "Failed to load Queue"
![Screenshot 2024-11-14 at 10 00 39](https://github.com/user-attachments/assets/b13f8611-07b8-4df9-bea1-ab612ddd52d1)

### Expected Behavior

load queue

### Steps To Reproduce

Request Failed. GET /api/v3/queue: Object reference not set to an instance of an object.

### Environment

```markdown
- OS: Synology DSM 7.2.1-69057 Update 5
- Sonarr: 4.0.10.2544
- Docker Install: -
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Main

### Trace Logs?

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Jobs.TaskManager.GetNextExecution(Type type) in ./Sonarr.Core/Jobs/TaskManager.cs:line 60
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at NzbDrone.Core.Download.Pending.PendingReleaseService.GetQueueItem(PendingRelease pendingRelease, Lazy`1 nextRssSync, Episode episode) in ./Sonarr.Core/Download/Pending/PendingReleaseService.cs:line 361
   at NzbDrone.Core.Download.Pending.PendingReleaseService.GetPendingQueue() in ./Sonarr.Core/Download/Pending/PendingReleaseService.cs:line 200
   at Sonarr.Api.V3.Queue.QueueController.GetQueue(PagingSpec`1 pagingSpec, HashSet`1 seriesIds, Nullable`1 protocol, HashSet`1 languages, Nullable`1 quality, Boolean includeUnknownSeriesItems)
   at Sonarr.Api.V3.Queue.QueueController.<>c__DisplayClass13_0.<GetQueue>b__0(PagingSpec`1 spec) in ./Sonarr.Api.V3/Queue/QueueController.cs:line 168
   at Sonarr.Http.Extensions.RequestExtensions.ApplyToPage[TResource,TModel](PagingSpec`1 pagingSpec, Func`2 function, Converter`2 mapper) in ./Sonarr.Http/Extensions/RequestExtensions.cs:line 67
   at Sonarr.Api.V3.Queue.QueueController.GetQueue(PagingRequestResource paging, Boolean includeUnknownSeriesItems, Boolean includeSeries, Boolean includeEpisode, Int32[] seriesIds, Nullable`1 protocol, Int32[] languages, Nullable`1 quality)
   at lambda_method74(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/UrlBaseMiddleware.cs:line 29
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by augustuen** [comment]
Hi, this looks more like a support issue. We don't use Github for support. Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord](https://discord.gg/Ex7FmFK), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by markus101** [comment]
In addition to reaching out in one of the support channels, there are a few things to do/check:

1. Restart Sonarr
2. Check System: Tasks to ensure tasks are running at the correct interval
3. Verify the DB isn't corrupt
