### ISSUE TITLE
SymLinks Don't Resolve to Target on some mounts

### ISSUE THREAD

**Issue by fatbob01** [Sonarr/Sonarr#7431]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have an error with latest version, rolling back to 4.0.10.254 clears the issue.  Radarr's latest version has the same issue for me.  Items don't get imported and rescans fail due to a failed system driver or corrupt drive

### Expected Behavior

Items to get imported and rescans to work without this error

### Steps To Reproduce

Rescan and import fail for all files.

### Environment

```markdown
- OS: Windows 11 24h2
- Sonarr: 4.0.11.2680
- Docker Install: NA
- Using Reverse Proxy: Yes
- Browser: Chrome 131.0.6778.86
- Database: Sqlite 3.36.0
```

### What branch are you running?

Main

### Trace Logs?

Request Failed. GET /api/v3/manualimport: The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted. : 'C:\Symlinks\sonarr\Before.2024.S01E07.1080p.x265-ELiTE\Before.2024.S01E07.1080p.x265-ELiTE.mkv'

```
System.IO.IOException: The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted. : 'C:\Symlinks\sonarr\Before.2024.S01E07.1080p.x265-ELiTE\Before.2024.S01E07.1080p.x265-ELiTE.mkv'
   at System.IO.FileSystem.GetFinalLinkTarget(String linkPath, Boolean isDirectory)
   at NzbDrone.Common.Disk.DiskProviderBase.GetFileSize(String path) in ./Sonarr.Common/Disk/DiskProviderBase.cs:line 188
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.MapItem(ImportDecision decision, String rootFolder, String downloadId, String folderName) in ./Sonarr.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs:line 441
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.<>c__DisplayClass18_0.<ProcessFolder>b__0(ImportDecision decision) in ./Sonarr.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs:line 296
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.ProcessFolder(String rootFolder, String baseFolder, String downloadId, Nullable`1 seriesId, Boolean filterExistingFiles) in ./Sonarr.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs:line 296
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.<>c__DisplayClass18_0.<ProcessFolder>b__2(String subfolder) in ./Sonarr.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs:line 287
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.ProcessFolder(String rootFolder, String baseFolder, String downloadId, Nullable`1 seriesId, Boolean filterExistingFiles) in ./Sonarr.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs:line 289
   at NzbDrone.Core.MediaFiles.EpisodeImport.Manual.ManualImportService.GetMediaFiles(String path, String downloadId, Nullable`1 seriesId, Boolean filterExistingFiles) in ./Sonarr.Core/MediaFiles/EpisodeImport/Manual/ManualImportService.cs:line 139
   at Sonarr.Api.V3.ManualImport.ManualImportController.GetMediaFiles(String folder, String downloadId, Nullable`1 seriesId, Nullable`1 seasonNumber, Boolean filterExistingFiles) in ./Sonarr.Api.V3/ManualImport/ManualImportController.cs:line 33
   at lambda_method274(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/UrlBaseMiddleware.cs:line 29
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)



Couldn't import file. C:\Symlinks\sonarr\Before.2024.S01E07.1080p.x265-ELiTE\Before.2024.S01E07.1080p.x265-ELiTE.mkv: The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted. : 'C:\Symlinks\sonarr\Before.2024.S01E07.1080p.x265-ELiTE\Before.2024.S01E07.1080p.x265-ELiTE.mkv'


System.IO.IOException: The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted. : 'C:\Symlinks\sonarr\Before.2024.S01E07.1080p.x265-ELiTE\Before.2024.S01E07.1080p.x265-ELiTE.mkv'
   at System.IO.FileSystem.GetFinalLinkTarget(String linkPath, Boolean isDirectory)
   at NzbDrone.Common.Disk.DiskProviderBase.GetFileSize(String path) in ./Sonarr.Common/Disk/DiskProviderBase.cs:line 188
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.GetDecision(LocalEpisode localEpisode, DownloadClientItem downloadClientItem, Boolean otherFiles) in ./Sonarr.Core/MediaFiles/EpisodeImport/ImportDecisionMaker.cs:line 192
```

**Comment by markus101** [comment]
`C:\Symlinks`... The symlink is being resolved and isn't accessible, what exactly is your setup that you're relying on symlinks?

**Comment by fatbob01** [comment]
> `C:\Symlinks`... The symlink is being resolved and isn't accessible, what exactly is your setup that you're relying on symlinks?

Rolling back to 4.0.10.254 clears the issue.  But my setup is sonarr + blackhole + Real Debrid + Zurg.  The symlinks are to tell me if the file has been added to Real Debrid.

**Comment by markus101** [comment]
> Rolling back to 4.0.10.254 clears the issue

You mentioned that, that version doesn't try to resolve the symlink to get the actual size of the file (instead of the size of the symlink).

> But my setup is sonarr + blackhole + Real Debrid + Zurg

Real debrid... 😬 

> The symlinks are to tell me if the file has been added to Real Debrid.

You're going to need to expand on what exactly your setup is doing. Are these valid symlinks that you can follow in Windows Explorer / play the file? When this error doesn't happen what is the import process?

**Comment by fatbob01** [comment]
> > Rolling back to 4.0.10.254 clears the issue
> 
> You mentioned that, that version doesn't try to resolve the symlink to get the actual size of the file (instead of the size of the symlink).
> >I dont need to validate file size if it causes an issue.  I just want to know if the file is present.  There are fine for me at 0B :)
> > But my setup is sonarr + blackhole + Real Debrid + Zurg
> 
> Real debrid... 😬
>  Haha, still works fine (mostly)
> > The symlinks are to tell me if the file has been added to Real Debrid.
> 
> You're going to need to expand on what exactly your setup is doing. Are these valid symlinks that you can follow in Windows Explorer / play the file? When this error doesn't happen what is the import process?

They are indeed valid, they point to files in zurg/rclone mount, mounted in windows as a drive.  But I dont use them to play anything, since plex can't target symlinks in windows.  Plex targets the rclone drive, which works fine.  I guess Sonarr is trying to validate the symlinks against the rclone mount?  What has changed between last version and this version that would cause an issue?  Same for Radarr?

I guess this is the cause of my issue? fix: Allow GetFileSize to follow symlinks by @eliasbenb in https://github.com/Sonarr/Sonarr/pull/7378

Any way to ignore this?

Bsically sonarr searches for a file, blackhole sends it to real debrid and creates symlink, zurg/rclone adds to "local" drive, sonarr imports symlink.

**Comment by bakerboy448** [comment]
> Real debrid

![image](https://github.com/user-attachments/assets/03fa52f7-2c49-4d50-aaf3-39b423d581ba)

**Comment by eliasbenb** [comment]
Hey, I made the original PR #7378.

This looks like an edge case scenario where you have to be on Windows + using a WinFSP mount + having a symlink point to that mount https://github.com/winfsp/sshfs-win/issues/243.

My guess is that the `System.IO.File.ResolveLinkTarget` doesn't resolve symlinks in the format WinFSP wants (e.g. `\\.\X:path\to\file`). However, I don't use Windows so can't really confirm.

**Comment by fatbob01** [comment]
> Hey, I made the original PR #7378.
> 
> This looks like an edge case scenario where you have to be on Windows + using a WinFSP mount + having a symlink point to that mount [winfsp/sshfs-win#243](https://github.com/winfsp/sshfs-win/issues/243).
> 
> My guess is that the `System.IO.File.ResolveLinkTarget` doesn't resolve symlinks in the format WinFSP wants (e.g. `\\.\X:path\to\file`). However, I don't use Windows so can't really confirm.

So it seems that the way RClone mounts the drive would be causing the issue.  Would it be possible to exclude this PR from Windows installs only?

**Comment by markus101** [comment]
Symlinks on Windows are valid so it doesn't make sense to outright remove it, but should be able to prevent things from failing as they are.

**Comment by medinauta** [comment]
Same issue, in windows, Rclone mount, Symlinks are fine and working but new Sonarr/Radarr update "GetFileSize" fail imports because it can't resolve the file size (which shows as zero) giving I/O or corrupted drive which is incorrect. Can this instead be implemented as an option like "Skip Free Space Check" is for us users that mount drives in unconventional file systems?

**Comment by markus101** [comment]
There really isn't a need for an option, we can just prevent the error from causing it to fail, like the linked PR does.
