### ISSUE TITLE
Failed to upgrade sonarr version in Synology NAS DS923+

### ISSUE THREAD

**Issue by N-o-Z** [Sonarr/Sonarr#7470]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Ever since version 4.0.0.748 I am not able to upgrade to any latest version.
When running the update it seems like the update is completed but in the end version remains the same.

### Expected Behavior

Will be able to update to latest version using Sonarr GUI

### Steps To Reproduce

1. Open Sonarr UI
2. Go to System -> Updates
3. Press on "Install Latest" button

### Environment

```markdown
- OS: DSM 7.2.2
- Sonarr: 4.0.0.748
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
- Database: SQLite?
```

### What branch are you running?

Main

### Trace Logs?

These are the relevant logs from the update run:

```
2024-12-10 00:16:16.9|Info|Bootstrap|Starting Sonarr - /volume1/@appstore/sonarr/share/Sonarr/bin/Sonarr - Version 4.0.0.748
2024-12-10 00:16:17.0|Info|AppFolderInfo|Data directory is being overridden to [/volume1/@appdata/sonarr/.config/Sonarr]
2024-12-10 00:16:17.0|Info|AppFolderInfo|Data directory is being overridden to [/volume1/@appdata/sonarr/.config/Sonarr]
2024-12-10 00:16:17.3|Info|AppFolderInfo|Data directory is being overridden to [/volume1/@appdata/sonarr/.config/Sonarr]
2024-12-10 00:16:17.4|Info|MigrationController|*** Migrating data source=/volume1/@appdata/sonarr/.config/Sonarr/sonarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 ***
2024-12-10 00:16:17.8|Warn|SingleInstancePolicy|Failed to check for multiple instances of Sonarr.

[v4.0.0.748] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in ./Sonarr.Common/Processes/ProcessProvider.cs:line 316
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Common.Processes.ProcessProvider.FindProcessByName(String name) in ./Sonarr.Common/Processes/ProcessProvider.cs:line 90
   at NzbDrone.Host.SingleInstancePolicy.GetOtherNzbDroneProcessIds() in ./Sonarr.Host/SingleInstancePolicy.cs:line 68

2024-12-10 00:16:17.8|Info|MigrationController|*** Migrating data source=/volume1/@appdata/sonarr/.config/Sonarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 ***
2024-12-10 00:16:19.8|Info|InstallUpdateService|Installing post-install update from 4.0.0.748 to 4.0.11.2680
2024-12-10 00:16:19.8|Info|InstallUpdateService|Downloading update 4.0.11.2680
2024-12-10 00:16:34.8|Info|InstallUpdateService|Verifying update package
2024-12-10 00:16:34.9|Info|InstallUpdateService|Update package verified successfully
2024-12-10 00:16:34.9|Info|InstallUpdateService|Extracting Update package
2024-12-10 00:16:38.9|Info|InstallUpdateService|Update package extracted successfully
2024-12-10 00:16:38.9|Info|BackupService|Starting Backup
2024-12-10 00:16:45.9|Info|InstallUpdateService|Preparing client
2024-12-10 00:16:47.5|Info|InstallUpdateService|Starting update client /volume1/@apptemp/sonarr/sonarr_update/Sonarr.Update
2024-12-10 00:16:47.5|Info|InstallUpdateService|Sonarr will restart shortly.
2024-12-10 00:17:17.5|Error|InstallUpdateService|Post-install update not completed within 30 seconds. Attempting to continue normal operation.
2024-12-10 00:17:17.7|Info|Microsoft.Hosting.Lifetime|Now listening on: http://[::]:8989
2024-12-10 00:17:28.4|Info|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2024-12-10 00:17:28.4|Info|Microsoft.Hosting.Lifetime|Hosting environment: Production
2024-12-10 00:17:28.4|Info|Microsoft.Hosting.Lifetime|Content root path: /
2024-12-10 00:17:57.5|Info|InstallUpdateService|Deleting old update files
2024-12-10 00:17:57.6|Info|InstallUpdateService|Downloading update 4.0.11.2680
2024-12-10 00:18:01.9|Info|InstallUpdateService|Verifying update package
2024-12-10 00:18:02.0|Info|InstallUpdateService|Update package verified successfully
2024-12-10 00:18:02.0|Info|InstallUpdateService|Extracting Update package
2024-12-10 00:18:05.0|Info|InstallUpdateService|Update package extracted successfully
2024-12-10 00:18:05.0|Info|BackupService|Starting Backup
2024-12-10 00:18:12.3|Info|InstallUpdateService|Preparing client
2024-12-10 00:18:13.3|Info|InstallUpdateService|Starting update client /volume1/@apptemp/sonarr/sonarr_update/Sonarr.Update
2024-12-10 00:18:13.3|Info|InstallUpdateService|Sonarr will restart shortly.
2024-12-10 00:19:26.4|Info|RssSyncService|Starting RSS Sync
2024-12-10 00:19:27.0|Warn|Torznab|Indexer 1337x rss sync didn't cover the period between 12/09/2024 22:04:08 and 12/09/2024 22:04:08 UTC. Search may be required.
2024-12-10 00:19:29.3|Info|DownloadDecisionMaker|Processing 120 releases
2024-12-10 00:19:30.2|Info|RssSyncService|RSS Sync Completed. Reports found: 120, Reports grabbed: 0
```

The following error caught my attention:
```
2024-12-10 00:17:17.5|Error|InstallUpdateService|Post-install update not completed within 30 seconds. Attempting to continue normal operation.
```

**Comment by markus101** [comment]
What do the update logs show?

**Comment by N-o-Z** [comment]
> What do the update logs show?

Can you instruct how to get the update log?

**Comment by markus101** [comment]
Same area in the UI.

![image](https://github.com/user-attachments/assets/73de6f3c-0af5-44b8-8c09-b88089f2d5d8)

**Comment by N-o-Z** [comment]
Neat!
This is the log of the latest update attempt:
```
2024-12-10 00:18:14.4|Info|UpdateApp|Starting Sonarr Update Client
2024-12-10 00:18:14.7|Info|AppFolderInfo|Data directory is being overridden to [/volume1/@appdata/sonarr/.config/Sonarr]
2024-12-10 00:18:14.7|Debug|UpdateApp|NzbDrone process ID: 4115
2024-12-10 00:18:14.7|Debug|UpdateApp|Arguments:
2024-12-10 00:18:14.7|Debug|UpdateApp|  4115
2024-12-10 00:18:14.7|Debug|UpdateApp|  /volume1/@apptemp/sonarr/sonarr_update
2024-12-10 00:18:14.7|Debug|UpdateApp|  /volume1/@appstore/sonarr/share/Sonarr/bin/Sonarr
2024-12-10 00:18:14.7|Debug|UpdateApp|  /data=/volume1/@appdata/sonarr/.config/Sonarr
2024-12-10 00:18:14.7|Debug|UpdateApp|  /nobrowser
2024-12-10 00:18:14.7|Debug|UpdateApp|Using executing application: /volume1/@appstore/sonarr/share/Sonarr/bin/Sonarr
2024-12-10 00:18:14.7|Debug|UpdateApp|Executable location: /volume1/@appstore/sonarr/share/Sonarr/bin/Sonarr
2024-12-10 00:18:14.8|Info|InstallUpdateService|Installation Folder: /volume1/@appstore/sonarr/share/Sonarr/bin
2024-12-10 00:18:14.8|Info|InstallUpdateService|Updating Sonarr from version 4.0.0.748 to version 4.0.11.2680
2024-12-10 00:18:14.8|Info|InstallUpdateService|Verifying requirements before update...
2024-12-10 00:18:14.8|Debug|ProcessProvider|Finding process with Id:4115
2024-12-10 00:18:14.8|Debug|ProcessProvider|Found process 4115:Sonarr [/volume1/@appstore/sonarr/share/Sonarr/bin/Sonarr]
2024-12-10 00:18:14.8|Info|InstallUpdateService|Verifying Update Folder
2024-12-10 00:18:14.8|Debug|ProcessProvider|Found 0 processes with the name: Sonarr.Console
2024-12-10 00:18:14.8|Debug|ProcessProvider|Found 2 processes with the name: Sonarr
2024-12-10 00:18:14.8|Debug|ProcessProvider| - [1497] Sonarr
2024-12-10 00:18:14.8|Debug|ProcessProvider| - [4115] Sonarr
2024-12-10 00:18:14.8|Fatal|UpdateApp|An error has occurred while applying update package.

[v4.0.11.2680] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Common.Processes.ProcessProvider.ConvertToProcessInfo(Process process) in ./Sonarr.Common/Processes/ProcessProvider.cs:line 316
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Common.Processes.ProcessProvider.FindProcessByName(String name) in ./Sonarr.Common/Processes/ProcessProvider.cs:line 90
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId) in ./Sonarr.Update/UpdateEngine/InstallUpdateService.cs:line 102
   at NzbDrone.Update.UpdateApp.Start(String[] args) in ./Sonarr.Update/UpdateApp.cs:line 60
   at NzbDrone.Update.UpdateApp.Main(String[] args) in ./Sonarr.Update/UpdateApp.cs:line 45
   ```
