### ISSUE TITLE
Value cannot be null. (Parameter 'input') from specific indexer

### ISSUE THREAD

**Issue by Golumpa** [Sonarr/Sonarr#7494]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I am unsure whether this is a Sonarr bug or a Prowlarr bug, but as the error occurs in Sonarr, I will start here.

Currently, when trying to grab a release from a specific provider (animetorrents.me) it gives an error and refuses to download.
When trying to grab the release from within Prowlarr itself it is successful and I can download the torrent and send it to the download client just fine.whether this is a Sonarr bug or a Prowlarr bug, but as the error occurs in Sonarr,

### Expected Behavior

To grab the release and add to download client.

### Steps To Reproduce

1. Add an animetorrents.me account to prowlarr (likely jackett aswel)
2. Add this account to Sonarr
3. Try to download any release from animetorrent.me through sonarr
4. oof error

### Environment

```markdown
- OS: Unraid 6.12.14 (Linux 6.1.118-Unraid x86_64)
- Sonarr: 4.0.11.2680-ls261 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: Yes (internally no)
- Browser: Brave Version 1.67.134 Chromium: 126.0.6478.186
- Database: Sqlite 3.45.3
```

### What branch are you running?

Main

### Trace Logs?

```
2024-12-17 10:09:30.4|Trace|Http|Res: 49 [GET] /api/v3/release?seriesId=42&seasonNumber=2: 200.OK (22678 ms)
2024-12-17 10:09:30.4|Debug|Api|[GET] /api/v3/release?seriesId=42&seasonNumber=2: 200.OK (22678 ms)
2024-12-17 10:09:35.6|Trace|Http|Req: 50 [GET] /logfile/sonarr.trace.txt (from 154.*.*.210 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36)
2024-12-17 10:09:35.6|Trace|Http|Res: 50 [GET] /logfile/sonarr.trace.txt: 200.OK (4 ms)
2024-12-17 10:09:48.9|Trace|Http|Req: 51 [POST] /api/v3/release (from 154.*.*.210 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36)
2024-12-17 10:09:48.9|Debug|Sonarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-12-17 10:09:49.0|Trace|SonarrErrorPipeline|Handling Exception
2024-12-17 10:09:49.0|Fatal|SonarrErrorPipeline|Request Failed. POST /api/v3/release

[v4.0.11.2680] System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at NzbDrone.Core.Parser.Parser.CleanSeriesTitle(String title) in ./Sonarr.Core/Parser/Parser.cs:line 848
   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingService.FindMappings(String seriesTitle, String releaseTitle)
   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingService.FindSceneMapping(String seriesTitle, String releaseTitle, Int32 sceneSeasonNumber) in ./Sonarr.Core/DataAugmentation/Scene/SceneMappingService.cs:line 97
   at NzbDrone.Core.Parser.ParsingService.Map(ParsedEpisodeInfo parsedEpisodeInfo, Int32 tvdbId, Int32 tvRageId, String imdbId, Series series, SearchCriteriaBase searchCriteria) in ./Sonarr.Core/Parser/ParsingService.cs:line 141
   at NzbDrone.Core.Parser.ParsingService.GetEpisodes(ParsedEpisodeInfo parsedEpisodeInfo, Series series, Boolean sceneSource, SearchCriteriaBase searchCriteria) in ./Sonarr.Core/Parser/ParsingService.cs:line 214
   at Sonarr.Api.V3.Indexers.ReleaseController.DownloadRelease(ReleaseResource release) in ./Sonarr.Api.V3/Indexers/ReleaseController.cs:line 126
   at lambda_method239(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/UrlBaseMiddleware.cs:line 29
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2024-12-17 10:09:49.2|Trace|Http|Res: 51 [POST] /api/v3/release: 500.InternalServerError (274 ms)
2024-12-17 10:09:49.2|Debug|Api|[POST] /api/v3/release: 500.InternalServerError (274 ms)
2024-12-17 10:09:50.9|Trace|Scheduler|Pending Tasks: 0
2024-12-17 10:09:52.1|Trace|Http|Req: 52 [GET] /logfile/sonarr.trace.txt (from 154.*.*.210 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36)
2024-12-17 10:09:52.1|Trace|Http|Res: 52 [GET] /logfile/sonarr.trace.txt: 200.OK (4 ms)
```

### Anything else?

Not sure what else you may need let me know

**Comment by Golumpa** [comment]
> This happens for every release and for every series from that indexer?
All releases from a specific series?
Just some releases for a specific series?

Yes, it is currently happening to every release from said indexer.

> What is the full, unedited/redacted release name shown in the Interactive Search? Please post a screenshot of the interactive search including the affected item you're trying to grab as well a link to the logs that cover the processing of the actual search results.

In this specific example I have here, I chose to use `Spice and Wolf`

The release I was trying to grab was
`Ookami to Koushinryou (2008) [Spirale] [Dual Audio] [10-bit] [BDRip]  [HD 1080p]`
when hovering over the red cloud I get this error `Value cannot be null. (Parameter 'input')`

Here is a link to the trace logs as its very big
https://privatebin.io/?a02f15e4e7f26381#AZNHfXJM3owL1ee4yVcVheZRmLi38iVKsPt61mJ6W5DC


![Screenshot 2024-12-17 175806](https://github.com/user-attachments/assets/6705e737-ccf1-4316-ade5-8f53b3f0f66f)
![Screenshot 2024-12-17 175715](https://github.com/user-attachments/assets/1fb0200b-9a9b-4407-8cf0-9bf39989c07f)
![Screenshot 2024-12-17 175744](https://github.com/user-attachments/assets/fe57ffc4-18a9-40b7-82bf-3a9eb6b620e5)

**Comment by markus101** [comment]
Sonarr cannot parse that release to determine the series and episodes within it, the only way you'll be able to grab it is via override and grab, but we can improve the messaging sent back to the UI and avoid logging the exception.

```
2024-12-17 17:56:13.6|Debug|DownloadDecisionMaker|Processing release 'Ookami to Koushinryou (2008) [Spirale] [Dual Audio] [10-bit] [BDRip]  [HD 1080p]' from 'AnimeTorrents (Prowlarr)'
2024-12-17 17:56:13.6|Debug|Parser|Parsing string 'Ookami to Koushinryou (2008) [Spirale] [Dual Audio] [10-bit] [BDRip]  [HD 1080p]'
2024-12-17 17:56:13.6|Debug|Parser|Unable to parse Ookami to Koushinryou (2008) [Spirale] [Dual Audio] [10-bit] [BDRip]  [HD 1080p]
2024-12-17 17:56:13.6|Debug|Parser|Parsing string 'Ookami to Koushinryou (2008) [Spirale] [Dual Audio] [10-bit] [BDRip]  [HD 1080p]'
2024-12-17 17:56:13.6|Debug|Parser|Unable to parse Ookami to Koushinryou (2008) [Spirale] [Dual Audio] [10-bit] [BDRip]  [HD 1080p]
2024-12-17 17:56:13.6|Debug|ParsingService|No matching series Ookami to Koushinryou (2008) [Spirale] [Dual Audio] [10-bit] [BDRip]  [HD 1080p]
2024-12-17 17:56:13.6|Debug|QualityParser|Trying to parse quality for 'Ookami to Koushinryou (2008) [Spirale] [Dual Audio] [10-bit] [BDRip]  [HD 1080p]'
2024-12-17 17:56:13.6|Debug|DownloadDecisionMaker|Release 'Ookami to Koushinryou (2008) [Spirale] [Dual Audio] [10-bit] [BDRip]  [HD 1080p]' from 'AnimeTorrents (Prowlarr)' rejected for the following reasons: [Permanent] Unable to parse release
```

**Comment by Golumpa** [comment]
I'm pretty sure it was failing on the force grab aswell but I'll check it tomorrow as I'm no longer at my computer.

**Comment by markus101** [comment]
Yeah I think that makes sense.
