### ISSUE TITLE
System.ArgumentException: ID does not match a known quality (Parameter 'id')

### ISSUE THREAD

**Issue by shackra** [Sonarr/Sonarr#7498]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

visiting the web interface shows the following:

```
Error parsing column 3 (Items=[ { "quality": 0, "items": [], "allowed": false }, { "quality": 1, "items": [], "allowed": true }, { "id": 1000, "name": "WEB 480p", "items": [ { "quality": 12, "items": [], "allowed": true }, { "quality": 8, "items": [], "allowed": true } ], "allowed": true }, { "quality": 2, "items": [], "allowed": true }, { "quality": 13, "items": [], "allowed": false }, { "quality": 22, "items": [], "allowed": false }, { "quality": 4, "items": [], "allowed": true }, { "quality": 9, "items": [], "allowed": true }, { "quality": 10, "items": [], "allowed": false }, { "id": 1001, "name": "WEB 720p", "items": [ { "quality": 14, "items": [], "allowed": true }, { "quality": 5, "items": [], "allowed": true } ], "allowed": true }, { "quality": 6, "items": [], "allowed": true }, { "id": 1002, "name": "WEB 1080p", "items": [ { "quality": 15, "items": [], "allowed": true }, { "quality": 3, "items": [], "allowed": true } ], "allowed": true }, { "quality": 7, "items": [], "allowed": true }, { "quality": 20, "items": [], "allowed": false }, { "quality": 16, "items": [], "allowed": false }, { "id": 1003, "name": "WEB 2160p", "items": [ { "quality": 17, "items": [], "allowed": false }, { "quality": 18, "items": [], "allowed": false } ], "allowed": false }, { "quality": 19, "items": [], "allowed": false }, { "quality": 21, "items": [], "allowed": false } ] - String)
VersionNumber
```

Checking journalctl, I see this:

<details>
<summary>[v4.0.9.2244] System.Data.DataException: Error parsing column 3 (Items=[</summary>

```
dic 17 14:43:32 woody Sonarr[2072238]: [v4.0.9.2244] System.Data.DataException: Error parsing column 3 (Items=[
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 0,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 1,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "id": 1000,
dic 17 14:43:32 woody Sonarr[2072238]:     "name": "WEB 480p",
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [
dic 17 14:43:32 woody Sonarr[2072238]:       {
dic 17 14:43:32 woody Sonarr[2072238]:         "quality": 12,
dic 17 14:43:32 woody Sonarr[2072238]:         "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:         "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:       },
dic 17 14:43:32 woody Sonarr[2072238]:       {
dic 17 14:43:32 woody Sonarr[2072238]:         "quality": 8,
dic 17 14:43:32 woody Sonarr[2072238]:         "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:         "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:       }
dic 17 14:43:32 woody Sonarr[2072238]:     ],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 2,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 13,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 22,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 4,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": true
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 9,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": true
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 10,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "id": 1001,
dic 17 14:43:32 woody Sonarr[2072238]:     "name": "WEB 720p",
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [
dic 17 14:43:32 woody Sonarr[2072238]:       {
dic 17 14:43:32 woody Sonarr[2072238]:         "quality": 14,
dic 17 14:43:32 woody Sonarr[2072238]:         "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:         "allowed": true
dic 17 14:43:32 woody Sonarr[2072238]:       },
dic 17 14:43:32 woody Sonarr[2072238]:       {
dic 17 14:43:32 woody Sonarr[2072238]:         "quality": 5,
dic 17 14:43:32 woody Sonarr[2072238]:         "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:         "allowed": true
dic 17 14:43:32 woody Sonarr[2072238]:       }
dic 17 14:43:32 woody Sonarr[2072238]:     ],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": true
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 6,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": true
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "id": 1002,
dic 17 14:43:32 woody Sonarr[2072238]:     "name": "WEB 1080p",
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [
dic 17 14:43:32 woody Sonarr[2072238]:       {
dic 17 14:43:32 woody Sonarr[2072238]:         "quality": 15,
dic 17 14:43:32 woody Sonarr[2072238]:         "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:         "allowed": true
dic 17 14:43:32 woody Sonarr[2072238]:       },
dic 17 14:43:32 woody Sonarr[2072238]:       {
dic 17 14:43:32 woody Sonarr[2072238]:         "quality": 3,
dic 17 14:43:32 woody Sonarr[2072238]:         "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:         "allowed": true
dic 17 14:43:32 woody Sonarr[2072238]:       }
dic 17 14:43:32 woody Sonarr[2072238]:     ],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": true
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 7,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": true
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 20,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 16,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "id": 1003,
dic 17 14:43:32 woody Sonarr[2072238]:     "name": "WEB 2160p",
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [
dic 17 14:43:32 woody Sonarr[2072238]:       {
dic 17 14:43:32 woody Sonarr[2072238]:         "quality": 17,
dic 17 14:43:32 woody Sonarr[2072238]:         "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:         "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:       },
dic 17 14:43:32 woody Sonarr[2072238]:       {
dic 17 14:43:32 woody Sonarr[2072238]:         "quality": 18,
dic 17 14:43:32 woody Sonarr[2072238]:         "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:         "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:       }
dic 17 14:43:32 woody Sonarr[2072238]:     ],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 19,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:   },
dic 17 14:43:32 woody Sonarr[2072238]:   {
dic 17 14:43:32 woody Sonarr[2072238]:     "quality": 21,
dic 17 14:43:32 woody Sonarr[2072238]:     "items": [],
dic 17 14:43:32 woody Sonarr[2072238]:     "allowed": false
dic 17 14:43:32 woody Sonarr[2072238]:   }
dic 17 14:43:32 woody Sonarr[2072238]: ] - String)
dic 17 14:43:32 woody Sonarr[2072238]:  ---> System.ArgumentException: ID does not match a known quality (Parameter 'id')
dic 17 14:43:32 woody Sonarr[2072238]:    at NzbDrone.Core.Qualities.Quality.FindById(Int32 id) in ./Sonarr.Core/Qualities/Quality.cs:line 191
dic 17 14:43:32 woody Sonarr[2072238]:    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
dic 17 14:43:32 woody Sonarr[2072238]:    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
dic 17 14:43:32 woody Sonarr[2072238]:    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
dic 17 14:43:32 woody Sonarr[2072238]:    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
dic 17 14:43:32 woody Sonarr[2072238]:    at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
dic 17 14:43:32 woody Sonarr[2072238]:    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
dic 17 14:43:32 woody Sonarr[2072238]:    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
dic 17 14:43:32 woody Sonarr[2072238]:    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
dic 17 14:43:32 woody Sonarr[2072238]:    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
dic 17 14:43:32 woody Sonarr[2072238]:    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
dic 17 14:43:32 woody Sonarr[2072238]:    at Dapper.SqlMapper.TypeHandler`1.Dapper.SqlMapper.ITypeHandler.Parse(Type destinationType, Object value) in /_/Dapper/SqlMapper.TypeHandler.cs:line 42
dic 17 14:43:32 woody Sonarr[2072238]:    at Dapper.SqlMapper.TypeHandlerCache`1.Parse(Object value) in /_/Dapper/SqlMapper.TypeHandlerCache.cs:line 23
dic 17 14:43:32 woody Sonarr[2072238]:    at Deserialized578bd56-4584-4985-a0c1-486f21e15bea(IDataReader )
dic 17 14:43:32 woody Sonarr[2072238]:    --- End of inner exception stack trace ---
dic 17 14:43:32 woody Sonarr[2072238]:    at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
dic 17 14:43:32 woody Sonarr[2072238]:    at Deserialized578bd56-4584-4985-a0c1-486f21e15bea(IDataReader )
dic 17 14:43:32 woody Sonarr[2072238]:    at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
dic 17 14:43:32 woody Sonarr[2072238]:    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
dic 17 14:43:32 woody Sonarr[2072238]:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
dic 17 14:43:32 woody Sonarr[2072238]:    at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
dic 17 14:43:32 woody Sonarr[2072238]:    at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param)
dic 17 14:43:32 woody Sonarr[2072238]:    at NzbDrone.Core.Datastore.ColumnMapper`1.<>c__DisplayClass8_0`1.<HasOne>b__0(IDatabase db, T parent)
dic 17 14:43:32 woody Sonarr[2072238]:    at NzbDrone.Core.Datastore.LazyLoaded`2.LazyLoad()
dic 17 14:43:32 woody Sonarr[2072238]:    at Sonarr.Api.V3.EpisodeFiles.EpisodeFileResourceMapper.ToResource(EpisodeFile model, Series series, IUpgradableSpecification upgradableSpecification, ICustomFormatCalculationService formatCalculationService)
dic 17 14:43:32 woody Sonarr[2072238]:    at System.Collections.Generic.List`1.ConvertAll[TOutput](Converter`2 converter)
dic 17 14:43:32 woody Sonarr[2072238]:    at Sonarr.Api.V3.EpisodeFiles.EpisodeFileController.GetEpisodeFiles(Nullable`1 seriesId, List`1 episodeFileIds)
dic 17 14:43:32 woody Sonarr[2072238]:    at lambda_method84(Closure , Object , Object[] )
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
dic 17 14:43:32 woody Sonarr[2072238]: --- End of stack trace from previous location ---
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
dic 17 14:43:32 woody Sonarr[2072238]: --- End of stack trace from previous location ---
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
dic 17 14:43:32 woody Sonarr[2072238]:    at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context)
dic 17 14:43:32 woody Sonarr[2072238]:    at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context)
dic 17 14:43:32 woody Sonarr[2072238]:    at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context)
dic 17 14:43:32 woody Sonarr[2072238]:    at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context)
dic 17 14:43:32 woody Sonarr[2072238]:    at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context)
dic 17 14:43:32 woody Sonarr[2072238]:    at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context)
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
dic 17 14:43:32 woody Sonarr[2072238]:    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```
</details>

### Expected Behavior

to show the regular UI, as normal

### Environment

```markdown
- OS: NixOS 24.11
- Sonarr: 4.0.9.2244
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox
- Database: sqlite
```

### What branch are you running?

Main

### Trace Logs?

I can't follow the instructions because the entire UI is overtaken by the error

**Comment by stevietv** [comment]
please update your sonarr first

**Comment by shackra** [comment]
> please update your sonarr first

okay, I started doing that. In a few minutes I'll report back

**Comment by shackra** [comment]
yay, updating from 4.0.9.2244 to 4.0.11.2680 fixed it!
