### ISSUE TITLE
Don't apply Indexer backoff in case of local network issue

### ISSUE THREAD

**Issue by Taloth** [Sonarr/Sonarr#751]

**Comment by jeffchen86** [comment]
It's still happening with the current version -  2.0.0.5252

**Comment by AidanHost** [comment]
Also been experiencing this issue for a while now. Here is my most recent error stacktrace

SignalR exception thrown by Task: System.AggregateException: One or more errors occurred. ---> System.IO.IOException ---> System.Net.HttpListenerException: The handle is invalid
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNet.SignalR.Owin.ServerResponse.Write(ArraySegment`1 data) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Owin\ServerResponse.cs:line 50
   at Microsoft.AspNet.SignalR.Infrastructure.BinaryTextWriter.<>c.<.ctor>b__0_0(ArraySegment`1 data, Object state) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BinaryTextWriter.cs:line 12
   at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter.ChunkedWriter.Flush(Byte[] byteBuffer, Boolean flushEncoder) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:line 182
   at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter.ChunkedWriter.Flush(Boolean flushEncoder) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:line 163
   at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter.Flush() in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:line 84
   at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.PerformSend(Object state) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Transports\LongPollingTransport.cs:line 322
   at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.<>c.<Send>b__43_0(Object state) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Transports\LongPollingTransport.cs:line 157
   at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.<Enqueue>b__14_0(Func`2 next, Object nextState) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Infrastructure\TaskQueue.cs:line 85
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod[T1,T2](Func`3 func, T1 arg1, T2 arg2) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\TaskAsyncHelper.cs:line 764
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException ---> System.Net.HttpListenerException: The handle is invalid
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   --- End of inner exception stack trace ---
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNet.SignalR.Owin.ServerResponse.Write(ArraySegment`1 data) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Owin\ServerResponse.cs:line 50
   at Microsoft.AspNet.SignalR.Infrastructure.BinaryTextWriter.<>c.<.ctor>b__0_0(ArraySegment`1 data, Object state) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BinaryTextWriter.cs:line 12
   at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter.ChunkedWriter.Flush(Byte[] byteBuffer, Boolean flushEncoder) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:line 182
   at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter.ChunkedWriter.Flush(Boolean flushEncoder) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:line 163
   at Microsoft.AspNet.SignalR.Infrastructure.BufferTextWriter.Flush() in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Infrastructure\BufferTextWriter.cs:line 84
   at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.PerformSend(Object state) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Transports\LongPollingTransport.cs:line 322
   at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.<>c.<Send>b__43_0(Object state) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Transports\LongPollingTransport.cs:line 157
   at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.<Enqueue>b__14_0(Func`2 next, Object nextState) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\Infrastructure\TaskQueue.cs:line 85
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod[T1,T2](Func`3 func, T1 arg1, T2 arg2) in C:\BuildAgent\work\5d7581516c0ee5b3\src\Microsoft.AspNet.SignalR.Core\TaskAsyncHelper.cs:line 764<---
