### ISSUE TITLE
History tab not updating properly - Couldn't add report to download queue. Unknown method

### ISSUE THREAD

**Issue by Nedlinin** [Sonarr/Sonarr#807]
NzbDrone.Core.Download.Clients.DownloadClientAuthenticationException: Unknown method
       at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.ProcessRequest[TResult](DelugeSettings       settings, String action, Object[] arguments) in   m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:lin    e 198
       at NzbDrone.Core.Download.Clients.Deluge.DelugeProxy.SetLabel(String hash, String label, DelugeSettings settings) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\DelugeProxy.cs:line 157
       at NzbDrone.Core.Download.Clients.Deluge.Deluge.AddFromTorrentFile(RemoteEpisode remoteEpisode, String hash, String filename, Byte[] fileContent) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:line 62
       at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteEpisode remoteEpisode, String torrentUrl) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 140
       at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteEpisode remoteEpisode) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 85
       at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteEpisode remoteEpisode) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\DownloadService.cs:line 57
       at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions(List`1 decisions) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:line 76

Using Deluge as my torrent client.  The downloads get added to the torrent client but the history never appears under the Activity->History tab and the download never appears to be indexed by Sonarr.

**Comment by markus101** [comment]
Please use the forums for support, if you're still having issues open a new thread there please.

Its failing to set the label on the torrent so Sonarr is never able to track it, make sure `Label` plugin is installed and enabled.
