### ISSUE TITLE
Error handling when episode name is very long

### ISSUE THREAD

**Issue by Nelluk** [Sonarr/Sonarr#815]
The error in the logs indicates that the file name length is to blame, but it is really the long episode name.

```
Couldn't import episode C:\Users\Nelluk\Deluge Downloaded\The.Late.Show.with.Stephen.Colbert.2015.09.24.Andrew.Sullivan.CBS.WEBRip.AAC2.0.x264-SynHD.mp4: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
at System.IO.Path.GetDirectoryName(String path)
at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.EnsureEpisodeFolder(EpisodeFile episodeFile, Series series, Int32 seasonNumber, String filePath) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 153
at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.CopyEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:line 88
at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile(EpisodeFile episodeFile, LocalEpisode localEpisode, Boolean copyOnly) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 60
at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:line 90
```

Episode name: **The Late Show With Stephen Colbert - 09/24/2015 - Andrew Sullivan, Maria Shriver, Jim Gaffigan, Archbishop Thomas Wenski, YMCA Jerusalem Youth Chorus, The Choir Of St. Jean Baptiste**

Happens with the automatically triggered import in CDH, and a Manual Import.

18:58 _zoggy_: yeah sonarr needs to add adapative renaming
18:58 _zoggy_: if multi-ep count is grater than x or ep title is greater than x revise what it uses
18:59 _zoggy_: was a few shows in sb we ran into that would never work if ep title was used until we added logic to prevent it from happening
18:59 _zoggy_: since most people would rather have the ep than no ep with the title

**Comment by ButtterBall** [comment]
+1 
Colbert's show is the first one to cause this in my Sonarr, but since SABNZB now supports long paths (in latest update 1.0.0 final) it would be great if Sonarr could add logic to handle them as well. Thank you all for your awesome work, Sonarr still amazes me every day,,,

**Comment by xamphear** [comment]
nzbget also now supports the API for very long file names too. Support for handling these files would be very much appreciated in Sonarr. Thank you to all the Sonarr developers for the work that they do. It is very much appreciated. 

For more information, here's the nzbget issue that lists the changes they had to make to support the "\\?\" prefix that supports very long filenames: https://github.com/nzbget/nzbget/issues/136

(Side Note: It's Colbert episodes that are doing it for me, too! The uploader insists on listing every single guest's full name, resulting in some very long filenames.)

**Comment by Mistywing** [comment]
Running into this issue myself with [http://www.thetvdb.com/?tab=season&seriesid=313435&seasonid=671382&lid=7](The Disastrous Life of Saiki K.), episodes fail to import after downloading if the name is too long and the rename function simply does not work and silently logs a complete failure in the logs.

`Request Failed: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.`

`System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at System.IO.FileInfo..ctor(String fileName)
   at NzbDrone.Common.Extensions.PathExtensions.CleanFilePath(String path) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 30
   at NzbDrone.Common.Extensions.PathExtensions.PathEquals(String firstPath, String secondPath, Nullable`1 comparison) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Extensions\PathExtensions.cs:line 48
   at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.<GetPreviews>d__11.MoveNext() in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:line 96
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.GetRenamePreviews(Int32 seriesId) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:line 62
   at NzbDrone.Api.Episodes.RenameEpisodeModule.GetEpisodes() in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\Episodes\RenameEpisodeModule.cs:line 30
   at NzbDrone.Api.REST.RestModule`1.<set_GetResourceAll>b__32_0(Object options) in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Api\REST\RestModule.cs:line 111
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)`

I think that if a solution to support the longer names is not made, a truncate option could be used instead while making sure the episode coding is at least included in the file name (SXXEXX etc).

**Comment by markus101** [comment]
Not to future self:

.net 4.6.2 and Winndows 10 make it easier to handle long paths (though we need to tweak things a bit): https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/

**Comment by SCRPD** [comment]
Season 4 of Gintama has this problem too, freaking anime...
I applied the Windows 10 long path fix, I guess we need an update on the Sonarr side? Because it still won't rename after doing the Windows 10 fix.

**Comment by Quiksmage** [comment]
+1 to this. I'm having this problem on nearly every episode of the show named, "WorldEnd: What Do You Do At The End Of The World? Are You Busy? Will You Save Us?"

I've been manually truncating the episode title on each episode.

**Comment by nilleiz** [comment]
+1 Having this nearly on every series.
Since Windows 10 / Windows Server 2016 does support "Win32 long paths" (with more characters than 248 / 260) by a gpo that can be activated. Is there going to be a fix soon? I am running on Win Serv 2016 with that GPO activated and sonarr still cant handle long paths.

**Comment by nrlatsha** [comment]
+1  Almost every episode now.

**Comment by ModerateWinGuy** [comment]
+1 Everything else seems to be handling the file find and download fine, would be great if the import worked too.

**Comment by markus101** [comment]
v3 will have long path support that was added in .net 4.6 I believe (as long as it's enabled in the OS).

**Comment by robertbaker** [comment]
![image](https://user-images.githubusercontent.com/907301/52997646-61518700-33de-11e9-874a-ef66dd628a48.png)
