### ISSUE TITLE
Cannot update windows version: Could not load file or assembly ICSharpCode.SharpZipLib

### ISSUE THREAD

**Issue by Safihre** [Sonarr/Sonarr#997]
On develop branch, shows update:
![image](https://cloud.githubusercontent.com/assets/5703454/11778518/18a591c2-a255-11e5-844d-f5f46cebef89.png)

Hitting update will result in:
```
Error occurred while executing task ApplicationUpdate: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' or one of its dependencies. The module was expected to contain an assembly manifest.
```
```
System.BadImageFormatException: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73'
   at NzbDrone.Common.ArchiveService.ExtractZip(String compressedFile, String destination)
   at NzbDrone.Common.ArchiveService.Extract(String compressedFile, String destination) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\ArchiveService.cs:line 33
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 107
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 206
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 91
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at CallSite.Target(Closure , CallSite , CommandExecutor , Object , CommandModel )
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 41
````

**Comment by markus101** [comment]
Please use the forums for support.

https://forums.sonarr.tv/search?q=Could%20not%20load%20file%20or%20assembly%20%27ICSharpCode.SharpZipLib
